### ISSUE TITLE
Go through the list of VMs for data8x and see if any can be shutdown and deleted

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#2407]
Data8x has a few VMs whose purpose may have been lost to time:

data8x-telemetry - ?
grader - ?, but presumably used for grading
grader-hub - ?
nfsserver - handles nfs for the data8x hub
sjcc-hub - ?, currently powered off

We can save some money if some of these VMs can be powered down and deleted.

**Comment by yuvipanda** [comment]
sjcc-hub used to host a hub specifically for a data8x version for San Jose Community College. I stopped it a while ago, and have deleted it now.

**Comment by felder** [comment]
data8x-telemetry and grader-hub were shutdown and then removed a few weeks later.  nfsserver and grader are still necessary.
