### ISSUE TITLE
JupyterHub opens when i try to open r.studio

### ISSUE THREAD

**Issue by dtrinidad002** [berkeley-dsep-infra/hubs#2460]
I was working on R.datahub, then out of nowhere my browser switched to jupyter.hub. Can someone please provide guidence on how to get back to r.datahub? I'll refresh the browser, but r.datahub now just sends me directly to jupyter.hub

**Comment by ericvd-ucb** [comment]
Hi 
your URL should look like this
https://r.datahub.berkeley.edu/user/username/rstudio/

alternatively you are probably right now looking at the file tree in Jupyterhiub
you can go on the right side and say new->rstudio

**Comment by yuvipanda** [comment]
This seems to be a new bug, and we are investigating it. Thanks for reporting this, @dtrinidad002

You can either use the 'New -> RStudio' pathway @ericvd-ucb mentioned, or use this link: https://r.datahub.berkeley.edu/hub/user-redirect/rstudio
