### ISSUE TITLE
add user to rstudio Admin

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#2462]
Hi - could we please add instructor @d-alex-hughes to the r hub admin?
he teaches for the Ischool and could help debug users 

Not sure what his Berkeley email is

**Comment by d-alex-hughes** [comment]
I'm at

**Comment by felder** [comment]
@yuvipanda has some other changes queued that I'm not sure I should merge to prod.  @yuvipanda feel free to merge this change if you're ready to merge the rest or let me know if I should go ahead.
