### ISSUE TITLE
Update Breaking Change in Rstudio Server 

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/hubs#2488]
R has updated its default graphics engine (now to version 14) and it is not compatible with the Rstudio Server version that is currently installed on r.datahub. As a result, plots are not rendered within Rstudio server. 

<img width="1313" alt="image (13)" src="https://user-images.githubusercontent.com/6474241/124638478-db63f880-de3f-11eb-8e29-9dc0d357ef3d.png">

I _suspect_ that an upgrade from the Rstudio version 1.3.959 that is currently deployed to a Rstudio version 1.4.x will resolve this. 1.4.x was released June 1, 2021. 

https://support.rstudio.com/hc/en-us/articles/200716783-RStudio-IDE-Release-History

**Comment by yuvipanda** [comment]
@d-alex-hughes unfortunately due to https://github.com/jupyterhub/jupyter-rsession-proxy/issues/95 we can't upgrade to 1.4 yet. Hopefully we can soon, but not yet. In the meantime, maybe I can downgrade to R 4.0 instead of R 4.1?

**Comment by yuvipanda** [comment]
@d-alex-hughes also, how is ischool.datahub.berkeley.edu? Does it work there?

**Comment by d-alex-hughes** [comment]
The ischool hub is great! Thanks for deploying it. I'll start pointing students that way as they come in (many have current class work hosted on r.datahub that I don't want to move in week 10.)

The graphics issues from R 4.1 and RStudio 1.3.x are present on the ischool.datahub as well.

**Comment by yuvipanda** [comment]
@d-alex-hughes ok good to know. I think I'll just try downgrading to R 4.0, and then work on migrating RStudio up

**Comment by yuvipanda** [comment]
@d-alex-hughes I deployed this change on Friday, hopefully things are ok for now on R 4.0.5

**Comment by yuvipanda** [comment]
We moved back to R 4.0.5 for now, and things seem to be ok?

**Comment by d-alex-hughes** [comment]
I haven't heard from any students -- either in our course channel, or study
group channels, or in the #datahub channel that we've started -- that they
are currently experiencing any performance issues.
Thanks!
