### ISSUE TITLE
Request R package Epi for class PH252

### ISSUE THREAD

**Issue by geneh0** [berkeley-dsep-infra/hubs#2524]
**Which package do you want installed?**

- `Epi`
- `foreign`

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

Public Health DataHub

**Which class will use this package?**

[PBHLTH 252](https://classes.berkeley.edu/content/2021-fall-pbhlth-252-001-lec-001) - Patrick Bradshaw

**Which semester will this package be used for?**

Fall 2021 (yearly)

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
Giving these a shot first:
https://cran.r-project.org/web/packages/Epi/index.html
https://cran.r-project.org/web/packages/foreign/index.html

**Comment by felder** [comment]
That seems to have worked.

@yuvipanda PR #2590 awaits your review.
