### ISSUE TITLE
Public Health Hub Private Repo Authorization

### ISSUE THREAD

**Issue by geneh0** [berkeley-dsep-infra/hubs#2528]
Hi, I'm working on a course that will be using the Public Health Hub. How do I go about granting it access to pull from a private repo via nbgitpuller? I found [this documentation](https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html) for the main hub, but it doesn't seem to be able to pull from there.

**Comment by balajialg** [comment]
Hi @geneh0, 

Did you complete all the steps outlined in the documentation and create a nbgitpuller link? If yes, Can you share the URL and also the snapshot of the error message that you are receiving? We will take a look and get back with our inputs.

**Comment by geneh0** [comment]
Yes, I was able to get it to work with the main hub before, but when I changed the url to the public health hub I get the error below: 
![image](https://user-images.githubusercontent.com/52678798/129428081-9c4553cf-73f8-443b-a09e-14c98a329c91.png)


The URL using the public health hub is 
https://publichealth.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fpatrickbradshaw%2FPH252_F2021_DataHub&urlpath=tree%2FPH252_F2021_DataHub%2F&branch=main

**Comment by yuvipanda** [comment]
Thanks for opening this and the details, @geneh0. We can add support for private repos to publichealth hub. When do you need this by?

**Comment by geneh0** [comment]
Ideally by the start of the semester!

**Comment by yuvipanda** [comment]
@geneh0 I've deployed this now, give it a shot?

**Comment by geneh0** [comment]
@yuvipanda  How do I grant the hub access to the repo?

**Comment by yuvipanda** [comment]
@geneh0 I put the link for the GItHub app in [the documentation](https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html)

**Comment by geneh0** [comment]
@yuvipanda Just pulled successfully! Thanks!
