### ISSUE TITLE
"Build recommended" page shouldn't appear for new users

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2532]
I just logged into the [Data 100 hub](https://data100.datahub.berkeley.edu) and got this one:

![image](https://user-images.githubusercontent.com/57394/129271240-87bfe7df-ef3b-4b23-8fd5-686bf61a628e.png)

I think we should have a build such that upon entry, no further action is needed by the user. These lab build screens are at best useless, at worst confusing/blockers for our students.

**Comment by balajialg** [comment]
Hi, @fperez I am Balaji Alwar, Service Lead for Datahub. Thanks for raising this issue! I tried replicating this issue at my end by logging into Data 100 hub, but I am not able to see the error message. Couple of questions,

1. Did you log in and open any specific file, or you got this prompt immediately post your login?
2. Is it possible to check if anyone else in your teaching team is also getting a similar kind of error?

In the meantime, I will check with the team to replicate this issue and figure out a way forward.

**Comment by fperez** [comment]
Hi @balajialg, nice meeting you (sorry I owe you an email, been drowning :).  To answer your questions:

1. Immediately upon login.
2. I can check later.

It's not a big deal, no worries. But this might point you in the right direction:

```
jovyan@jupyter-fernando-2eperez:/opt/conda/share/jupyter/lab/extensions$ jupyter lab path
Application directory:   /opt/conda/share/jupyter/lab
User Settings directory: /home/jovyan/.jupyter/lab/user-settings
Workspaces directory: /home/jovyan/.jupyter/lab/workspaces
jovyan@jupyter-fernando-2eperez:/opt/conda/share/jupyter/lab/extensions$ pwd
/opt/conda/share/jupyter/lab/extensions
jovyan@jupyter-fernando-2eperez:/opt/conda/share/jupyter/lab/extensions$ ls -l
total 2484
-rw-r--r-- 1 jovyan jovyan  654135 Aug 12 04:30 jupyter-gmaps-0.9.0.tgz
-rw-r--r-- 1 jovyan jovyan    3129 Aug 12 04:11 jupyterlab-plotly-4.14.3.tgz
-rw-r--r-- 1 jovyan jovyan    2697 Aug 12 04:11 jupyterlab-server-proxy-3.1.0.tgz
-rw-r--r-- 1 jovyan jovyan 1864456 Aug 12 04:11 plotlywidget-4.14.3.tgz
-rw-r--r-- 1 jovyan jovyan   10480 Aug 12 04:11 rm-0.1.8.tgz
```

**Comment by fperez** [comment]
That shows lab is looking for extensions under `/opt/conda/share/jupyter/lab`, and indeed there, under `extensions/`, I see a `jupyter-gmaps` tarball...

**Comment by balajialg** [comment]
@fperez That's super helpful. Thank you for taking the time to troubleshoot! Look forward to your email :)

@felder

**Comment by yuvipanda** [comment]
I had opened https://github.com/pbugnion/gmaps/issues/349 a while ago to try get it fixed, unfortunately upstream development seems to have stopped.
