### ISSUE TITLE
Python package bumps for datahub ahead of Fall 2021

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2533]
**Which package do you want installed?**

These are all installed but with older versions, it would be good to bump up to these current versions:

```
jupyterlab     : 3.1.6
matplotlib     : 3.4.2
numpy          : 1.21.1
pandas         : 1.3.1
plotly         : 5.1.0
scipy          : 1.7.1
sklearn        : 0.24.2
statsmodels    : 0.12.2
xarray         : 0.19.0
```

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

Data 100.

**Which class will use this package?**

Data100 - @fperez and @alvinwan

**Which semester will this package be used for?**

Fall 2021

**Any additional information we should know about?**

JupyterLab >= 3.1.5 is particularly important, so that we get the fix for [this issue](https://github.com/jupyterlab/jupyterlab/issues/10732) that was merged in 3.1.5.

**Comment by fperez** [comment]
For reference, these are the current versions on the 100 hub

```
jupyterlab     : 3.1.4
matplotlib     : 3.3.3
numpy          : 1.19.5
pandas         : 1.2.0
plotly         : 4.14.3
scipy          : 1.6.0
seaborn        : 0.11.1
sklearn        : 0.24.0
statsmodels    : 0.11.1
xarray         : 0.16.2
```

**Comment by fperez** [comment]
In case anyone wants to do a quick check of what's there upon import (rather than checking conda/mamba package lists, to avoid any potential kernel namespace confusions), I use this snippet to quickly see what's in my various environments:

```python
import sys
from importlib import import_module

mods = sorted("""
jupyterlab
matplotlib
numpy
pandas
IPython
scipy
sklearn
seaborn
statsmodels
plotly
xarray
geopandas
""".strip().splitlines())
    
for mod in mods:
    try:
        p = import_module(mod)
        print(f"{mod:<15}: {p.__version__}")
    except ModuleNotFoundError as err:
        print(err, file=sys.stderr)
    except AttributeError:
        print(f"{mod} has no '__version__' attribute", file=sys.stderr)
```

**Comment by yuvipanda** [comment]
@fperez should be all new now!

**Comment by fperez** [comment]
Thx @yuvipanda! I see most things updated, but Lab seems to be still at 3.1.4 - that's a pretty critical one as there's a major issue with interactive input that was only resolved in 3.1.5... Current is 3.1.7, so we might as well update to that and we can hopefully let it be for the semester...

**Comment by echarles** [comment]
Posting here a copy of the issue report on gitter.

<img width="566" alt="Screenshot 2021-09-01 at 09 41 57" src="https://user-images.githubusercontent.com/226720/131632299-2b1758ae-d3a9-4b5c-bd18-1df8b97ab702.png">
 
The issue should be solved with a release of a new JupyterLab 3.1.10 (cc/ @blink1073 @goanpeca).

@fperez @yuvipanda To mitigate today the issue before the release, you can set (or ask the users) to set the following notebook settings in the JupyterLab UI

```
{
    "numberCellsToRenderDirectly": 999999,
    "renderCellOnIdle": false
}
```

<img width="1044" alt="Screenshot 2021-09-01 at 09 38 38" src="https://user-images.githubusercontent.com/226720/131632818-284696d0-c536-4e36-a506-116a60dc15aa.png">

**Comment by yuvipanda** [comment]
Thanks for the shout out, @echarles. I'll just wait for 3.1.10 - we're on 3.1.9 currently.

**Comment by fperez** [comment]
Heads-up @yuvipanda - 3.1.10 is now out on PyPI.

This one is hitting us on Data100 hard (Multiple students super-confused by it), so if you have a chance to pull an update, it would be phenomenally appreciated.

cc @consideRatio too, as it's the same one @whyjz hit on the JMTE hub :)

**Comment by fperez** [comment]
Huge thanks to @echarles  for keeping an eye here on our use case, immensely appreciated!

ps - I have to hop on a meeting now, but will check [10732](https://github.com/jupyterlab/jupyterlab/issues/10732) ASAP. I know you worked hard on that too based on our concerns, and very much appreciate it.

**Comment by echarles** [comment]
> ps - I have to hop on a meeting now, but will check 10732 ASAP. I know you worked hard on that too based on our concerns, and very much appreciate it.

No worries, we still have time for https://github.com/jupyterlab/jupyterlab/issues/10732. Let's first make sure all students have a correct JupyterLab to learn Data.

Please keep us in the loop on the specific reported issue. And also on any other issues (hopefully not). JupyterLab 3 has some major changes (python extension packaging, RTC, performance, ToC...). I have been part on some of them, and your deployment is maybe one with the most of users so far for JLab3. We really want to make it success.

**Comment by yuvipanda** [comment]
@fperez it's deployed now

**Comment by fperez** [comment]
Awesome @yuvipanda, thanks so much! I pinged our infra folks so they can flag the students to restart any servers they have running before they run into the problem again.

**Comment by fperez** [comment]
And indeed @echarles - we have about ~1,100 students and a team of ~50 teaching assistants, so this is a pretty serious deployment. I'd been experimenting with Lab on previous editions of this course, and many students had chosen to use it, but we had never made it the default til now. 

Over the last few months I did a fair amount of testing and convinced myself it would be sane to give it a try - at some point you have to commit to it, and accept you'll run into some issues that only appear at scale. But between the fact that we have a great team around us, and that we can always fall back to Classic if absolutely necessary, it felt like a reasonable risk to take.  @yuvipanda  has been super patient with us on this one, and I think shaking out these remaining issues is very valuable. I do hope we won't run into any more truly problematic ones like this as the semester progresses (this one was really bad, as it just made certain assignments unusable).

Thx again for your care and attention!

**Comment by echarles** [comment]
Really really sorry for the troubles. This issue has been really annoying and generated by a set of circumstances. Please raise any other issue (if any), we are here to help.

**Comment by echarles** [comment]
A user has justreported 3.1.10 was fixing the issue https://discourse.jupyter.org/t/code-cells-not-rendering-on-jupyter-lab/10597/2

**Comment by fperez** [comment]
No worries @echarles - fixed and deployed, and we're back on track :)
