### ISSUE TITLE
Request some packages on eecs hub

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2535]
**Which package do you want installed?**
1. Emacs 
2. Gdb 
3. Gfortran
2. Upgrade gcc to version 10.0
3. OpenBlas 
4. Lapack
5. Armadillo 

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
EECS Hub

**Which class will use this package?**
Server Engineering for Scientific Computing class as part of **Master of Molecular Science and Software Engineering (MSSE)** degree program

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.
Luis Crivelli
College of Chemistry

**Which semester will this package be used for?**
Fall, 2021

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@yuvipanda @felder Can you please take a look and let me know the feasibility of installing gfortran and upgrading gcc?

**Comment by yuvipanda** [comment]
Heya!
 
gfortran, gdb and emacs should be no problem. I think upgrading gcc will be difficult though. You can use https://packages.ubuntu.com/ to see what version of packages are available - our Ubuntu version is 'focal'. I think 9.3 is latest available?

**Comment by balajialg** [comment]
Thanks a lot! Yes, it's [version 9.3 ](https://packages.ubuntu.com/focal/gcc-9)
