### ISSUE TITLE
Remove stat159 hub

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2553]
I am not sure if stat159 is happening this fall - can't find it on https://classes.berkeley.edu/search/class/stat159?retain-filters=1. If it isn't, we should remove that hub

**Comment by ryanlovett** [comment]
There's no stat159 according to the [Stat department website](https://statistics.berkeley.edu/courses/schedule?term_reference=6&level=UGRD&enrollment_status=&number_formatted=) either. Both get their info from the SIS.
