### ISSUE TITLE
Request R package "tableone" for class PH252

### ISSUE THREAD

**Issue by zbutzin** [berkeley-dsep-infra/hubs#2556]
**Which package do you want installed?**

"tableone"

**Which hub do you want it installed on?**

Public Health DataHub

**Which class will use this package?**

[PBHLTH 252](https://classes.berkeley.edu/content/2021-fall-pbhlth-252-001-lec-001) - Patrick Bradshaw

**Which semester will this package be used for?**

Fall 2021 (yearly)

**Any additional information we should know about?**

I apologize for omitting this package in our earlier request. Thank you so much for your help.

**Comment by felder** [comment]
cran does not appear to have a linux binary for this.
https://cran.r-project.org/web/packages/tableone/index.html

Trying to add it the easy way fails with:

```
Error in download_version_url(package, version, repos, type) : 
  version '0.13.0' is invalid for package 'tableone'
```

**Comment by felder** [comment]
Seems to work on staging.

```
> library(tableone)
> packageVersion("tableone")
[1] ‘0.12.0’
```

**Comment by felder** [comment]
Works in prod.
