### ISSUE TITLE
Request R package estimatr for class PS 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#2579]
**Which package do you want installed?**
`estimatr`

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
PS 3 Fall 2021, David Broockman

**Which semester will this package be used for?**
Fall 2021 and Spring 2022

**Any additional information we should know about?**
The package is available on CRAN.

**Comment by felder** [comment]
https://cran.r-project.org/web/packages/estimatr/index.html

**Comment by dbroockman** [comment]
That's the one.

**Comment by felder** [comment]
@yuvipanda PR #2592 awaits your review.
