### ISSUE TITLE
Public Health Repo throwing error

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2586]
publichealth.datahub.berkeley.edu  server with people trying to access a datahub link for the first time (see below). Restarting the individual servers seems to work, but we don't want to have 100 people emailing us with this question when the datahub link gets released next week. Any idea why this is happening/how to pre-empt it? [It](url) seems to be happening for some but not all testers.****

**Comment by balajialg** [comment]
@yuvipanda How to avoid this error going forward?

**Comment by felder** [comment]
![image](https://user-images.githubusercontent.com/1211730/130281649-271ba023-b666-4e7a-9bee-5b1cf2f86888.png)

**Comment by yuvipanda** [comment]
From looking at the screenshot, we notice the `[...]` characters in the git URL, suggesting that the URL was somehow 'corrupted' before being clicked. We see that if you paste the link on slack, it displays it with the `[...]` (something like https://publichealth.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithu[...]Intro-to-Epidemiology), and if you click that, you get the reported error.

So I think what happened is the URL got corrupted this way somewhere before the user clicked on it, leading to this error. I've asked the reporting user (on slack) to check that, and we can re-open this if that is the case.

However, we should open an issue in https://github.com/jupyterhub/nbgitpuller/ about better error messages! This is incomprehensible for most people.

**Comment by felder** [comment]
heh yeah I thought maybe the error message was truncating the URL :P

**Comment by yuvipanda** [comment]
I opened https://github.com/jupyterhub/nbgitpuller/issues/198 upstream

**Comment by balajialg** [comment]
that's awesome @yuvipanda ! Who maintains nbgitpuller repo actively?

**Comment by yuvipanda** [comment]
@balajialg https://github.com/jupyterhub/nbgitpuller/graphs/contributors has a list of contributors. Recently, @sean-morris has been working on it from Berkeley - although he hasn't been doing anything in the UI space yet.

**Comment by balajialg** [comment]
Thanks @yuvipanda
