### ISSUE TITLE
g++ not finding dependent libraries during run time in EECS Hub

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2604]
### Bug description

Able to compile the C++ files using g++, but getting the following errors during the run time. 
/srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'

/srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `clock_gettime@GLIBC_2.17'

collect2: error: ld returned 1 exit status

### Environment & setup

- Hub:  EECS Hub
- Language:  C++

### How to reproduce

1. You can access the instance [here](https://eecs.datahub.berkeley.edu/user/luis.crivelli/lab/workspaces/auto-D). 
2. Open the uploads directory. 
3. Run a C++ file named fpdemo.cpp. Command to run it **g++ -o fpdemo fpdemo.cpp -lm**

**Comment by felder** [comment]
The issue is the path by default is calling g++ from /srv/conda/envs/notebook/bin/g++

```
(notebook) jovyan@jupyter-luis-2ecrivelli:~/Uploads$ which g++
/srv/conda/envs/notebook/bin/g++
(notebook) jovyan@jupyter-luis-2ecrivelli:~/Uploads$ g++ -o fpdemo fpdemo.cpp -lm
/srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'
/srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `clock_gettime@GLIBC_2.17'
collect2: error: ld returned 1 exit status
```

A quick solution is to run /usr/bin/g++

```
(notebook) jovyan@jupyter-luis-2ecrivelli:~/Uploads$ /usr/bin/g++ -o fpdemo fpdemo.cpp -lm
(notebook) jovyan@jupyter-luis-2ecrivelli:~/Uploads$ ./fpdemo
s|->exponent<-|---> mantissa
63        55        47        39        31        23        15        7
+011 1111|1110 1111|1111 1111|1111 1111|1111 1111|1111 1111|1111 1111|1111 1110
  3    F    E    F    F    F    F    F    F    F    F    F    F    F    F    E
decoding 9.999999999999997779554e-01: 
exponent: 1022, unbiased exponent: -1, 2^e: 5.000000e-01, mantissa: 0.99999999999999956
Breakup of source: 9.99999999999999778e-01
mantissa: 0.99999999999999956 1+mantissa: 1.99999999999999956
exponent: 2^-1 = 5.00000000000000000e-01 
(1+mantissa)*2^-1: 9.99999999999999778e-01
Double parameters:
Size: 8 bytes DBL_MAX_EXP 1024 DBL_MANT_DIG 53 DBL_MAX 1.79769313486231571e+308
DBL_EPSILON 2.220446e-16
Long Double parameters:
Size: 16 bytes LDBL_MAX_EXP 16384 LDBL_MANT_DIG 64 :DBL_MAX 1.189731495357231765021264e+4932
LDBL_EPSILON 1.084202e-19
Floating point behavior:
FLT_ROUNDS 1 FLT_EVAL_METHOD 0 printing: DECIMAL_DIG 21
(notebook) jovyan@jupyter-luis-2ecrivelli:~/Uploads$
```

**Comment by balajialg** [comment]
Thanks a lot @felder! This is fantastic. I will inform the faculty

**Comment by yuvipanda** [comment]
We intentionally installed g++ with conda so they can have a newer version, vs the version from apt that's much older. However, this means I'm not sure what `ld` needs to find appropriate libraries.

**Comment by balajialg** [comment]
@yuvipanda this seems to resolve the issue according to the faculty! You can re-open this issue if you want to investigate further!
