### ISSUE TITLE
Make JupyterLab default landing environment for Data 100

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2606]
Once #2605 lands, we'll have JupyterLab 3.1.7 available. At that point, I'd prefer to make Lab the default endpoint for all students when they open the environment, instead of the classic notebook. I think we're at a point where we can start using Lab for courses like 100.

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

data100 hub

**Which class will use this package?**

Data 100 - Alvin Wan and myself.

**Comment by balajialg** [comment]
Thanks, @fperez! We will scope this request into our plan as soon as possible. Quick question - Do you want to see this set up before the start of the instruction?

**Comment by fperez** [comment]
That would be ideal - I can always tell them to manually modify the URL to `/lab`, but it's obviously better to have it work out of the box, given the class size... If I recall, the actual switch is pretty trivial, it's a matter of adding

```
# Start Users at the JupyterLab Interface
c.Spawner.default_url = '/lab'
```

to `jupyterhub_config.py` - I can look into making a PR for you if that makes things easier on your end.

Thanks!

**Comment by yuvipanda** [comment]
@fperez done! Should be deployed to production in about 20-30min

**Comment by balajialg** [comment]
Thanks, @fperez for the offer to make a PR and @yuvipanda for closing it!

**Comment by fperez** [comment]
Wonderful, thanks so much @yuvipanda!! As you've seen elsewhere, we're seeing a bit of fallout from this, but I knew that would be the case :) Nothing to shake out those little lurkers like 1,100 eager students going live in prod. Life on the edge! 🚀 💥 😬

**Comment by yuvipanda** [comment]
@fperez thanks for taking the plunge :)
