### ISSUE TITLE
Update PR documentation to include R packages

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#2608]
# Template Credits: 2I2C
# Summary

The [docs for submitting a PR](https://docs.datahub.berkeley.edu/en/latest/admins/howto/new-packages.html#submitting-a-pull-request) mention conda, pip, and python, but don't mention R package management. One instructor was uncertain how to proceed. We should probably document the r-packages/ directories and the files it contains.

# User Stories

This is for instructors and GSIs who want to make PRs for adding R packages for their new courses.

**Comment by balajialg** [comment]
Thanks, @ryanlovett, for raising this important issue! If you could support me with relevant information, I could take a stab at getting this out by next month!

FYI, Yuvi created a related [issue ](https://github.com/berkeley-dsep-infra/datahub/issues/2550)sometime back!
