### ISSUE TITLE
2021-08-26 Th 6:22 PDT: 500 Internal Server Error... 

### ISSUE THREAD

**Issue by braddelong** [berkeley-dsep-infra/hubs#2628]
### Bug description

...in response to <http://datahub.berkeley.edu/user-redirect/interact?account=braddelong&repo=delong-python-problem-sets&branch=main&path=delong-jn-00.ipynb>.

<https://github.com/braddelong/delong-python-problem-sets/blob/main/delong-jn-00.ipynb> exists and, yes, runs on my machine...

How do I go about problem solving here?

Brad DeLong
Professor of Economics

### Environment & setup

- Hub: 
- Language: 
- 
<img width="1451" alt="JupyterHub_and_Draft_of_possible_initial_Python_Jupyter_Notebook_Data_Science_Problem_Set" src="https://user-images.githubusercontent.com/27788138/130970738-b6bb58a4-81ad-4958-ad33-05ae07ef00ed.png">

**Comment by andrewpbray** [comment]
I'm running into the same problem with students in lab this morning for Stat-20. They're on r.datahub.berkeley.edu.

**Comment by yuvipanda** [comment]
I'm working on this now.

**Comment by yuvipanda** [comment]
This should be fixed now on datahub and r hub! Fix for other hubs is in progress

**Comment by andrewpbray** [comment]
Many thanks!

**Comment by yuvipanda** [comment]
Should be fixed in all the hubs now. Sorry for the inconvenience, @andrewpbray and @braddelong!
