### ISSUE TITLE
Request otter update for class PS3

### ISSUE THREAD

**Issue by castroian** [berkeley-dsep-infra/hubs#2639]
**Which package do you want installed?**
The most recent version of otter-grader, v3.0.6 (as of 8/29)

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
Political Science 3 with David Broockman @dbroockman

**Which semester will this package be used for?**
Fall 2021

**Any additional information we should know about?**

Students currently receive a subscript out of bounds error when running tests, which can resolved by updating to the newest version of otter. Probably due to the new implementation when using testthat and ottr in R notebooks

**Comment by dbroockman** [comment]
This is creating errors in notebooks we have going live on Tuesday for 350 students, so would appreciate a quick fix here if possible. Thank you!

**Comment by yuvipanda** [comment]
Fixed in https://github.com/berkeley-dsep-infra/datahub/pull/2640

**Comment by dbroockman** [comment]
Thanks, @yuvipanda . Do you know when this fix will go live on the production servers?

**Comment by yuvipanda** [comment]
@dbroockman it's already live.

**Comment by dbroockman** [comment]
Thanks. Turns out we also need `testthat` updated, I just made #2646 for this.

**Comment by dbroockman** [comment]
Turns out this updated the python package, but what we need is the new R package. I made #2656 to track the R package update issue.
