### ISSUE TITLE
Request `testthat` R package update for class PS 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#2646]
**Which package do you want installed?**
The most recent version of `testthat` from CRAN.

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
PS 3 Fall 2021
Professor David Broockman (me)

**Which semester will this package be used for?**
Fall semester; class starts tomorrow.

**Any additional information we should know about?**
Students currently receive a subscript out of bounds error when running tests, which can resolved by updating to the newest version of otter. Probably due to the new implementation when using testthat and ottr in R notebooks.

**Comment by balajialg** [comment]
@felder Request from the teaching team below! Can you please take a look into it asap?

_**Could you please update the testthat package on r.datahub today? The students will be working on these notebooks tomorrow at 5 PM and we want to avoid having them deal with the errors. Our GitHub issue is here: https://github.com/berkeley-dsep-infra/datahub/issues/2646**_

**Comment by felder** [comment]
https://cran.r-project.org/web/packages/testthat/index.html

**Comment by felder** [comment]
Phew it takes a while to build that image.

rstudio in staging reports:

```
> library(testthat)
> packageVersion("testthat")
[1] ‘3.0.4’
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_3.0.4

loaded via a namespace (and not attached):
 [1] compiler_4.0.5  magrittr_2.0.1  R6_2.5.1        fastmap_1.1.0   htmltools_0.5.2 tools_4.0.5     yaml_2.2.1     
 [8] rmarkdown_2.10  knitr_1.33      xfun_0.25       digest_0.6.27   rlang_0.4.11    evaluate_0.14  

>
```

**Comment by felder** [comment]
Done!

**Comment by balajialg** [comment]
Thanks a lot, @felder for the quick turnaround! Appreciate it
