### ISSUE TITLE
Sprint Planning Meeting #1: September 2nd

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2663]
Hi All,

Given that tomorrow's meeting will be the first and only sprint planning meeting for September, I would like us to set an agenda for open items that need to get discussed tomorrow.  Would you please add open items and expected time for discussion to this list whenever you have some time today? Thanks!

**Agenda**
1. Decide the overall priorities for September! (20-25 mins)
2. Define how week by week reporting structure should work (5-10 mins)
3. Finalize the support process (10 - 15 mins)

**Comment by balajialg** [comment]
@all - Closing this issue with the assumption and hope that you all are aligned with the agenda tomorrow!

**Comment by yuvipanda** [comment]
@balajialg let's keep this open and then close it with action items from the meeting?

**Comment by balajialg** [comment]
Action items added to the September Sprint Board!
