### ISSUE TITLE
500: Internal Server Error while downloading notebook as PDF (via latex) 

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2664]
### Bug description

**Issue as raised by faculty Scott Dreger:**

One student was having a problem downloading their notebook as a pdf (via latex). I have attached screenshots of the error. Apparently, download as pdf (via HTML) works for him. Both works for me and I am running 10.15 on a MacBook. The student is using a MacBook too but is running a new OS 11.2 I think.
<img width="988" alt="Screen Shot 2021-09-01 at 10 26 56 AM" src="https://user-images.githubusercontent.com/2306166/131724943-e7edd1c3-8548-47c9-92f4-a850ea32b748.png">
<img width="1007" alt="Screen Shot 2021-09-01 at 10 27 22 AM" src="https://user-images.githubusercontent.com/2306166/131724947-459d0d28-3c58-4b94-b217-33c1ae91a485.png">

### Environment & setup

- Hub: Datahub
- Language: Python

### How to reproduce
1. Access datahub.berkeley.edu from a MacBook having latest OS version 10.15 
2. Create a sample notebook
3. Try File -> Download as PDF via Latex
4. Should get 500 internal server error!

**Comment by yuvipanda** [comment]
Does it work for you with the exact same notebook? It's probably related to some content in the notebook.

Is the output from `download as pdf (via HTML)` acceptable? If so, I'd suggest they recommend students use it. It's far more robust than the latex method

**Comment by balajialg** [comment]
@yuvipanda I don't have access to the student's calnet id and have requested the same to access his server. 

It seems your suggested approach was what they went with finally since this option was not working. Requested more details but yet to receive any inputs.

**Comment by balajialg** [comment]
I was able to replicate this [issue ](https://datahub.berkeley.edu/user/balajialwar/nbconvert/pdf/Jupyter%20Books%20Intro.ipynb?download=true)at my end and @ericvd-ucb could also replicate this issue! Access to his instance [here](https://datahub.berkeley.edu/user/ericvd/nbconvert/webpdf/88e-fa21/lec/lec01/EVANS60_Class.ipynb?download=true)

**Comment by yuvipanda** [comment]
Great! However, I generally consider LaTeX a scourge on civilization as it exists today. Can we tell them (and others) to just use `download as pdf (via HTML)` instead?

**Comment by balajialg** [comment]
@yuvipanda hahaha, funny! Eric connected me with the prof! He is yet to respond but will communicate your point once he does.

**Comment by balajialg** [comment]
Links to a policy!

**Comment by balajialg** [comment]
Has a policy/feature implication,

- Feature: Sunset the download via Latex feature?
- Policy: Recommend users to use download PDF via HTML!

**Comment by yuvipanda** [comment]
yeah, I'd like both of these things to happen.
