### ISSUE TITLE
Provide policy for when course needs to get its own hub

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2670]
- [x] Define the policy for when a course gets its own hub
- [x] Figure out where our policy proposals reside

**Comment by balajialg** [comment]
Trying to iterate in this thread regarding the policy to create a new hub. Will tag relevant folks once the below proposal is ready for feedback,

- Some of the policy considerations for creating a new hub are,
	- Course has a large user base with more than 300+ students (like Data 8 and Data 100 hubs)
	- Course is computationally intensive and requires a large amount of CPU/Memory requirements (RAM greater than 2 GB or requires the use of calendar-based scheduling on a weekly basis) like a biology hub
	- Testbed for deploying new features which once matures can be enabled across other major hubs (Like Stat 159/RTC hub)
	- Course requirements tend to be dynamic and require making more than 5+ CI/CD deployments every month (Like Stat 159 hub)
	- Course has a specific requirement for multiple packages which are incompatible with the standard package version in Datahub (Like Astro hub)
	- Course uses Datahub and also has undergrad students who act as GSIs requiring admin access (Like Data 8 hub)
	- Hub is created for organizational/strategic reasons to build institutional buy-in from specific departments (Like Public Health and ISchool)
	- Hub is created for organizational/strategic reasons to evangelize a specific service (Like Julia or R hub)

- Policy changes for deployment to the main Datahub
	- Package changes at the start and end of the semester
	- Package changes during the semester with robust testing protocol in staging + deployment in prod during non-class times (Open to feedback from the team regarding this articulation)
	- RAM and CPU changes as and when requested
	- Admin access related changes
	- Enabling functionalities that have been tested **successfully** with varied instructors across smaller hubs

**Comment by ryanlovett** [comment]
Thanks for building this out!

@yuvipanda mentioned that user count of 300+ should also be considered. This was in the context of Stat 20.

**Comment by ericvd-ucb** [comment]
To reflect on the past year, we had started hubs for  Public Health and ISchool, that sort of reflect robust institutional use by these partners?  Not sure how to describe that protocol

**Comment by balajialg** [comment]
@ryanlovett and @ericvd-ucb Thanks for your input. Have included your suggestions in the above list. 

@ericvd-ucb Let me know if the articulation about dept specific hub makes sense!

**Comment by balajialg** [comment]
**Next Steps from March Sprint Planning Meeting:**

- [x] Balaji to codify the policy inputs into a PR that needs to get published into the Datahub docs repository!

**Comment by balajialg** [comment]
PR for the policy is currently merged to staging branch!
