### ISSUE TITLE
Investigate data100 503 errors

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2677]
From Andrew Lenz on Slack

> Data 100 is wondering if we can get more resources/computational power for DataHub. We constantly get overloaded for resources and get 503s on due dates, which is quite unfortunate.

There were many different issues provided, some which showed 503 and others exhibited themselves in other ways. We should track these, and fix them however we can. 

I don't think most of them are due to lack of resources though, except for some kernel deaths.

**Comment by yuvipanda** [comment]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/30430/131911094-5bd95693-270a-4f31-91d6-0f1231c4e123.png">


Looking at server start times, I don't see anything too bad. I also don't see a lot of pending or waiting users

<img width="677" alt="image" src="https://user-images.githubusercontent.com/30430/131911299-70bfcfeb-5cef-413b-93f1-b501061140c1.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/30430/131911342-8666fae4-a8d1-449a-982a-a28be8f13d02.png">

**Comment by yuvipanda** [comment]
A bunch of different issues were reported!

![image](https://user-images.githubusercontent.com/30430/131921194-e9f0e9c6-8d45-47a7-bd31-eb3ee3cdfd37.png)

is one.  I haven't seen this one before, and there were several users reporting this. This is perhaps also a race condition between the multiple user schedulers we had, and could be fixed by #1817. Let's wait and watch to see if there are more reports of this.

**Comment by balajialg** [comment]
Message from the teaching team - _sorry to tag you all (I know we decided on the Piazza route), but yet again, it's the due date for a major assignment and DataHub is down with a Service Unavailable screen (503?). Any ideas_

Link to [Piazza1](https://piazza.com/class/kqsiwfz12g0482?cid=445) and [Piazza 2](https://piazza.com/class/kqsiwfz12g0482?cid=439)where students raised the issue.

Request is to provide more resources to avoid such scenarios in the future!

**Comment by felder** [comment]
@yuvipanda while I cannot prove this conclusively, there appears to be a V shaped currently running users graph here:
https://grafana.datahub.berkeley.edu/goto/g_YrOXSnz

With a correlation to this particular PR:
https://github.com/berkeley-dsep-infra/datahub/pull/2768

Can you think of any reason why that PR might result in lots of pods being knocked off?  Is it possible that any change to data100 causes a mass drop off which could possibly explain the odd behavior above as well.

I also see this in the hub log for data100-prod:
```
[I 2021-09-16 23:28:00.379 JupyterHub app:2459] Running JupyterHub version 1.4.2
[I 2021-09-16 23:28:00.379 JupyterHub app:2489] Using Authenticator: canvasauthenticator.CanvasOAuthenticator
[I 2021-09-16 23:28:00.379 JupyterHub app:2489] Using Spawner: builtins.CustomAttrSpawner
[I 2021-09-16 23:28:00.380 JupyterHub app:2489] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.4.2
[I 2021-09-16 23:28:00.564 JupyterHub app:1838] Not using allowed_users. Any authenticated user will be allowed.
[I 2021-09-16 23:28:01.955 JupyterHub reflector:275] watching for pods with label selector='component=singleuser-server' in namespace data100-prod
[I 2021-09-16 23:28:02.655 JupyterHub reflector:275] watching for events with field selector='involvedObject.kind=Pod' in namespace data100-prod
[W 2021-09-16 23:28:06.954 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.956 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.958 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.962 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.969 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.970 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down
[W 2021-09-16 23:28:06.974 JupyterHub app:2194] REMOVED appears to have stopped while the Hub was down

```

Along with a bunch of messages like this:
```
[W 2021-09-16 23:29:07.424 JupyterHub user:767] REMOVED server never showed up at http://10.20.14.206:8888/user/REMOVED/ after 30 seconds. Giving up
[E 2021-09-16 23:29:07.517 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.0.40:8888/user/REMOVED/, shutting it down.
[I 2021-09-16 23:29:07.518 JupyterHub spawner:2620] Deleting pod data100-prod/REMOVED
```


I also saw this:
```
[I 2021-09-16 23:29:07.659 JupyterHub service:121] Spawning python3 -m jupyterhub_idle_culler --url=http://localhost:8081/hub/api --timeout=3600 --cull-every=600 --concurrency=10
[E 210916 23:29:27 ioloop:761] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f1c8794f4f0>>, <Future finished exception=HTTP 599: Operation timed out after 20000 milliseconds with 0 bytes received>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 120, in cull_idle
        resp = yield fetch(req)
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 113, in fetch
        return (yield client.fetch(req))
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
        value = future.result()
    tornado.curl_httpclient.CurlError: HTTP 599: Operation timed out after 20000 milliseconds with 0 bytes received
[I 2021-09-16 23:30:08.202 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@127.0.0.1) 60289.54ms
[E 2021-09-16 23:30:08.512 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.17.12:8888/user/REMOVED/, shutting it down.
[E 2021-09-16 23:30:08.628 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.0.4:8888/user/REMOVED/, shutting it down.
[E 2021-09-16 23:30:08.701 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.14.64:8888/user/REMOVED/, shutting it down.
[E 2021-09-16 23:30:08.787 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.45.236:8888/user/REMOVED/, shutting it down.
[E 2021-09-16 23:30:08.852 JupyterHub app:2178] REMOVED does not appear to be running at http://10.20.14.65:8888/user/REMOVED/, shutting it down.

```

**Comment by balajialg** [comment]
Service showed 503 errors from 4.30 - 5.15 PM! Based on the GSI's report, it was back to normal after that. 

@yuvipanda Could this issue be due to the last merge that happened? 

If not, What would be the potential way forward to avoid such scenarios? Should we increase the Data 100 hub's resource requirement?

**Comment by yuvipanda** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/30430/133753837-cff88e93-b7ee-4d85-b8a5-bbfd01f78713.png">

This is the node on which the data100 hub and proxy pod were located. The '100%' is 'full saturation of all CPUs', and you can see that we were almost there. I don't know if this is a symptom or a cause, but we can give data100 pods more CPU guarantees to eliminate that as a cause - https://github.com/berkeley-dsep-infra/datahub/pull/2772.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/30430/133754506-d4e86b88-5772-4563-b46e-37e49deba6bd.png">

This is actual CPU usage. It was never saturated (hit 100% of 1 core, which is max python processes can do), but perhaps that was because CPU wasn't available.

There's also a *lot* of user entries on the hub - about 8k. Sometimes, the CPU usage of the hub process scales linearly with total number of users (rather than active users). Upstream is working on fixing it, but in the meantime I've just deleted users who aren't currently active. This should help reduce CPU usage as well.

**Comment by yuvipanda** [comment]
@felder I looked at an alternative source of count of running users (from the hub), and you can see there's a gap in the data:

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/30430/133777847-b6619677-07dc-45d0-9d6a-428dd744944d.png">

When #2768  was merged, it restarted the data100-prod hub pod, and it took a long time to come back up!

<img width="690" alt="image" src="https://user-images.githubusercontent.com/30430/133778450-bf2d6180-3ae7-44bd-b7d5-dfd602291a2a.png">

This isn't common - restarts mostly take much less time. I don't see any other gaps in the last 7 days in this data:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/30430/133778542-25b6169e-9e19-4c5b-a4e3-ac54f47ce7e7.png">

So I looked at how long hub startup has taken:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/30430/133779012-0754e309-a34c-482b-9c3b-961e39365161.png">

And it took many many minutes. I think that is the cause of the 503s in this case. 

https://github.com/jupyterhub/jupyterhub/issues/2928 is probably super related.

I think the script I ran to remove unused users from the database (which should have no practical effects) should help with this.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyterhub-idle-culler/pull/30 might help too.

**Comment by yuvipanda** [comment]
I've run the script for the R hub (which cleaned up some 3235 users), DataHub (cleaned up some 14k users) and data100 hub (cleaned up some 7k users).

**Comment by yuvipanda** [comment]
One remaining mystery is why some user pods were missing / deleted during this time - I need to investigate that still. But I think that's a *symptom* rather than a cause.

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/2774 is the script for deleting unused users.

**Comment by felder** [comment]
@yuvipanda would it make sense to run #2774 or perhaps just clear db entirely during semester breaks?

**Comment by yuvipanda** [comment]
@felder yes! We should make a proper structured list
