### ISSUE TITLE
using gspread for Google Sheets to Pandas does not work

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#2690]
### Bug description

I am trying to follow along the documentation here
https://docs.datahub.berkeley.edu/en/latest/services/google-sheets.html

I have an old notebook from like 2019
and I can't get it to work
https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-88e%2Fecon-fa19&urlpath=tree%2Fecon-fa19%2Fwk03%2FDemand_Survey.ipynb

Has this service been discontinued?

### Environment & setup

- Hub: 
-Datahub
- Language: 
- Python

### How to reproduce

```python
from gspread_pandas import Spread
import os
import json
from oauth2client.service_account import ServiceAccountCredentials
from datascience import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Authenticate to Google
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_dict(json.loads(os.environ['GOOGLE_SHEETS_READONLY_KEY']), scope)

#This line reads in data from a google sheet that is the responses to the survey form
url = 'https://docs.google.com/spreadsheets/d/1Ias5oYZIQCQgVbjL-2jeeo04-tyg_4-hhPZZFPRFO1U/edit#gid=1350374019'

# Open the Google Sheet, and print contents of sheet 1 as a dataframe
spread = Spread(creds, url)
sheet_df = spread.sheet_to_df(sheet='Form Responses 1',header_rows=1,index=0)
print(sheet_df)
print (sheet_df.dtypes)
```

GIves me this error

```
OSError: No Google client config found.
Please download json from https://console.developers.google.com/apis/credentials and save as /home/jovyan/.config/gspread_pandas/google_secret.json
```

**Comment by ericvd-ucb** [comment]
I found this https://github.com/berkeley-dsep-infra/datahub/issues/1902
Ill check the syntax there

**Comment by balajialg** [comment]
@ericvd-ucb Were you able to get it to work? this is a good nudge to update our documentation!

If it's time-sensitive, I can share an R code that authenticates with the google server and reads from google sheets. Tested it in Datahub. Let me know!

**Comment by balajialg** [comment]
@ericvd-ucb Closing this assuming #1902 was helpful! Please feel free to reopen this issue if it is not.
