### ISSUE TITLE
Could not use armadillo library of C++

### ISSUE THREAD

**Issue by JiashuLiang** [berkeley-dsep-infra/hubs#2695]
### Bug description

When I try to use the armadillo library of C++, g++ will report this error:

`(notebook) jovyan@jupyter-jsliang:~/Discussion/Dis2$ g++ -o arma arma.cpp `
`arma.cpp:2:10: fatal error: armadillo: No such file or directory `
`2 | #include <armadillo>`
`compilation terminated.`

### Environment & setup

- Hub:  ~~Datahub~~ eecs
- Language: C++, 

### How to reproduce
1. [Link](https://eecs.datahub.berkeley.edu/user/jsliang/lab) to Datahub instance
2. Add one line " #include <armadillo>" to one C++ file
2. Compile this file 'g++ -o arma arma.cpp'
3. See error

**Comment by balajialg** [comment]
**Additional Context**: Professor has an assignment next week and wants to get this library to work so that students have a seamless experience. 

**Pasting the email received:**
_Jiashu tried to link with armadillo on the datahub and g++ couldn't find either the include files or the libraries. Students have  homework due in a week and they need to use this library. Please, could you check with/talk to the installers and see if the problem can be addressed as soon as possible. Thank you very much for your help on this issue_


@felder Thoughts on the feasibility of this request?

**Comment by felder** [comment]
@balajialg

Looks like armadillo is available as a system package.

```
# apt search armadillo
Sorting... Done
Full Text Search... Done
libarmadillo-dev/focal,focal 1:9.800.4+dfsg-1build1 amd64
  streamlined C++ linear algebra library - Headers

libarmadillo9/focal,focal 1:9.800.4+dfsg-1build1 amd64
  streamlined C++ linear algebra library
```

So assuming this version of the package is ok and the system g++ is what's being used, it seems feasible.

@yuvipanda would adding the above to the list of packages apt installs for the datahub image be the reasonable course of action here?

**Comment by felder** [comment]
It seems quite likely that above is correct since I believe on datahub the g++ being called is the system one:

```
jovyan@jupyter-felder:~$ which g++
/usr/bin/g++
jovyan@jupyter-felder:~$ ls -l /usr/bin/g++
lrwxrwxrwx 1 root root 5 Mar 20  2020 /usr/bin/g++ -> g++-9
jovyan@jupyter-felder:~$ ls -l /usr/bin/g++-9
lrwxrwxrwx 1 root root 22 Aug  8  2020 /usr/bin/g++-9 -> x86_64-linux-gnu-g++-9
jovyan@jupyter-felder:~$ ls -l /usr/bin/x86_64-linux-gnu-g++-9
-rwxr-xr-x 1 root root 1158288 Aug  8  2020 /usr/bin/x86_64-linux-gnu-g++-9
jovyan@jupyter-felder:~$
```

**Comment by felder** [comment]
@balajialg what class is this for, how long do they need it, etc? basically this should've been filed using the package-request template as that's really what's being asked for here.

**Comment by felder** [comment]
I'm going to bundle this in with the same commit for #2696.

It seems unlikely installing this will break anything even if it is not the right thing to do.  Depending on how long the build takes, I may not get this into prod before Tuesday.

**Comment by balajialg** [comment]
@felder this is fantastic! thank you so much for taking your time to do this. You are right, it should have been a package request than a bug. 

**Course Details:**
Server Engineering for Scientific Computing class as part of Master of Molecular Science and Software Engineering (MSSE) degree program at the College of Chemistry

Most likely, they need it for the entire semester!

**Comment by felder** [comment]
It's going to be another hour before this makes it to staging.

I probably will not test this in staging until Tuesday morning.

**Comment by felder** [comment]
Works!

```
jovyan@jupyter-felder:~$ cat test.cpp
#include <armadillo>
#include <iostream>

int main() {
    std::cout << "Hello World!\n";
    return 0;
}
jovyan@jupyter-felder:~$ g++ -o test test.cpp
jovyan@jupyter-felder:~$ ./test
Hello World!
jovyan@jupyter-felder:~$ 
```

**Comment by balajialg** [comment]
Thanks a lot @felder! This is awesome work.

@JiashuLiang Feel free to reopen this issue if there are issues!

**Comment by JiashuLiang** [comment]
I still have this problem. Is it because my environment is wrong?

```
(notebook) jovyan@jupyter-jsliang:~$ cat test.cpp 
#include <armadillo>
#include <iostream>

int main() {
    std::cout << "Hello World!\n";
    return 0;
}(notebook) jovyan@jupyter-jsliang:~$ g++ -o test test.cpp
test.cpp:1:10: fatal error: armadillo: No such file or directory
    1 | #include <armadillo>
      |          ^~~~~~~~~~~
compilation terminated.
(notebook) jovyan@jupyter-jsliang:~$ which g++
/srv/conda/envs/notebook/bin/g++
(notebook) jovyan@jupyter-jsliang:~$ ls -l /usr/bin/g++
lrwxrwxrwx 1 root root 5 May 20  2019 /usr/bin/g++ -> g++-7
(notebook) jovyan@jupyter-jsliang:~$ ls -l /usr/bin/g++-9
ls: cannot access '/usr/bin/g++-9': No such file or directory
(notebook) jovyan@jupyter-jsliang:~$ ls -l /usr/bin/g++-7
lrwxrwxrwx 1 root root 22 Dec  4  2019 /usr/bin/g++-7 -> x86_64-linux-gnu-g++-7
(notebook) jovyan@jupyter-jsliang:~$ 
```

**Comment by felder** [comment]
@JiashuLiang which hub are you doing this in?  Your report says datahub.

When l login to https://datahub.berkeley.edu and type "which g++", I get /usr/bin/g++ pointing to g++-9.

**Comment by felder** [comment]
Looking at the link you posted...you're not using datahub...

You're using eecs hub.  That would be the problem.

**Comment by felder** [comment]
@balajialg @yuvipanda I don't know how to handle these issues which require conda packages since we typically have linking issues when we add conda packages.

**Comment by balajialg** [comment]
@felder - I am trying to understand the issue better, Is the fix you made in Datahub not replicable in the EECS hub?

**Comment by JiashuLiang** [comment]
I am sorry that I thought eecs datahub was just datahub at that time. 

> @JiashuLiang which hub are you doing this in? Your report says datahub.
> 
> When l login to https://datahub.berkeley.edu and type "which g++", I get /usr/bin/g++ pointing to g++-9.

**Comment by balajialg** [comment]
@JiashuLiang I can understand why it would be confusing! By when do you need the hub for your classes?

**Comment by felder** [comment]
@balajialg that is correct because EECS hub does not use system packages for g++.

**Comment by JiashuLiang** [comment]
@balajialg My students have used eecs datahub now. For this week, the armadillo is not necessary though it will be better if we can use it. But for the class next Thursday, we have to use it.

**Comment by JiashuLiang** [comment]
If armadillo could not be installed in eecs.datahub, we can move to datahub.
But there are two classes, one needs armadillo, another needs GUI and emacs to teach students gdb. Can Datahub provide both?

**Comment by felder** [comment]
@JiashuLiang I'm not certain a migration to datahub is required.  Let's see what @yuvipanda has to say about installing c++ libraries via conda first.  It looks like we have about a week to figure this out.

**Comment by felder** [comment]
What is a bit disconcerting about this, is I believe armadillo is already slated to be part of the conda installation.

https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/eecs/image/environment.yml#L24

**Comment by felder** [comment]
armadillo is indeed already installed.

```
(notebook) jovyan@jupyter-felder:~$ find /srv/conda/envs/notebook/ -name "*armadillo*"
/srv/conda/envs/notebook/lib/pkgconfig/armadillo.pc
/srv/conda/envs/notebook/lib/libarmadillo.so
/srv/conda/envs/notebook/lib/libarmadillo.so.9
/srv/conda/envs/notebook/lib/libarmadillo.so.9.900.5
/srv/conda/envs/notebook/conda-meta/armadillo-9.900.5-h7c03176_0.json
/srv/conda/envs/notebook/include/armadillo_bits
/srv/conda/envs/notebook/include/armadillo
(notebook) jovyan@jupyter-felder:~$ 
```

Now knowing that, I did a bit of googling and came across passing -I to g++.

This time (on eecs hub):

```
(notebook) jovyan@jupyter-felder:~$ cat test.cpp 
#include <armadillo>
#include <iostream>

int main() {
    std::cout << "Hello World!\n";
    return 0;
}
(notebook) jovyan@jupyter-felder:~$ g++ -o test test.cpp -I /srv/conda/envs/notebook/include
(notebook) jovyan@jupyter-felder:~$ ./test 
Hello World!
(notebook) jovyan@jupyter-felder:~$

```

@JiashuLiang let me know if that works for you.

**Comment by balajialg** [comment]
@felder Thanks for the hack! I accessed @JiashuLiang's instance and ran the code for the highlighted program. Sharing a snapshot of what I saw,

![image](https://user-images.githubusercontent.com/2306166/132416926-0611bc40-821a-47a6-83a1-31938e07d2c1.png)

It seems like the armadillo issue is gone! @JiashuLiang, please confirm!

**Comment by JiashuLiang** [comment]
Thanks a lot for your help! The problem is solved. By the way, "-larmadillo" command is needed otherwise there will be other bugs.

![image](https://user-images.githubusercontent.com/61406031/132422349-0e68f416-944b-4af8-b7cb-bd141049ba6c.png)

**Comment by JiashuLiang** [comment]
By the way, could you also help me update the GitHub version of eecs datahub?

**Comment by felder** [comment]
@JiashuLiang I'll open another issue for your request, can you comment in that issue for what version of github you need?

**Comment by felder** [comment]
@JiashuLiang see #2717
