### ISSUE TITLE
Request python package genomics for class IB 105 / ESPM 125

### ISSUE THREAD

**Issue by Elias326** [berkeley-dsep-infra/hubs#2696]
**Which package do you want installed?** genomics. For reference: (https://github.com/drewhart/geonomics)

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.** Datahub

**Which class will use this package?** IB 105 / ESPM 125

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?** Fall 2021

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?** https://github.com/drewhart/geonomics

**Comment by felder** [comment]
https://pypi.org/project/geonomics/
