### ISSUE TITLE
Request update of `ottr` R package for class PS 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#2700]
**Which package do you want installed?**
`ottr` was recently updated to 1.1.1.

`devtools::install_github("ucbds-infra/ottr@stable")`

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
PS 3
Fall 2021
Prof David Broockman

**Which semester will this package be used for?**
Fall 2021 and Spring 2022

**Any additional information we should know about?**
Not urgent. Update simply adds some useful functionality.

**Comment by yuvipanda** [comment]
Thanks for opening this! We should pin this to 1.1.1 (instead of `@stable`) so we can force an image rebuild when bumping version.
