### ISSUE TITLE
Newer git for eecs hub

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#2717]
**Which package do you want installed?**

newer git

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

eecs

**Which class will use this package?**

Server Engineering for Scientific Computing class as part of Master of Molecular Science and Software Engineering (MSSE) degree program at the College of Chemistry

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 2021?

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

**Comment by felder** [comment]
@JiashuLiang

Can you please comment here with what version of git you require or what functionality you require that is currently missing?

Also do you have a link to your class in https://classes.berkeley.edu ?  Lastly, is this just for Fall 2021?

**Comment by JiashuLiang** [comment]
Any version >=2.28 is acceptable. It's for Chem 279:
https://classes.berkeley.edu/content/2021-fall-chem-279-001-lec-001

I am not sure whether the GSI next year will use it but I think they will prefer the latest version.

**Comment by yuvipanda** [comment]
You can probably install it via environment.yml, as it is present in conda-forge

**Comment by felder** [comment]
Ran `conda install -c conda-forge git` on my server in staging which succeeded.

Verified it was picked up by my $PATH and was >= 2.28

```
(notebook) jovyan@jupyter-felder:~$ which git
/srv/conda/envs/notebook/bin/git
(notebook) jovyan@jupyter-felder:~$ git --version
git version 2.33.0
```

**Comment by felder** [comment]
Tested in staging, works!

**Comment by felder** [comment]
`git --version` reports 2.33.0 in prod.

**Comment by JiashuLiang** [comment]
Get it! Thanks a lot for the help these days! @felder
