### ISSUE TITLE
R Hub stalling on launch!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2733]
### Bug description
As reported by Eric VD,

![Image from iOS](https://user-images.githubusercontent.com/2306166/132785800-af2a3997-197f-4508-af2c-8ad49f601ee7.jpg)

### Environment & setup

- Hub: R Hub
- Language: R

**Comment by yuvipanda** [comment]
https://classes.berkeley.edu/content/2021-fall-polsci-3-001-lec-001 has about 300 students, I'm going to add it to the scale up calendar as suggested by @ericvd-ucb. This is them waiting for new nodes to come up.

**Comment by yuvipanda** [comment]
Added to calendar! https://calendar.google.com/calendar/u/0/r/eventedit/NWQ1Z3RtN2M5NzdjNjhpaGptbGlwa3JqdDBfMjAyMTA5MTRUMjM1MDAwWiBjX3M0N20zbTFudWozczgxMTg3azNiMmI1czVvQGc

**Comment by yuvipanda** [comment]
Let's close this after we validate that their next class goes ok?

**Comment by yuvipanda** [comment]
I can also see this in the graphs:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/30430/132807528-767c9e8c-07db-42b1-b67b-05af37abc803.png">


https://grafana.datahub.berkeley.edu/d/R3O4mbg7z/cluster-information?viewPanel=7&orgId=1&refresh=30s&from=now-12h&to=now

This is user servers waiting for a new node to come up.

**Comment by balajialg** [comment]
@yuvipanda sounds great! Thanks for looking into this!

@dbroockman, Can you please comment on how your next class went in this issue? It would help us with our next steps. Thanks!

**Comment by dbroockman** [comment]
I will let you know. We'll have ~320 students all requesting notes at the same time on Tuesday at 5:15 pm.

**Comment by yuvipanda** [comment]
Someone will need to keep an eye on https://grafana.datahub.berkeley.edu/d/R3O4mbg7z/cluster-information?viewPanel=7&orgId=1&refresh=30s during the start of the class at least once or twice. Pods in 'pending' state is what cause people to wait. It's ok if there are one or two for a minute, but larger numbers point to issues where users have to wait.

**Comment by ryanlovett** [comment]
Looks like it got as high as 14 on two occasions, at 7a and 9:10a for about 15m each.

![Screen Shot 2021-09-13 at 9 40 45 AM](https://user-images.githubusercontent.com/10248125/133123448-2571c142-afec-4313-b7a9-f560e1a7e5bb.png)

**Comment by yuvipanda** [comment]
@ryanlovett it was counting non-jupyter pods too - I just modified that graph to only count jupyter pods. The peaks went away.

**Comment by dbroockman** [comment]
Today in class ~350 people showed up at 5:15 and we still had a lot of students saying the notebook wouldn’t load.

**Comment by balajialg** [comment]
@dbroockman Sorry about that! Could see a big spike around 5.15 PM
![image](https://user-images.githubusercontent.com/2306166/133354516-ce4a1e01-79db-4353-a188-5275b36d1fbb.png)
![image](https://user-images.githubusercontent.com/2306166/133354590-1a1d19b2-4d68-4d93-a6ae-1ebcc0b479bb.png)

@yuvipanda Any idea whether the auto-scaling through the calendar happened prior to the class?

**Comment by yuvipanda** [comment]
Adding y axes to the graph, I can see there's ~60-70 pending users:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/30430/133459349-7d5ab5a0-8353-4a7a-a9a2-3d692c3d184e.png">

If you hover over the red line just before, you can see that the scale up did happen:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/30430/133459451-92d1b8e0-fdec-4f29-93dd-6d4074d9f09b.png">

You can also see more clearly from this graph of node counts that the number of nodes did go up

<img width="675" alt="image" src="https://user-images.githubusercontent.com/30430/133459546-6dc5b14a-8432-42e3-95eb-02ecb30b89f6.png">

So it looks like the node placeholder did bring up new nodes, but as new users came up yet another node popped up! And that is where users ended up, thus having to wait for the images to pull...

**Comment by yuvipanda** [comment]
Earlier I had moved all non-data8 hubs to the alpha pool. Now my inclination is to move some of them back to their own pools. Alpha pool can have all hubs that share the datahub image, and I can move to beta pool everything else. This at least means there won't be multiple different images being pulled when a new node comes up.

**Comment by balajialg** [comment]
@yuvipanda, that's helpful! Would moving to the beta pool affect the performance of the non-Data eight hubs that don't share the Datahub image?

**Comment by yuvipanda** [comment]
ok, I've moved other hubs to a beta nodepool - let's see how this goes today.

Longer term, I think the node-placeholder-scaler needs to be smarter as well, so new nodes aren't brought up when placeholder nodes can be used instead...

**Comment by balajialg** [comment]
@dbroockman How did the class go today? Were there any auto scaling issues?

**Comment by dbroockman** [comment]
No, no problems today. Today they are doing group work so it’s only around
100 concurrent notebooks. Tuesday it will be 350 again.

**Comment by balajialg** [comment]
@dbroockman Thanks for reporting! Will monitor logs during Tuesday's class.

**Comment by balajialg** [comment]
@dbroockman Did you face any issues with your class today? I could see few nonperforming pods in the dashboard. Wanted to confirm!

![image](https://user-images.githubusercontent.com/2306166/134257911-c6f4ae98-f06c-4571-83fe-61581720001f.png)

**Comment by dbroockman** [comment]
Class isn't until 5. Notebooks will start booting up en masse (around 350 of them) right at 5:15.

**Comment by dbroockman** [comment]
Live from class, we do have lots of students saying the notebooks won't open.

**Comment by dbroockman** [comment]
Generally, I would say today was as worse as it's been. We had dozens of students saying they couldn't get the notebook to load for a while. Took 10 minutes before everyone was able to get in.

Thanks for all your efforts on this. It's an in-class timed assignment that gets released at 5:12, so all the students all rush in at that time, 350 of them or so.

**Comment by balajialg** [comment]
@dbroockman Really sorry that the last fix didn't work! I can see a lot of nonperforming pods in the dashboard around 5.15 PM. 

![image](https://user-images.githubusercontent.com/2306166/134267099-5bf325f2-99f4-4928-903c-f1eaab407be8.png)

Active users using the hub
![image](https://user-images.githubusercontent.com/2306166/134267040-2f0cf96a-11f3-4937-9cd5-41f557f791d0.png)

Hub CPU
![image](https://user-images.githubusercontent.com/2306166/134267001-71599dc4-6fa1-4392-9aca-88ea69b293ca.png)


@yuvipanda Can we use the automated scheduler to allocate more resources between 5.10 - 5.40 PM? It looks like that's the slot where the assignment gets released, and the rush to access them happens.

**Comment by balajialg** [comment]
@felder Ran the GCP query to find if there are any helpful logs for the issue. I am not able to fetch any real-time log updates regarding this issue.  I assume there has to be some application-level error message that would have been logged since students couldn't access the hub. Correct me if I am wrong. Here is the query I ran,

```
labels."k8s-pod/release"="r-prod"
textPayload=~"\[E "
textPayload!~"metrics"
labels."k8s-pod/component"="singleuser-server"
```

**Comment by yuvipanda** [comment]
In this case, I think you won't find any errors - the pods are just waiting to start, and it takes that long for a new node to spin up. So it's a delay than an outright error, making it more difficult to figure out why it is problematic. A classic case of https://en.wikipedia.org/wiki/Thundering_herd_problem.

@dbroockman as a temporary (very temporary!) mesure, can you just ask your students to go to r.datahub.berkeley.edu ahead of time and log in? That should help spread out the load a bit, and give us time to figure out a better solution here.

**Comment by yuvipanda** [comment]
The node-placeholder did trigger an upscaling:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/30430/134355365-152e7992-00d2-4f2a-96e8-0b304a70c1de.png">

But more nodes were spun up just at the time of the class (just after 5pm):

<img width="691" alt="image" src="https://user-images.githubusercontent.com/30430/134355318-0199260f-1f86-4479-beea-4e8a85bf5020.png">

The important question is if the new users were put on the new nodes that were spun up by node-placeholder, or if additional nodes were spun up just for the new users. Ideally, new users should've been put up only on the nodes brought up by the node-placeholder based on the calendar event - this would leave nobody waiting, and this is what seems to happen for the most part on data8. But I'm not exactly sure how to properly measure this with our grafana charts alone.

**Comment by yuvipanda** [comment]
I've also given it 5 placeholder nodes (up from 3), so let's see how it goes.

**Comment by balajialg** [comment]
@yuvipanda Sounds good Yuvi! Let's see how next Tuesday's class goes.

@dbroockman Thanks for patiently working with us on this.

**Comment by balajialg** [comment]
@dbroockman How did your classes go yesterday? Did the latest change made by @yuvipanda have any effect during yesterday's class? Thanks again for your patience!

**Comment by dbroockman** [comment]
I think it helped, we only had maybe 5 students who had to wait 3 minutes or so.

**Comment by yuvipanda** [comment]
Thanks, @dbroockman! Did you instruct them to login to the hub earlier, or is this just the effect of the larger placeholder count?

**Comment by dbroockman** [comment]
Yes, I also gave them access to the assignment earlier so that students logged on over a longer length of time than before (basically whenever they showed up to class).

I can't disentangle the effects of the two changes, they both went into effect this past Tuesday.

**Comment by balajialg** [comment]
@dbroockman This is excellent news! Finally, Either both these strategies or one of them seem to solve the problem. Considering that, I am closing this issue for now. Please do open it again if you see this error reoccurring. Hope that works for you!
