### ISSUE TITLE
Changing the outreach message for requesting archived data!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2736]
# Summary

We recommend our users share their data archival requests to the ds-infra email list as part of the NFS server. Sharing the message that we communicate with users below, (Thanks for the heads up @felder )

_root@nfsserver-01:/export/datahubhomes-2020-07-29/homes/riohayakawa# cat WHERE-ARE-MY-FILES.txt
Your files have been archived due to inactivity.
Send an email to ds-infrastructure@lists.berkeley.edu from your berkeley.edu
email address to get a copy of your files. You must include the following
text to help us retrieve your file:
gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/your-calnet-id.tar.gz_

Instead of this process, I would like us to recommend users to make a Github issue for the following reasons,

1. Log all repetitive requests from our users into Github which we kind of use both as a ticketing/project management system.
2. Slowly sunset the usage of the ds-infra list for external communication with students

The message that I would like to add to such requests:
_Your files have been archived due to inactivity. If you want to request your files from previous semesters, please make a request using this template - https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml. We will be able to complete your request within three working days._

**Comment by balajialg** [comment]
**Open Question:**

Should students be forced to use GitHub to make this request?

**Comment by felder** [comment]
So to be clear, I'm changing this:

```
Your files have been archived due to inactivity.

Send an email to ds-infrastructure@lists.berkeley.edu from your berkeley.edu
email address to get a copy of your files. You must include the following
text to help us retrieve your file:

gs://filesarehere
```

to this:
```
Your files have been archived due to inactivity.

If you want to retrieve a copy of your files, please open a Data Archival Request via github here:
https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml

The following text is the link to your datahub folder, it must be included with your request:
gs://filesarehere
```

**Comment by felder** [comment]
@balajialg this is done for all the existing files on the server.

@yuvipanda can you please modify the archiver script accordingly?

**Comment by yuvipanda** [comment]
@felder I've modified the script now to use the new language (https://github.com/yuvipanda/homedir-archiver/blob/b0adec9533f2bf3eaa0d9343add08ced32e538ec/archiver/scanner.py#L18). This will affect all new files when we run the archiver again. But the current files will not be affected - I think they need a `find` and `sed` combination (or similar) to modify. How can I help with that?

**Comment by felder** [comment]
@yuvipanda I took care of changing the files already.
