### ISSUE TITLE
Docs reference master instead of prod

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#2756]
### Bug description

https://github.com/berkeley-dsep-infra/datahub/blame/staging/docs/admins/howto/new-packages.rst#L58

We have no master branch, only prod.

### Environment & setup

docs.datahub.berkeley.edu

### How to reproduce

`master` is referenced multiple times in https://docs.datahub.berkeley.edu/en/latest/admins/howto/new-packages.html?highlight=master#submitting-a-pull-request.

**Comment by balajialg** [comment]
Thanks for raising this @ryanlovett! Any idea where is the repository that hosts this jupyter book? I hope it isn't an old version using Jekyll as that might involve additional tasks to upgrade to the latest version using Sphinx.

**Comment by yuvipanda** [comment]
When https://github.com/berkeley-dsep-infra/datahub/blame/staging/docs/admins/howto/new-packages.rst#L58 is modified and merged, it'll automatically be built and deployed to docs.datahub.berkeley.edu by readthedocs.io. 

The documentation in this repo uses fairly vanilla [sphinx](https://www.sphinx-doc.org/en/master/). To test how it looks locally, you can:

```bash
cd docs
pip install -r requirements.txt
make html
open docs/_build/html/index.html
```
