### ISSUE TITLE
Request python package `ipython-sql` for class Data 100

### ISSUE THREAD

**Issue by alvinwan** [berkeley-dsep-infra/hubs#2767]
**Which package do you want installed?**

We plan to use the SQL iPython magic: https://github.com/catherinedevlin/ipython-sql . No rush to install by any particular date though. We'll plan to use a `%pip install ipython-sql` and if this PR gets in before lab, we'll simply drop that `%pip`.

**Are there specific package dependencies?**

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

Data 100

**Which class will use this package?**

Data 100 - @fperez and me

Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.

**Which semester will this package be used for?**

Fall 2021

This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**

*Using this package in lectures, so future iterations of the course may need it by default?

**Comment by felder** [comment]
https://pypi.org/project/ipython-sql/

**Comment by alvinwan** [comment]
Wow thanks @felder @yuvipanda @balajialg  for the super fast turnaround! Much appreciated.
