### ISSUE TITLE
Policy to handle requests for RAM/CPU allocation!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2785]
# Summary
We currently don't have a policy around what constitutes an acceptable request for RAM/CPU allocation. We do want to take a lot of such requests on a case-to-case basis which is understandable. I also know that each such request has financial implications and, to an extent, affects the performance of a specific hub. As a result, it needs to get decided with caution. However, escalating every request can also waste a lot of our time and our users' time. Defining what constitutes an acceptable request can be help @felder with quick decision-making to provision/escalate and reduce the delay that gets introduced due to the back and forth communication. 

I am proposing this policy to kickstart our discussion! It is entirely arbitrary and wants to stress the rule of thumb/policy we should strive to get at. Please feel free to articulate the ideal policy to handle such requests,

_Any requests for RAM allocation above 2 GB for a classroom with more than 100 students require a detailed review process at our end_

Is that a fair summary?

**Comment by felder** [comment]
@balajialg we may want to define something like:

Approve if:
ram * class size < 200GB

**Comment by balajialg** [comment]
> @balajialg we may want to define something like:
> 
> Approve if:
> ram * class size < 200GB

Carl's case might be a yes if we adopt this rule! This policy should have some overlap with #2670! We could use this space to narrow down the ideal policy.

**Comment by yuvipanda** [comment]
There are three factors here:

1. Number of students
2. RAM requested
3. Amount of time the resource increase is requested for.

For classes that need extra RAM for a week or two, we can be more generous than for ones that need it permanently.

How about this table:

| Duration | < 1 week | < 1 month | > 1 month |
| - | - | - | - |
| Auto-approve (student count * RAM) threshold | 600 GB | 400 GB |  200 GB |

And anything more we discuss.

CPU grants must always be discussed I think, as they are more complex than this - they are much more likely to affect performance of other people on the same node.

**Comment by balajialg** [comment]
@yuvipanda, this makes a lot of sense to me! Thanks for adding more nuance to the policy. I will also add this to the FAQ document for future reference.

**Comment by balajialg** [comment]
@felder Closing this issue for now. Please reopen if you want to make further edits to the proposed policy!
