### ISSUE TITLE
Request R package cummeRbund for class PlantBi135

### ISSUE THREAD

**Issue by seangallaher** [berkeley-dsep-infra/hubs#2793]
**Which package do you want installed?**

I need the R library called cummeRbund. It can be installed with bioconductor. Whatever is the current version should be fine. Here is the link:
https://bioconductor.org/packages/release/bioc/html/cummeRbund.html

**Are there specific package dependencies?**

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

**Which class will use this package?**
PlantBi135

https://classes.berkeley.edu/content/2021-fall-plantbi-135-001-lec-001

**Which semester will this package be used for?**
Current (fall 2021)

**Any additional information we should know about?**

**Comment by seangallaher** [comment]
I am using it with RStudio on the datahub. I.e. here:
https://datahub.berkeley.edu/user/gallaher/rstudio/

**Comment by felder** [comment]
This is a pretty significant dependency.  I'm also having issues with it.

Following the instructions here:
https://bioconductor.org/install/#install-bioconductor-packages
https://bioconductor.org/packages/release/bioc/html/cummeRbund.html

I'd like to note first it mentions R 4.1, which we're not using on the hub.  Attempting to install version 3.13 of the bioconductor-packages gives me the following error:


```
Error: Bioconductor version '3.13' requires R version '4.1'; use `BiocManager::install(version = '3.12')` with R
  version 4.0; see https://bioconductor.org/install
```

That aside, the installation takes quite a long time and asks questions about updating numerous other installed packages which is something that we probably should not do.  Ultimately I settled on trying this in my own hub environment (something you can also attempt to do):

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.12", update = FALSE)
BiocManager::install("cummeRbund", update = FALSE)
```

This seems to avoid having it ask about updating other packages.  However, doing that results in the following error output:

```
> BiocManager::install("cummeRbund", update = FALSE)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

Bioconductor version 3.12 (BiocManager 1.30.16), R 4.0.5 (2021-03-31)
Installing package(s) 'cummeRbund'
also installing the dependencies ‘VariantAnnotation’, ‘GenomicFeatures’, ‘ensembldb’, ‘BSgenome’, ‘biovizBase’, ‘Gviz’

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/VariantAnnotation_1.36.0.tar.gz'
Content type 'application/x-gzip' length 1727899 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/GenomicFeatures_1.42.3.tar.gz'
Content type 'application/x-gzip' length 1375333 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/ensembldb_2.14.1.tar.gz'
Content type 'application/x-gzip' length 3320259 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/BSgenome_1.58.0.tar.gz'
Content type 'application/x-gzip' length 6076433 bytes (5.8 MB)
==================================================
downloaded 5.8 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/biovizBase_1.38.0.tar.gz'
Content type 'application/x-gzip' length 2431860 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/Gviz_1.34.1.tar.gz'
Content type 'application/x-gzip' length 7254600 bytes (6.9 MB)
==================================================
downloaded 6.9 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/cummeRbund_2.32.0.tar.gz'
Content type 'application/x-gzip' length 2559079 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

* installing *source* package ‘GenomicFeatures’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Killed
ERROR: lazy loading failed for package ‘GenomicFeatures’
* removing ‘/opt/r/GenomicFeatures’
* installing *source* package ‘BSgenome’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Killed
ERROR: lazy loading failed for package ‘BSgenome’
* removing ‘/opt/r/BSgenome’
ERROR: dependencies ‘BSgenome’, ‘GenomicFeatures’ are not available for package ‘VariantAnnotation’
* removing ‘/opt/r/VariantAnnotation’
ERROR: dependency ‘GenomicFeatures’ is not available for package ‘ensembldb’
* removing ‘/opt/r/ensembldb’
ERROR: dependencies ‘GenomicFeatures’, ‘VariantAnnotation’, ‘ensembldb’ are not available for package ‘biovizBase’
* removing ‘/opt/r/biovizBase’
ERROR: dependencies ‘GenomicFeatures’, ‘ensembldb’, ‘BSgenome’, ‘biovizBase’ are not available for package ‘Gviz’
* removing ‘/opt/r/Gviz’
ERROR: dependency ‘Gviz’ is not available for package ‘cummeRbund’
* removing ‘/opt/r/cummeRbund’

The downloaded source packages are in
	‘/tmp/RtmpLnfaKN/downloaded_packages’
Warning messages:
1: In .inet_warning(msg) :
  installation of package ‘GenomicFeatures’ had non-zero exit status
2: In .inet_warning(msg) :
  installation of package ‘BSgenome’ had non-zero exit status
3: In .inet_warning(msg) :
  installation of package ‘VariantAnnotation’ had non-zero exit status
4: In .inet_warning(msg) :
  installation of package ‘ensembldb’ had non-zero exit status
5: In .inet_warning(msg) :
  installation of package ‘biovizBase’ had non-zero exit status
6: In .inet_warning(msg) :
  installation of package ‘Gviz’ had non-zero exit status
7: In .inet_warning(msg) :
  installation of package ‘cummeRbund’ had non-zero exit status

> 
```


I'm not sure how to resolve this issue.

@seangallaher do you have any ideas?

**Comment by seangallaher** [comment]
Thanks for your help. It was so easy on my local installation of R. I didn't realize it would be so hard on the DataHub. I will have about 46 inexperienced students trying to do this, so I was hoping to avoid having everyone do this individually in their own instance. I have tried to install other packages via Bioconductor, and none has worked so far. I don't imagine that we could update R or Bioconductor to their latest.

**Comment by felder** [comment]
@seangallaher I do not believe we could accommodate upgrading R at this time.  @yuvipanda or @ryanlovett please let me know if I'm wrong.

Bioconductor 3.12 is for sure the latest version that will run on the hub with R being < 4.1

While I'm not ruling out getting cummeRbund 2.32.0 (the version I believe is packaged as part of bioconductor 3.12) installed, I simply do not know what needs to be done to resolve the errors above to make its dependencies happy.  Thus if you knew of a way to get that work in your hub environment (preferably without also upgrading all the other packages aka with upgrade = FALSE), I could incorporate those changes into the image which would make it available to your students.

**Comment by seangallaher** [comment]
Are you able to install any packages from BioConductor? I still have not had any luck with this.

**Comment by balajialg** [comment]
Thanks, @felder for looking into this! @seangallaher Are there alternative packages that you would recommend if we are stuck with BioConductor installation?

Looking at the issues/PR history, I am not able to find any packages which were installed via BioConductor

**Comment by felder** [comment]
@seangallaher The BioConductor base install seems to work and I tried this package:
https://www.bioconductor.org/packages/3.12/bioc/html/zlibbioc.html

```
Bioconductor version 3.12 (BiocManager 1.30.16), R 4.0.5 (2021-03-31)
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/site-library
  packages:
    littler
Old packages: 'ade4', 'arrow', 'blogdown', 'bookdown', 'bslib', 'cpp11', 'dagitty', 'digest', 'dtplyr',
  'e1071', 'future', 'gert', 'ggthemes', 'git2r', 'googlesheets4', 'gstat', 'hdf5r', 'htmlwidgets',
  'httpuv', 'imager', 'infer', 'IRkernel', 'kableExtra', 'Lahman', 'latex2exp', 'lattice', 'lfe', 'mapview',
  'margins', 'matrixStats', 'mgcv', 'multcomp', 'nlme', 'nycflights13', 'parallelly', 'pdftools', 'pegas',
  'pkgload', 'plotly', 'proj4', 'RandomFields', 'RandomFieldsUtils', 'RCurl', 'reticulate', 'rgdal',
  'rgeos', 'rgl', 'rJava', 'rlas', 'rlist', 'RMariaDB', 'rmarkdown', 'rngtools', 'roxygen2', 'rpart.plot',
  'RPostgres', 'rsconnect', 'RSQLite', 'rticles', 'shape', 'shiny', 'sm', 'spatialreg', 'spatstat', 'spdep',
  'summarytools', 'testit', 'tidycensus', 'tidyverse', 'tigris', 'tmap', 'tufte', 'vioplot', 'vroom',
  'waldo', 'xaringan', 'xfun', 'XML'
Update all/some/none? [a/s/n]: 
n
Warning message:
package(s) not installed when version(s) same as current; use `force = TRUE` to re-install: 'zlibbioc' 
> packageVersion("zlibbioc")
[1] ‘1.36.0’

>
```

Had a similar seemingly successful result with the following:
https://www.bioconductor.org/packages/3.12/bioc/html/DelayedArray.html
https://www.bioconductor.org/packages/3.12/bioc/html/S4Vectors.html
https://www.bioconductor.org/packages/3.12/bioc/html/HDF5Array.html

Here's an example of me force reinstalling HDF5Array successfully:

```
> BiocManager::install("HDF5Array", force = TRUE, update = FALSE)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

Bioconductor version 3.12 (BiocManager 1.30.16), R 4.0.5 (2021-03-31)
Installing package(s) 'HDF5Array'
trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/HDF5Array_1.18.1.tar.gz'
Content type 'application/x-gzip' length 8071706 bytes (7.7 MB)
==================================================
downloaded 7.7 MB

* installing *source* package ‘HDF5Array’ ...
** using staged installation
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c H5DSetDescriptor.c -o H5DSetDescriptor.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c R_init_HDF5Array.c -o R_init_HDF5Array.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c S4Vectors_stubs.c -o S4Vectors_stubs.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c global_errmsg_buf.c -o global_errmsg_buf.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5dimscales.c -o h5dimscales.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5mread.c -o h5mread.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5mread_helpers.c -o h5mread_helpers.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5mread_sparse.c -o h5mread_sparse.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5mread_starts.c -o h5mread_starts.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c h5mread_startscounts.c -o h5mread_startscounts.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I'/opt/r/S4Vectors/include' -I'/opt/r/Rhdf5lib/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-tRgc13/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c uaselection.c -o uaselection.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o HDF5Array.so H5DSetDescriptor.o R_init_HDF5Array.o S4Vectors_stubs.o global_errmsg_buf.o h5dimscales.o h5mread.o h5mread_helpers.o h5mread_sparse.o h5mread_starts.o h5mread_startscounts.o uaselection.o /opt/r/Rhdf5lib/lib/libhdf5_hl.a /opt/r/Rhdf5lib/lib/libhdf5.a /opt/r/Rhdf5lib/lib/libsz.a -lcrypto -lcurl -lz -L/usr/lib/R/lib -lR
installing to /opt/r/00LOCK-HDF5Array/00new/HDF5Array/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (HDF5Array)

The downloaded source packages are in
	‘/tmp/RtmpLnfaKN/downloaded_packages’

> 
```

However, I found this would not install:
https://www.bioconductor.org/packages/3.12/bioc/html/GenomicScores.html

```
> BiocManager::install("GenomicScores", update = FALSE)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

Bioconductor version 3.12 (BiocManager 1.30.16), R 4.0.5 (2021-03-31)
Installing package(s) 'GenomicScores'
trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/GenomicScores_2.2.0.tar.gz'
Content type 'application/x-gzip' length 2611957 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

* installing *source* package ‘GenomicScores’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Killed
ERROR: lazy loading failed for package ‘GenomicScores’
* removing ‘/opt/r/GenomicScores’

The downloaded source packages are in
	‘/tmp/RtmpLnfaKN/downloaded_packages’
Warning message:
In .inet_warning(msg) :
  installation of package ‘GenomicScores’ had non-zero exit status

> 
```

So it seems like it's hit or miss.

**Comment by seangallaher** [comment]
Wow, this is weird. I was able to install Genomic Scores, which did not work for you.

Sorry I am a little new to this. How do I re-set my instance of RStudio so that it will be the same as what my students get when they first log on?

**Comment by felder** [comment]
@seangallaher do that, you just need to restart your server.

You can reach the controls for doing that by going here:
https://datahub.berkeley.edu/hub/home

**Comment by felder** [comment]
@seangallaher you were able to get GenomicScores installed eh?  I wonder if it's memory availability issue, perhaps the packages require more RAM than is available in the instance to build.

**Comment by felder** [comment]
Although hmm I don't think so because when I run top in a terminal and attempt to install GenomicScores I don't see that as being an issue.

**Comment by felder** [comment]
@seangallaher so on a whim I decided to fire up docker on my desktop and execute the datahub docker image.  The install completes successfully there, thus I actually think it might be likely that it is running out of RAM in the instance when attempting to install the package.

So it's possible that the image build process will succeed.  However, I have another question for you.  Assuming this is a resource issue, do you have any indication of how much RAM your assignment will require?  Since it fails when actually attempting to load the package (as opposed to building it) this may be a concern.

**Comment by seangallaher** [comment]
That is interesting. I can work with a toy dataset to keep the memory requirements low. But I am completely stuck if the students cannot install any of the needed packages. Each instance gets 2 GB, right? I think that should be fine for my students. Would it be possible to try installing cummeRbund on an instance with 4 or more GB and see if that works?

**Comment by felder** [comment]
@seangallaher 
Each instance gets 1GB.

I'm already one step ahead of you.  I'm telling docker to only allocate 1GB of RAM to my container and I'm going to execute the build process again.  Additionally I'm going to time it because another concern I have is the amount of time this particular package installation will add to the overall build process.

**Comment by felder** [comment]
@seangallaher yes I was able to confirm this issue.

With only 1GB allocated to my local instance, I can watch memory usage spike and then the build process dies.

So I think in theory we should be able to get this installed.  However, would you have any interest in profiling your assignment on your machine to see if it will exceed the current 1GB default memory limit when you load and try to use the libraries?

**Comment by seangallaher** [comment]
Sure. Just tell me what to do.

**Comment by felder** [comment]
@yuvipanda @balajialg I'll also note that with 4 cores allocated to my container it takes 12 minutes for the build.

**Comment by felder** [comment]
@seangallaher

Newer versions of rstudio seem to have this built in, but alas the version on the hub is older:
https://support.rstudio.com/hc/en-us/articles/1500005616261-Understanding-Memory-Usage-in-the-RStudio-IDE

You mentioned R 4.1, though.  If you've got the newer rstudio on your machine you might be able to do the above to get some idea of what you're looking at.  Granted it's not the same version as on the hub so YMMV, but for a ballpark estimate it probably will work.

Alternatively, you can also use tools available in your OS to view rstudio's memory usage while you run the assignment.

On linux that would be top, on os-x that would be "activity monitor", and on windows that would be the "task manager"

In the meantime I think we are getting closer to a possible resolution here.

**Comment by seangallaher** [comment]
I ran the script with the full data set and it used about 1.5 GB, so that is a problem. As I said above, I can use a smaller toy dataset to help out with that. HOWEVER, just loading cummeRbund is taking the memory up to about 1 GB. So unless I can get instances of RStudio for my students with >1 GB, this whole enterprise is doomed.

**Comment by felder** [comment]
@seangallaher how many students are in your class?

**Comment by seangallaher** [comment]
I think we are at 46 now. Under 50 for sure.

**Comment by felder** [comment]
@seangallaher ok i think we can make this work.  I can increase the RAM allocation for your students to 2GB.

How soon do you require this?

**Comment by seangallaher** [comment]
That would be amazing. They would need the larger allocation by Wednesday morning (9/29) if that is at all possible. It would only be for a week and a half, as we will be done with this module on Friday, 10/8. Would that work?

**Comment by felder** [comment]
@seangallaher yeah that should likely work.  The RAM allocation is easy to do, my main concern now is getting these packages through the build process.  I’ll know more about that on Monday when I try it.  Also there might be other hubs that would be better suited to your class.  For example the biology hub.

@petersudmant what do you think?

**Comment by felder** [comment]
@seangallaher oh can you please give me the url to your course as listed in https://classes.berkeley.edu ?

**Comment by seangallaher** [comment]
https://classes.berkeley.edu/content/2021-fall-plantbi-135-001-lec-001

**Comment by felder** [comment]
@seangallaher thanks!

**Comment by seangallaher** [comment]
I didn't know there was a separate biology hub. I just tried it and I was able to install and load cummeRbund, and run my whole script. I don't know if the biology hub has more resources per instance, but switching to it seems to have solved me problem. Assuming my students can use that too, I guess I am good. Thanks for all of your help!!!!

**Comment by seangallaher** [comment]
@felder @balajialg  I was so excited that I was able to install my package on biology.datahub, that I forgot about my original request. Could we install cummeRbund on RStudio on the biology hub?  In my instance, it installs just fine with:
BiocManager::install("cummeRbund")
It just takes a long time to install, and I would hate to waste half of my limited class time trying to get 46 inexperienced students to install it. 

Thanks!

**Comment by petersudmant** [comment]
Yes! cummeRbund  is a  great idea! I'll  do  that right now. 

Indeed the  biology hub is for  such biology related stuff!!!!

>> TO BE SURE @seangallaher do u need anything  else ASAP? (was trying to figure that out going through the thread above)

**Comment by petersudmant** [comment]
OK, fyi -> this is installed.   It's in staging and I haven't merged to prod yet because there's all sorts of stuff floating around in there that i wanted to ask about. But, should be good to go shortly.

**Comment by felder** [comment]
@seangallaher @petersudmant this is going to work out nicely.  Let me know if you have any questions and/or assign me as a reviewer for the PR to prod and i’ll look at it Monday.

**Comment by seangallaher** [comment]
@petersudmant 
Thanks so much for helping me get this set up. As of right now (Monday morning) I do not see the cummeRbund libraries on my instance of biology.datahub.berkeley.edu. Is that something that will be available by Wednesday morning? Thanks!

**Comment by petersudmant** [comment]
@seangallaher I have just initiated the merge - so, should be ready to roll in 60-90 mins or so!

**Comment by seangallaher** [comment]
@petersudmant 
Fantastic! I thank you and my students will thank you for saving us from 20 minutes of grief in class trying to get cummeRbund installed on 46 different instances of RStudio.

**Comment by balajialg** [comment]
Thanks a lot, @petersudmant @felder, for helping @seangallaher by recommending the biology hub and installing the packagecummeRbund!

@seangallaher, I am closing this issue for now. However, if you face any issues with the package, please do reopen this issue and tag us. In the meantime, Good luck with your modules.
