### ISSUE TITLE
Request R package epitools for class PH 252

### ISSUE THREAD

**Issue by zbutzin** [berkeley-dsep-infra/hubs#2801]
### Package Name

epitools

### Hub details

- Hub: Public Health DataHub
- Language: R

### Course Name

[PBHLTH 252 - Patrick Bradshaw](https://classes.berkeley.edu/content/2021-fall-pbhlth-252-001-lec-001)

### Semester Details

Fall 2021 (annual)

### Additional Information

https://cran.r-project.org/web/packages/epitools/

Thank you!

**Comment by felder** [comment]
@zbutzin is there any way you would be able to test package installation in your own hub environment and then submit a single issue with all of your dependency requirements?  It'd be a lot easier for me to install all of your dependencies at once as opposed to a whack-a-mole approach.

This is the sixth package request in a bit over a month.
https://github.com/berkeley-dsep-infra/datahub/issues?q=is%3Aissue+252

Alternatively maybe I should teach you how to submit your own PRs.  Is that something you'd be open to?

**Comment by felder** [comment]
I'm going to bundle this in with issue #2802
