### ISSUE TITLE
Request R package multcomp for class PH 252

### ISSUE THREAD

**Issue by zbutzin** [berkeley-dsep-infra/hubs#2802]
### Package Name

multcomp

### Hub details

- Hub: Public Health DataHub
- Language: R

### Course Name

[PBHLTH 252 - Patrick Bradshaw](https://classes.berkeley.edu/content/2021-fall-pbhlth-252-001-lec-001)

### Semester Details

Fall 2021 (annual)

### Additional Information

https://cran.r-project.org/web/packages/multcomp/index.html

Thank you for your help!

**Comment by felder** [comment]
@zbutzin is there any way you would be able to test package installation in your own hub environment and then submit a single issue with all of your dependency requirements? It'd be a lot easier for me to install all of your dependencies at once as opposed to a whack-a-mole approach.

This is the seventh package request in a bit over a month.
https://github.com/berkeley-dsep-infra/datahub/issues?q=is%3Aissue+252

Alternatively maybe I should teach you how to submit your own PRs. Is that something you'd be open to?

**Comment by zbutzin** [comment]
@felder Thanks for reaching out, and sorry to make things challenging for you. 

I am open to whatever solution you recommend. For context, we converted this entire course to Jupyter notebooks over the summer (previously pdfs and standalone .rmd). At the end of the summer, we attempted to check which packages were missing so that we could submit a single package request. We must have done so incorrectly (not sure whether the package list on the main DataHub differs from the Public Health DataHub) because as students have loaded the Jupyter notebooks through datahub, we have encountered many more missing packages. 

A first step could be for me to upload all remaining lecture materials to Public Health DataHub again to check for missing packages and dependencies, now that I'm more familiar with the platform.

I'd be happy to move forward with any solution you recommend. Thanks again for all of your help.

**Comment by felder** [comment]
@zbutzin yes, the public health hub uses a different image than datahub so it does have different packages.

I'm willing to provide what assistance I can if you need it, but yeah if possible I'd really appreciate it if you could try uploading your remaining lecture materials to the public health hub, test, and then submit an issue with all of your missing packages so I can work on adding them all at once.

Additionally, you can install packages in your own hub environment (these changes do not persist when your server restarts) which should allow you to work through each notebook and get a good idea of everything that is missing.

In the meantime I'll work on your existing open requests and get those installed.

**Comment by zbutzin** [comment]
@felder Thank you so much for your help. I think that must be the issue -- we originally created the notebooks and checked for missing packages in DataHub, but the materials are now in Public Health Hub. Sorry for this oversight and the complications it's caused.

I will work on uploading the remaining lecture materials, check for missing packages and dependencies, and will submit a single issue with all missing packages. Thanks again for all of your help through this process.

**Comment by felder** [comment]
When installing via rstudio in staging I get epitools 0.5-10.1 and multcomp 1.4-17 which both match with the latest versions in cran.

**Comment by felder** [comment]
It's now available in prod:

```
> packageVersion("multcomp")
[1] ‘1.4.7’
> packageVersion("epitools")
[1] ‘0.5.10.1’

>
```
