### ISSUE TITLE
EECS Hub: No Space left on Device [BLOCKER]

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2808]
### Bug description

@Quizenger raised this issue in the Slack channel!

![Image from iOS](https://user-images.githubusercontent.com/2306166/135307570-61123ff4-a4a2-4127-8c48-c62e38a5432e.png)

### Environment & setup

- Hub: EECS Hub
- Language: Python

### How to reproduce

Try accessing a notebook in the EECS hub

![image](https://user-images.githubusercontent.com/2306166/135308056-a0c729bc-f9b6-4a90-b060-35c7a9cc65cb.png)

**Comment by balajialg** [comment]
@felder 5xx Error logs 
![image](https://user-images.githubusercontent.com/2306166/135308188-0f0247fc-c159-4475-9b0d-e4aedcd6757f.png)

EECS Hub Memory Usage:
![image](https://user-images.githubusercontent.com/2306166/135308888-13ecaf3c-c90f-475e-9050-681e8144f440.png)

@felder Could this be similar to this [error](https://github.com/berkeley-dsep-infra/datahub/pull/2749)?

**Comment by balajialg** [comment]
@felder @ryanlovett @yuvipanda 

Would increasing the storage [here](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/eecs/config/prod.yaml) to 8Gi help?

**Comment by ryanlovett** [comment]
@balajialg That is the size of storage for the hub's database volume, not user storage. The NFS disk is full:
```
rylo@nfsserver-01:~$ df -h /export/homedirs-other-2020-07-29/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        5.0T  5.0T  180K 100% /export/homedirs-other-2020-07-29
```
I'll have to lookup how the storage has been setup and if it is possible to grow it. I'll also see if some unnecessary things can be removed.

**Comment by balajialg** [comment]
@ryanlovett Thanks for jumping in! Your support would be crucial, considering an EECS 16A lab is happening right now, and it is a blocker for every student.

**Comment by ryanlovett** [comment]
@felder replied on slack that he is handling it

**Comment by balajialg** [comment]
> @felder replied on slack that he is handling it

Thanks, @ryanlovett!

**Comment by felder** [comment]
The disk on the nfs server used by this particular hub was full.  I increased it from 5TB to 7.5TB.

**Comment by balajialg** [comment]
@felder Data 8 also had the same issue today morning! Is the NFS file storage issues common across all the hubs?
![Screen Shot 2021-09-29 at 9 26 02 AM](https://user-images.githubusercontent.com/2306166/135364198-33d5d22e-7b9d-4734-9198-bda1426427f8.png)

**Comment by yuvipanda** [comment]
data8 and eecs hubs shared NFS disks - see #2815

**Comment by balajialg** [comment]
@yuvipanda that's helpful!
