### ISSUE TITLE
[EPIC] Tracking NFS server filesystem monitoring!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2811]
# Summary

Currently, we track the NFS usage data across all hubs using command-line tools. However, tracking this data in a centralized way can make it easier for us to understand which hubs require additional memory or needs to reduce their memory usage (by other mechanisms such as reducing the size of the dataset, etc.). #2808 is an example of this kind of issue we may run into if this data is not tracked on a consistent basis.

Also, @felder's analysis showed that certain hubs such as genomics had a spike in their disk usage. Having this data reported would help us understand such unique cases!

```
--- /export/homedirs-other-2020-07-29 ----------------------------------------------------------------------------------
    2.4 TiB [##########] /eecs
    1.6 TiB [######    ] /genomics
  339.1 GiB [#         ] /dlab
  240.7 GiB [          ] /data8
  209.1 GiB [          ] /data102
   84.4 GiB [          ] /cs194
   75.5 GiB [          ] /prob140
   27.4 GiB [          ] /julia
   20.7 GiB [          ] /buds-2020
   17.8 GiB [          ] /stat159
    6.7 GiB [          ] /stat89a
    6.0 GiB [          ] /workshop
  408.0 KiB [          ] /xfsconfig
    4.0 KiB [          ]  -
    4.0 KiB [          ]  wat
@   0.0   B [          ]  highschool
@   0.0   B [          ]  biology

```
# User Stories

- As a Datahub team member, I want an easy way to know the NFS disk usage across all the hubs so that I can grow/trim the disk space in a specific hub whenever required.

# Acceptance criteria

- If I need to know the NFS disk usage across all the hubs, I can check the centralized dashboard such as grafana to know the filesystem-related stats across different hubs.

# Important information
@ryanlovett shared an [example](https://grafana.com/grafana/dashboards/14173) which might be relevant
@felder highlighted that this use case would also be useful for Data 8x monitoring!

# Tasks to complete

- Identify ways to monitor the NFS server filesystem usage!
- Analyze the feasibility of visualizing the disk usage data in a centralized dashboard
- Evaluate whether prometheus/grafana configuration would allow for such reporting

**Comment by yuvipanda** [comment]
Would be great to have per-hub NFS stats reported.

https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/directory-size.sh is an example of how prometheus_node_exporter (which we already run) can be configured to collect per-directory metrics. Those can then be visualized on grafana.

**Comment by balajialg** [comment]
@yuvipanda that will be fantastic! I am scoping this for the October sprint for now. If you think it would not be feasible, I can move it to our backlog.

From an implementation perspective, Is this a low-hanging fruit or requires extensive custom scripting?

**Comment by yuvipanda** [comment]
Ok so I've added https://grafana.datahub.berkeley.edu/d/R3O4mbg7z/cluster-information?orgId=1&viewPanel=26, and set it to alert  via pagerduty when any disk is over 90% full.

**Comment by felder** [comment]
@yuvipanda can this be modified to show mount points instead of device names?

**Comment by yuvipanda** [comment]
@felder done

**Comment by balajialg** [comment]
@felder @yuvipanda I assume that the acceptance criteria for this issue is met using this [dashboard](https://grafana.datahub.berkeley.edu/d/j2uCW9vGz/nfs-stats?orgId=1&refresh=30s). Considering that, I am closing this issue. If you think otherwise, please feel free to reopen the issue. Thanks!
