### ISSUE TITLE
Add Morris and Van Dusen to Data 8x hub

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#2813]
### Your Name

Eric Van Dusen 

### Affiliated Course Name

Data 8x

### Role

admins

### Name of the Hub

- 

### List of Usernames

- 

> 

> 

### End Date

-

**Comment by balajialg** [comment]
@ericvd-ucb @sean-morris Can you follow the below steps and share your EdX Id? Need that for providing admin access!

EdX IDs look like the random strings eg: c741d11d7f0bed9930e04276115b1a37. 

You can find yours by:

1. Enrolling in the class
2. Launching into the lab
3. Finding the user id from the control panel

**Comment by sean-morris** [comment]
Here you go: 
bd1e7c64c6f5faddbf6b32af3010cf75

Thanks

**Comment by balajialg** [comment]
@sean-morris Thank you! Once @ericvd-ucb  shares his id will create a PR for admin access!

**Comment by balajialg** [comment]
@sean-morris FYI, We have provided admin access!

**Comment by sean-morris** [comment]
great thanks. @balajialg

**Comment by balajialg** [comment]
@ericvd-ucb Closing this issue considering the urgency! Please feel free to reopen based on your need.
