### ISSUE TITLE
Allow ssh requests from the hub

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2814]
# Summary

Correct me if I'm wrong, but it seems that outbound SSH connections are currently forbidden...

Once I set up my ssh agent, cloning a tiny repo over SSH never completes:

```
jovyan@jupyter-fernando-2eperez[~]> ssh-github 
Agent pid 219
Enter passphrase for /home/jovyan/.ssh/id_ed25519_github: 
Identity added: /home/jovyan/.ssh/id_ed25519_github (fernando.perez@berkeley.edu)
jovyan@jupyter-fernando-2eperez[~]> git clone git@github.com:fperez/mytoy.git
Cloning into 'mytoy'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
```

# User Stories

In order to develop directly on the hub, cloning repos over SSH with a properly configured agent is a very convenient workflow.  I do the same on other hubs, but it seems to not be possible at least on the D100 hub.

It would be great to be able to do this, thanks for considering it!

# Acceptance criteria

Cloning/pulling/pushing to github over SSH works.

**Comment by yuvipanda** [comment]
We explicitly allow the ports outbound network communication can take place over - specified [here](https://github.com/berkeley-dsep-infra/datahub/blob/5718a15c9340c4d10e2fece33df70dbddc307f0e/hub/values.yaml#L100). We can add ssh port 22 to it fairly easily.

The bigger question is to determine what benefit we get from filtering outbound ports, and see if we should consider just removing that as a limitation. I'll try form some thoughts too, but also pinging @ryanlovett and @felder who might have opinions. Removing outbound port restrictions will also fix FTP (#1789), making @cboettig happy.

**Comment by yuvipanda** [comment]
Particularly, we allow outbound 443/80 to the wide internet with no restrictions. So, users can in fact tunnel out to wherever they want on the internet via that.

However, there is a lot of value in allowing only explicitly listed ports when accessing *internal IPs*. For example, there's no reason for user pods to hit promethues server or the configurable-http-proxy API endpoint. So maybe we should try and find a way to allow unlimited outbound internet access but tightly controlled access to things on the internal network?

**Comment by fperez** [comment]
Big +1 to opening up these port restrictions - my ssh case and @cboettig's for FTP are both I think very legitimate use cases that would be greatly helped. While you consider the bigger design issues, if this is viable now, it would be greatly appreciated.

Thanks for the quick response!

**Comment by ryanlovett** [comment]
@yuvipanda The only harm I can think of is unexpectedly high data egress charges. If there was a big bill, can the outbound data be tracked to a class or user?

Looks like egress is $0.12/GB when monthly usage is under 1TB. So 100 students each sending a 10MB file would cost $0.12. Guessing it won't be a problem.

**Comment by yuvipanda** [comment]
@fperez ssh should be open in a few minutes :)

**Comment by fperez** [comment]
```
jovyan@jupyter-fernando-2eperez[~]> ssh-github
Agent pid 73
Enter passphrase for /home/jovyan/.ssh/id_ed25519_github: 
Identity added: /home/jovyan/.ssh/id_ed25519_github (fernando.perez@berkeley.edu)
jovyan@jupyter-fernando-2eperez[~]> git clone git@github.com:fperez/mytoy.git
Cloning into 'mytoy'...
The authenticity of host 'github.com (140.82.113.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.113.3' (RSA) to the list of known hosts.
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 33 (delta 14), reused 26 (delta 7), pack-reused 0
Receiving objects: 100% (33/33), 5.76 KiB | 536.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.
```

Wohoo!!! 🎉 🚀 Thanks so much @yuvipanda!! Awesome :)

**Comment by fperez** [comment]
Sweet! We're adding a new lecture/lab on climate change to D100 (developed by the inimitable @cgentemann) and now I can properly do the development on the hub itself, so I know the code will run for the students identically... Super grateful!
