### ISSUE TITLE
Update Cartopy to version 0.20

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2824]
### Package Name

cartopy

### Hub details

- Hub: D100
- Language: Python

### Course Name

Data 100 - me :)

### Semester Details

Fall 2021

### Additional Information

We already have cartopy, unfortunately there's a critical bug breaking our usage for an upcoming lecture that was [only very recently fixed  upstream](https://github.com/SciTools/cartopy/pull/1833/files). With 0.19, certain cartopy plot calls try to access that [old naciscdn.org](https://naciscdn.org) URL, which doesn't work at all anymore. The traceback is huge, here's just the relevant part:

```
/opt/conda/lib/python3.9/site-packages/cartopy/io/__init__.py in _urlopen(self=<cartopy.io.shapereader.NEShpDownloader object>, url='https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip')
    240         """
    241         warnings.warn('Downloading: {}'.format(url), DownloadWarning)
--> 242         return urlopen(url)
        global urlopen = <function urlopen at 0x7f43280f8700>
        url = 'https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip'
    243 
    244     @staticmethod

...
elided
...

URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

Sorry for not having noticed this problem earlier!

**Comment by fperez** [comment]
FYI, this one isn't easy to work around temporarily as a normal user, b/c cartopy is a pain to build... Trying to `pip install cartopy` in the hub leads to:

```
Collecting cartopy
  Downloading Cartopy-0.20.0.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 2.0 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.9 /opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwkniy4fj
       cwd: /tmp/pip-install-ov08c2ym/cartopy
  Complete output (1 lines):
  Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.9 /opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwkniy4fj Check the logs for full command output.
```

So I don't really have any way of pushing forward on this for now. Help much appreciated!

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/135634378-2ede2c0d-6b0b-445c-b0fd-8bbde5a55f54.png)

Cartopy has been updated in conda-forge to 0.20.0, 27 minutes ago!

**Comment by yuvipanda** [comment]
We get all our packages from pip, and we get proj from apt. It looks like the version of proj we have is too old for cartopy 0.20, so this is gonna take a bunch of digging

**Comment by yuvipanda** [comment]
Had to revert this as the R package `sf` depended on older version of proj that was coming from apt.

**Comment by yuvipanda** [comment]
Note that this is required for October 28

**Comment by yuvipanda** [comment]
@fperez this is done now! Can you verify?

**Comment by fperez** [comment]
All perfect, huge thanks @yuvipanda and team!!
