### ISSUE TITLE
Request for retrieving archived files

### ISSUE THREAD

**Issue by qimingwu** [berkeley-dsep-infra/hubs#2829]
### Email Id

wuqiming9897@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/data100.berkeley.edu/wuqiming9897.tar.gz

**Comment by balajialg** [comment]
@qimingwu Do you have any specific timeline for this request? Can we get back to you in a week's time?

**Comment by felder** [comment]
signed url sent!
