### ISSUE TITLE
Request R packages rms, lmtest, car, SurvRegCensCov, ProfileLikelihood, and biostat3 for class PH 252

### ISSUE THREAD

**Issue by zbutzin** [berkeley-dsep-infra/hubs#2831]
### Package Name

 rms, lmtest, car, SurvRegCensCov, ProfileLikelihood, and biostat3

### Hub details

- Hub: Public Health DataHub
- Language: R

### Course Name

[PBHLTH 252 - Patrick Bradshaw](https://classes.berkeley.edu/content/2021-fall-pbhlth-252-001-lec-001)

### Semester Details

Fall 2021 (annual)

### Additional Information

Package documentation:
[rms](https://cran.r-project.org/web/packages/rms/index.html)
[lmtest](https://cran.r-project.org/web/packages/lmtest/index.html)
[car](https://cran.r-project.org/web/packages/car/index.html)
[SurvRegCensCov](https://cran.r-project.org/web/packages/SurvRegCensCov/index.html)
[ProfileLikelihood](https://cran.r-project.org/web/packages/ProfileLikelihood/ProfileLikelihood.pdf)
[biostat3](https://cran.r-project.org/web/packages/biostat3/index.html)

Thank you so much for your help in adding these packages. Please let me know if I can do anything to help streamline this process for you.

**Comment by yuvipanda** [comment]
@zbutzin can you make a pull request editing [this file](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/publichealth/image/r-packages/ph-252.r) to add these libraries? You can see how other libraries are being added from line 14. You can find the version numbers for these packages at https://packagemanager.rstudio.com/client/#/repos/1/packages. Think you can give that a shot?

**Comment by balajialg** [comment]
@yuvipanda @zbutzin FYI, I have raised a PR for the requested packages [here](https://github.com/berkeley-dsep-infra/datahub/pull/2822)!

@zbutzin Going forward, Please do raise a PR using the process suggested by @yuvipanda!

**Comment by zbutzin** [comment]
Thank you for sharing this information, @yuvipanda and @balajialg ! To be clear, do you need me to take any additional action at this time? Adding Professor @patrickbradshaw and co-GSI @kvntchn so that the full teaching team can learn this process. Thank you so much for your help!

**Comment by balajialg** [comment]
@zbutzin Thanks for the detailed package request! Appreciate your consideration of our inputs.

I would like to correct that, the previous suggestion made by us was more a "good to have" than a "must-have"! Steps are,

1. Install the required package in your version of datahub
2. Identify dependencies along with their version
3. Raise an [issue ](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=felder%2Cbalajialg&labels=package-request&template=package_request.yml&title=Request+python+package+X+for+class+Y)
**If possible**, (not mandatory from a process perspective) 
4.  Add the required packages along with their version in this [list](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/publichealth/image/r-packages/ph-252.r) and make a commit. Refer to the version using https://packagemanager.rstudio.com/client/#/repos/1/packages
5. Create a Pull Request to the staging branch of this repository!

**Comment by balajialg** [comment]
@zbutzin FYI, Have installed all the required packages!

**Comment by zbutzin** [comment]
@balajialg That's fantastic. Thank you so much for your help!
