### ISSUE TITLE
Request python `geopandas` upgrade to 0.10.0 for Data 100

### ISSUE THREAD

**Issue by alvinwan** [berkeley-dsep-infra/hubs#2838]
### Package Name

geopandas=0.10.0

### Hub details

- Hub: data100.datahub
- Language: Python

### Course Name

Data 100 - @fperez and me - are using it for our final project

### Semester Details

Fall 2021

### Installation Deadline

If I had to nail down a date, Nov 1, but we're flexible. We plan on using features specific to `geopandas=0.10.0` in our final project, which isn't released until Nov. In the meantime, a `%pip install --upgrade` works just fine.

Thanks in advance!

**Comment by felder** [comment]
`pip install geopandas==0.10.0` works in data100-staging.

**Comment by felder** [comment]
In staging, pip reports geopandas 0.10.0 is now available:

```
!pip list installed | grep geopandas

geopandas                         0.10.0

```

**Comment by felder** [comment]
Should be live in prod now.

**Comment by fperez** [comment]
Excellent, many thanks all!
