### ISSUE TITLE
Use Canvas course data for resource allocation

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#2839]
# Summary

We currently use a sidecar to get course enrollment info via the enrollment API. It may be easier to consult the information we get from Canvas. See

- https://github.com/berkeley-dsep-infra/datahub/commit/07bcfcb754107dc60d7ab1eaf43c4ea3c4b60540
- https://github.com/berkeley-dsep-infra/datahub/pull/2629

Getting the info this way will probably be more reliable too. Right now, the enrollment API returns each student's "Campus" email address (along with Home and Other which maybe be private), however that is not always the same as their berkeley.edu address. I've seen students with other UC campus email addresses and another with a "bekeley.edu" address which suggests that people can customize this. One must account for this by manually specifying these outlier student resource allocations within secrets/.

We need to check what is actually in the Canvas data to verify it is providing actionable information. If it looks good, we can modify the [custom spawner's start method](https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L232) to consult it.

# User Stories

- As a hub admin, I want the enrollment information to be more accurate.

# Acceptance criteria

- When someone logs into the hub, their auth_state will contain Canvas course data and we can use that to authorize resources in the spawner.

**Comment by ryanlovett** [comment]
The auth_state's course data [can be passed](https://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html#using-auth-state) to the spawner in CanvasOAuthenticator's [pre_spawn_start](https://github.com/berkeley-dsep-infra/datahub/blob/staging/images/hub/canvasauthenticator/canvasauthenticator/__init__.py#L93).

**Comment by ryanlovett** [comment]
We started a PR for this a while back, https://github.com/berkeley-dsep-infra/datahub/pull/1101

**Comment by ryanlovett** [comment]
I merged https://github.com/berkeley-dsep-infra/datahub/pull/2888 and it worked in prob140-staging with the following in deployments/prob140/config/common.yaml:
```
  custom:
    canvas_courses:
      1507757: # CRS:STAT-243-2021-D
        mem_limit: 2048M
        mem_guarantee: 1024M
```

I tested with prob140 staging because it is using CanvasOAuthenticator as are most of the hubs. data8, ischool, and publichealth are using the generic oauthenticator but configured with bCourses. To use this feature, they'll need to have jupyterhub.hub.config.JupyterHub.authenticator_class removed, along with jupyterhub.hub.config.JupyterHub.GenericOAuthenticator. biology and highschool use Google auth, and data8x uses LTI auth, so that latter three can't use this.

Here I'm testing by adding a stanza for Stat 243. The current practice in custom.profiles is to use the CCN numbers from classes.berkeley.edu as headings in the customization sections because those values are also in the SIS feed, and anyone can easily look them up. Unfortunately bcourses doesn't have that in the courses API. Here are some notable attributes in it:

```
'course_code': 'STAT 243-LEC-001',
'id': 1507757,
'name': 'Introduction to Statistical Computing (Fall 2021)',
'sis_course_id': 'CRS:STAT-243-2021-D',
```

`id` is what you see in the URL when you're visiting a bcourses class at bcourses.berkeley.edu/courses/{id}. I think only members of the class can see what that ID is. This means that infrastructure staff will need to solicit this from course staff -- maybe via a github issue form.

We could use one of the other parameters instead however. It may be possible to infer`course_code` and `sis_course_id`. I would exclude `course_code` because that doesn't have the year. `sis_course_id` seems like the best choice, but it is not always obvious what the department abbreviation will be. Also, what is `-D` ? Is that Fall? Additionally, projects in Canvas have an `sis_course_id` of `PROJ:{long_hash}` and that is not decipherable. In any case, I felt that going with `id` for the time being was best. I think I'll have it be configurable in the canvas authenticator.

Btw, one cool thing that comes from this is that people can create ad hoc projects in bCourses and datahub can use their enrollments for hub customization in the same way it does for courses.

I did not port the `users` mechanism from the custom.profiles section to custom.canvas_courses. I think user profiles should be separate (cuz strictly speaking, they're not canvas courses) and can remain in custom.profiles, though the parsing code is very similar and can be combined in some way later. If/when we transition to custom.canvas_courses, I can remove the SIS class parsing code.

It'd be nice to test this with a real course before the end of Fall. I've asked for the bcourse ID from one instructor where the SIS api was inadequate. (three students had campus email addresses which differed from their canvas login)

**Comment by balajialg** [comment]
@ryanlovett This is awesome work! Thanks for figuring this out.

Clarification for the naive me, Can we think about the use cases in #2867 considering the changes you made?

**Comment by ryanlovett** [comment]
@balajialg I just commented on that issue.

One other issue that arises from obtaining the Canvas data during auth, is that if a student logs into a hub before they are enrolled, they will have to log out and log back in (not just restart their server) in order for the hub to populate their user auth_state with the course info. Imagine a scenario where an instructor asks us to grant additional resources to their students in the middle of a term. We can add their Canvas course to the hub config, but with these changes, students will have to log out and back in, rather than just restart their server.

**Comment by ryanlovett** [comment]
One way of addressing the above to call self.authenticator.get_courses() from the spawner rather than picking up the data from when it last put it in auth_state, however I don't know when the user's access token is valid. If it is only valid after having recently authenticated, then there is no point.

Edit: the access token has a [one hour lifespan](https://canvas.instructure.com/doc/api/file.oauth.html#using-refresh-tokens). The generic oauthenticator puts the refresh token in auth_state, so maybe call [refresh_user()](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.Authenticator.refresh_user) ?

Edit 2: https://github.com/jupyterhub/oauthenticator/issues/398 is an issue to implement refresh_user in the oauthenticator.

**Comment by balajialg** [comment]
@ryanlovett FYI, Is this epic complete, or is it in scope for December or should this get pushed to the January backlog?

**Comment by ryanlovett** [comment]
It is complete. I should add ways of improving this to new issues.

**Comment by balajialg** [comment]
@ryanlovett That's amazing!
