### ISSUE TITLE
Request more RAM for class POLSCI 88

### ISSUE THREAD

**Issue by DiegoVillegasA** [berkeley-dsep-infra/hubs#2848]
**Which hub do you want more RAM on?**

datahub.berkeley.edu

**Which class is this request for?**

POLSCI 88 001
The Scientific Study of Politics
Fall
https://classes.berkeley.edu/content/2021-fall-polsci-88-001-lec-001

**How many students do you expect in this class?**

47

**How much RAM does this class need?**

4 GB

**Why does this class need this much RAM?**

We want to replicate the following investigation in class. It has a 2.5 GB dataset.

Preventing and Responding to Dissent: The Observational
Challenges of Explaining Strategic Repression
EMILY HENCKEN RITTER University of California, Merced
COURTENAY R. CONRAD University of California, Merced

**Any additional information we should know about?**

I tried linking an interactive terminal with my cmd and datahub.berkeley.edu and had problems with port 22.

**Comment by balajialg** [comment]
@DiegoVillegasA Thanks for raising this request! This should be doable. What is the timeline you are looking at to get this done?

**Comment by DiegoVillegasA** [comment]
Hi Balajialg! Students are probably going to be ask to start replicating until the first or second week of November.

**Comment by balajialg** [comment]
@DiegoVillegasA Sounds good! If we get this done by the last week of October then would that work from your perspective?

**Comment by DiegoVillegasA** [comment]
That would work out great! Is there a time limit for it to go back to 1GB?

**Comment by balajialg** [comment]
@DiegoVillegasA That's awesome. Would the end of the fall semester (around 12/15) work for you?

**Comment by DiegoVillegasA** [comment]
That sounds wonderfull. I appreciate your help a lot!

**Comment by felder** [comment]
@DiegoVillegasA Regarding this dataset, is it your expectation that each student in your class will maintain their own copy of this dataset?

**Comment by ryanlovett** [comment]
@DiegoVillegasA Can you please let us know your course's bcourse ID? (the number at the end of the URL, https://bcourses.berkeley.edu/courses/{number})

**Comment by DiegoVillegasA** [comment]
Felder, they will manipulate the dataset for a couple of weeks, and the main objective is to obtain two regression tables. After that, they do not need to have a copy themselves anymore. 
Ryanlovett, it is the following: 1509087

**Comment by balajialg** [comment]
Thanks, @ryanlovett! 


@DiegoVillegasA Closing this issue as we increased the RAM!

**Comment by ryanlovett** [comment]
Just an FYI @balajialg and @DiegoVillegasA that some people may have to logout of the datahub before their server is aware of the change. (not server stop/start -- they need to click `Logout` at the top right)This naturally happens when bcourses expires cookies and people are forced to relogin, but there may be people who will have to take this action.
