### ISSUE TITLE
Develop the 'usage metrics' dashboard some more - it can be very helpful for evangelism, but isn't in a usable state now.

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2861]

**Comment by yuvipanda** [comment]
I think using prometheus data for this is the wrong way to go - I couldn't really figure out a proper set of prometheus queries that gave me data I could really trust. Instead, I've done some log analysis and given @balajialg the raw data to help process - I trust that data a lot more than this, as I can understand how it is generated vs these promql queries.

**Comment by balajialg** [comment]
@yuvipanda Once I complete the R file that ingests this log data does analysis and spits out the metrics & visuals, do I use the R script whenever it is required? Is there a way to do the analysis and send that data to the grafana dashboard? Not sure I am overcomplicating the use-case but from a long-term perspective, having every metric accounted/visualized on the same grafana page would be a better approach. Thoughts?
