### ISSUE TITLE
Telemetry for Data 8 project

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#2869]
# Summary

Data 8 has a project to gather information from when students dont pass the autograder
that is creating a csv file in each users directory for each homwork lab

would there be way to collect these csvs from each user?
if you had admin access and a list of users 

Data 8 course staff to gather information

- As a `<type of user>` I want to `<do something not yet possible>` so that `<I get some kind of value>`.

As a Data 8 course staff I want to recover a file that each user generates as they do a lab in order to gather information on common errors, or where students are getting stuck 

# Acceptance criteria

Not sure what the solution is, just thought I would ask here if the admin team has ideas how to collect these files from each users file system

# Tasks to complete

**Comment by ericvd-ucb** [comment]
Another related question is whether someone with Admin status can go into users directories via command line?

**Comment by balajialg** [comment]
@ericvd-ucb Thanks for raising this request! I would wait for the team to chime in on your earlier query regarding accessing CSV files. However, considering what Ryan did in this [issue](https://github.com/berkeley-dsep-infra/datahub/issues/2688#issuecomment-912265497), I do think that someone with admin status can go into user directories via command line. @ryanlovett Please correct me if I am wrong.

**Comment by yuvipanda** [comment]
Yeah, if you are an admin user you should be able to access each user's home directory and gather the files. However, that can take a while as it's a manual process.

**Comment by yuvipanda** [comment]
On the data8 hub, all the students' home directories can be accessed by admins at `/srv/homes`. Be careful though - you can accidentally delete everything here as well :)

**Comment by balajialg** [comment]
@ericvd-ucb FYI, Incase you haven't seen this!

**Comment by ericvd-ucb** [comment]
Ok thanks - I think for now the person wanting to gather the files is using Otter to have them submitted  - but I will let them know this is possible
