### ISSUE TITLE
Request metpy for Data 100

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#2875]
### Package Name

metpy

### Hub details

- Hub: Data 100
- Language: Python

### Course Name

Data 100

### Semester Details

Fall 2021

### Installation Deadline

November 1.

We're designing a final project where metpy will make some visualizations much easier, so it would be great if it could be added. On my testing, it installs without any issues with standard conda/pip commands.

Thanks!

**Comment by felder** [comment]
pip installs metpy 1.1.0 and pooch 1.5.2

**Comment by felder** [comment]
Done!

**Comment by fperez** [comment]
Excellent, huge thanks for the quick reply!
