### ISSUE TITLE
iSchool R Datahub not loading

### ISSUE THREAD

**Issue by Cadherin** [berkeley-dsep-infra/hubs#2891]
### Bug description

I have been working with iSchool R datahub most of today and it has been working fine. However, it just crashed on me and I am unable to get back on. My assignment files are all on Datahub and I am unable to retrieve them for submission at the moment. 

### Environment & setup

- Hub:  https://ischool.datahub.berkeley.edu/
- Language:  R

**Comment by balajialg** [comment]
Helped @Cadherin download the files using this URL (https://ischool.datahub.berkeley.edu/user/xxx/lab/workspaces/lab?reset) so that the assignment submission goes smoothly. However, she is still having issues with launching the R studio in the Ischool hub and requires further debugging,

**Comment by felder** [comment]
@balajialg @Cadherin typically the way forward when rstudio misbehaves is to rename the .rstudio directory via the terminal and relaunch it. 

That work around is described here:
https://github.com/berkeley-dsep-infra/datahub/issues/1899

This can be fixed by renaming or removing ~/.rstudio via the terminal.

To do so while bypassing the typical rstudio session startup:
1.   Go to https://ischool.datahub.berkeley.edu/user-redirect/tree
2.   Click New->Terminal
3.   In the terminal, type: `mv .rstudio .rstudio.$(date +%s)` and press return
4.   Try to launch rstudio as you normally would and it should now work.

**Comment by balajialg** [comment]
@felder Thanks a lot!

@Cadherin Added this to the troubleshooting documentation - https://ds-modules.github.io/curriculum-guide/faq/troubleshoot.html#restarting-servers

**Comment by yuvipanda** [comment]
I think this might also be related to https://github.com/berkeley-dsep-infra/datahub/issues/2878, where the unsafe exit causes corruption of ~/.rstudio

**Comment by felder** [comment]
@yuvipanda definitely a likely possibility!

**Comment by Cadherin** [comment]
An update here that I tried signing onto the iSchool datahub today, it is working for me now. Thank you all for looking into this. Much appreciated! Let me know if there are specific things that I need to be aware of to prevent the related in the future.

**Comment by yuvipanda** [comment]
Am very glad it works for you again, @Cadherin! I'm hopefull that #2908 will fix this one for good...

**Comment by nojedam** [comment]
I have been working with iSchool R datahub yesterday and most of today and it has been working fine. However, it suddenlt says  just crashed on me and I am unable to get back on. My assignment files are all on Datahub and I am unable to retrieve them for submission at the moment.

![image](https://user-images.githubusercontent.com/76932698/140261560-d3b0f568-f6d3-4949-a377-50c716eebce5.png)

**Comment by balajialg** [comment]
@nojedam Did you try couple of fixes suggested in this thread to retrieve your files in the short term?

> @balajialg @Cadherin typically the way forward when rstudio misbehaves is to rename the .rstudio directory via the terminal and relaunch it.
> 
> That workaround is described here: #1899
> 
> This can be fixed by renaming or removing ~/.rstudio via the terminal.
> 
> To do so while bypassing the typical rstudio session startup:
> 
> 1. Go to https://ischool.datahub.berkeley.edu/user-redirect/tree
> 2. Click New->Terminal
> 3. In the terminal, type: `mv .rstudio .rstudio.$(date +%s)` and press return
> 4. Try to launch rstudio as you normally would and it should now work.

**Comment by nojedam** [comment]
@balajialg Today I tried to start iSchool R datahub without any workaround and it worked! However it got messed up again (same thing). I tried the workaround you suggested but it didn't work. Is there anything else you suggest?

**Comment by balajialg** [comment]
@nojedam Sorry, I was on leave this Friday! Is the issue still persisting? If yes, please feel free to reopen this issue? Can you also please list the steps that led to this issue?
