### ISSUE TITLE
R Datahub not loading: Error 503: Service Unavailable 

### ISSUE THREAD

**Issue by HahehaLing** [berkeley-dsep-infra/hubs#2902]
### Bug description

I am not able to open w203's datahub, I downloaded my lab1.rmd and could open it in Rstudio server, but not the 203's datahub (with all the installed libraries) anymore. 

503 : Service Unavailable
Your server appears to be down. Try restarting it from the hub

### Environment & setup

- Hub: W203 datahub
- Language: R

### How to reproduce

1) go to this link: https://r.datahub.berkeley.edu/user/lingyue/rstudio/

expected: 
open w203 datahub

actual:
error message 503

**Comment by ryanlovett** [comment]
Thanks for the report. There was a storage problem with the hub that was resolved earlier this evening. You should be able to access your server now.

**Comment by balajialg** [comment]
@ryanlovett Thanks a lot for handling this issue!
