### ISSUE TITLE
Unable to get Visual Markdown Editing tool in Rstudio

### ISSUE THREAD

**Issue by aazizi13** [berkeley-dsep-infra/hubs#2923]
### Bug description

I couldn't figure out how to install/get the Visual Markdown editing tool in datahub for rstudio. Based on my googling, it looks like it only works for v1.4 versions. Datahub rstudio version is 1.3.959. 

### Environment & setup

Rstudio DataHub. 

### How to reproduce

N/A

**Comment by yuvipanda** [comment]
Thanks for opening this, @aazizi13. We're stuck in RStudio 1.3 for now, so no visual editing :( @ryanlovett is graciously working on bumping it up to 1.4 but we need to revisit that I think.

**Comment by balajialg** [comment]
@yuvipanda @ryanlovett What are the complexities involved with regards to making this bump?

**Comment by ryanlovett** [comment]
@balajialg It is fairly complex. We tried [one approach](https://github.com/jupyterhub/jupyter-rsession-proxy/pull/107), but it didn't fix everything. I think jupyter-server-proxy needs to be modified so we can customize responses.

I haven't had time to work on this.

**Comment by balajialg** [comment]
@ryanlovett Makes a lot of sense! Moving this request to backlog considering the context.

**Comment by yuvipanda** [comment]
We've upgraded our RStudio now, so Visual Markdown editing is available!
