### ISSUE TITLE
Request python library linearmodels.iv for class PS 88

### ISSUE THREAD

**Issue by anthlittle** [berkeley-dsep-infra/hubs#2925]
**Which library do you want installed?**
linearmodels v4.24, in particular the functions for instrumental variables

**Which hub do you want it installed on? For example r.datahub, datahub, data100.datahub, etc.**
datahub

**Which class will use this package?**
PS 88 Fall 2021, Professor Andrew Little

**Which semester will this package be used for?**
Fall 2021, and future iterations of the class. I'm hoping to include this in material for class this week (class on Thursday), so if you can do this in the next couple days that would be great!

**Comment by yuvipanda** [comment]
@anthlittle this should be done now!

**Comment by anthlittle** [comment]
It's working, thanks!

**Comment by balajialg** [comment]
@yuvipanda Thanks Yuvi for the quick turnaround! Appreciate it.
