### ISSUE TITLE
10/28 Sprint Retro Objective, Agenda and Next Steps!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2939]
I assume all of you are super busy with varied tasks and deliverables. Hence, articulating the objective and the agenda for tomorrow's retro if in case it is useful to any of you.

**Objective:** 

1. Use the meeting time to come together as a team to recognize each other's critical contributions during the month, 
2. Identify continue-stop-start for varied activities by reflecting on things that are going well/not going well from a process/policy/product perspective in the spirit of continuous iteration

**Agenda:**

1. What went well in October?
2. What could have been better?
3. What are some action items/next steps from this meeting?

**Pre-Requisites**
If possible, please do fill the [Trello board](https://trello.com/b/kiOQDf3A/datahub-monthly-sprint-retro-2) before the meeting

**Comment by yuvipanda** [comment]
@balajialg i don't seem to have access to the trello board... Do you think we can just use a github board for this as well? They can have arbitrary cards on them, not just issues. Reduces the number of tools we need to be using

**Comment by balajialg** [comment]
@yuvipanda Sorry about that! I thought of using Trello from a confidentiality standpoint but as an afterthought, realize that we are not going to discuss anything super confidential. I gave access to the Trello board this time, but in future iterations will use the GitHub board

**Comment by balajialg** [comment]
**Next Steps from this meeting:**

1. @yuvipanda @ryanlovett to codify the framework for changes that need to go out by the end of the semesters!
2. @balajialg to work with @ericvd-ucb to explore the newsletter idea further and get a pilot version out in November!
3. @yuvipanda and @felder to think and explore potential solutions for over-provisioning resources at the start of the semester!
4. Consider [Python usage dashboards](https://grafana.datahub.berkeley.edu/d/1EJ3WNi7z/python-popularity-contest-copy?orgId=1&refresh=1m&from=now-90d&to=now) to make decisions with regards to removing python packages.
