### ISSUE TITLE
Plan for Spring 2022

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2945]
Issue to track 

**Things we want to do *before* Spring 2022**

- [x] Support RStudio 2021.09  (They switched to calendar versioning, https://www.rstudio.com/products/rstudio/release-notes/)
- [ ] Have alerts that trigger whenever there is an outage
- [ ] Move the user images out of this repository, to make self-serve image requests easier. See https://github.com/2i2c-org/justiceinnovationlab-image for an example workflow - primary advantage is ability to test the image without needing staging. 
- [ ] <s>Switch to Python 3.10 as default, from 3.9 (should be done during the semester switch)</s>
- [x] Make data8 use retrolab #2422 
- [x] Codify cleanup tasks (https://github.com/berkeley-dsep-infra/datahub/issues/2946)

**Things we want to do *during* Spring 2022**

I## Big Ticket items

- [x] - Ensure that Data 8 adopts Retro Lab? (@yuvipanda)
- [x] - Get stat159 to pilot RTC hub? (@yuvipanda)
- [x] - Upgrade R & RStudio (@yuvipanda @ryanlovett)
- [ ] - Initiate cloud cost-sharing conversations with EECS and (possibly) Biology? (@balajialg)
- [x] - Finalize a decision on resourcing forward - 2I2C pilot and/or resource sharing with RTL (@ericvd-ucb, @balajialg?)
- [x]    - Scoping the JD irrespective of the path taken wrt resourcing
- [ ] - Figure out a storage solution (@felder)
- [ ] - Keep leadership at Berkeley and RTL aware of the changes happening in accessibility support in Jupyter @balajialg 

## Smaller ticket items
- [ ] - Invest more efforts into improving alerting system
- [ ] - Invest more efforts into improving grafana dashboards
- [x] - Communicate our work to our users in the monthly newsletter format
- [x] - Support faculty at Public Policy, Civil, and Sociology adopt Datahub?
- [x] - Evangelize the nbgitpuller extension for Chrome and Mozilla as part of our conversation with the faculty

**Comment by yuvipanda** [comment]
Another potential inclusion here is to move away from SIS and use only CanvasAuthenticator, but I think the other stuff here is higher priority.

**Comment by balajialg** [comment]
@yuvipanda What do you think about using some time during our Nov/Dec Tech strategy meeting/separate meeting to evaluate our roadmap for spring? I know it will be messy, but we can scope the meeting better to explore 7-8 significant changes (listed from users and hub admin perspective). Also, we could use the time to narrow down the stuff we want to work on. What do you think?

**Comment by yuvipanda** [comment]
@balajialg sounds great! I think this is a perfect fit for the tech strategy meeting. I don't think we need to wait on it though, some of the discussion can happen asynchronously and we can start working on some of the items that will take a while to do.

In the longer run, I think we can start a 'Roadmapping for next semester' process maybe  a month into each semester?

**Comment by balajialg** [comment]
@yuvipanda Like the idea of having specific meetings at the start of the semester. Helpful from a recruitment standpoint too.

Let's scope the December Tech strategy meeting to focus on the roadmap for the next semester. Async conversations can help us define the sample set of features to consider for that meeting.

**Comment by balajialg** [comment]
@ericvd-ucb @yuvipanda @felder @ryanlovett Scoping this as part of the agenda for this week's Tech Strategy Meeting. Please let me know if you think otherwise!

**Comment by ericvd-ucb** [comment]
This is great. I would like to add an update on nbgitpuller.  I don't really understand what is about to happen, would love an update, and consideration for how we can communicate these changes to our users.

**Comment by balajialg** [comment]
Sounds good! Adding @sean-morris in the loop considering his recent work updating nbgitpuller.

**Comment by sean-morris** [comment]
@balajialg and @ericvd-ucb -- just a quick piece. There are no breaking changes here. What worked in nbgitpuller from git sources still works as-is. The piece being added is the ability to use google drive, dropbox, and any publicly available web address as the source for notebooks you would like to distribute via nbgitpuller links into JupyterHubs.

**Comment by balajialg** [comment]
Thanks, @sean-morris for the clarification.

@All, We have many potential priorities for Spring 2022 (to be specific, January). During tomorrow's discussion, an ideal outcome I envision would be having clarity around our team's top strategic priorities for Spring. Having a discussion to explicitly articulate why we choose to prioritize particular use cases while deprioritizing others would help us a lot IMHO.

# Potential priorities!

## Big Ticket items
- Ensure that Data 8 adopts Retro Lab? (@yuvipanda)
- Get stat159 to pilot RTC hub? (@yuvipanda)
- Upgrade R & RStudio (@yuvipanda @ryanlovett)
- Initiate cloud cost-sharing conversations with EECS and (possibly) Biology? (@balajialg)
- Finalize a decision on resourcing forward - 2I2C pilot and/or resource sharing with RTL (@ericvd-ucb, @balajialg?)
   - Scoping the JD irrespective of the path taken wrt resourcing
- Figure out a storage solution (@felder)
- Keep leadership at Berkeley and RTL aware of the changes happening in accessibility support in Jupyter @balajialg 

## Smaller ticket items
- Invest more efforts into improving alerting system
- Invest more efforts into improving grafana dashboards
- Communicate our work to our users in the monthly newsletter format
- Support faculty at Public Policy, Civil, and Sociology adopt Datahub?
- Evangelize the nbgitpuller extension for Chrome and Mozilla as part of our conversation with the faculty

Anything else that I missed?

**Comment by yuvipanda** [comment]
Sounds good, @balajialg. Thanks for writing this up. One additional item is moving to newer RStudio, but I think discussion isn't primarily needed there right now.

**Comment by felder** [comment]
@balajialg We should also add a bullet point for storage policy and management.

**Comment by balajialg** [comment]
@yuvipanda Thanks a lot for tracking the changes from today's meeting!

**Comment by yuvipanda** [comment]
I've co-ordinated with the ischool and publichealth folks, and their R + RStudio versions are newer now. I've opened #3090 to upgrade the biology hub. That just leaves us with datahub / r hub, which I'll upgrade later this week.

**Comment by yuvipanda** [comment]
RStudio and R are now at latest versions on all our hubs. Huge thanks to @ryanlovett for making this possible!

**Comment by balajialg** [comment]
@yuvipanda Can you make edits to the issue and highlight the priority items?

**Comment by balajialg** [comment]
Closing this issue as highlighed priorities are tracked across other issues!
