### ISSUE TITLE
data8 needs more CPU

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2966]
Currently, data8 students are reporting that cells sometimes take really long to run.

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/30430/140467304-dc55ba1a-5f15-4713-8fab-ca80ac8870fd.png">

This is because the CPUs are being maxed out on all data8 dedicated nodes, by users running code at 100% CPU. Since we overprovision here, it doesn't work out well.

**Comment by yuvipanda** [comment]
As there's a project deadline, I've:

- Manually deployed #2967, as we still have a datahub image build happening in CircleCI
- I increased the minimum amount of nodes in the delta nodepool to 13, and scaled up nodes to 20. This should help data8 students who restart to land on a new and existing node. However autoscaler immediately brings it down to 13 anyway, so that wasn't helpful

**Comment by yuvipanda** [comment]
I've also created a new gamma pool with `n1-custom-16-16384` machine type - 16 cores and 16GB of RAM, matching the 0.5 CPU guarantee and the 0.5GB memory guarantee we give users. Previously, they were on n1-highmem-8 nodes, which wasted a *lot* of RAM - only about 16 users could fit on it due to the CPU constraint, leaving a lot of wasted RAM.

**Comment by yuvipanda** [comment]
Let's tone down teh CPU requests on Monday.

**Comment by yuvipanda** [comment]
I've turned this down to a 0.1 guarantee and a 0.5 limit with #2983.

**Comment by yuvipanda** [comment]
I added an alert for 90% CPU utilization in https://grafana.datahub.berkeley.edu/d/R3O4mbg7z/cluster-information?orgId=1&viewPanel=9.

**Comment by yuvipanda** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/30430/140869981-898e783d-759b-4f55-8493-6a26c5b96501.png">

The CPU requests are filling up the node faster than the memory requests, which I don't want - data8 (and most of our students really) are bottlenecked on memory, not CPU. Since the goal is to make sure students never end up with *no* CPU, I'm instead going to give everyone 0.05 (5%) CPU than 10%

**Comment by balajialg** [comment]
@yuvipanda Closing this issue as the underlying problem seems to be solved by you. Please reopen if that is not the case!
