### ISSUE TITLE
retrieivng a copy of my files

### ISSUE THREAD

**Issue by lyrasheu1210** [berkeley-dsep-infra/hubs#2978]
### Email Id

lyrasheu1210@berkeley.edu
changed my email address to lyrasheu@berkeley.edu after graduating 

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/spring-2021/data100.berkeley.edu/lyrasheu.tar.gz

**Comment by felder** [comment]
Signed URL sent!

**Comment by felder** [comment]
lyrasheu reports that the above file is empty.  After clicking on the link myself, I can see the file is 263 bytes.

Clearly some investigation is required.

Perhaps the change in email address is at fault here.  I'll do some research and get back to you.

**Comment by felder** [comment]
I can see that directories corresponding to lyrasheu and lyrasheu1210 exist, and lyrasheu1210 contains 1.6GB of data.

**Comment by felder** [comment]
@yuvipanda this would appear to be a corner case for the archiver.

**Comment by felder** [comment]
I have emailed lyrasheu1210 an email asking for identity confirmation.  A reply to that email containing the text of what I sent should suffice to tell me that lyrasheu1210 and lyrasheu are the same person.

If that doesn't work I'll need to check with calnet before I can release the files.

**Comment by felder** [comment]
Identity confirmed.

I'll get your files to you soon!

**Comment by felder** [comment]
I placed a tar archive of lyrasheu1210's files here:
gs://ucb-datahub-archived-homedirs/spring-2021/data100.berkeley.edu/lyrasheu1210.tar.gz

Signed URL sent.
