### ISSUE TITLE
Support Latex in Retrolab

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/hubs#2989]
# Summary

We are considering moving from classic Jupyter notebook to Jupyterlab Retrolab in Data 8.  Currently, we rely heavily on Latex in notebooks.  It appears that Retrolab doesn't render Latex.

For instance, see https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa21&branch=master&urlpath=retro%2Ftree%2Fmaterials-fa21%2Fmaterials%2Ffa21%2Flab%2Flab09%2Flab09.ipynb, under "2. The regression line", you can see the Latex formula doesn't render as mathematics.

We need to support Latex in Retrolab to adopt Retrolab in Data 8.

(Should this be filed on the Retrolab Github instead of here?)

**Comment by fperez** [comment]
Mmh, this is odd - I'm using locally the same exact version of RetroLab (0.3.12) as is installed in the D8 hub, and when I open the lab @davidwagner links above side by side, with the same browser, the campus hub shows indeed the non-rendering LaTeX, but my local one works OK:

![image](https://user-images.githubusercontent.com/57394/141418392-cb24f0d9-bf13-469f-8fcf-b28655346da1.png)

So evidently RetroLab 0.3.12 _can_ render LaTeX, though for some reason our deployment isn't doing so...

I'd love to hear if @jtpio has any input here - can you think of what we might be doing with the Data 8 hub that's causing this? Obviously @yuvipanda or others might know too, but I figured I'd bug Jeremy in case he's aware of the issue already...

**Comment by jtpio** [comment]
It seems to be the case when testing on this Binder too: https://gist.github.com/jtpio/4a6a34da66b32249e28df718ec30e4d7

![image](https://user-images.githubusercontent.com/591645/141449457-af459812-9a49-4c57-af7a-b09a9a1ab112.png)

So probably something to do with the handling of the base url in retro.

**Comment by jtpio** [comment]
@davidwagner @fperez this should now be fixed with the latest `0.3.13` release: https://github.com/jupyterlab/retrolab/releases/tag/v0.3.13

**Comment by fperez** [comment]
Awesome, huge thanks for the quick turnaround @jtpio!

**Comment by yuvipanda** [comment]
I've deployed this new release, and i see the LaTeX be rendered now!

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/30430/141831364-f43fdcd7-aab3-4dab-8511-19ea02228901.png">

Thanks for reporting this, @davidwagner! And thanks for the quick fix, @jtpio!
