### ISSUE TITLE
Retrolab vs classic notebook - long string outputs

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/hubs#2990]
I noticed a difference in how output is rendered in classic Jupyter notebook vs Retrolab.  Compare

classic notebook: http://data8.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/data-8/materials-fa21&subPath=lec/lec01.ipynb
Retrolab: https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa21&branch=master&urlpath=retro%2Ftree%2Fmaterials-fa21%2Flec%2Flec01.ipynb

Try using 'Kernel > Restart & Rerun All', then compare the output from the 4th cell.  In particular, the output from the 4th cell is a very long string; classic notebook puts it in a scrollable subframe, whereas Retrolab tries to include the entire output.

classic notebook:
![lec01cell4classic](https://user-images.githubusercontent.com/3349841/141417339-b0d2d7b9-592e-4751-a80b-4a4f2588dfff.png)
retrolab:
![lec01cell4retro](https://user-images.githubusercontent.com/3349841/141417365-e806ca7a-ac6a-47c2-b7f9-4fad4128df3d.png)

As a result, retrolab ends up trying to make a ridiculously long web page.  Perhaps as a result, retrolab runs out of memory on this particular notebook.

It's not a big deal for Data 8 -- this is something we can presumably work around by changing the notebook.  But I wanted to check: Should I be filing an issue on the Retrolab github?  Is Retrolab trying to be identical in its user interface, or merely close enough?

**Comment by jtpio** [comment]
This issue and the others related to the scrolling behavior sound similar to this: https://github.com/jupyterlab/jupyterlab/issues/5897

Does the "Enable Scrolling for Outputs" help mitigate this?

![image](https://user-images.githubusercontent.com/591645/141452988-d4c15cdb-a2cd-40c2-b805-c5714c247169.png)

If so then maybe RetroLab can execute that command automatically on startup so it's the default.

**Comment by yuvipanda** [comment]
I opened https://github.com/jupyterlab/retrolab/issues/287 suggesting that, @jtpio!

**Comment by yuvipanda** [comment]
retrolab now renders this like:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/30430/147959737-c2ac3b7f-5e70-4377-863c-9caf5a437d12.png">

Thanks to @jtpio for fixing this!
