### ISSUE TITLE
Retrolab vs classic notebook - long tables

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/hubs#2991]
It appears that long tables are displayed differently in classic notebook vs Retrolab.  For example, compare the output of cell 2 in lec10 demos:

classic notebook: http://data8.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/data-8/materials-fa21&subPath=lec/lec10.ipynb

![lec10cell2classic](https://user-images.githubusercontent.com/3349841/141418600-fc237796-5f0f-481f-ae1a-a3c5be464b80.png)

Retrolab: https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa21&branch=master&urlpath=retro%2Ftree%2Fmaterials-fa21%2Flec%2Flec10.ipynb

![lec10cell2retro1](https://user-images.githubusercontent.com/3349841/141418612-ca558929-7e93-4028-bc98-693196b394bf.png)

As you can see, in Retrolab the output is put in a scrollable frame, and we can't see the bottom of the output.  (You can also a slight UI glitch in the border of the frame and the lowest row that is displayed.)  If we scroll the scrollable frame down to its bottom, then the Retrolab UI looks like this:

![lec10cell2retro2](https://user-images.githubusercontent.com/3349841/141418668-a4ed5101-9f49-4585-8f1d-ecaa42039f93.png)

For the particular use of tables and the datascience package used in Data 8, I like the classic notebook's style better, because the datascience package has already truncated the output so it doesn't spam your window, and because it shows "(924 rows omitted)" in the part that is immediately visible; whereas retrolab truncates and doesn't show the "(924 rows omitted)" unless you click and scroll.

I don't know that this is a showstopper but this is a difference that seems worth noting.  Is there an easy way to modify the datascience library or the retrolab interface to recover the old classic notebook display style for this situation?

**Comment by yuvipanda** [comment]
Looks like this now in retrolab:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/30430/147959916-bfe20c49-b0fe-4847-88b0-3716f094cf78.png">


Thanks to @jtpio for fixing this!
