### ISSUE TITLE
Retrolab vs classic notebook - display of long arrays

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/hubs#2992]
Long arrays are displayed differently in classic notebook vs Retrolab: they are put into a scrollable frame in classic notebook, but they spam the display in Retrolab.  For example, compare the output of cell 13 in lec10 demos:

classic notebook: http://data8.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/data-8/materials-fa21&subPath=lec/lec10.ipynb

![lec10cell13classic](https://user-images.githubusercontent.com/3349841/141419886-d2a0a9f8-31b1-4316-9196-1aa305794391.png)

Retrolab: https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa21&branch=master&urlpath=retro%2Ftree%2Fmaterials-fa21%2Flec%2Flec10.ipynb

![lec10cell13retro](https://user-images.githubusercontent.com/3349841/141419897-df2e9cfa-0360-4eaf-8a08-6a928b8da22a.png)

In Retrolab the display of the array continues on for pages, without being truncated.  This is annoying.  I'm not sure there's an easy way to work around this in the notebook (by changing the cell).  What would you suggest?  Is there a way to get a more reasonable display for this?  Should I be filing this as an issue on the Retrolab github?

**Comment by jtpio** [comment]
There is now an issue on the RetroLab repo: https://github.com/jupyterlab/retrolab/issues/287

And a WIP PR to fix it so the behavior is similar to the classic notebook: https://github.com/jupyterlab/retrolab/pull/288

As a workaround, explicitly setting `scrolled` in the cell metadata (https://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata) of the source material should automatically make the outputs scrollable in JupyterLab and RetroLab. We could imagine manually setting that `scrolled` flag for cells we know are going to generate long outputs.

**Comment by yuvipanda** [comment]
Looks like this in retrolab now:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/30430/147960020-d58f2ce7-1a76-41e8-ab8a-aa20b9e4a8cc.png">

Thanks to @jtpio for fixing this!
