### ISSUE TITLE
Retrolab vs classic notebook - truncation of scatter plots

### ISSUE THREAD

**Issue by davidwagner** [berkeley-dsep-infra/hubs#2993]
Scatter plots seem to be truncated differently in classic notebook vs Retrolab.  For example, compare the output of cell 15 in lec10 demos:

classic notebook: http://data8.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/data-8/materials-fa21&subPath=lec/lec10.ipynb

![lec10cell15classic](https://user-images.githubusercontent.com/3349841/141423596-48a46bcc-36f1-4fb6-9bf8-eddb51fd4296.png)

Retrolab: https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa21&branch=master&urlpath=retro%2Ftree%2Fmaterials-fa21%2Flec%2Flec10.ipynb

![lec10cell15retro](https://user-images.githubusercontent.com/3349841/141423605-823a655a-9b7f-43c2-8fcc-09a06ae84e0c.png)

Not the biggest deal in the world, but Retrolab looks worse to my eyes.  Any ideas or suggestions on how to control the truncation/size of the scrollable frame that scatter plots are put into, in Retrolab?

**Comment by jtpio** [comment]
Thanks @davidwagner for reporting :+1: 

Agree, and we should be able to tweak the CSS to make it look nicer.

For example by applying a `padding-top: 6px` (to match the box shadow blur radius):

![image](https://user-images.githubusercontent.com/591645/142074206-57636b9f-bed8-41d9-9508-98dec7c2416e.png)

**Comment by yuvipanda** [comment]
It looks like this in retrolab now

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/30430/147960280-b5051a4b-86d6-452c-91a0-b4c8270f5ed0.png">

Thanks to @jtpio for this!

**Comment by balajialg** [comment]
@jtpio Thanks a lot for fixing all the reported issues in the new retro lab release. Appreciate it!

@yuvipanda Thanks for testing all the changes and deploying them in Datahub. Look forward to retro lab being used in Data 8 during this semester.
