### ISSUE TITLE
Request more RAM for class PS 88 (or just instructors)

### ISSUE THREAD

**Issue by anthlittle** [berkeley-dsep-infra/hubs#2995]
My course reader Diego Villegas was in touch with someone about getting the RAM for our class increased, and it did work for him, but not for me, even after logging out and in again. My id is andrew.little. I haven't checked with my students yet to see if it worked for them, and figured it would be good ask here first to avoid confusing them :). Thanks!

Rest of the info request is below

**Which hub do you want more RAM on?**

datahub

**Which class is this request for?**
PS 88
https://classes.berkeley.edu/content/2021-fall-polsci-88-001-lec-001
**How many students do you expect in this class?**

45

**How much RAM does this class need?**

4GB

**Why does this class need this much RAM?**

We are working with a large data file for one of the projects

**By when (MM/DD) do you want this request to be fulfilled?**

ASAP

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@anthlittle Quick clarification, Did you try as per the last comment highlighted by @ryanlovett in [this](https://github.com/berkeley-dsep-infra/datahub/issues/2848) issue? We can take it from there if this hack is not working.

**Comment by anthlittle** [comment]
I tried the hack of logging out and that didn't seem to work for me. Thanks!

**Comment by balajialg** [comment]
@anthlittle We will look into this issue immediately. Thanks!

**Comment by ryanlovett** [comment]
@anthlittle I've configured the hub to pull the course roster from SIS. It should work for you the next time you start your server. But when you get a chance, can you also please log out and back in once more? I've added some debugging so we can see how many bcourses courses you are a member of.

**Comment by anthlittle** [comment]
Works for me now, thanks! I'll let you know if students have any issues. 

I also did the logout/login.

**Comment by balajialg** [comment]
Thanks a lot, @ryanlovett for the quick fix!

**Comment by ryanlovett** [comment]
@balajialg No problem. This particular issue was fixed by #3005, and it should be fixed in general for other Canvas courses by #3018.

**Comment by yuvipanda** [comment]
@ryanlovett think we can move this away from SIS?

**Comment by ryanlovett** [comment]
@yuvipanda If you mean remove the SIS stanza for this class in particular, sure, though it'd require that some people re-login. If you mean in general, I think we can put new courses on the Canvas method.
