### ISSUE TITLE
Error Reading csv File

### ISSUE THREAD

**Issue by HahehaLing** [berkeley-dsep-infra/hubs#3017]
### Bug description

Hi,

I am trying to upload this csv file to datahub but keep getting stalled at 581.56 MB read. Then I get the corresponding error messages.

![image](https://user-images.githubusercontent.com/85141145/142086260-052e6386-b61b-454b-b4bc-28bdae677de3.png)
![image](https://user-images.githubusercontent.com/85141145/142086279-d8cb2a11-fec1-4146-a55f-79c76cf202fc.png)
![image](https://user-images.githubusercontent.com/85141145/142086294-ddf4ed0c-44f0-4082-bdee-c2c12678545c.png)

### Environment & setup

203 datahub

### How to reproduce

1) uploaded my csv file to datahub

2) Run the code. The following is my code. 

> library(readr)
> WeatherEvents_Jan2016_Dec2020 <- read_csv("WeatherEvents_Jan2016-Dec2020.csv")
indexed 581.56MB in  4s, 132.52MB/s

**Comment by balajialg** [comment]
@felder I spent some time debugging this issue and suggested that they upload the CSV file in their tree. However, the User's file system in R studio looks different from the file system in user's [tree](https://ischool.datahub.berkeley.edu/user/lingyue/tree#notebooks)? What could be the reason and how to ensure that they remain the same?
![image](https://user-images.githubusercontent.com/2306166/142088157-e1ca80d8-2231-49c8-b121-97152ab62d60.png)

**Comment by felder** [comment]
@balajialg @HahehaLing 

Does the upload actually succeed and then the function call fails?  If so, 500MB?  Is it possible that we're seeing memory exhaustion here?

It's unclear to me how the upload is performed.  The notes to produce say to upload the file and run the code, but the screen shot does not show that occurring.

**Comment by felder** [comment]
@balajialg with regard to the tree not matching, your URL points to ischool hub while the screenshot indicates r hub

The bug report also mentions datahub...

So which is it?

r hub?  ischool hub?  or datahub?

**Comment by HahehaLing** [comment]
Hi,

I have done another csv file upload, which succeeded. But the file size is much smaller at 2mb. 

My current csv is around 750 mb. 

Best regards,
Eric (Yue) 

——

**Comment by balajialg** [comment]
@HahehaLing Any reasons why you are reading a 750 MB file requirement? Was this dataset prescribed as part of your course or is it a personal project? 

Ischool and R Hub has a guarantee of 512M and a limit of 1G of ram which may not be feasible to perform such a complex operation.

**Comment by ryanlovett** [comment]
@balajialg If RStudio's upload mechanism reads the whole thing into memory, then people won't be able to upload large files this way. If the file is hosted online somewhere, they can retrieve the file onto the hub with R or some other client. It might also be possible to upload through Jupyter Notebook or Lab, if those apps stream the file to disk rather than reading in the whole thing.

**Comment by felder** [comment]
@ryanlovett @HahehaLing another approach could be to compress it first, upload it, and then decompress it.  I imagine a csv will likely compress quite well.

However, that's still not going to fix the issue if the code needs to read the whole thing in.

**Comment by HahehaLing** [comment]
Hi all,

Yes this is the lab 2 for w203 where we have to find our own dataset. My team is trying to find a relationship between rain and store sales.

I have uploaded a zip file (successful) and extracted in data hub, but have issue loading the csv data to a data frame.

Best regards,
Eric

**Comment by felder** [comment]
@HahehaLing that's what I would expect.  Is it possible for you to break up the data set into multiple parts and process those parts individually?  Alternatively is there a smaller dataset you could use?

**Comment by yuvipanda** [comment]
We can also temporarily give you more RAM?

**Comment by HahehaLing** [comment]
Hi,

No problem, I have found another data set.


Thanks for your help.

Best regards,
Eric

**Comment by felder** [comment]
@HahehaLing excellent!
