### ISSUE TITLE
Add an issue template for requesting extra CPU

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#3024]
We can either repurpose the current 'request more RAM' issue template to also count for CPU, or make a new one.

**Comment by balajialg** [comment]
@yuvipanda What details would you want to collect in this template? I am listing the obvious ones below,

1. Duration of the request
2. Reason for the request
3. Total number of students affected
4. Estimate the number of CPUs to be added? 
5. Deadline by when this change needs to be added

Feel free to add/edit/delete the fields!
