### ISSUE TITLE
eecs pods stay running for days

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3049]
### Bug description

If I pull up a list of running eecs pods I can see several of them have been running for days.  Looking at the logs for those pods, it would appear the student is not actively interacting with the pod.

If I access one of the pods, I can see there is a classic notebook running.  Notebook indicates the last saved state was days ago (similar to the age of the pod).  Best guess is notebook is stuck an infinite loop.  I can see the notebook does contain a while loop.

### Environment & setup

- Hub: eecs
- Language: python

### How to reproduce

`kubectl -n eecs-prod get pods | grep -e " \dd" | grep jupyter`

Pick a pod, any pod, and view it's logs.

Compare with activity listed in admin interface.  Admin interface indicates very recent activity.  Logs do not.

View as user, go to tree view, click the running tab, and access the notebook.  Note that notebook indicates last saved state of some time ago.

This is likely very similar behavior that led to me manually mass culling a bunch of long running pods in the beta pool (a few days after we setup the gamma pool for them) that were eating large amounts of cpu.

**Comment by felder** [comment]
@Quizenger It's our belief there is likely an issue with this assignment notebook, perhaps an infinite loop.  This behavior has been seen in a lot of eecs pods.  Would you be willing to help us investigate that?

**Comment by felder** [comment]
I'll be taking some corrective action by manually killing all eecs pods in the gamma pool older than 24h, however this will also get rid of some of the evidence.  Thus it'd be good to troubleshoot it first.

**Comment by felder** [comment]
This is the path of one of the notebooks:
notebooks/public-fa21-hw-notebooks/fa21_hw12/iPython_release/ikinematics.ipynb

This may be eecs 16B, but I'm not sure.

Inverse Kinematics
Changelog:
    Created by Stephen Bailey, Anant Sahai
    Fall 21: Added draggable goal animation, Ashwin Vangipuram

**Comment by felder** [comment]
Spot checking several of these pods reveals they seem to all be running the same notebook.

**Comment by balajialg** [comment]
@felder Thanks for writing this up! @Quizenger Just checking, Are you the point of contact related to Datahub for both 16 A and 16B?  If not, Who else is the right point of contact for EECS 16 B?

**Comment by raghav-g13** [comment]
@felder @balajialg  I'm the point of contact for 16A. That's one of 16Bs homeworks. I honestly don't know who'd be the right person to reach out to, so here's their staff list: https://eecs16b.org/staff.html

**Comment by felder** [comment]
@Quizenger yeah I figured that might be the case once I dug into who authored the suspect notebook.  Thanks anyway!

**Comment by msswn** [comment]
Hi! I'm on the content team for EECS16B - this has been relayed to us - we should be deploying a fix for things of this sort so that we don't have infinite runtimes on notebooks. Apologies!

**Comment by dhasteer** [comment]
Hi @felder @balajialg, member of 16B staff here. Would it be possible for you to manually kill the pods running the `ikinematics.ipynb` notebook? We've deployed a fix so that new instances of the notebook will not have an infinite loop. Thanks and sorry about any trouble!

**Comment by felder** [comment]
@dhasteer yeah that should be possible, I'll just keep my eye out for long running eecs pods and I'll stop them.

**Comment by felder** [comment]
@dhasteer 

This morning I killed 5 pods that had been running since yesterday.  All the rest appear to be pretty recent.  There is one that has been up for 2 hours, if it's still up later this afternoon I'll kill it too.

I'll update this ticket periodically over the next several (work) days to see if any additional action is required.

**Comment by felder** [comment]
I don't see any running pods this morning that have this issue.

I'm going to close this for now, but I'll still keep an eye out.
