### ISSUE TITLE
Data Archival Request for Tavisha Thapar - files from Data 100 Course (Fall 2020 semester)

### ISSUE THREAD

**Issue by tavisha-thapar** [berkeley-dsep-infra/hubs#3053]
### Email Id

tavisha.thapar@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/tavisha-2ethapar.tar.gz

**Comment by felder** [comment]
Signed url sent.

**Comment by tavisha-thapar** [comment]
question - there were only materials from fall 2018 in the folder. does data100 delete their course files? I had projects and stuff that are gone now, and only my data8 (from fall 2018) materials are left.
