### ISSUE TITLE
Agenda for Sprint Planning and Retro Meeting on 12/2!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3064]
Hi All,

Sharing the tentative agenda for the sprint planning and retro meeting on 12/2 (got clubbed due to the Thanksgiving holiday last week). Would you mind adding/editing/deleting the agenda items for this meeting? 

1. Retro: Reviewing the November Sprint (~15 minutes)
2. Curating and prioritizing cards for the December sprint (~25 minutes)
3. Review of EECS cost-sharing request (~10 mins)
4. Buffer time (~10 mins)

Removed:
4. Circle CI subscription discussion (~10 mins) @felder

**Comment by yuvipanda** [comment]
Let's just pay for CircleCI! That way we don't have to discuss this at the meeting, and get some time back :)

**Comment by yuvipanda** [comment]
Let's also run the home directory archival.

**Comment by felder** [comment]
I'd like to make sure we discuss issues #3048 #2946 

Specific to tasks outlined in #2946 we should also discuss staff availability.

**Comment by balajialg** [comment]
**Next Steps from the Sprint Planning Meeting:**

1. @balajialg to set up some time with the team to discuss the EECS cost-sharing request and figure out the next steps!
2. @felder to work closely with @yuvipanda in archiving home directories and clean up unused directories before holidays 
3. @yuvipanda to work closely with @ryanlovett to upgrade R studio and relevant R packages
5. @balajialg to reach out to the big classes to get their package, RAM, and admin access requirements at the end of the fall semester
6.  @balajialg to explore the site improve the tool for accessibility checking and create a detailed issue focused on accessibility challenges in the Jupyter notebook/lab
7. @felder to fiddle around with pager duty (if his time permits)
8. @balajialg to figure out the communication mechanism with instructors (Iterate on the newsletter idea further with @ericvd-ucb)
