### ISSUE TITLE
Seeking Clarification: Adding users to grafana dashboard!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3067]
As part of establishing a support process at ISchool, I spent some time orienting the teaching team about the admin feature in Datahub (today) and also explained the troubleshooting process we follow. They expressed interest in viewing grafana metrics so that they can review Ischool hub's performance on their own before escalating issues with us. 

Considering the precedent set with Data 8 [here](https://data8fall2021.slack.com/archives/C0293DZF1K5/p1636357934050700), I am inclined to provide dashboard access to the teaching team. Would like to know how to add users to the grafana dashboard?

**Comment by yuvipanda** [comment]
The privacy concern with giving people access to the grafana dashboard is that you can see which users are currently active on which board - although you can't see their files or anything. Is that an acceptable level of access? If so, I think it's great to provide access to the teaching team.

**Comment by balajialg** [comment]
@yuvipanda When you mean the "board," Do you mean the different views like "NFS Stats", "Cluster Health" etc. in grafana?  Since we only provide this access to the teaching team, it should not be a problem, right? I am inclined towards sharing this access as I am not able to visualize a negative consequence as of now.

If there is a way only to provide access to a specific grafana dashboard view tailored towards a particular hub, that would be a better deal, but I don't want to add more work unnecessarily. So I am inclined to provide this access to the teaching team on a case-by-case basis.

**Comment by yuvipanda** [comment]
@balajialg yeah, I think it's ok to share on a case by case basis.

**Comment by balajialg** [comment]
@yuvipanda, Can you elevate my access in grafana so that I can add users to grafana dashboard directly? Of course, I will align you all before adding new users but wanted to take away the logistical step
