### ISSUE TITLE
Create a new hub for astro

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#3105]
Mostly to simplify image management (see https://github.com/berkeley-dsep-infra/datahub/pull/3098), let's create a new hub for the astro department.

**Comment by yuvipanda** [comment]
@profjsb there now exists an astro.datahub.berkeley.edu! We can customize this to your liking. The image is very plain - just contains numpy and matplotlib now (https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/astro/image). Can you install things from conda-forge you want there via a PR? Should be much less hassle than doing the same in the huge datahub image.

I've installed a Linux Desktop environment in there by default so we can add FITS viewers and what not later if needed (see https://github.com/yuvipanda/ds9-binder for a demo). 

It currently puts people by default into classic notebook. I can turn that into JupyterLab or RetroLab as well if you would like.

I hope this makes managing dependencies much easier for you!

**Comment by balajialg** [comment]
Closing this issue as the task is complete! Thanks @yuvipanda
