### ISSUE TITLE
Solve for Circle CI deployment failures!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3129]
# Summary
We use CircleCI's free version for our CI/CD requirement which provides up to [6000 build minutes](https://circleci.com/pricing/) and 30k free credits per month. However, looking at our 9-month data from Circle CI, it is clear that we have been using more credits than offered and as a consequence @yuvipanda has been spending dollars from his credit card to pay for the extra cost.

![image](https://user-images.githubusercontent.com/2306166/149024586-6ba3d4c7-76ea-4366-a2cd-75007c518e2f.png)

In addition, 1/5th of jobs that were deployed during the last 3 months in Circle CI has resulted in a failure. @yuvipanda and @felder have made recommendations during different time periods to upgrade the Circle Ci account with more credits (The performance plan has 55k credits) so that we possibly don't face similar deployment failures in the future. Considering their request, we quickly need to make a decision on this upgrade and also figure out a policy + process around such requests in the future.

![image](https://user-images.githubusercontent.com/2306166/149024885-6f39c0c2-09f6-4b3f-bb89-a9145217136c.png)

Circle CI estimates the cost for this upgrade to be around $540 per year
![image](https://user-images.githubusercontent.com/2306166/149027518-9e4dbf12-9ef7-4490-b9de-a70e05e220bf.png)

@ericvd-ucb had suggestions about using Github Actions as the default CI/CD tool over Circle CI with the assumption that it provides free credits which should satisfy our needs. However, the point to consider is that GitHub actions have [2000 build minutes per month](https://github.com/pricing) compared to 6000 provided by Circle CI. Another point to consider is the technical cost of making this transition! I will leave it to the talented folks in the team to articulate the cost of switching to GA.

# Tasks to complete
1. Decision to upgrade Circle CI
2. Identify process and policy for such requests in the future
2. Reimburse the expenses incurred till now by @yuvipanda

**Comment by ryanlovett** [comment]
Another possibility is to try to reduce build times. For example, it may be possible to separate python and R environments into [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) so that the whole stack doesn't have to be rebuilt on smaller changes.

**Comment by balajialg** [comment]
@ryanlovett That's an interesting suggestion! 

- How complex an engineering/scripting task would that be?
- I know it is harder to estimate; what would be an order of magnitude in terms of reduction in build time would this task accomplish considering that we use extra 20k credits from Circle CI every month on an average during the course of the semester.

**Comment by ryanlovett** [comment]
I don't think it looks especially complex, but I've never created multi-stage builds. Maybe there would need to be changes to CI that involve hubploy?

If we were to have two stages, python and R, then the biggest savings would probably be for when there was a python modification and not an R modification. (From memory, the R build takes a lot longer.) The python image would get rebuilt, the R image wouldn't, and the multi-stage build would only take as long as it would for just python. (if I understand multi-stage correctly) So if the python portion takes X seconds and the R portion takes 2X seconds, then we'd save 2/3 build time for all python-only modifications. We have no analytics on the nature of our modifications.

**Comment by balajialg** [comment]
@ryanlovett Makes sense! Thanks for taking the time to articulate the value of a multistage build process.

We spent around $120 for 200,000 credits from Circle CI in the past six months. So if the build time gets reduced by 1/3rd or even 2/3rd, we are looking at saving around $40 - $80 (Correct me if I am not thinking about it in the right way). Considering that, would it make sense to just pay for the extra credits in the short term while optimizing our build time using the multi-stage build process in the long run?

**Comment by ryanlovett** [comment]
@balajialg Yes, that's a great way of looking at it! :)

**Comment by balajialg** [comment]
Upgraded the Circle CI account to a premium account!
