### ISSUE TITLE
Datahub retrieval

### ISSUE THREAD

**Issue by tarunikakapoor** [berkeley-dsep-infra/hubs#3136]
### Email Id

tarunikakapoor@berkeley,edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@tarunikakapoor I need the link to the datahub folder which should be in the text file on your instance.

**Comment by tarunikakapoor** [comment]
gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/tarunikakapoor.tar.gz

**Comment by felder** [comment]
Signed URL sent!
