### ISSUE TITLE
Increase compute resources for Course PS 3 on Tuesdays & Thursdays from 5-630 pm PT

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#3146]
### Course Name

https://classes.berkeley.edu/content/2022-spring-polsci-3-001-lec-001

### Detailed Requirements

350 students will be jumping into notebooks all at once at 5 pm PT on Tuesdays and Thursdays this semester (starting this Thursday).

### Semester Details

Yes

### Request Deadline

Thursday January 20, 5 pm

**Comment by balajialg** [comment]
@dbroockman We have over-provisioned resources for all hubs during the first week of classes to ensure that there are not many hassles due to auto-scaling. So, you should most likely not face any issues during this week. Let us know if it is otherwise. As it is costly to keep the status quo, Will create calendar events for your request in the subsequent weeks!

**Comment by dbroockman** [comment]
Thanks! Yes, this will be every Tues and Thurs at 5 all semester.

**Comment by balajialg** [comment]
- [x] Schedule 7 nodes from 4 - 8 PM PST on Tue and Thu!

**Comment by dbroockman** [comment]
I still have a few students who are reporting the notebook hanging on load. Do we need more resources by any chance?

**Comment by felder** [comment]
@dbroockman @balajialg looking at the node count and given dbroockman's comments maybe we should schedule 10 nodes between 4-8pm.

**Comment by balajialg** [comment]
@dbroockman Thanks for raising the performance issue! Let us know how the hub performs next week

@felder @yuvipanda Have scheduled 10 nodes for alpha pool between 4 - 7 PM on Tuesday and Thursday (Reason being - Last semester we scheduled around 7 nodes from 4.30 - 6.15 PM and, based on the feedback received it seemed to go smoothly).

**Comment by balajialg** [comment]
@dbroockman How did your class go this week? If it helps, You can also respond after your class today!

**Comment by dbroockman** [comment]
Things have been going well - no issues.

**Comment by balajialg** [comment]
Thanks a lot @dbroockman! Great to know that things are going smoothly. Will keep the current resource allocation as-is and close this issue! Please do reopen this issue if you face any issues during the semester.
