### ISSUE TITLE
Increase compute resources for Stat 20 between specific date(s)/time(s)

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3148]
### Course Name

- https://classes.berkeley.edu/content/2022-spring-stat-20-001-lec-001
- https://classes.berkeley.edu/content/2022-spring-stat-20-002-lec-002
- https://classes.berkeley.edu/content/2022-spring-stat-20-003-lec-003

### Detailed Requirements

 
The class has lecture MWF from 11a-12p. It will use RStudio with standard compute. The main issue is that the class has 600-700 students.

@andrewpbray What other time windows do you anticipate significant hub usage?

### Semester Details

Yes

### Request Deadline

The duration of the semester.

**Comment by andrewpbray** [comment]
The main usage times will be:

- Thursday 8 am - 8 pm (main lab day + study session)
- Monday 5 - 10:30 pm (labs at due at 10 pm)

**Comment by balajialg** [comment]
@andrewpbray @ryanlovett Thanks for raising this request! Will add a calendar event for the 1-hour slots raised by @ryanlovett. 

Trying to understand the impact of provisioning extra resources all day (on Thursday) has on the cloud costs. @yuvipanda @felder Is this something that we should be able to manage? or Should we start with the slots suggested by @ryanlovett and add more resources based on how the hub performs?

**Comment by andrewpbray** [comment]
The Thursday lab won't slam the data hub, it'll just be a time of higher-than-baseline usage since there will be lab meetings held throughout the day that will use the hub.

**Comment by felder** [comment]
@balajialg my understanding is we're boosting the compute resources across the board for semester startup.  Given that, I'm thinking we should see how the hub performs.  If the students come and go gradually throughout the day the resource usage might be such that we don't have to do much scaling.

**Comment by balajialg** [comment]
@felder Makes sense! Let's see the usage this week to make a call on this

**Comment by balajialg** [comment]
- [x] Set beta node count to 5 during Thursday

**Comment by balajialg** [comment]
@ryanlovett @yuvipanda @felder As per our discussion yesterday, Have scheduled 5 nodes for the beta pool between 8 AM - 8 PM every Thursday! Let me know if that's okay

**Comment by felder** [comment]
@balajialg If IIRC, @ryanlovett mentioned that there is an expectation that the labs may require more compute resources.

So I think 5 is good for now, but we should keep an eye on it because based on previous usage I think 3 would be appropriate.

**Comment by balajialg** [comment]
@felder Makes sense! Let's revisit this in a week or two

**Comment by ryanlovett** [comment]
@andrewpbray and I also discussed having him test a lab in advance, then we can check the CPU load of the pod at grafana. This would help us determine if we needed CPU guarantees, which would spread out the load.

**Comment by balajialg** [comment]
@andrewpbray @ryanlovett How did the labs go this week? Is the current resource allocation sufficient to handle your lab needs?

**Comment by andrewpbray** [comment]
So far so good. No reported incidences of significant load issues. The main issue we've been troubleshooting has to do with latex and compiling documents to pdf, but that's a config issue as far as I can tell, not a resources issue. 

Thanks for checking in.

**Comment by balajialg** [comment]
Great @andrewpbray! I am closing this issue as of now. Please feel free to reopen if the resourcing issue occurs.

On another note, is the issue you are facing with latex, similar to the issue highlighted [here](https://github.com/berkeley-dsep-infra/datahub/issues/2664)?

**Comment by ryanlovett** [comment]
@balajialg It is similar to that report. The knitting process fails in the latex stage because graphics are either too big, or do not pass some unknown measure that a simple `convert old.jpg new.jpg` fixes. I added the `pagedown` R package and Google Chrome so that students can convert by using a headless web browser, which is analogous to what @yuvipanda mentioned in the linked issue. Migrating to `pagedown` requires altering some of the lab templates however. I'm not sure whether some of the included stylesheets are suitable for the assignments. They do generate working PDFs though.

**Comment by balajialg** [comment]
@ryanlovett Thanks a lot for this hack! Is this hack a solution that we can recommend to other profs who may face a similar issue with latex? More from the feasibility of implementing this change across other hubs?

**Comment by ryanlovett** [comment]
@balajialg I think one would need to find out if any other instructors also have as much trouble with latex within RStudio. If so then one would need to identify a suitable [pagedown](https://github.com/rstudio/pagedown) style that is appropriate for that class' assignments. I have a feeling there is none and that one would have to be crafted.

**Comment by balajialg** [comment]
Sounds good! It is effort-intensive at our end to find the suitable pagedown style I guess.  Will keep this in mind for future requests.
