### ISSUE TITLE
Add Admin Access to Data 100 Hub

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#3198]
### Your Name

Dominic Liu

### Affiliated Course Name

Data 100

### Role

TA

### Name of the Hub

- Data 100

### List of Usernames

- yanlisa
- hug@cs.berkeley.edu

### End Date

- 05/20/2022

**Comment by balajialg** [comment]
@Dominicliu129 Instead of cs.berkeley.edu id, Can I use j.hug@berkeley.edu id for creating admin credentials?

**Comment by Dominicliu129** [comment]
@balajialg Hi, I think Prof. Hug uses h___@berkeley.edu for datahub, can you add this instead? Thank you!

**Comment by balajialg** [comment]
@Dominicliu129 Let's add the cs.berkeley.edu account for now (considering the PR is merged in prod). If the prof has issues with accessing the admin instance, I will create another PR with your suggested email id.

**Comment by Dominicliu129** [comment]
@balajialg Hi! I don't think yanlisa has been added to the datahub admin? Can you check again?

**Comment by balajialg** [comment]
@Dominicliu129 Yes, already added. Can you ask the user to restart the server and confirm the same?
