### ISSUE TITLE
Request kaleido package for ds100

### ISSUE THREAD

**Issue by joshHug** [berkeley-dsep-infra/hubs#3208]
### Package Name

kaleido

### Hub details

- Hub: Data 100
- Language: Python

### Course Name

https://ds100.org/sp22/ - Josh Hug and Lisa Yan

### Semester Details

Sp22

### Installation Deadline

If possible we'd love to have this by Friday, but understand if that's not feasible.

**Comment by felder** [comment]
@joshHug 

Having trouble adding packages to datahub right now, opened issue #3216 to investigate.

As soon as this is figured out, I'll resume adding kaleido.  Sorry for the inconvenience.

**Comment by felder** [comment]
Done!
