### ISSUE TITLE
datahub image fails when building ottr for R

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3216]
### Bug description

When building the datahub image, the following error is produced:

```
Step 38/95 : RUN r /tmp/r-packages/econ-140.r && rm -rf /tmp/downloaded_packages
 ---> Running in abdf31d30694
[1] "Installing packages for Econ 140"
[1] "Installing ottr..."
Downloading GitHub repo ucbds-infra/ottr@1.1.1


* checking for file ‘/tmp/remotes61c6a99d/ucbds-infra-ottr-cec1b94/DESCRIPTION’ ... OK
* preparing ‘ottr’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘ottr_1.1.1.tar.gz’

Installing package into ‘/opt/r’
(as ‘lib’ is unspecified)
* installing *source* package ‘ottr’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading

** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location

** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ottr)

Error in `action()`:
! `class` is absent but must be supplied.
Backtrace:
     ▆
  1. ├─base `<fn>`("/tmp/r-packages/econ-140.r", print.eval = FALSE)
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. └─devtools::install_github(...) at tmp/r-packages/econ-140.r:10:0
  6.   └─rlang `<fn>`() at tmp/r-packages/econ-140.r:10:0
  7.     └─rlang:::check_dots(env, error, action, call)
  8.       └─rlang:::action_dots(...)
  9.         ├─base try_dots(...)
 10.         └─rlang action(...)
 11.           └─rlang:::validate_signal_args(.subclass)
 12.             └─rlang::check_required(class, call = env)
 13.               └─rlang::abort(msg, call = call)
Removing intermediate container abdf31d30694
The command '/bin/sh -c r /tmp/r-packages/econ-140.r && rm -rf /tmp/downloaded_packages' returned a non-zero code: 1Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy", line 8, in <module>
    sys.exit(main())
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 122, in main
    image.build(not args.no_cache)
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/config.py", line 160, in build
    self.r2d.build()
  File "/root/repo/venv/lib/python3.7/site-packages/repo2docker/app.py", line 812, in build
    raise BuildError(l["error"])
repo2docker.engine.BuildError: The command '/bin/sh -c r /tmp/r-packages/econ-140.r && rm -rf /tmp/downloaded_packages' returned a non-zero code: 1

Exited with code exit status 1

CircleCI received exit code 1
```
You can see the output from circleci here:
https://app.circleci.com/pipelines/github/berkeley-dsep-infra/datahub/1085/workflows/6a8faa6b-b65c-4652-8088-a9611332c7db/jobs/9210

### Environment & setup

- Hub: datahub
- Language: R, ottr-1.1.1 via econ-140.r

I attempted moving econ-140.r around in the build order and there was no change with this particular issue.

### How to reproduce

Attempt to build the datahub docker image.

**Comment by felder** [comment]
@chrispyles Do you perhaps have any idea what this is about?

**Comment by felder** [comment]
@ryanlovett @yuvipanda ottr builds if I comment out the lines in the Dockerfile that pertain install.R and specify the devtools installation as part of econ-140.r.

**Comment by felder** [comment]
I'm going to try specifying the devtools install in both econ-140.r and install.R, and I'm going to place econ-140.r above  install.R in the Dockerfile

**Comment by felder** [comment]
I'm doing a test build for a PR that I think is going to work.

**Comment by chrispyles** [comment]
Sorry for the late response @felder but I'm not sure what the issue is here. If you figure out what it is please let me know - there are a couple Docker bugs in the main Otter repo that may be related (not 100% sure though). Thanks and sorry I couldn't be of more help!

**Comment by felder** [comment]
@chrispyles I'm not sure what the actual cause is, but I was able to work around it by moving ottr to a different spot in the Dockerfile.  Must be some sort of weird dependency conflict.  Sadly, it would appear the error that is thrown has not even been indexed by google.

**Comment by chrispyles** [comment]
Hmm that's odd. Well I'm currently in the process of getting ottr put onto CRAN so maybe once that's up we could try  `install.packages` instead to see if that could alleviate the issue?

**Comment by felder** [comment]
@chrispyles sure.  However I think we're still on ottr 1.1.1.  My understanding is there might be some breaking changes in future versions, but I could be wrong.

**Comment by felder** [comment]
I believe this is now fixed.  Ottr builds and I can import the library via R studio.

**Comment by ryanlovett** [comment]
Nice detective work @felder!

**Comment by balajialg** [comment]
Agreed, thanks for investigating this @felder
