### ISSUE TITLE
gs://ucb-datahub-archived-homedirs/spring-2021/data100.berkeley.edu/smarvin.tar.gz

### ISSUE THREAD

**Issue by sabrinamarvin** [berkeley-dsep-infra/hubs#3217]
### Email Id

smarvin@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Signed URL sent!
