### ISSUE TITLE
data100 PostgreSQL containers cause deployments to fail.

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3225]
### Bug description

```
$ kubectl -n data100-prod get pod | grep image
continuous-image-puller-2ltxt   1/1     Running                 0          6d18h
continuous-image-puller-4jvtr   1/1     Running                 0          7d17h
continuous-image-puller-4n8vg   1/1     Running                 0          7d17h
continuous-image-puller-n8g2n   1/1     Running                 0          7d17h
continuous-image-puller-x7s99   1/1     Running                 0          7d17h
hook-image-awaiter-zt9fx        1/1     Running                 0          5d2h
hook-image-puller-26jk9         0/1     Init:ImagePullBackOff   0          5d2h
hook-image-puller-6q5rv         0/1     Init:ImagePullBackOff   0          5d2h
hook-image-puller-6wn82         0/1     Init:ImagePullBackOff   0          5d2h
hook-image-puller-7kgxn         0/1     Init:ImagePullBackOff   0          5d2h
hook-image-puller-mm9rd         1/1     Running                 0          5d2h
```

```
$ kubectl -n data100-prod describe pod hook-image-puller-26jk9
...
Events:
  Type    Reason   Age                       From     Message
  ----    ------   ----                      ----     -------
  Normal  BackOff  2m21s (x32502 over 5d2h)  kubelet  Back-off pulling image "gcr.io/ucb-datahub-2018/jupyterhub-postgres:0.0.1-n3657.h4f7f88c"
```

### Environment & setup

- Hub: data100-staging, data100-prod
- Language: PostgreSQL 

### How to reproduce

Tell hubploy to deploy to data100-staging or data100-prod with the postgresql container defined in the config.

**Comment by felder** [comment]
Note I double checked with data100 instructors to make sure this would not cause an issue.  It seems unlikely it would, because I do not believe this container is working currently anyway.

The data100 instructors have also been notified that they should file an issue if they believe they are going to need postgresql in the future.

**Comment by felder** [comment]
I caused a brief outage for data100-prod while implementing a fix for the deployment problems.

**Comment by felder** [comment]
@yuvipanda if we don't need postgresql it's probably safe to close this.

**Comment by balajialg** [comment]
Closing it as per slack comment - https://uctech.slack.com/archives/CC3NKQA3B/p1643987599130899?thread_ts=1643748432.834489&cid=CC3NKQA3B
