### ISSUE TITLE
Add GSI to ENVECON C118

### ISSUE THREAD

**Issue by searsjm** [berkeley-dsep-infra/hubs#3229]
### Your Name

James Sears

### Affiliated Course Name

ENVECON C118

### Role

GSI

### Name of the Hub

ENVECON-118-SP22

### List of Usernames

lenjb

### End Date

05/31/22

**Comment by balajialg** [comment]
@searsjm Is this Datahub (datahub.berkeley.edu)?

**Comment by searsjm** [comment]
Yes, for Datahub https://github.com/ds-modules/ENVECON-118-SP22

**Comment by balajialg** [comment]
Done
