### ISSUE TITLE
[Minor Issue] Correct SyncThing option's case to align with other options in the "New" Dropdown list

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3241]
### Bug description

"syncthing" text's case is not in alignment with other options available in the new drop-down list. It will be helpful if we can change the label "synching" to "SyncThing"

![image](https://user-images.githubusercontent.com/2306166/152606257-7463c811-74eb-4803-a12c-66064ceaad3b.png)

### Environment & setup

- All hubs where syncthing is enabled

### How to reproduce

1. Launch Datahub
2. Access the home page
3. Click the "New" dropdown list
4. You can see that "syncthing" option is not in alignment with other options.

**Comment by balajialg** [comment]
In prod - ![image](https://user-images.githubusercontent.com/2306166/166743989-f22a3b16-e591-41cc-94ea-98f6942016f9.png)

**Comment by felder** [comment]
@balajialg It looks different to me in staging.
![Screen Shot 2022-05-04 at 1 47 22 PM](https://user-images.githubusercontent.com/1211730/166804962-6ec3abe1-7c7a-40d7-828e-e20070ce5ba1.png)

**Comment by felder** [comment]
Although it now says Syncthing instead of SyncThing.

**Comment by balajialg** [comment]
Issue fixed. Thanks @yuvipanda!
![image](https://user-images.githubusercontent.com/2306166/169850421-4812eeed-7685-4c21-a199-e9de940c7705.png)
