### ISSUE TITLE
Econ 140

### ISSUE THREAD

**Issue by bcav2334** [berkeley-dsep-infra/hubs#3244]
### Bug description

I have a problem set due this Friday for Econ 140 and it is not showing up on my dashboard on Jupyterhub like the rest of my class. I don’t know why I do not have access because I have signed in a logged out multiple times to refresh the page and nothing is helping. 

### Environment & setup

- Hub: 
- Language:

**Comment by balajialg** [comment]
@bcav2334 Hey, Can completely understand your frustration but need the following information to dig further,

- Link to the assignment as shared by the course instructor
- Your Calnet id (email id without @berkeley.edu part)
- Link to your hub is datahub.berkeley,edu? right?

Would request you to take a few more minutes to fill the bug template as that would reduce the back and forth communication. Thanks!

**Comment by bcav2334** [comment]
The instructor didn’t send any link for the assignment. He just said the
assignment should already be on our Jupyterhub accounts. And it is bcav2334

**Comment by balajialg** [comment]
@bcav2334 Not sure whether that's feasible. You should reach out to your instructor to get the unique link that populates your assignment in Datahub. The assignment would not appear directly in your account without accessing those links. 

On another note, can you check whether the problem set links presented in this repository works for you? https://github.com/ds-modules/ECON-140-SP22

**Comment by bcav2334** [comment]
That’s it I can access them now. I appreciate it!

**Comment by felder** [comment]
@bcav2334 just a quick follow up, as @balajialg mentioned it's not feasible for assignments to just show up in your datahub account.  Any data in your account must be created by you or downloaded through some sort of interaction like clicking on a problem set link.
