### ISSUE TITLE
nbdime not displaying diff contents via proxy

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3245]
### Bug description

Let's say there's two notebooks `nb1` and `nb2` that simply differ in their content as follows:

![image](https://user-images.githubusercontent.com/57394/152900885-561fc5e4-de2b-493f-aaab-09e112e489f1.png)

I can view their diff at the cmd line with `nbdime diff nb1.ipynb nb2.ipynb`:

![image](https://user-images.githubusercontent.com/57394/152900941-6c1b7d70-770b-4909-9223-8d872ff72f89.png)

But when trying to access the output of `nbdime diff-web`, I can't seem to see the content...

I call it with 

`nbdime diff-web --ip 0.0.0.0 -p 8001 nb1.ipynb nb2.ipynb` 

to fix IP/port, and then try to view the output with the proxy, by connecting to `https://stat159.datahub.berkeley.edu/user-redirect/proxy/8001/diff?base=nb1.ipynb&remote=nb2.ipynb`

However, when I connect to that page, I see this only:

![image](https://user-images.githubusercontent.com/57394/152902109-ad4f3a19-366e-4fd7-9641-9f71982f3501.png)

and no actual content... I know, however, the content is there and being served correctly by nbdime, as I can see it if I open a local browser to the same address by using the VNC client:

![image](https://user-images.githubusercontent.com/57394/152902332-62a84afd-7aab-4112-b166-a18f67a20961.png)

I'm pretty confused as to what's going on here...

### Environment & setup

- Hub: stat159

### How to reproduce

Steps above in the description, it seemed easier to explain it all together.

**Comment by ryanlovett** [comment]
@fperez This might be a bug in jupyter-server-proxy or nbdime. Can you please check the browser's developer console and see if there are any errors? I'm guessing that it is reporting 404s for js and/or css files.

**Comment by fperez** [comment]
Thx @ryanlovett - I see the following error message on my console, and nothing else:

```
Loading failed for the <script> with source “https://stat159.datahub.berkeley.edu/static/nbdime.js?v=5f53beca6d127b99ce9ef6ec418202a9b1a26c9d74b12124ebed5a5ca2bcbd6de7a62b0f58e3d0ece7a4f13e18bc73a90d3ab34f43511a7c58ba49bf269fce98”.
```

I'm basically a total ignoramus on webdev debugging, so I'm not sure what to provide you next, sorry!

**Comment by ryanlovett** [comment]
No worries, that error indicates that nbdime.js is not being served by the right base URL -- it is actually available at `/user/{user}/proxy/8001/static/nbdime.js`. I fiddled with nbdiff-web's `--base-url` parameter but was not successful.

If you create ~/.jupyter/jupyter_notebook_config.py with:
```
c.ServerProxy.servers = {
  'nbdime': {
    'command': ['nbdiff-web', '--ip', '0.0.0.0', '-p', '{port}', '--base-url', '{base_url}nbdime/'],
    'absolute_url': True
  }
}
```

and then restart your server, you will see a new launcher in the lab interface named `nbdime`. This will spawn a new browser tab with nbdiff-web running in it. Setting up a named proxy server, and passing in the base url and setting `absolute_url` to True helps nbdiff-web find the static web assets.

<img width="1101" alt="Screen Shot 2022-02-08 at 5 07 56 PM" src="https://user-images.githubusercontent.com/10248125/153102443-5167e8a3-673f-44b9-9449-6497767c5560.png">


Is this development method just for you or do you want your students to have it too?

**Comment by fperez** [comment]
This was for the students too - it's part of my plan of having them live fully in the hub, and do all manner of "real world" development work. Trying to really "live in the hub" has made me quickly realize how many web apps we use these days, and so I'm trying to dog-food this as much as I can by testing it myself first.

Thanks a lot for this input though, this is already a great step in the right direction!

**Comment by fperez** [comment]
The only problem I see with the above is that tools like `nbdime`  have multiple cmd-line args, and we don't want to have to hardcode every possible call with a new launcher entry..

**Comment by ryanlovett** [comment]
I was able to get the CLI invocation to serve the shared assets properly. You can launch from the command-line with:

`nbdiff-web --ip 0.0.0.0 -p 9999 --base-url /user/{user}/proxy/absolute/9999`

and then visit https://stat159.datahub.berkeley.edu/user/{user}/proxy/absolute/9999/diff. So this gives you the ability to easily change nbdiff-web's invocation, at the expense of a somewhat unwieldy command.

It seems like it would be convenient if nbdiff-web had in-app controls (or query string args?) to alter the same behavior as the command-line parameters.

Let me know if you want everyone to be able to see the nbdime launcher since we can push it to the singleuser config. Unfortunately there's no way to dynamically change the proxy launcher parameters.

**Comment by balajialg** [comment]
Thanks a lot, @ryanlovett for looking into this!  Appreciate it. I am not sure about the effort involved in pushing this to a single user-config (will let @fperez take a call on the urgency/desirability) but having nbdime launcher in UI seems like the right direction to go in the long run if we don't support any other alternative tool to do this task. I see this as a pathway not just to support Stat 159 but to engage more instructors who want to expose students to git via Datahub and want tools that facilitate it (like #3133)

**Comment by fperez** [comment]
Thanks a lot @ryanlovett! I'm looking into this but I'm failing with your instructions - am I meant to replace anything in them or should I type them as-is? I'm getting the Jupyter 404 when I run them as-is:

![image](https://user-images.githubusercontent.com/57394/153489367-cc4aeeeb-06a9-4a62-aa0b-ccf202d5d02c.png)

and then I go to the URL you provide above, and I get:

![image](https://user-images.githubusercontent.com/57394/153489439-a291ac55-efae-49e1-b7b3-78551e7926da.png)

If I can get this to work reliably, I think for now it's an OK solution for 159: I can guide them to making an alias and triggering it from the terminal, that's OK in this setting for now. And we can think about UI improvements both on nbdime and Lab over time...

**Comment by ryanlovett** [comment]
Ah, yes, sorry @fperez! You should replace `{user}` with the username, e.g. /user/rylo/proxy/absolute/...

**Comment by fperez** [comment]
I should have known, thx - I was wondering but thought it might be a template variable that nbdime was smart enough to map on its own. No worries :)

The good news is that the correct user name is available as `$JUPYTERHUB_USER`, so we can put this into a command-line wrapper or an alias that works consistently... 

In summary, the user should call:

```
nbdiff-web --ip 0.0.0.0 -p 9999 --base-url /user/$JUPYTERHUB_USER/proxy/absolute/9999  <notebook name>
```

And then open this URL (which is also username-independent):

https://stat159.datahub.berkeley.edu/user-redirect/proxy/absolute/9999/difftool

I'm thinking of a convenient way to wrap this for them, but for now I'll start just with some basic instructions they can copy/paste the above from. 

So we're on the right track, thanks!
