### ISSUE TITLE
Retrieve my old Datahub files

### ISSUE THREAD

**Issue by irisk2050** [berkeley-dsep-infra/hubs#3258]
### Email Id

minjeekim303@berkeley.edu

I have a problem; I filled out this request before, but some of my files are missing. I took Data 100 in Spring 2020 and did not see those files in my last retrieval.

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/minjeekim303.tar.gz

**Comment by felder** [comment]
@irisk2050 

Each hub has it's own filesystem and it's own set of archived files.  Thus a request for me to retrieve files for datahub.berkeley.edu will not include files from data100.

Can you please login to data100.datahub.berkeley.edu and post the link to the datahub folder that is listed there?

**Comment by irisk2050** [comment]
https://data100.datahub.berkeley.edu/user/minjeekim303/lab/tree/sp20

These files are all blank; my submitted work is not there.

**Comment by irisk2050** [comment]
https://data100.datahub.berkeley.edu/user/minjeekim303/lab

**Comment by felder** [comment]
```
# cat WHERE-ARE-MY-FILES.txt

Your files have been archived due to inactivity.

If you want to retrieve a copy of your files, please open a Data Archival Request via github here:
https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml

The following text is the link to your datahub folder, it must be included with your request:
gs://ucb-datahub-archived-homedirs/spring-2021/data100.berkeley.edu/minjeekim303.tar.gz
```

**Comment by felder** [comment]
Signed URL sent!
