### ISSUE TITLE
Request 4 GB RAM for class Stat 159

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3273]
**Which hub do you want more RAM on?**

Stat 159 hub

**Which class is this request for?**

Stat 159
https://classes.berkeley.edu/content/2022-spring-stat-159-001-lec-001

**How many students do you expect in this class?**

An approximate number would do.
~57

**How much RAM does this class need?**

4 GB RAM 

Why does this class need this much RAM?

We're starting to analyze datasets where the processing crashes the kernel at the 1GB limit. I tested on a 4GB machine and saw my memory consumption hover around 2 GB on average, so I'm pretty sure a 4GB node would suffice.

By when (MM/DD) do you want this request to be fulfilled?

Ideally by 2/23/2022 - I'm sorry to make the request on short notice, I only saw the problem this morning when I loaded a new dataset for next week's lectures into the hub.

**Any additional information we should know about?**

**Comment by balajialg** [comment]
Based on our [policy](https://github.com/berkeley-dsep-infra/datahub/issues/2785) for RAM allocation, this should be a yes!

**Comment by yuvipanda** [comment]
This was done in #3274
