### ISSUE TITLE
No desktop menus/controls on VNC but only for some users

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3277]
### Bug description

This is what the VNC desktop looks like for me and most of my students:

![image](https://user-images.githubusercontent.com/57394/154776305-1f186bfb-44df-4cd4-b94d-4541110701b3.png)

However, for _some_ students, there are no top or bottom panels, no "Applications"  menu, and only a strange blank hovering bar:

![image](https://user-images.githubusercontent.com/57394/154776370-99c25dac-5cc5-496c-a0f8-c9e19381061f.png)

Can anyone here think what could be going on? Is it a server-side problem, or could the students have done something to their config to cause this?

I'll continue investigating, but I figured I'd ask in case anyone has ideas...

### Environment & setup

- Hub: Stat 159

### How to reproduce

Unfortunately I have no idea. It was reported in class by some students and I took that screenshot as they screen shared, but I don't know what the problem might be.

I'll try to track down who it was and log in as their user from the admin interface to play with it a bit more, and will add to this issue if I learn more.

**Comment by ryanlovett** [comment]
@fperez Iirc, when xfce starts for the first time, [it asks](https://linuxhint.com/wp-content/uploads/2017/12/arch-15.png) if you want the default panel or one empty one. I wonder if this is the result of people not choosing the default?

If so, it might be that the short term solution is to either reset the panel preferences*, or one can right-click on the floating panel, and configure it to behave like the default.

Long term, it'd be best to [choose the default automatically](https://unix.stackexchange.com/questions/155007/xfce4-panel-default-layout-without-asking-a-user-during-the-first-login/312783). But this is all based on if this is the result of the original choice.

* [something like](https://askubuntu.com/a/224037) `xfce4-panel --quit ; pkill xfconfd ; rm -rf ~/.config/xfce4/panel ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml ; xfce4-panel &`

**Comment by fperez** [comment]
Ah, good catch @ryanlovett, that's probably it. I'll pass the info along, thx!

**Comment by fperez** [comment]
Let's close this one as I suspect @ryanlovett's answer is correct, and that's enough to get our users moving. Thx!!

**Comment by balajialg** [comment]
Thanks, @fperez! Appreciate it
