### ISSUE TITLE
Request python package openpyxl for class ESPM-109E

### ISSUE THREAD

**Issue by jonathanferrari** [berkeley-dsep-infra/hubs#3280]
### Package Name

openpyxl

### Hub details

- Hub: 
–> Datahub
- Language: 
–> Python
###

### Course Name

[ESPM 109E](http://guide.berkeley.edu/courses/espm/#:~:text=ESPM%C2%A0109E%20Data,Expand%20course%20description)
Data Science Communication and Professionalism

### Semester Details

Spring 2022

### Installation Deadline

Preferably by 2/28, needed for class use in march

**Comment by felder** [comment]
openpyxl is already installed.

```
jovyan@jupyter-felder:~$ pip list | grep -i pyxl
openpyxl                          3.0.7
```
