### ISSUE TITLE
FEniCS on datahub

### ISSUE THREAD

**Issue by sanjayg0** [berkeley-dsep-infra/hubs#3305]
For the finite element course CE 133, ME 180, and ME 280A (and perhaps more), we often use FEniCS.  Would it be possible to have these packages available in the datahub jupyter notebooks?

The configuration has been worked out for google colab and it seems to work there but we would prefer to use datahub.  Given the power of FEniCS, it could prove to be useful for a lot more people.

Here is the script to get working on colab:
try:
    import dolfin
    import mshr
except ImportError:
    !wget "https://fem-on-colab.github.io/releases/fenics-install.sh" -O "/tmp/fenics-install.sh" && bash "/tmp/fenics-install.sh"
    import dolfin
    import mshr

**Comment by felder** [comment]
Looks we can pull this in with apt as it appears to be an available package.

python3-mshr, python3-dolfin, python3-slepc4py, python3-boost, python3-pybind11, and fenics are all available.

That will be preferable to pulling in a shell script and executing it.

**Comment by sanjayg0** [comment]
This sounds great.   I will be happy to perform some testing once you are ready.

**Comment by felder** [comment]
@sanjayg0 great!  It's working on deploying to staging (https://staging.datahub.berkeley.edu) currently.  It'll likely be another 30m or so before the deploy completes.  At that point I'll login to staging and verify the imports in your description work, then I'll ask you to test one of your notebooks in staging before I merge it to production.

**Comment by felder** [comment]
Hmm that no workie.

I'm going to send another job through to have conda install it.

**Comment by sanjayg0** [comment]
For what it is worth, I did an install on an Ubuntu box last night with

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:fenics-packages/fenics
sudo apt-get update
sudo apt-get install fenics

That seemed to pull down everything I needed for some basic tests.

**Comment by felder** [comment]
@sanjayg0 yeah using apt worked, but datahub calls python via a conda environment so the installed modules were not available for use by notebooks.

Hopefully the PR I'm working on now will cause the right thing to happen.  Alas it takes about 3 hours before I can test a change in staging.

**Comment by felder** [comment]
@sanjayg0 ok progress

```
jovyan@jupyter-felder:~$ conda list | grep fenics
fenics                    2019.1.0        py39hf3d152e_26    conda-forge
fenics-dijitso            2019.1.0        py39hf3d152e_26    conda-forge
fenics-dolfin             2019.1.0        py39h68d5232_26    conda-forge
fenics-ffc                2019.1.0        py39hf3d152e_26    conda-forge
fenics-fiat               2019.1.0        py39hf3d152e_26    conda-forge
fenics-libdolfin          2019.1.0            h12c0dc9_26    conda-forge
fenics-ufl                2019.1.0        py39hf3d152e_26    conda-forge
```

dolfin imports in staging

```
import dolfin
import mshr

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import dolfin
----> 2 import mshr

ModuleNotFoundError: No module named 'mshr'
```


mshr didn't come with, however.

```
jovyan@jupyter-felder:~$ conda list | grep -E 'boost|slepc4py|mshr|pybind11'
boost-cpp                 1.74.0               h312852a_4    conda-forge
pybind11                  2.8.1            py39h1a9c180_1    conda-forge
pybind11-global           2.8.1            py39h1a9c180_1    conda-forge
slepc4py                  3.16.1          real_hd623573_100    conda-forge
```

I'm going to add mshr and send it through again.

**Comment by felder** [comment]
@sanjayg0 The two imports noted in your description now work.

```
jovyan@jupyter-felder:~$ conda list | grep -E 'boost|slepc4py|mshr|pybind11|fenics'
boost-cpp                 1.74.0               h312852a_4    conda-forge
fenics                    2019.1.0        py39hf3d152e_26    conda-forge
fenics-dijitso            2019.1.0        py39hf3d152e_26    conda-forge
fenics-dolfin             2019.1.0        py39h68d5232_26    conda-forge
fenics-ffc                2019.1.0        py39hf3d152e_26    conda-forge
fenics-fiat               2019.1.0        py39hf3d152e_26    conda-forge
fenics-libdolfin          2019.1.0            h12c0dc9_26    conda-forge
fenics-ufl                2019.1.0        py39hf3d152e_26    conda-forge
mshr                      2019.1.0         py39h9761ab4_5    conda-forge
pybind11                  2.8.1            py39h1a9c180_1    conda-forge
pybind11-global           2.8.1            py39h1a9c180_1    conda-forge
slepc4py                  3.16.1          real_hd623573_100    conda-forge
```

Can you please test on https://staging.datahub.berkeley.edu ?

**Comment by sanjayg0** [comment]
I've run a few tests and it seems to be working

**Comment by sanjayg0** [comment]
One thing that I notice is that if the memory hits 1GB, then the kernel crashes.   That seems kind of bad as it is easy to exceed a need for 1GB in a computation.

**Comment by felder** [comment]
@sanjayg0 1GB is the default memory allocation we provide, and yes there is no virtual memory so if you exceed your RAM allocation your kernel will crash.

You can request an increase for your class.

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&template=higher-resources.md&title=Request+more+RAM+for+class+X

Example:  https://github.com/berkeley-dsep-infra/datahub/issues/3296

**Comment by felder** [comment]
Deployed to prod.
