### ISSUE TITLE
Request more RAM for class CE C133/ME C180, Spring 2022

### ISSUE THREAD

**Issue by sanjayg0** [berkeley-dsep-infra/hubs#3317]
**Which hub do you want more RAM on?**
 datahub

**Which class is this request for?**
CE C133/ME C180  
https://classes.berkeley.edu/content/2022-spring-civeng-c133-001-lec-001
https://classes.berkeley.edu/content/2022-spring-meceng-c180-001-lec-001

**How many students do you expect in this class?**
65

**How much RAM does this class need?**

4GB per student

**Why does this class need this much RAM?**

Assignments involve the use of FEniCS which involves solving large systems of linear equations, which can consume a far bit of memory.  In some of my test runs, I easily exceed the current 1GB limit.  Past experience indicates that 4GB should be safe.

**By when (MM/DD) do you want this request to be fulfilled?**

03/28

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@sanjayg0 Thanks for raising this request! I assume you are using the main Datahub which has 1 GB RAM as a limit. The general use case for Datahub is to support intro-level courses using standard packages for which 1 GB RAM is more than sufficient. Considering your unique requirements from a RAM and [package ](https://github.com/berkeley-dsep-infra/datahub/issues/3305) standpoint, I will have a discussion with our team internally on the potential solutions to resolve your request. Is 03/28 a hard deadline at your end or are you flexible with this request  (maybe get it resolved in the next 2/3 days)?

**Comment by sanjayg0** [comment]
3/28 is slightly flexible.  I just posted a datahub assignment for the 
class but I think it can be accomplished mostly without hitting the 1GB 
limit, but on occasion I have hit it, so the sooner the better.  The 
next class assignment will almost definitely hit the limit.  The 
student's can also jump over to Google colab but that is rather 
non-ideal since they have to run a full install of the packages each 
time they fire up the server.

-------------------------------------------------------------------
Sanjay Govindjee, PhD, PE
Horace, Dorothy, and Katherine Johnson Professor in Engineering

779 Davis Hall
University of California
Berkeley, CA 94720-1710

Voice:  +1 510 642 6060
FAX:    +1 510 643 5264
***@***.***
http://faculty.ce.berkeley.edu/sanjay
-------------------------------------------------------------------

Books:

Continuum Mechanics of Solids
https://global.oup.com/academic/product/continuum-mechanics-of-solids-9780198864721

Example Problems for Continuum Mechanics of Solids
https://www.amazon.com/dp/1083047361/

Engineering Mechanics of Deformable Solids
https://www.amazon.com/dp/0199651647

Engineering Mechanics 3 (Dynamics) 2nd Edition
http://www.amazon.com/dp/3642537111

Engineering Mechanics 3, Supplementary Problems: Dynamics
http://www.amzn.com/B00SOXN8JU

-------------------------------------------------------------------
NSF NHERI SimCenter
https://simcenter.designsafe-ci.org/
-------------------------------------------------------------------

**Comment by balajialg** [comment]
@sanjayg0 Thanks for the info! We will try to resolve your request as soon as possible (either today/tomorrow) so that it is not a blocker for your next assignment.

**Comment by felder** [comment]
Done!

**Comment by balajialg** [comment]
Thanks a lot @felder for the quick turnaround!

**Comment by sanjayg0** [comment]
How does one "access" the higher RAM limit?
-------------------------------------------------------------------
Sanjay Govindjee, PhD, PE
Horace, Dorothy, and Katherine Johnson Professor in Engineering

779 Davis Hall
University of California
Berkeley, CA 94720-1710

Voice:  +1 510 642 6060
FAX:    +1 510 643 5264
***@***.***
http://faculty.ce.berkeley.edu/sanjay
-------------------------------------------------------------------

Books:

Continuum Mechanics of Solids
https://global.oup.com/academic/product/continuum-mechanics-of-solids-9780198864721

Example Problems for Continuum Mechanics of Solids
https://www.amazon.com/dp/1083047361/

Engineering Mechanics of Deformable Solids
https://www.amazon.com/dp/0199651647

Engineering Mechanics 3 (Dynamics) 2nd Edition
http://www.amazon.com/dp/3642537111

Engineering Mechanics 3, Supplementary Problems: Dynamics
http://www.amzn.com/B00SOXN8JU

-------------------------------------------------------------------
NSF NHERI SimCenter
https://simcenter.designsafe-ci.org/
-------------------------------------------------------------------

**Comment by felder** [comment]
@sanjayg0 The limit is tied to the course.  When someone who is associated with the course signs in, they receive it.

**Comment by sanjayg0** [comment]
Thanks.  So it will be automatic for the student.
If possible, please also tag the instructors,
myself and Nikolay G Velkov, who handles the labs.

**Comment by felder** [comment]
@sanjayg0 I thought I had merged this to prod, but for some reason did not.  I'm merging it now.

I believe the instructors should also get the increase.  Please test.

If you have a running server, you have to stop it and relaunch it first.

**Comment by sanjayg0** [comment]
just tried it again and it is working.

-------------------------------------------------------------------
Sanjay Govindjee, PhD, PE
Horace, Dorothy, and Katherine Johnson Professor in Engineering

779 Davis Hall
University of California
Berkeley, CA 94720-1710

Voice:  +1 510 642 6060
FAX:    +1 510 643 5264
***@***.***
http://faculty.ce.berkeley.edu/sanjay
-------------------------------------------------------------------

Books:

Continuum Mechanics of Solids
https://global.oup.com/academic/product/continuum-mechanics-of-solids-9780198864721

Example Problems for Continuum Mechanics of Solids
https://www.amazon.com/dp/1083047361/

Engineering Mechanics of Deformable Solids
https://www.amazon.com/dp/0199651647

Engineering Mechanics 3 (Dynamics) 2nd Edition
http://www.amazon.com/dp/3642537111

Engineering Mechanics 3, Supplementary Problems: Dynamics
http://www.amzn.com/B00SOXN8JU

-------------------------------------------------------------------
NSF NHERI SimCenter
https://simcenter.designsafe-ci.org/
-------------------------------------------------------------------
