### ISSUE TITLE
Request python package gdown for class Data 100

### ISSUE THREAD

**Issue by westernguy2** [berkeley-dsep-infra/hubs#3324]
### Package Name

gdown

### Hub details

- Hub: Data 100
- Language: Python

### Course Name

Data 100 (Lisa Yan and Josh Hug)

### Semester Details

Spring 2022 (and beyond)

### Installation Deadline

ASAP, before April 1

**Comment by felder** [comment]
This has been merged to prod.

Tested by calling "import gdown" in a notebook.
