### ISSUE TITLE
Old Datahub File Requests

### ISSUE THREAD

**Issue by westernguy2** [berkeley-dsep-infra/hubs#3325]
### Email Id

kagarwal2@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2019/datahub.berkeley.edu/kagarwal2.tar.gz

I hope the above is the right location?

Thanks!

**Comment by felder** [comment]
@westernguy2 that does not appear to be a correct location.

The location should be retrieved from a file in your home directory called "WHERE-ARE-MY-FILES.txt"

Can you explain what files specifically you're attempting to retrieve as well as how you came across that "Link to Datahub Folder"?

If you're attempting to construct a link based on what you believe it might be, that is not likely to be very fruitful.

**Comment by westernguy2** [comment]
oh ok, yes I don't have the "WHERE-ARE-MY-FILES.txt" file in my Datahub. I took Data 100 in Spring 2019, and those files are no longer in my Data 100 Datahub, and I was wondering if they could still be recovered. Apologies if this was the wrong place to ask that! Thanks!

**Comment by felder** [comment]
@westernguy2 This is the right place.

This might be a silly question, but have you tried logging into https://datahub.berkeley.edu and seeing if your files are there?

**Comment by felder** [comment]
Please reopen this if you still need help restoring these.
