### ISSUE TITLE
Request more RAM for class ENVECON 153

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#3330]
I would like to request additional RAM (4G total) on datahub for the approximately  50 students in my ENVECON153 class this spring: link https://classes.berkeley.edu/content/2022-spring-envecon-153-001-lec-001

At this point in the semester students are doing some simple analysis of datasets which are sufficiently large that 1G won't do. 

Projects involving those datasets are due April 6th, so this request is urgent! (I apologize for noticing the issue previously).

**Any additional information we should know about?**

This is a request which has been routinely granted for the last several years--if for some reason these resources aren't available I would have to do some fairly serious redesign of the 2nd half of the course.

**Comment by felder** [comment]
@ligon The extra RAM should now be available.

If people currently have servers running, they'll need to restart them in order to see the increase.
