### ISSUE TITLE
Data Archival Request

### ISSUE THREAD

**Issue by bryantla** [berkeley-dsep-infra/hubs#3334]
### Email Id

bryantla@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/bryantla.tar.gz

**Comment by balajialg** [comment]
@bryantla  We should be able to retrieve your logs by early next week. Thanks for your patience!

**Comment by felder** [comment]
Signed URL sent!
