### ISSUE TITLE
Retrieve a copy of my files

### ISSUE THREAD

**Issue by sthulsi** [berkeley-dsep-infra/hubs#3336]
### Email Id

sthulasi@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/sthulasi.tar.gz

**Comment by balajialg** [comment]
@sthulsi We should be able to retrieve your logs by next week. Thanks for your patience!

**Comment by felder** [comment]
Signed URL sent!
