### ISSUE TITLE
Request more RAM for class EE120

### ISSUE THREAD

**Issue by aparande** [berkeley-dsep-infra/hubs#3343]
**Which hub do you want more RAM on?**

Datahub

**Which class is this request for?**

https://classes.berkeley.edu/content/2022-spring-eleng-120-001-lec-001

**How many students do you expect in this class?**

~120

**How much RAM does this class need?**

4 GB

**Why does this class need this much RAM?**

Some of our lab assignments, which are Jupyter notebooks, have students look at video and audio data. These objects need to be stored in RAM for them to be processed by the students' code.

**By when (MM/DD) do you want this request to be fulfilled?**

As soon as possible. We have an assignment due this Friday that students will need the extra RAM for.

**Any additional information we should know about?**

NA

**Comment by balajialg** [comment]
@aparande Thanks for raising the github issue. Do you need the RAM increase for the entire semester or specific dates in this semester when the assignments are due? More specifically, Do you need an increased RAM just for the next assignment alone? I am asking these questions as increased resource allocation is correlated with increased cloud costs.

**Comment by aparande** [comment]
Hi @balajialg, we just need the RAM increase until May 2nd as we have this assignments and another one, but students will not be working on them beyond May 2nd.

**Comment by balajialg** [comment]
Thanks, @aparande! 2-3 weeks should not be a problem as per our policy.

@felder Would you have some bandwidth today to help with this request? Thanks!

**Comment by felder** [comment]
Done!

**Comment by balajialg** [comment]
Thanks a lot @felder!
