### ISSUE TITLE
BUDS For Summer 

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#3375]
Hey there 

I checked in with Deb Nolan who is faculty lead for the summer program - BUDS

Just like last summer we will have high school students who will have google authed achieve.org email addresses
That deb will get guest access for bcourses authentication 

and the student lead is Ciara Acosta 

@yuvipanda

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/blob/303d7ec8eb87f625849f2d7715babbcd05e97b4a/deployments/highschool/config/common.yaml#L32 looks like we already allow logins from achieveteam.org emails to highschool.datahub.berkeley.edu. Is that enough, @ericvd-ucb?

**Comment by felder** [comment]
@yuvipanda @balajialg Do we need the data from the previous instance of the highschool hub?  Might make sense to clear out the old stuff before this year's program starts.

**Comment by balajialg** [comment]
@felder I am not sure about the specific details of this hub - disk space it occupies, students archival needs etc.. So, broadly I don't have enough context to respond to your question. Having said that, does it make sense to wait till we formulate our storage policy across all hubs and then define the plan for this hub based on that.

**Comment by yuvipanda** [comment]
We can leave this up to @ericvd-ucb to decide. I don't think it's a lot of data so I'm not too concerned.

**Comment by ericvd-ucb** [comment]
I think it would be fine to delete old users if easy to do so. But as yuvi says probably not a lot of memory.  The new lead for this year is Ciara Acosta

**Comment by balajialg** [comment]
Closing this issue with the assumption that the high school hub is up and running while serving user needs. Please feel free to re-open if anyone of you thinks otherwise. Thanks!
