### ISSUE TITLE
Recover my old datahub files

### ISSUE THREAD

**Issue by shamin321** [berkeley-dsep-infra/hubs#3378]
### Email Id

shamin321@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/shamin321.tar.gz

**Comment by felder** [comment]
The specified archive does not exist.

Looking at your datahub home directory, it does not appear to have been archived.  There are lots of files there, including some dating back to 2018.

What are you attempting to have retrieved?

**Comment by shamin321** [comment]
I would like some of the files from my home directory. I can't access it now, so I can't quite name off specific files. I wouldn't mind having the whole home directory if possible.

**Comment by felder** [comment]
@shamin321 can you please explain your issue in more detail?  Why can you not access your files?  Are you no longer able to login to the hub because your calnet credentials no longer work?

Please do not derive links and ask for a restore.  The links are generated as part of the archival process, they are not arbitrary.  The link is meaningless if your files have not been archived.

**Comment by shamin321** [comment]
When I try to login to the datahub, I get a screen saying "Failed to Log In; Canvas doesn't have an account for user: 1507641" I think it might be because I graduated a while back. My calnet credentials still work for logging into my email though.

**Comment by felder** [comment]
@shamin321 ok, I know alumni get to keep their emails but I don't about bcourses access.  You're probably right.

We're going to be performing end of semester archiving very soon.  I suspect your directory will archived in this round.  Stay tuned and I'll be in touch via email with a signed URL you can use to download your files.

**Comment by felder** [comment]
@shamin321 signed URL sent!  Please reopen this if the files you're looking for are not there.

**Comment by felder** [comment]
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/shamin321.tar.gz

**Comment by shamin321** [comment]
Thank you!
