### ISSUE TITLE
Retrieving files from Fall 2020 Data 8

### ISSUE THREAD

**Issue by abemhelilasin** [berkeley-dsep-infra/hubs#3386]
### Email Id

amilasin@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/fall-2021/datahub.berkeley.edu/amilasin.tar.gz

**Comment by abemhelilasin** [comment]
Hello, I took Data 8 in Fall 2020 and wanted to look at my old files from the class recently. When I logged into jupyterhub, there was a WHERE-ARE-MY-FILES.txt that sent me here.

**Comment by felder** [comment]
@abemhelilasin Signed URL sent.  Please reopen this if the files you're looking for are not there.
