### ISSUE TITLE
Move our archival storage bucket to 'archive' class

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#3389]
Our storage archiver now moves home directories into this [GCS bucket](https://console.cloud.google.com/storage/browser/ucb-datahub-archived-homedirs;tab=configuration?forceOnBucketsSortingFiltering=false&project=ucb-datahub-2018&prefix=&forceOnObjectsSortingFiltering=false).

It's currently set to 'standard' storage class, but that offers us a level of performance that we just do not need. These are barely accessed, and we keep them for a while now. If we switch them to the 'archive' class, it drops our storage pricing by about 94%
(see https://cloud.google.com/storage/pricing).

So let's do that?

**Comment by balajialg** [comment]
@yuvipanda Looks like a good optimization from a cost perspective and I am in! Thanks for thinking about this :)

@felder Should chime in with his verdict here as this affects his day-to-day to a certain extent!

**Comment by felder** [comment]
@yuvipanda like a good idea.  How about I setup a lifecycle rule to transition all objects in the bucket to the archive storage class after 30 days?  That way if necessary I have a window to remove them before we end up with a 365 day commitment.

**Comment by yuvipanda** [comment]
@felder great idea! Lmk if I can help :)

**Comment by felder** [comment]
Did a quick test to make sure signed urls could be created and fetched if an object was in archive storage class.

They can be.

Setup a bucket lifecycle rule to transition all objects over 30 days old to the archive storage class.
