### ISSUE TITLE
Request more RAM for UCB/LBL summer research projects

### ISSUE THREAD

**Issue by enze-chen** [berkeley-dsep-infra/hubs#3397]
Hello Datahub team!

**Which hub do you want more RAM on?**

Datahub (staging), please!

**Which class is this request for?**

This is _not_ an official UCB class, but rather a summer research internship through LBL/UCB that uses Jupyter Book to teach materials informatics (materials science + data science).
The Book (work in progress) will eventually be hosted here: https://enze-chen.github.io/mi-book-2022/
The link for last year, which synced quite well with Datahub, is here: https://enze-chen.github.io/mi-book-2021/

**How many students do you expect in this class?**

Exactly 5 students and 2 instructors.

**How much RAM does this class need?**

For a few of the larger data queries and machine learning models may require up to 4GB of RAM.

**Why does this class need this much RAM?**

We are querying the [Materials Project database](https://materialsproject.org/) for tens of thousands of compounds and their properties (chemical, but also structural which tends to be big).
These materials must also be featurized which can be memory intensive, as are large models (e.g., deep neural networks).
We hope that more RAM will give students greater flexibility to experiment with their ideas as they learn about informatics workflows.
We are making this request because our students ran up against the 1GB limit last year. 😅

**By when (MM/DD) do you want this request to be fulfilled?**

By **June 7th**, if possible! We apologize for the short notice.
EDIT: We only need this for three weeks, so until June 25th.

**Any additional information we should know about?**

We realize this is a fairly last-minute request, and if things are delayed for a few days we should be able to implement workarounds similar to last year. We're also not sure with these larger-memory requests if you need specific IDs for the users as we're still recruiting the remaining students to complete the cohort. We can give you these as soon as we find out.

Thank you for your consideration of our request 🙇🏼‍♂️ and please don't hesitate to follow up with questions.

**Comment by yuvipanda** [comment]
This should be doable, although you should just use the regular datahub - not the staging hub (that is strictly meant for testing, and can break at any time). 

My suggestion is we use the explicit list of usernames, and set an end-date for this special casing to be removed. How does that sound?

**Comment by enze-chen** [comment]
> This should be doable, although you should just use the regular datahub - not the staging hub (that is strictly meant for testing, and can break at any time).    

Thank you for this advice. We used staging last year because we had to install two more packages, `pymatgen` and `matminer`, but I just checked and these two packages are on the regular Datahub now! Which makes sense based on what you said. Thanks a lot. 🙇🏼‍♂️

> My suggestion is we use the explicit list of usernames, and set an end-date for this special casing to be removed. How does that sound?    

This sounds perfect! When the time comes, who should I contact to send the information to?

**Comment by balajialg** [comment]
@enze-chen Thanks for the detailed inputs! You can either add the calnet id (without @berkeley.edu) of all students/instructors who would require additional RAM as part of this GitHub issue or send an email to balajialwar@berkeley.edu/felder@berkeley.edu providing their email ids if you are hesitant about adding their details here. Let me know if you need more input. Thanks!

**Comment by enze-chen** [comment]
Hello Balaji,
Thanks for the clarification. Here are the CalNet IDs for the five students and two instructors:
- `ana303`
- `luismflores99`
- `slamorte`
- `jessemed023`
- `asimonova`
- `chenze`
- `mdasta`

Please let me know if there's anything else I can do to assist! Note that per Yuvi's suggestion we will be using the regular DataHub, not staging.

**Comment by balajialg** [comment]
@enze-chen Sounds great! Thank you :)

**Comment by felder** [comment]
@enze-chen what's a good end date for this extra allocation?

**Comment by enze-chen** [comment]
@felder ack, thanks for checking! We only need it for **three weeks, so until June 25th**.

**Comment by felder** [comment]
@enze-chen ok the new allocations are live.  If you had a server running before I made the changes, you'll need to restart it.  Please reopen if you find that someone doesn't have 4GB available.

**Comment by yuvipanda** [comment]
Thanks a lot for handling this, @felder!
