### ISSUE TITLE
Upgrade Ottr to the latest version 1.1.4 in Public Health Hub and Datahub

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3403]
### Package Name

Ottr

### Hub details

- Hub: Public Health
- Language: R

### Course Name

Mainly PH 142 uses Ottr in the Public Health Hub!
Poli Sci 3 in Datahub

### Semester Details

Fall 2022

### Installation Deadline

Prior to the start of the Fall semester!

**Comment by felder** [comment]
@balajialg what about datahub?  It is running version 1.1.1

**Comment by balajialg** [comment]
@felder That's a good question. Maybe do the ottr upgrade for public health now and backlog datahub upgrade till we gain clarity?

@chrispyles Should instructors who use version 1.1.1 in R hub rewrite their test cases when we upgrade ottr version to 1.1.4 or both the versions are compatible? This will guide our decision on whether to reach out to concerned instructors and check the feasibility of this update.  Let us know :)

**Comment by felder** [comment]
Ottr 1.1.4 on cran:

https://cran.r-project.org/web/packages/ottr/index.html

**Comment by felder** [comment]
ottr 1.1.4 loads in staging.

**Comment by felder** [comment]
@cdbeon @corinne-riddell

Deployed to prod.

Please test at your convenience!

**Comment by chrispyles** [comment]
@balajialg tests for ottr 1.1.1 and 1.1.4 should be the in the same format. the format only changed between v0 and v1

**Comment by balajialg** [comment]
awesome! Thanks, @chrispyles.

@felder Given Chris's suggestion, can we upgrade Ottr to the latest version in Datahub?

**Comment by felder** [comment]
@balajialg sure!  I'll do it next week.

**Comment by felder** [comment]
Done!
