### ISSUE TITLE
Request to retrieve archived data

### ISSUE THREAD

**Issue by mon203** [berkeley-dsep-infra/hubs#3412]
### Email Id

mon.young@berkeley.edu or mon@ischool.berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-1-spring/ischool.datahub.berkeley.edu/mon-2eyoung.tar.gz

**Comment by felder** [comment]
Signed URL sent!
