### ISSUE TITLE
Possible reinstall of an existing package on DataHub

### ISSUE THREAD

**Issue by enze-chen** [berkeley-dsep-infra/hubs#3414]
### Package Name

Pymatgen

### Hub details

- Hub: DataHub
- Language: Python

### Course Name

Summer research internship mentored by Enze Chen (PhD student) and MSE Prof. Mark Asta.
The Jupyter Book we're using is this one: https://enze-chen.github.io/mi-book-2022

### Semester Details

Summer 2022

### Installation Deadline

We're running from June 7th to June 24th. Sincere apologies for the last-minute request. 

**DETAILS**: Pymatgen (2022.0.11) is already installed on DataHub, but I think due to some dependency upgrades, things broke along the way.

Specifically, if I run the commands
```python
from pymatgen.ext.matproj import MPRester
```
I get the following error:
```markdown
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

From a Google search, this seems to be from a NumPy API incompatibility. When I uninstall and reinstall this same version of `pymatgen==2022.0.11`, things seem to be OK again. So it's not the version, I don't think, but rather it just needs to be rebuilt with the current version of NumPy on DataHub. Could someone check this on the admin side? Thank you. 🙏🏼 

Not the end of the world—I can have my students do it individually, but maybe safer to do it system-wide?

**Comment by felder** [comment]
pymatgen is currently installed via pip and numpy is installed via conda.

The way to fix this is probably to have conda install pymatgen.  Current versions listed for conda-forge are:

pymatgen=2022.5.26
matminer=0.7.8

I'm seeing if conda will install 2022.0.11 and 0.7.4 to match the existing versions in requirements.txt

**Comment by enze-chen** [comment]
Hi @felder , I apologize for the late reply but yes, I think those more recent versions will also be OK! Thanks for looking into this.

**Comment by yuvipanda** [comment]
@enze-chen this works fine now.

Thanks for making it happen, @felder!
