### ISSUE TITLE
Upgrade to z2jh 2.0

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#3418]
A new release of z2jh is coming soon, and we should start the upgrade process early to shake out bugs.

**Comment by yuvipanda** [comment]
The pod definition no longer sets `args` on the container. So before the upgrade, pod definitions had this:

```
  - args:
    - jupyterhub-singleuser
    - --ip=0.0.0.0
    - --port=8888
    - --SingleUserNotebookApp.default_url=/retro
```

After, they don't. So pod startups error out with the following message:

```
➜ k -n data8-staging logs jupyter-yuvipanda
tini (tini version 0.18.0)
Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version

Execute a program under the supervision of a valid init process (tini)

Command line options:

  --version: Show version and exit.
  -h: Show this help message and exit.
  -s: Register as a process subreaper (requires Linux >= 3.4).
  -p SIGNAL: Trigger SIGNAL when parent dies, e.g. "-p SIGKILL".
  -v: Generate more verbose output. Repeat up to 3 times.
  -w: Print a warning when processes are getting reaped.
  -g: Send signals to the child's process group.
  -e EXIT_CODE: Remap EXIT_CODE (from 0 to 255) to 0.
  -l: Show license and exit.

Environment variables:

  TINI_SUBREAPER: Register as a process subreaper (requires Linux >= 3.4).
  TINI_VERBOSITY: Set the verbosity level (default: 1).
  TINI_KILL_PROCESS_GROUP: Send signals to the child's process group.
```

**Comment by yuvipanda** [comment]
This is mostly thanks to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2449.

Setting this in values.yaml fixes this:

```
  singleuser:
    cmd:
      # Explicitly define this, as it's no longer set by z2jh
      # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2449
      - jupyterhub-singleuser
```

However, this doesn't seem to respect the default url - we start in lab, not retro.

**Comment by yuvipanda** [comment]
And I see that the default env var is in fact set:

```
    - name: JUPYTERHUB_DEFAULT_URL
      value: /retro
```

so not sure why that isn't working.

**Comment by yuvipanda** [comment]
@minrk helped debug this, possibly fixed in https://github.com/jupyterhub/jupyterhub/pull/3918

**Comment by yuvipanda** [comment]
All service tokens (which we use to get our hubs to auth with the central datahub) now need to be prefixed with `service-` as well

**Comment by minrk** [comment]
> All service tokens (which we use to get our hubs to auth with the central datahub) now need to be prefixed with service-

I'm not sure if it's a terminology issue, but this restriction [only applies to _oauth client ids_](https://github.com/jupyterhub/jupyterhub/blob/2.3.0/jupyterhub/services/service.py#L311-L318), which aren't typically picked by hand. Not tokens themselves, which can be any (long enough) string. The default values are unchanged (`service-$serviceName`), but now this pattern is enforced. I don't think there's much reason to pick a value other than the default, really.

**Comment by yuvipanda** [comment]
Next up - control panel is missing in classic notebook interface :( Exists in lab and retro tho.

**Comment by yuvipanda** [comment]
With some testing, setting `      JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"` fixes the Control Panel issue by just ignoring jupyter_server. Let's try that out for now, but this should be fixed upstream.

**Comment by yuvipanda** [comment]
I think the control panel issue is fixed in https://github.com/jupyterhub/jupyterhub/pull/3919

**Comment by yuvipanda** [comment]
LTIAuthenticator's config needed to change from:

```yaml
hub:
  config:
     LTIAuthenticator: 
```

to

```yaml
hub:
   config:
      LTI11Authenticator:
```

**Comment by yuvipanda** [comment]
Discovered that by default users can no longer access any services unless they are admin, so access to hubs using the primary hub as auth was broken for non-admin users.

Fixed with:

```yaml
hub:
  config:
      JupyterHub:
        load_roles:
          - name: user
            scopes:
            - access:services
            - self
```

**Comment by balajialg** [comment]
@yuvipanda @felder @ryanlovett What is the significance of making this upgrade? Do we have any release notes for the same?

**Comment by ryanlovett** [comment]
@balajialg We typically try to stay close to upstream's latest (and at times we've used prereleased) since it will have more bug fixes and features. @minrk wrote a blog post about JH 2.0 at https://blog.jupyter.org/jupyterhub-2-0-7a038715e96d.

**Comment by balajialg** [comment]
Thanks, @ryanlovett! Helpful :)

**Comment by yuvipanda** [comment]
@balajialg I think the primary user facing change would be a redesigned admin interface. Check it out!

**Comment by balajialg** [comment]
@yuvipanda Sounds good. Just reviewed the UI changes. Looks like, the changes are not that drastic enough that it require an update in our existing documentation - https://ds-modules.github.io/curriculum-guide/faq/admin.html?highlight=admin. Correct me if I am wrong.

**Comment by balajialg** [comment]
@yuvipanda @ryanlovett Is this issue done? Can it be closed?

**Comment by yuvipanda** [comment]
yeah this is done i think!
