### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by dannyticknor** [berkeley-dsep-infra/hubs#3425]
### Email Id

dannyticknor@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@dannyticknor I need the link from the file that was dropped in your home directory (the one that probably lead you here).

**Comment by dannyticknor** [comment]
@felder  I think you're looking for this one.
gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/dannyticknor.tar.gz

Here are the other links though.
https://datahub.berkeley.edu/user/dannyticknor/tree/
https://datahub.berkeley.edu/user/dannyticknor/edit/WHERE-ARE-MY-FILES.txt

**Comment by felder** [comment]
@dannyticknor yep that first one is what I need.

Signed URL sent!
