### ISSUE TITLE
Workshop Prep!

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#3436]
*Ramp up for National Workshop*

- [ ] Workshop hub - datahub. berkeley  - what is login / edu only?
- [ ] Jupyterlite - what does it take to luanch data 8 in jupyerlite
- [ ] othter things to demo - syncthing?  Rtc?  read write? shiny?

Events are 

1. Monday 1hr on tech explanations - Eric and Balaji leads?
2. Tuesday 1hr on tech overview + innovations, whats new- Yuvi , Pyles 
3. Thursday - panel form parternships - invite 2i2c
4. Friday - demo on jupyterhub for new cloudbank pilots

**Comment by yuvipanda** [comment]
@felder can you just wipe everything in the workshop home directory? And unify prod / staging if needed?

**Comment by balajialg** [comment]
@yuvipanda Would it make sense to do a short demo to launch data 8 in Jupyter lite? I know you fixed this issue  https://github.com/data-8/datascience/issues/522 sometime back and highlighted that all the blockers to launch data 8 in Jupyterlite are taken care of. 

@ericvd-ucb I am not sure whether it makes sense to highlight RTC in its current form (unless there are updates I am not aware). 

I personally think it would be exciting to highlight Fernando's Stat 159 coursework and the list of things they did using Datahub (articulated [here](https://github.com/berkeley-dsep-infra/datahub/issues/3133#issuecomment-1022913547))

Let's chose from Shiny, SyncThing, Shared read-write, nbgitpuller updates (pulling assignments from non git repo?), otter update, Linux Desktop Environment, Serialhub, Testing infrastructure update (running test cases using pytest?) etc. to highlight interesting usecases

**Comment by felder** [comment]
@yuvipanda done!

**Comment by chrispyles** [comment]
Is the plan for the workshop to use Jupyterlite or a normal JupyterHub? If the former then let me know so I can push a beta release of Otter v4 beforehand so that a compatible version can be installed via micropip.

**Comment by ericvd-ucb** [comment]
Plan is to use Jupyterhub for workshop demos 

But we would like to demo Jupyterlite separately - but not necessarily needed to get otter working for that 

Eric

**Comment by balajialg** [comment]
Closing the issue considering the successful completion of workshop!
