### ISSUE TITLE
Retrieve Files

### ISSUE THREAD

**Issue by yohany99** [berkeley-dsep-infra/hubs#3452]
### Email Id

yohany99@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by yohany99** [comment]
gs://ucb-datahub-archived-homedirs/2022-1-spring/data100/yohany99.tar.gz

**Comment by felder** [comment]
Signed URL sent!
