### ISSUE TITLE
Retrieve old Datahub files

### ISSUE THREAD

**Issue by sammieboy26** [berkeley-dsep-infra/hubs#3453]
### Email Id

samuel_holland@berkeley.edu

Please allow me to have access to all the files I had in the archive. All of my notes on R/Rstudio are contained in those archived folders. Thank you. 

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/fall-2021/datahub.berkeley.edu/samuel-5fholland.tar.gz

**Comment by felder** [comment]
Signed URL sent!

**Comment by sammieboy26** [comment]
Hi, I have never done this before. What do I do with the signed link? It is opening up winrar, and I do not know what to do from there. Thanks.
-Sam

**Comment by felder** [comment]
The file in question is a tar archive that is compressed with gzip.  You'll want to download the file to your personal computer and extract it.

If your computer is a Mac, the functionality should be built in and you should be able to just double click it.  If your computer is a PC, you'll probably need a 3rd party tool to open it.  I'd recommend 7-zip for that.  It's free and it'll open just about any archive/compression format you're likely to encounter.

https://www.7-zip.org/

Once you have the files extracted, you can decide what specifically you want to keep and back it up however you see fit.
