### ISSUE TITLE
Retrieve my old files

### ISSUE THREAD

**Issue by vastava** [berkeley-dsep-infra/hubs#3457]
### Email Id

ashrivastava@berkeley.edu

### Link to Datahub Folder

https://datahub.berkeley.edu/user/ashrivastava/notebooks/

**Comment by felder** [comment]
@vastava

The link I need should be in a text file in your directory when you login to datahub.

The link begins with gs://

**Comment by vastava** [comment]
I'm no longer able to log into my account since I graduated in May 2021. Is it not possible to recover these files? @felder

**Comment by felder** [comment]
I currently have two archives for you:

gs://ucb-datahub-archived-homedirs/2018-1-spring-data100/ashrivastava.tar.gz
gs://ucb-datahub-archived-homedirs/2018-1-spring/ashrivastava.tar.gz

I'll send you signed URLs to both.

**Comment by felder** [comment]
Signed URLs sent!
