### ISSUE TITLE
Request python package sklearn for Data Science + Social Justice workshop

### ISSUE THREAD

**Issue by emilygrabowski** [berkeley-dsep-infra/hubs#3472]
### Package Name

sklearn

### Hub details

- Hub: dlab.datahub
- Language: Python
- The notebooks we are using include functions and attributes that require a more recent sklearn version (1.0.2)

### Course Name

Data Science + Social Justice Workshop (D-Lab/ Grad Div)

### Semester Details

Summer 2022

### Installation Deadline

Preferably before the start of the course on 7/5/22

**Comment by felder** [comment]
https://anaconda.org/conda-forge/scikit-learn
