### ISSUE TITLE
Request python package spacy for Data Science + Social Justice workshop

### ISSUE THREAD

**Issue by emilygrabowski** [berkeley-dsep-infra/hubs#3473]
### Package Name

spacy

### Hub details

- Hub: dlab.datahub
- Language: Python
- Requesting most recent version of spacy, as well as the component pipeline 'en_core_web_sm' to use with the package

### Course Name

Data Science + Social Justice Workshop (D-Lab/ Grad Div)

### Semester Details

Summer 2022

### Installation Deadline

Preferably before class begins 07/05/22

**Comment by felder** [comment]
https://anaconda.org/conda-forge/spacy-model-en_core_web_sm
https://anaconda.org/conda-forge/spacy
