### ISSUE TITLE
Request python package gensim for Data Science + Social Justice workshop

### ISSUE THREAD

**Issue by emilygrabowski** [berkeley-dsep-infra/hubs#3474]
### Package Name

gensim

### Hub details

- Hub: dlab.datahub
- Language: Python

### Course Name

Data Science + Social Justice Workshop (D-Lab/ Grad Div)

### Semester Details

Summer 2022

### Installation Deadline

Preferably before class begins 07/05/22

**Comment by felder** [comment]
In the future, you can put multiple package requests into a single issue.

**Comment by emilygrabowski** [comment]
Understood. Thanks for your help!

-Emily

**Comment by felder** [comment]
https://anaconda.org/conda-forge/gensim

**Comment by felder** [comment]
@emgrabow9 I'm going to speak for #3472 and #3473 in this ticket.

I've just merged a PR to staging for installing these packages.  It'll likely take 1-2 hours before the changes build and land in staging.  Would you be willing to login to https://dlab-staging.datahub.berkeley.edu when https://app.circleci.com/pipelines/github/berkeley-dsep-infra/datahub/1333 finishes and test the changes?

**Comment by emilygrabowski** [comment]
Yes, I'll do that.

-Emily

**Comment by felder** [comment]
@emgrabow9 great!  Assuming all goes well, I'll await the results of your testing.  If the deploy fails, I should be notified, but depending on how late it is I may not address any failures until tomorrow.

**Comment by felder** [comment]
@emgrabow9 deploy to staging worked.

```
jovyan@jupyter-felder:~$ conda list | grep -E 'scikit|spacy|gensim'
gensim                    4.2.0            py39h1832856_0    conda-forge
scikit-build              0.15.0                   pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              1.1.1            py39h4037b75_0    conda-forge
spacy                     3.3.1            py39hac2352c_0    conda-forge
spacy-legacy              3.0.9              pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.2              pyhd8ed1ab_0    conda-forge
spacy-model-en_core_web_sm 3.3.0              pyhd8ed1ab_1    conda-forge
```

**Comment by emilygrabowski** [comment]
I just went through all of the notebooks, and the packages all work great!

Thanks,
Emily

**Comment by felder** [comment]
@emgrabow9 ok good.  Looks like it has been merged to prod, so it should be available.
