### ISSUE TITLE
Canvas tokens build up and don't expire

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3495]
### Bug description

Each time a user approves the canvas/jupyterhub auth, a new, unexpiring token is created. These are viewable in the user's settings of the Canvas instance under [Approved Integrations](https://community.canvaslms.com/t5/Student-Guide/How-do-I-manage-API-access-tokens-as-a-student/ta-p/273). In general it isn't good for there to be a lot of unused auth tokens just "laying around" in user accounts.

Since Canvas seems to age out tokens by prompting the user to re-approve, maybe we should try to set their expiration age to match.

Questions:
 - if the token is set to never expire, why does Canvas create new ones? 
 - do other Canvas integrations behave similarly?

### Environment & setup

- Hub: 
- Language: 

### How to reproduce

Go to bCourses settings and look at all of the tokens.

**Comment by felder** [comment]
I asked our devs working on bcourses about this, and their reply was that we don't really use user-generated auth tokens for other Canvas integrations.  So they had very little to add with regard to how other canvas integrations behave.

It seems logical we should set the tokens to expire.  Would that be development task to fix?

**Comment by felder** [comment]
Service lead for bcourses said:
_I noticed Balaji repeatedly being prompted to authorize canvas access tokens during yesterday’s demo. Typically these tools will only generate a token upon first use, and continue to re-use that one._

He also mentioned:
_expired tokens still “lay around” they have to be manually deleted_

**Comment by ryanlovett** [comment]
@yuvipanda Is this an oauthenticator issue? Should we raise it on discourse?

**Comment by felder** [comment]
https://canvas.instructure.com/doc/api/file.oauth.html

**Comment by ryanlovett** [comment]
Per @yuvipanda 's suggestion, we will add `replace_tokens=true` to the request.

 - https://canvas.instructure.com/doc/api/file.oauth.html#oauth2-flow-3
 - https://groups.google.com/g/canvas-lms-users/c/jC7qZbYeYB0/m/9m6BYGccBgAJ

**Comment by ryanlovett** [comment]
Fixed by #3499.
