### ISSUE TITLE
Retrieving Old Files

### ISSUE THREAD

**Issue by luclamontagne** [berkeley-dsep-infra/hubs#3504]
### Email Id

luc.lamontagne@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/genomics/luc-2elamontagne.tar.gz

**Comment by felder** [comment]
Signed URL sent!

**Comment by luclamontagne** [comment]
I never accessed the signed URL, hoping to just reopen this and get a fresh link.
