### ISSUE TITLE
Retrieving More Old Files

### ISSUE THREAD

**Issue by luclamontagne** [berkeley-dsep-infra/hubs#3505]
### Email Id

luc.lamontagne@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/genomics/luc-2elamontagne.tar.gz

**Comment by felder** [comment]
@luclamontagne did you make a mistake with the Link to Datahub folder here?  It appears to be the same as issue #3504

**Comment by felder** [comment]
I'm going to go ahead and close this.  Please reopen it if you need additional files that were not retrieved as part of #3504.
