### ISSUE TITLE
Pull materials from private git repositories in Biology and EECS Hub

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3508]
# Summary

Instructor teaching PlantBio 190 (https://classes.berkeley.edu/content/2022-fall-plantbi-190-001-lec-001) this fall wants to generate nbgitpuller links that pull materials from a private GitHub repository. They will be using Biology Hub for their course. I understand (based on the [existing documentation](https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html)) that the Github app supports Datahub, R hub, and Public Health Hub currently. Can we enable the [Github app](https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html) to support the Biology hub as well? The instructor will need this request satisfied prior to the start of classes this fall!

**Comment by balajialg** [comment]
**Next Steps from 08/04 Sprint Planning Meeting:**

[ ] @yuvipanda to enable this feature in Biology Hub!

**Comment by yuvipanda** [comment]
This is now done for both the EECS and Biology hubs! You can find instructions + links to the appropriate github apps at https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html
