### ISSUE TITLE
Track RTC Usability Testing 

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#3517]
# Summary

Turn on RTC in Data 8 for the last project  -  which will be deployed on 8/3

# User Stories

Try out using RTC in Data 8 hub with students working on projects together
Beginner level users

# Acceptance criteria

What does Data 8 team need to know for success?

- Given `<some scenario>`, when `<some action is taken>`, then `<a specific result happens>`.

# Important information

data8.datahub.berkeley.edu

# Tasks to complete

**Comment by yuvipanda** [comment]
We should wait for JupyterLab 4.0, which I think won't be out by this time I'm afraid.

**Comment by ericvd-ucb** [comment]
can we not just try it out for a week?  in this case this would be just for the last week of the summer term -

**Comment by yuvipanda** [comment]
@ericvd-ucb the primary concern I have is that the issue @fperez reported was student data loss, and that's sort of a biggie...

**Comment by yuvipanda** [comment]
We'd probably also need to fix https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/10

**Comment by balajialg** [comment]
@ericvd-ucb Sharing some prior context about the data loss issues reported by Stat 159 instructors a few months back below. @yuvipanda fixed this issue by [disabling RTC](https://github.com/berkeley-dsep-infra/datahub/pull/3287). His suggestion to wait till Jupyter Lab 4.0 seems like a safer bet considering the seriousness of the reported issue. 

The issue raised by Stat 159 TA a few months back - https://github.com/berkeley-dsep-infra/datahub/issues/3292

@fperez's reported issue in Slack:

```
Team - I am encountering a series of extremely nasty and weird problems with the 159 hub that I hadn't seen before, and I'm wondering if anyone has any thoughts - after some debugging, I'm suspecting yjs is involved, but there could be more... Before I open a lot of issues, here's a quick summary:

- Frequent file revert requests, on files that were not recently/currently opened, so it doesn't make sense to encounter this. Then the file never opens, the spinner stays forever. Happening both with notebooks and md files. Once the problem starts, closing and reopening the file doesn't help - it becomes impossible to load the file at all.

Seems related to yjs, this error in the web console points to it: Firefox can’t establish a connection to the server at wss://stat159.datahub.berkeley.edu/user/fernando.perez/api/yjs/file:159/site/schedule.md.

- Entire directory lost for a student - fortunately she had pushed it to github, but a whole directory disappeared from her home dir in one shot. She has screenshots and will open an issue on GH.

- Corrupted notebooks with duplicate cell IDs - reported already on GH, but it keeps happening. Extremely puzzling.

- Constant kernel requests on reopening notebooks - for me, this hub doesn't seem to remember the kernel associated with my notebooks. It keeps asking me to do kernel selection every time I reopen a notebook.

Any thoughts on these? It's getting to be serious enough that I'd be happy to sit down with anyone to dig a bit into it, revert to older versions of anything if need be, etc... We're encountering real data loss, which had never happened to me on our hubs before. It could be an issue with Lab/yjs, I have no idea, but I'm pretty worried...
```

**Comment by balajialg** [comment]
Closing this issue considering it is actively tracked in issue #3027
