### ISSUE TITLE
Upgrade support helm charts to pave the way to upgrade to GKE > v1.21

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3519]
# Summary

GKE is indicating that our cluster is using deprecated APIs.  Yuvi said that 2i2c recently upgraded the support helm charts to the latest versions and we should do the same.

Those are located in datahub/support/requirements.txt:
https://github.com/berkeley-dsep-infra/datahub/blob/staging/support/requirements.yaml

# Tasks to complete

Modify the requirements.yaml one item at a time to install the latest version and make sure the system doesn't break.

**Comment by balajialg** [comment]
**Next Steps from 08/04 Sprint Planning Meeting:**
[ ] Not a priority but @felder to look into it whenever his time permits.

**Comment by felder** [comment]
I think @yuvipanda did this in #3536 and #3537
