### ISSUE TITLE
Improve Grafana dashboard's resilience!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3538]
### Bug description

Grafana dashboard threw a 503 error when there was an outage across all the hubs today. Considering that @felder uses grafana hub metrics to measure the health across all hubs, it is important that grafana gets isolated from such outages. 

Note: Grafana came back after all the hubs started operating. So, there is no issue with grafana as of now. 

![image (8)](https://user-images.githubusercontent.com/2306166/183542888-9ada0701-291c-41d3-99a4-0fe7e08c3a59.png)

Creating this issue to explore different design choices to avoid this scenario in the future. 

### Environment & setup

Grafana + Prometheus combination

### How to reproduce

See the above description!

**Comment by balajialg** [comment]
One of the discussion items we had from a short meeting today was steps to improve Grafana's resilience. @shaneknapp had an idea that it would make sense to create a new monitoring node pool and move our monitoring infrastructure which includes Grafana and Prometheus to this node pool. Through this approach, we will still have the monitoring infra work when the hubs part of the core node pool goes down.

**Comment by yuvipanda** [comment]
You should consider https://cloud.google.com/managed-prometheus too

**Comment by balajialg** [comment]
Closing this issue as it is fixed by #3995.
