### ISSUE TITLE
Issue: Data Archival Request

### ISSUE THREAD

**Issue by charcoon** [berkeley-dsep-infra/hubs#3559]
### Email Id

zogo1767008598@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@charcoon I need the actual link from the file left by the archival process in your home directory.

**Comment by charcoon** [comment]
Your files have been archived due to inactivity.

If you want to retrieve a copy of your files, please open a Data Archival Request via github here:
https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml

The following text is the link to your datahub folder, it must be included with your request:
gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/zogo1767008598.tar.gz

**Comment by felder** [comment]
Signed URL sent!
