### ISSUE TITLE
Request more RAM for EE 120 Fall 2022

### ISSUE THREAD

**Issue by ee120-staff** [berkeley-dsep-infra/hubs#3566]
**Which hub do you want more RAM on?**

Datahub

**Which class is this request for?**

EE 120 Fall 2022: https://classes.berkeley.edu/content/2022-fall-eleng-120-001-lec-001

**How many students do you expect in this class?**

About 130

**How much RAM does this class need?**

4 GB per student

**Why does this class need this much RAM?**

Some of our lab assignments, which are Jupyter notebooks, have students look at video and audio data. These objects need to be stored in RAM for them to be processed by the students' code.

**By when (MM/DD) do you want this request to be fulfilled?**

By the beginning of September.

**Any additional information we should know about?**
N/A

**Comment by balajialg** [comment]
@ee120-staff Are you aware of the [EECS hub](https://eecs.datahub.berkeley.edu/) used by multiple EECS classes like EECS 16A and 16B which offer 2 GB RAM? Do you want to use the EECS hub going forward?

@felder I am not seeing any strong reasons to enforce [this policy](https://github.com/berkeley-dsep-infra/datahub/issues/2785#issuecomment-924935677) for this request considering the cost-related conversations we had recently. Let's go ahead?

**Comment by ee120-staff** [comment]
@balajialg Yes, we'd like to use the EECS hub going forward.

**Comment by ee120-staff** [comment]
Actually, do the instructions for accessing private repos [here](https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html) apply to the EECS hub as well @balajialg?

Edit: I tested it out and it doesn't seem like it, so we'll stick with datahub.berkeley.edu for this semester at least.

**Comment by balajialg** [comment]
@ee120-staff Ah got it. By when do you need this functionality ready? We need to enable this functionality in EECS hub. We already have an issue tracking something similar to this for the Biology hub in #3508 and I added the EECS hub requirement to the same issue.

**Comment by ee120-staff** [comment]
Likely by the end of the second week of classes.

**Comment by balajialg** [comment]
Got it! I will let [@yuvipanda](https://github.com/yuvipanda) chime in with his ideas regarding the complexity of enabling this functionality to fetch from a private repository in the EECS hub (before EOD tomorrow). If it is complex, we will just increase the RAM for Datahub.

**Comment by yuvipanda** [comment]
Just added support for the EECS hub: https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html

**Comment by ee120-staff** [comment]
Amazing, we'll switch to the EECS hub then! We'll still need 4GB of RAM for some of our labs though.

**Comment by ee120-staff** [comment]
Actually, I just tried it out and it doesn't seem to work; I'm getting an access error when using a `nbgitpuller` link.

Edit: works now! I just had to wait

Edit 2: Sorry, one more thing. I'm running a notebook on the EECS hub (works fine on datahub), and it's failing on `from scipy import signal`, with error message
```
ImportError: /srv/conda/envs/notebook/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /srv/conda/envs/notebook/lib/python3.9/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-39-x86_64-linux-gnu.so)
```

**Comment by balajialg** [comment]
Thanks, @yuvipanda! 

@ee120-staff Seems like a libgcc installation error in the EECS hub - https://github.com/BVLC/caffe/issues/4953.

@felder Do you have some time today to look into this? Can you also bump up the RAM requirement for this class? Thanks!

**Comment by felder** [comment]
@ee120-staff @balajialg RAM changes are in, also I believe the issue with `from scipy import signal` is fixed.

Please test and let me know.

**Comment by balajialg** [comment]
Thanks, @felder for quickly responding to this request. @ee120-staff I am closing the issue for now. Please reopen this issue,if you face issues with Ram allocation and Scipy installation at your end.
