### ISSUE TITLE
Can UC Berkeley extension students and instructors use the UCB Data Hub?

### ISSUE THREAD

**Issue by markyashar** [berkeley-dsep-infra/hubs#3572]
Hello,

Can UC Berkeley Extension Students and instructors of UCB extension courses use the UCB Data Hub? Are they eligible to use the DataHub

For example, see the course here: https://extension.berkeley.edu/search/publicCourseSearchDetails.do?method=load&courseId=41598#courseSectionDetails_77577842

Thanks,

Mark Yashar
Research IT Domain Consultant, UC Berkeley
myashar@berkeley.edu

**Comment by yuvipanda** [comment]
@markyashar if they can log into bcourses.berkeley.edu, then they totally can! It uses the same auth mechanism

**Comment by balajialg** [comment]
@markyashar Excited to know that UC Berkeley extension instructors and students are using Datahub. Would love to know the list of courses using Datahub. I also added you to the datahub-announce email list which is our outreach mechanism for instructors. Let us know if you face any issues during the semester. Closing this issue assuming your query got resolved. Please do reopen if that is not the case. Thanks!
