### ISSUE TITLE
Request python package spaCy and language models for class L&S 22

### ISSUE THREAD

**Issue by winstonyin** [berkeley-dsep-infra/hubs#3577]
### Package Name

lemminflect, en_core_web_xx

### Hub details

- Hub: Datahub
- Language: Python

The natural language processing packages `spaCy` and `lemminflect`, as well as the language models `en_core_web_sm`, `en_core_web_md`, `en_core_web_lg`, and `en_core_web_trf`. Though the first two can be installed by the user in Jupyter notebook via `%pip install`, the language models have to be installed by the command `python -m spacy download <name_of_model>`, as detailed in https://spacy.io/models, hence this request.

### Course Name

https://classes.berkeley.edu/content/2022-spring-ls-22-1-lec-1

### Semester Details

Spring 2023

### Installation Deadline

We plan to be able to test these teaching modules in the coming two weeks.

**Comment by felder** [comment]
Done!

mamba list reports:
```
lemminflect               0.2.2              pyh8a188c0_0    conda-forge
spacy                     3.4.1            py39hac2352c_0    conda-forge
spacy-model-en_core_web_lg 3.4.0              pyhd8ed1ab_0    conda-forge
spacy-model-en_core_web_md 3.4.0              pyhd8ed1ab_0    conda-forge
spacy-model-en_core_web_sm 3.4.0              pyhd8ed1ab_0    conda-forge
spacy-model-en_core_web_trf 3.4.0              pyh55bf090_0    conda-forge
```
