### ISSUE TITLE
Archived File 1

### ISSUE THREAD

**Issue by futurecsminorstudent** [berkeley-dsep-infra/hubs#3578]
### Email Id

annamariacrone@gmail.com

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@futurecsminorstudent I need the link to datahub folder from the document left in your home directory.

**Comment by felder** [comment]
Closing for now, please reopen if you'd still like these files.
