### ISSUE TITLE
Instructor + Student files are missing in Data 100 Hub!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3594]
### Bug description

Dominic Liu (Data 100 GSI) reached out with the issue that all student and instructor files have suddenly disappeared from Data 100 hub. They can only see empty directories even when they regularly log into the Data 100 hub during the past few days/weeks. Tagging @Dominicliu129 so that he can provide more context to this request. 

![img_2986](https://user-images.githubusercontent.com/2306166/185222545-5295ae9b-fa2e-49b3-90d9-b87e3c909483.png)

### Environment & setup

- Hub: Data 100

### How to reproduce

1. Log in to Data 100 Hub
2. Check whether the directory is completely empty

**Comment by felder** [comment]
@Dominicliu129

Sorry about that.

Please try it again.

**Comment by Dominicliu129** [comment]
> @Dominicliu129
> 
> Sorry about that.
> 
> Please try it again.

It works for me now! Thank you so much! Will confirm with other staff and students who were facing the issue.

**Comment by felder** [comment]
Ok closing this for now.  Please reopen if you find there are more issues.

**Comment by balajialg** [comment]
@felder What was the issue here? Did we accidentally delete files while archiving?

**Comment by felder** [comment]
@balajialg No data was accidentally deleted.  It was just not in the right place.

When standardizing the directories for each hub on the nfsserver, I made a mistake with data100 so the files were not where the configs stated they should be.

**Comment by balajialg** [comment]
@felder Got it. Thanks for the context!
