### ISSUE TITLE
Retrieve files

### ISSUE THREAD

**Issue by JenniferY02** [berkeley-dsep-infra/hubs#3618]
### Email Id

jennifery@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/jennifery.tar.gz

**Comment by felder** [comment]
Signed URL sent!
