### ISSUE TITLE
Retrieve my old files

### ISSUE THREAD

**Issue by eramey16** [berkeley-dsep-infra/hubs#3629]
### Email Id

Hello, I would like to retrieve my archived files. Here is the link to my datahub folder: gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/emily-5framey.tar.gz

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/emily-5framey.tar.gz

**Comment by felder** [comment]
Signed URL sent!
