### ISSUE TITLE
Update mpl inline

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3630]
### Package Name

matplotlib_inline version 0.1.6

### Hub details

- Hub: Data 100
- Language: Python

### Course Name

D100.

### Semester Details

Fall 2022

### Installation Deadline

Sept 30, 2022

**Comment by yuvipanda** [comment]
@fperez so it's using the stat159 image - do you think you can get some data100 staff to refresh whatever packages you want in https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/stat159/image?

**Comment by fperez** [comment]
Mmh - I kind of went through that entire exercise in #3605 hoping that would be enough... Unfortunately right now I'm busy preparing class and can't deal with this.

Is the info in #3605 not enough to do a versions update? Do you need me to update the yaml files by hand?

**Comment by yuvipanda** [comment]
@fperez I'm guessing the slack messages i left you got lost in your notifications deluge - no worries. That package list wasn't enough, as we still have to manually find a way to update each version in https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/stat159/image/environment.yml and pick a new version. 

Anyway, I wrote a small script that talks to the PyPI API and automates this, and opened https://github.com/berkeley-dsep-infra/datahub/pull/3632 which upgrades all packages to latest available version. I'll cleanup that script shortly and publish it. But I'll merge the PR once build is done, and you'll get latest versions of all packages! That sounds ok?

**Comment by fperez** [comment]
Sounds perfect, thx! Yes, I actually had started writing the same script, so glad you did :) LMK when you have it, I'd love to see it...

**Comment by yuvipanda** [comment]
@fperez script is not clean enough yet, but here it is:

```python
#!/usr/bin/env python3
import sys
import requests
import argparse
import tempfile
import shutil
from ruamel.yaml import YAML
import re

yaml = YAML(typ="rt")

def get_latest_pip_version(package_name):
    url = f'https://pypi.org/pypi/{package_name}/json'
    data = requests.get(url).json()
    if data.get('message') == 'Not Found':
        return None
    return data['info']['version']

def get_latest_conda_version(package_name):
    url = f'https://api.anaconda.org/package/conda-forge/{package_name}'
    data = requests.get(url).json()
    return data['latest_version']

def main():
    argparser = argparse.ArgumentParser()

    argparser.add_argument(
        'filename',
        help='Requirements filename to upgrade'
    )
    args = argparser.parse_args()

    with open(args.filename, 'r') as f, tempfile.NamedTemporaryFile('w') as out:
        env = yaml.load(f)
        new_deps = []
        for d in env['dependencies']:
            if isinstance(d, str):
                match = re.match(r'([a-zA-Z0-9_-]+)==?([0-9.]+)', d)
                if match:
                    package = match.group(1)
                    version = match.group(2)

                    print(f'Fetching version for {package}')
                    latest_version = get_latest_conda_version(package)
                    if latest_version is None:
                        print(f"Package {package} not found in conda-forge!", file=sys.stderr)
                        sys.exit(1)
                    new_deps.append(f'{package}=={latest_version}')
                else:
                    new_deps.append(d)
            elif isinstance(d, dict):
                if 'pip' in d:
                    new_pip = []
                    print("processing pip block")

                    for p in d['pip']:
                        match = re.match(r'([a-zA-Z0-9_-]+)==([0-9.]+)( .*)?', p)
                        if match:
                            package = match.group(1)
                            version = match.group(2)
                            extra = match.group(3) if match.group(3) else ''

                            print(f'Fetching version for {package}')
                            latest_version = get_latest_pip_version(package)
                            if latest_version is None:

                                print(f"Package {package} not found in pypi!", file=sys.stderr)
                                sys.exit(1)

                            new_pip.append(f'{package}=={latest_version}{extra}')
                        else:
                            new_pip.append(p)
                    new_deps.append({'pip': new_pip})
            else:
                new_deps.append(d)


        env['dependencies'] = new_deps

        yaml.dump(env, out)

        out.flush()
        shutil.copyfile(out.name, args.filename)

if __name__ == '__main__':
    main()
```

**Comment by yuvipanda** [comment]
@fperez also the comment you left was for the datahub image, while this is a *completely different* image - same as the stat159 one.

**Comment by fperez** [comment]
Nice, thanks!!! Good to see this - I looked around and couldn't find a clean way to get the conda version info. Is that REST API documented somewhere? Even now knowing it exists, I can't seem to find any docs...

In any case, this is the script I wanted, now you've written it, so we're good to go for future updates like this!  Many thanks.

**Comment by yuvipanda** [comment]
@fperez yes! https://api.anaconda.org/docs is where the API docs are.

**Comment by fperez** [comment]
Ah, good, thx! Various googling kept turning out conda packages for someone else's REST api! Thx :)

**Comment by yuvipanda** [comment]
@fperez of course, this has resulted in an environment.yml file that just doesn't resolve haha. For some reason it's trying to install python 2 versions of packages... 

Do you need the following packages?

```
- geopandas
- geos
- geotiff
- cartopy
```

I'll try figure out how to resolve this shitshow, but if you don't need those in data100 that makes things simpler :D

**Comment by yuvipanda** [comment]
I'm upgrading just mpl and mpl-inline in https://github.com/berkeley-dsep-infra/datahub/pull/3634

**Comment by fperez** [comment]
No worries, can live without them for now, though it's weird you're getting issues with those...

FYI, these are the versions I have on my system (all py3):

```
  - cartopy=0.20.3
  - geopandas=0.11.1
  - geopandas-base=0.11.1
  - geos=3.11.0
  - geotiff=1.7.1
 ```
 
 We may need cartopy/geopandas but half-way through the semester, so don't sweat it for now.

**Comment by fperez** [comment]
And I don't think we'll need geos/geotiff at all (unless cartopy pulls them in).

**Comment by yuvipanda** [comment]
@fperez ok, I've removed those packages for now. Can you ping us before you need them so we can add them at that time?

**Comment by fperez** [comment]
Will do, and only if we actually need them. I'll check. Thx so much!!

**Comment by yuvipanda** [comment]
@fperez great!

**Comment by ryanlovett** [comment]
@yuvipanda I wonder if it'd be easier to remove all version numbers so that conda figures out the compatibility of the "latest" versions, and then use --dry-run to see the versions that would get installed. I haven't tried that before.

**Comment by yuvipanda** [comment]
@ryanlovett yeah, or use something like https://github.com/conda-incubator/conda-lock

**Comment by fperez** [comment]
BTW, I ran into the issue that your script can potentially create environments that don't actually resolve due to version conflicts... So, inspired by this, I finished [the one I had started](https://github.com/fperez/homesetup/blob/main/usr/bin/env-update.py). It has to be used differently as it relies instead on looking at the actual current packages in a system, but for my use case (refreshing an env I'd created a while ago) it's a bit more robust and less fussy.

I'll make a PR for the 159 image now based on this :)

**Comment by fperez** [comment]
NVM, it seems the current one is pretty good already. All done for now, but I finally have the script I wanted, thanks @yuvipanda!!
