### ISSUE TITLE
I need to retrieve my files to the datahub

### ISSUE THREAD

**Issue by martagberkeley** [berkeley-dsep-infra/hubs#3637]
### Email Id

martag@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/martag.tar.gz

**Comment by felder** [comment]
Signed URL sent!
