### ISSUE TITLE
Configure gh-scoped-creds for D100

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3638]
### Package Name

gh-scoped-creds

### Hub details

- Hub: Data 100

The package is already installed, but currently not configured:

![image](https://user-images.githubusercontent.com/57394/186608747-dbc3ef71-5620-4bb0-96a7-b62afc322d12.png)

### Course Name

Data 100

### Semester Details

Fall 2022

### Installation Deadline

Not super urgent - the students won't be using this, but I prefer as an instructor to be able to do all dev work on the hub itself, to ensure better reproducibility. gh-scoped-creds makes that process far smoother/safer.

Thanks!

**Comment by felder** [comment]
@fperez looking at the documentation for this package, is this not something that is configured at the user level?
https://github.com/jupyterhub/gh-scoped-creds

**Comment by felder** [comment]
@fperez 
Oh I see it's set here:

https://github.com/berkeley-dsep-infra/datahub/blob/be2ed2c32873c8c21b5ed4b44a005148e0ca2eb2/deployments/stat159/config/common.yaml#L53

https://github.com/berkeley-dsep-infra/datahub/blob/be2ed2c32873c8c21b5ed4b44a005148e0ca2eb2/deployments/stat159/config/common.yaml#L54

I can place a similar config in common.yaml for data100, however what should the values be set to?

**Comment by fperez** [comment]
Pinging @yuvipanda who's the author :)

**Comment by fperez** [comment]
@felder - this was configured for the 159 hub and works very well, but if I understood @yuvipanda correctly, it does need one step of initial configuration on your end for each new hub.

**Comment by balajialg** [comment]
@felder Are you comfortable doing the Github App configuration highlighted in [this link](https://github.com/jupyterhub/gh-scoped-creds)? If you are interested, I can block sometime in your bcal and we can do the confguration steps together during a zoom call next week (clubbing this with bcourses id request). Let me know if that's okay for you.

**Comment by felder** [comment]
@balajialg no because it's not clear to me from the documentation which account should be used

**Comment by felder** [comment]
Actually it's probably this:
https://github.com/organizations/berkeley-dsep-infra/settings/apps

**Comment by felder** [comment]
@fperez can you give this another try?

**Comment by fperez** [comment]
![image](https://user-images.githubusercontent.com/57394/186999995-a9413ffc-bd5b-49d5-a58e-475c5559aa02.png)

thanks! The github part seems to be working, however for some reason, opening a terminal right now is stalling - I can never get to a shell prompt. Weird...

So I haven't been able to test to the end quite yet, though I think this should work, once I can get a working shell.

Any thoughts on what could be causing that?

**Comment by fperez** [comment]
Oh, never mind. It finally gave me a prompt!  Very odd - took several _minutes_ to get a shell prompt.

Testing the rest now.

**Comment by fperez** [comment]
![image](https://user-images.githubusercontent.com/57394/187000695-db8f6c0f-6e3f-4148-bcee-0e2e5a69a3cd.png)

🚀 🎉 !!

**Comment by fperez** [comment]
All set, huge thanks!

**Comment by yuvipanda** [comment]
Thanks a lot, @felder and @balajialg!

**Comment by balajialg** [comment]
Awesome, thanks a lot @felder and @fperez!
