### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by kylebouchet** [berkeley-dsep-infra/hubs#3644]
### Email Id

kbouchet@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/kbouchet.tar.gz

**Comment by felder** [comment]
Signed URL sent!
