### ISSUE TITLE
Data Science retrieval 

### ISSUE THREAD

**Issue by Edward2721** [berkeley-dsep-infra/hubs#3648]
### Email Id

edward0818@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Please provide the link to the datahub folder as referenced from the text file left within your account.

**Comment by felder** [comment]
Haven't heard back in a week.  Please reopen this if you still want your files.
