### ISSUE TITLE
Error uploading image to stat20 server

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3665]
A student in Stat 20 tried to upload an image to their server on stat20 but RStudio returned, "Unexpected response from server".

<img width="1383" alt="Screen Shot 2022-08-29 at 8 57 53 AM (1)" src="https://user-images.githubusercontent.com/10248125/187319734-2be2069d-f75b-4790-9c7a-5234bb4f5df7.png">

The images were created on an image, transferred to an M1 MacBook, and uploaded from there. I've asked for copies of the images, which are less than 1MB in size.

**Comment by balajialg** [comment]
@ryanlovett Is this issue still relevant? I am closing this issue for now but please feel free to reopen it if you think otherwise.

**Comment by ryanlovett** [comment]
@balajialg There was no solution, however it wasn't a problem for most people. I had reset their RStudio settings which did not help. My instinct was that this was a browser-specific issue because I was not able to reproduce as them using my browser, however the student wasn't able debug their browser. In the end, using /tree as a workaround was sufficient.
