### ISSUE TITLE
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/neemarashidi.tar.gz

### ISSUE THREAD

**Issue by nrashidi** [berkeley-dsep-infra/hubs#3673]
### Email Id

neemarashidi@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
I need the link to datahub folder that is present in your home directory when you log in.

**Comment by felder** [comment]
Never mind I see you put it in the title.

**Comment by felder** [comment]
Signed URL sent!
