### ISSUE TITLE
Retrieve files

### ISSUE THREAD

**Issue by williampu8889** [berkeley-dsep-infra/hubs#3677]
### Email Id

jcp0907@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/jcp0907.tar.gz

**Comment by felder** [comment]
Signed URL sent!
