### ISSUE TITLE
Unable to access the Data 100 Hub

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#3690]
### Bug description

A number of Data 100 TA's and students are unable to access the Data 100 datahub.

Event log says "Spawn failed: Server at http://10.20.9.168:8888/user/xxxxxx/ didn't respond in 30 seconds"

### Environment & setup

- Hub: Data 100
- Language: All

### How to reproduce

Go to [Data 100 Hub](https://data100.datahub.berkeley.edu/hub/).

**Comment by yuvipanda** [comment]
I responded on slack, but this should be fixed now. More details tomorrow

**Comment by Dominicliu129** [comment]
Thanks!
