### ISSUE TITLE
Request an upgrade for python package otter-grader for class data 100

### ISSUE THREAD

**Issue by rohanjha123** [berkeley-dsep-infra/hubs#3693]
### Package Name

otter-grader

### Hub details

- Hub: data100.datahub
- Language: Python

### Course Name

(https://classes.berkeley.edu/content/2022-fall-data-c100-001-lec-001)

### Semester Details

For all subsequent semesters

### Installation Deadline

As soon as possible please. We were planning on upgrading our otter version in the notebooks this semester, only to run into bugs because the default datahub otter version was not updated to 4.0.1. We're using temporary workarounds but it would be greatly appreciated if the update could be done ASAP.

**Comment by ericvd-ucb** [comment]
Is this going to resolve the Gradesope public tests issue?

**Comment by rohanjha123** [comment]
That issue is resolved in otter 4.0.1, which data 100 is currently using (so, we don't have the issue for our most recent assignments). As of now, we ask students to manually upgrade their otter via datahub - this is so the default is otter 4.0.1 and students don't have to perform the upgrade on their end.
