### ISSUE TITLE
Does DataHub w/ JupyterBook only work with "master" branch?

### ISSUE THREAD

**Issue by enze-chen** [berkeley-dsep-infra/hubs#3695]
### Bug description

Hello! I was trying to set up a simple Jupyter Book on the main DataHub and wanted to launch a Jupyter notebook in DataHub to test things, only to encounter the following error:

![branch_error](https://user-images.githubusercontent.com/20807339/188710571-24383368-944c-4764-b6d4-f1fa27ccc96b.png)

Indeed my default branch, which seems to be the git default for a while now, is named `main` as opposed to the historical `master`.
Just curious, is DataHub set up to handle the name `main` as well, or do I have to rename it to `master`? I've gotten DataHub working in the past with the latter, so there's a path forward, this is just to note the issue.

Thanks!

### Environment & setup

- Hub: DataHub
- Language: Python

### How to reproduce

1. Go to [example page](file:///C:/Users/enzec/Documents/GitHub/mse104l/_build/html/lab1/intro_python_jupyter_blank.html)
2. Click the 🚀 to launch in JupyterHub

**Comment by ryanlovett** [comment]
Hi @enze-chen , you can append a branch=_branchname_ parameter to the gitpuller mechanism. See the [link generator](https://jupyterhub.github.io/nbgitpuller/link.html) for more information,  but you might use:

https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fenze-chen%2Fmse104l&urlpath=notebooks%2Fmse104l%2Flab1%2Fintro_python_jupyter_blank.ipynb&branch=main

Note the `&branch=main` at the end of the URL.

@balajialg Fyi, **when you return**, to update the Curriculum Guide, https://ds-modules.github.io/curriculum-guide/technology/interact-links.html to use the official link generator.

**Comment by enze-chen** [comment]
Thanks, Ryan! I'll give this a try :)

EDIT: Realized now that you mentioned it that it was my mistake in the _config.yml file, where I now specify to pull from the `main` branch. Sorry about that. Appreciate the fast response.

**Comment by balajialg** [comment]
@ryanlovett To avoid such issues, generally, I recommend folks use the nbgitpuller plugin that Yuvi created a year ago which eliminates the need for specifying branch. Documentation for the nbgitpuller plugin is mentioned [here](https://ds-modules.github.io/curriculum-guide/workflow/distributing-notebooks.html?highlight=interact%20links#nbgitpuller-link-generator). I updated the current link generate to the doc you shared which I was not aware previously.
