### ISSUE TITLE
Stat 20 hub getting hung up over the weekend and this morning

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-dsep-infra/hubs#3701]
### Bug description

Over the weekend and this morning around 10 am, we've been seeing the Stat 20 getting hung up, where the browser becomes unresponsive. In some cases, refreshing the tab solves the problem. In others (like this morning around 10:15 am), neither refreshing nor restarting helps, but after a several minutes, it resumed working for everyone.

I realize the description here is vague, but is there anything in the logs that would give a better sense of what was going on?

### Environment & setup

- Hub: Stat 20
- Language: R

### How to reproduce

Impossible to reproduce atm.

**Comment by ryanlovett** [comment]
@andrewpbray Can you please email me the logins of the students that experienced this, and if possible the times of those bad sessions? I can try to see if their sessions are associated with a bad node, or if there is something else in common. 

@yuvipanda had to disable a bad cluster node over the weekend that was affecting other courses.

**Comment by andrewpbray** [comment]
Sure thing. I'll send over a few emails (one of them was me!).

**Comment by yuvipanda** [comment]
Hey @andrewpbray. data100 was moved into the same pool that stat20 uses this semester, and that was causing some overcommitment issues for both them and others on the pool. I've moved them to their own pool now, and things seem to have settled down - if you have users currently experiencing issues, asking them to restart their server should also help a lot. Apologies for the issues!

**Comment by ryanlovett** [comment]
@andrewpbray said in person yesterday that they haven't had any server issues since.

**Comment by andrewpbray** [comment]
Hello!

We've been getting (retrospective) reports of the server being down over the weekend and then it was offline from roughly 2:45 - 3:30 pm today. This was observed by @shomurali and @jeremy-sanchez. Is there anything in the logs that documents this outtage or suggests what the issue was?

Thanks!

**Comment by balajialg** [comment]
Hi @andrewpbray! 

Yes - we had a minor outage between 2.45 - 3.30 PM when we tried to upgrade the NFS server. We reverted the change immediately in order to bring stability to the service. We are also debugging what looks like a deep race condition in the Linux kernel, and it is unfortunately causing issues affecting our users over the last few weeks. We have put in place some band-aid fixes that should limit the maximum time out of the outage to about 15 minutes when it happens as we work towards a longer-term resolution. We deeply apologize for the issues - we recognize that reliability is the #1 thing instructors need and are working towards making the service more reliable. Thank you for your patience

**Comment by andrewpbray** [comment]
Thanks for the background. 

We've had reports of outages tonight from 20:45 to 21:10 (there is an assignment deadline at 11 pm). Is this the same issue?

**Comment by ryanlovett** [comment]
I'm not seeing any file server activity similar to the events that have happened previously. One Stat 20 student sent Shobhana a screenshot of their server starting up, but the logs show that it started up right away. I checked their server and it was running.

With the previous issue, the server would start up, but RStudio would show a message indicating that it was taking a while. What was the behavior tonight? Did they send you screenshots?

**Comment by shomurali** [comment]
yes, my students basically sent me similar screenshots to what I sent you,
saying that it was hanging.
-----
Shobhana Murali Stoyanov
Continuing Lecturer
Department of Statistics
University of California, Berkeley

pronouns: *she/her*

**Comment by ryanlovett** [comment]
I've created a new issue to track this at #3836.

**Comment by andrewpbray** [comment]
Here's an image from a student.

![image](https://user-images.githubusercontent.com/1627362/195514210-8845bf19-903d-440e-851d-ecc40cbf6fc7.png)

**Comment by ryanlovett** [comment]
I'm going to lock this issue -- #3836 can track tonight's issue.
