### ISSUE TITLE
Request more RAM for class Legal Studies 190

### ISSUE THREAD

**Issue by Elias326** [berkeley-dsep-infra/hubs#3702]
**Which hub do you want more RAM on?** Datahub

**Which class is this request for?** Legal Studies 190

https://classes.berkeley.edu/content/2022-fall-legalst-190-007-sem-007

**How many students do you expect in this class?** 15

An approximate number would do.

**How much RAM does this class need?** 2 GB

The default is 1GB of RAM per student.

**Why does this class need this much RAM?** Conducting natural language processing and using machine learning and neural network packages.

A short justification for this resource request.

**By when (MM/DD) do you want this request to be fulfilled?** 09/08

This will help us with prioritization of this request.

**Any additional information we should know about?** N/A.

**Comment by felder** [comment]
Directives to do this in #3651 were in the wrong place!

Should be fixed when https://github.com/berkeley-dsep-infra/datahub/pull/3712 is merged.

Sorry for the inconvenience.
