### ISSUE TITLE
Retreive files.

### ISSUE THREAD

**Issue by martinjameswhite** [berkeley-dsep-infra/hubs#3708]
### Email Id

mwhite@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/mwhite.tar.gz

**Comment by felder** [comment]
Signed URL sent!
