### ISSUE TITLE
retrieve a copy

### ISSUE THREAD

**Issue by azhouzhu** [berkeley-dsep-infra/hubs#3716]
### Email Id

azhouzhu1@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
- Mine: gs://ucb-datahub-archived-homedirs/2022-1-spring/data8/azhouzhu1.tar.gz

**Comment by felder** [comment]
Signed URL sent!
