### ISSUE TITLE
Request more RAM for class LEGALST 190 - 3 GB

### ISSUE THREAD

**Issue by ilyaakdemir** [berkeley-dsep-infra/hubs#3717]
Which hub do you want more RAM on? Datahub

Which class is this request for? Legal Studies 190

https://classes.berkeley.edu/content/2022-fall-legalst-190-007-sem-007

How many students do you expect in this class? 12

An approximate number would do.

How much RAM does this class need? 3 GB

The default is 1GB of RAM per student.

Why does this class need this much RAM? Conducting natural language processing and using machine learning and neural network packages.

A short justification for this resource request.

By when (MM/DD) do you want this request to be fulfilled? 09/09

This will help us with prioritization of this request.

Any additional information we should know about? N/A.

**Comment by felder** [comment]
This should land in prod in a few minutes.  After which time, a server restart should show the increased limit.
