### ISSUE TITLE
Request more RAM for Legal Studies 123 Spring 2023

### ISSUE THREAD

**Issue by jdmarshl** [berkeley-dsep-infra/hubs#3718]
**Which hub do you want more RAM on?**

datahub

**Which class is this request for?**

Legal Studies 123 Spring 2023 -- no link yet for Sp23 classes but I am Legal Studies Program Director so I know the course is going to run.

**How many students do you expect in this class?**

45

**How much RAM does this class need?**

Probably 3GB

**Why does this class need this much RAM?**

There are labs and homework problems that use large datasets--syllabus from Sp22 attached

**By when (MM/DD) do you want this request to be fulfilled?**

by 12/01 would be great so I can test things

**Any additional information we should know about?**

This will be much easier than having students run the labs locally. 
[DPLSyllabus_v6.1.docx](https://github.com/berkeley-dsep-infra/datahub/files/9531367/DPLSyllabus_v6.1.docx)

**Comment by balajialg** [comment]
@jdmarshl This should be good to go from our end based on our [existing ram allocation](https://github.com/berkeley-dsep-infra/datahub/issues/2785#issuecomment-924935677) policies.

**Comment by jdmarshl** [comment]
Got it. Thank you!

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@felder Do you want to look into this request? I am not sure how to add increased RAM for per-class profiles.

**Comment by felder** [comment]
@balajialg I think we need to service #3906 and then document the updated procedure for allocating per course resources.  Then I can service this request.

This particular issue is for a Spring course so I have not been overly concerned about it for the time being.

**Comment by felder** [comment]
I guess they do want it by Dec 1 though, so I guess we need to get on it.

**Comment by balajialg** [comment]
Got it. Thanks, @felder. @ryanlovett do you have any helpful inputs for us here to service this request?

**Comment by ryanlovett** [comment]
@balajialg Yes, @jdmarshl , can you please let us know the bCourses ID for this class? This is the identifier in the URL when you visit the class at bCourses.

**Comment by jdmarshl** [comment]
Dear Ryan,

Here is the url: https://bcourses.berkeley.edu/courses/1519998
Thank you, everyone, for your help with this.

Yours,
Jon

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by ryanlovett** [comment]
@jdmarshl I've deployed increased RAM for members of the class on https://staging.datahub.berkeley.edu. Please test there and report if this is sufficient for your needs. If it works then we can migrate this to production.

Note that if you also are receiving increased limits from Legal Studies 190, Fall 2022, that will mask this change -- both request 3GB. But the important part is that you're getting an increased limit from _somewhere_.

**Comment by jdmarshl** [comment]
Thank you, Ryan. My long-time GSI Ilya Akdemir (who is teaching the Legal
Studies 190 class in Fall 2022 on NLP; I am the grade approver) assures me
that we can do the assignments with 3GB of RAM. I don't have time to test
it right now, but Ilya was tracking the issue last Spring, so I take his
word for it. Also, he had his students do similar problem sets this
semester. I probably will not get to revising and testing the labs until
finals week or after--can we go ahead with 3GB for the students in Legal
Studies 123 in Spring  2023?

If there is a problem during the semester, should I contact you then? I
think this will be sufficient for our students to be able to run everything
in the class on datahub.

Thank you,
Jon

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl If there is any issue with resource allocation during the semester, you can always highlight the issue in this thread. One of us will take a look into the issue and solve it for you. 

Thanks a lot, @ryanlovett for resolving the request. Appreciate it. Is it documented somewhere for future reference?

**Comment by jdmarshl** [comment]
Understood. Thank you!

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by ryanlovett** [comment]
@balajialg We had docs at https://docs.datahub.berkeley.edu/en/latest/admins/howto/course-config.html, but they needed updating. I've just done so.

**Comment by ryanlovett** [comment]
Fixed by #3966.

**Comment by balajialg** [comment]
Thanks a lot @ryanlovett! This is amazing.

**Comment by jdmarshl** [comment]
Thank you for upping the memory to 3GB per student. Apparently, the mapping
in the first homework is using that by the time students get about halfway
through. Maps take up a lot of memory. Can we increase the memory quota? If
not, I will find an alternative. Thanks,

Jon

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl Do you have a sense of how much RAM do you need for this class? Till when do you want this RAM increase? These details will help speed up the process at our end.

**Comment by jdmarshl** [comment]
Students have found workarounds. Some had problems even after reducing the
size of the dataset by sampling. After talking to the class today I think
we are doing fine with the workarounds. Really this is only for the
homework problems and the projects, so I think we will muddle through. I
honestly don't know how much memory would be required to map more points
for the first homework assignment, for example.

I think for now we can leave it as is, and close out the ticket. Thank you,
Jon
Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl Thanks for the clarification! It is great that students found workarounds to solve the assignments. We can work together at the start of the next semester (if you have plans to teach this class) to analyze a realistic amount of compute required for all the assignments and projects. Is this the repo for your class - https://github.com/ds-modules/Legalst-123?

**Comment by jdmarshl** [comment]
Yes, that is our git repo for labs--we also have homework assignments that
are much more resource intensive.

Jon Marshall, Ph.D.
Assistant Dean
JSP/Legal Studies
