### ISSUE TITLE
Fandol font issue in data100

### ISSUE THREAD

**Issue by rohanjha123** [berkeley-dsep-infra/hubs#3726]
Hey, sorry for the inconvenience but students are still running into this issue. Please let me know if you would like me to paste the error log of one of the recent student submissions here.

_Originally posted by @rohanjha123 in https://github.com/berkeley-dsep-infra/datahub/issues/3719#issuecomment-1242302791_

**Comment by felder** [comment]
@rohanjha123 you do not need to open a new issue for the same problem.  Please just reopen the old issue.
