### ISSUE TITLE
Switch eecs hub to use CanvasOAuthenticator?

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3733]
### Bug description

In #3721 re: RAM allocations, @ryanlovett writes:

https://github.com/berkeley-dsep-infra/datahub/issues/3721#issuecomment-1242465565

However, the EECS hub along with a bunch of others was moved from CanvasAuthenticator to GenericAuthenticator [before Fall](https://github.com/berkeley-dsep-infra/datahub/commit/c6fc539b807ce392da936ea789ab00fe87554b6a), meaning it relies on the main hub for auth. The course affiliation is stored in the auth_state so I think while the main hub sees it, the EECS hub may not.

We could address this by:

Unsetting config.JupyterHub.authenticator_class in eecs/config/common.yaml, so that is uses the default of CanvasOauthenticator in hub/values. (basically undo the eecs hub change from the linked commit above)
Deploy to staging.
Have GSI login on staging to test that logins work and that it gets allocated the 4G.
Deploy to prod.

### Environment & setup

- Hub: eecs

### How to reproduce

NA

**Comment by felder** [comment]
@yuvipanda is this something we should do?

**Comment by yuvipanda** [comment]
@felder if we want per-class allocations on the eecs hub, this is the only way for now - so seems like a good idea to do.

**Comment by ryanlovett** [comment]
We found out that the Canvas-to-Generic conversation also updated secrets via https://github.com/berkeley-dsep-infra/datahub/commit/11b885d2820905caa7f648ae6b9f4bcad767f955. So that change had to be reverted as well.

**Comment by felder** [comment]
@ryanlovett not sure if I'm making a mistake, but modifying secrets as well as commenting out the generic_authenticator in common.yaml results in a 400 error for invalid client_id parameter value and it redirects to staging.datahub.berkeley.edu.

I verified in the bcourses admin console that the client_id and secret were correct and that eecs-staging is a permitted redirect URL.  Also verified that the client_id and client_secret match with what datahub-staging is configured with.

I used hubploy to push the changes directly to eecs-staging for testing.  

```
$ git status
On branch felder_3733
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   common.yaml
	modified:   ../secrets/staging.yaml
```

```
$ git diff common.yaml
diff --git a/deployments/eecs/config/common.yaml b/deployments/eecs/config/common.yaml
index db1ea7b2..6905e3aa 100644
--- a/deployments/eecs/config/common.yaml
+++ b/deployments/eecs/config/common.yaml
@@ -20,11 +20,11 @@ jupyterhub:
     nodeSelector:
       hub.jupyter.org/pool-name: core-pool
     config:
-      JupyterHub:
-        authenticator_class: generic-oauth
-      GenericOAuthenticator:
-        login_service: bCourses
-        username_key: name
+#      JupyterHub:
+#        authenticator_class: generic-oauth
+#      GenericOAuthenticator:
+#        login_service: bCourses
+#        username_key: name
       Authenticator:
         admin_users:
           # infrastructure
```

```
$ sops -d ../secrets/staging.yaml | tail -10
        config:
            CanvasOAuthenticator:
                client_id: "REMOVED"
                client_secret: REMOVED
                oauth_callback_url: https://eecs-staging.datahub.berkeley.edu/hub/oauth_callback

#            GenericOAuthenticator:
#                client_secret: REMOVED
#                extra_params:
#                    client_secret: REMOVED
```

**Comment by ryanlovett** [comment]
@felder I believe this is fixed by #3747. Lmk if it works for you.

**Comment by felder** [comment]
@ryanlovett thanks!  It seems to work.

@ee120-staff Can you please login to https://eecs-staging.datahub.berkeley.edu and let me know if you see the memory increase?

**Comment by ee120-staff** [comment]
@felder Yep, it shows the 4GB!

**Comment by felder** [comment]
@ryanlovett thanks for merging this to prod.

@ee120-staff ok that should do it!
