### ISSUE TITLE
Request retrieval of my Datahub files

### ISSUE THREAD

**Issue by luclamontagne** [berkeley-dsep-infra/hubs#3736]
### Email Id

luc.lamontagne@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz](gs://ucb-datahub-archived-homedirs/2022-1-spring/genomics/luc-2elamontagne.tar.gz

**Comment by felder** [comment]
Signed URL sent!
