### ISSUE TITLE
Retrieve a copy of files

### ISSUE THREAD

**Issue by nolanhorner** [berkeley-dsep-infra/hubs#3743]
### Email Id

nolan.horner@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

The following text is the link to your datahub folder,
it must be included with your request:

gs://ucb-datahub-archived-homedirs/fall-2021/datahub.berkeley.edu/nolan-2ehorner.tar.gz

**Comment by felder** [comment]
Signed URL sent!
