### ISSUE TITLE
Accessing the file

### ISSUE THREAD

**Issue by A-meya** [berkeley-dsep-infra/hubs#3754]
### Email Id

ameya.naik@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@A-meya I need the link to datahub folder from the file that should be in your hub home directory.

**Comment by felder** [comment]
Please reopen this and provide the link if you still need your files.
