### ISSUE TITLE
Retrieving Data 100 Files (Fa'21) 

### ISSUE THREAD

**Issue by 5mod8** [berkeley-dsep-infra/hubs#3755]
### Email Id

meiji193@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-2-summer/data100/meiji193.tar.gz

**Comment by felder** [comment]
Signed URL sent!
