### ISSUE TITLE
Former UC Berkeley Student; Data Archival Request

### ISSUE THREAD

**Issue by jhyoon-03** [berkeley-dsep-infra/hubs#3758]
### Email Id

jhyoon03@berkeley.edu

### Link to Datahub Folder

- gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/jhyoon03.tar.gz
-  gs://ucb-datahub-archived-homedirs/spring-2022/datahub/jhyoon03.tar.gz
-  gs://ucb-datahub-archived-homedirs/fall-2021/datahub/jhyoon03.tar.gz
-  gs://ucb-datahub-archived-homedirs/spring-2021/datahub/jhyoon03.tar.gz
- gs://ucb-datahub-archived-homedirs/fall-2020/datahub/jhyoon03.tar.gz
- gs://ucb-datahub-archived-homedirs/spring-2020/datahub/jhyoon03.tar.gz
- gs://ucb-datahub-archived-homedirs/fall-2019/datahub/jhyoon03.tar.gz
- gs://ucb-datahub-archived-homedirs/spring-2019/datahub/jhyoon03.tar.gz
- gs://ucb-datahub-archived-homedirs/spring-2018/datahub/jhyoon03.tar.gz

I would like all my Datahub files from all 8 semesters -- FALL 2018, SPRING 2019, FALL 2019, SPRING 2020, FALL 2020, SPRING 2021, FALL 2021, SPRING 2022. 
If the texts above do not work, please try converting the last part to datahub.berkeley.edu/jhyoon03.tar.gz 
Thank you.

**Comment by felder** [comment]
Signed URLs sent!
