### ISSUE TITLE
please allow me to access these images

### ISSUE THREAD

**Issue by eletra** [berkeley-dsep-infra/hubs#3759]
### Email Id

borahl@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datags://ucb-datahub-archived-homedirs/2022-2-summer/datahub/borahl.tar.gzhub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Signed URL sent!
