### ISSUE TITLE
Data Archival Request - Uma Krishnaswamy

### ISSUE THREAD

**Issue by umakrishnaswamy** [berkeley-dsep-infra/hubs#3763]
### Email Id

umakrishnaswamy@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

- location: gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/umakrishnaswamy.tar.gz

**Comment by felder** [comment]
Signed URL sent!
