### ISSUE TITLE
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/guilhem-2elabadie.tar.gz

### ISSUE THREAD

**Issue by guilhemlabadie** [berkeley-dsep-infra/hubs#3776]
### Email Id

guilhem.labadie@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@guilhemlabadie I need the link to datahub folder from the file dropped into your home directory on the hub.

**Comment by felder** [comment]
Oh it's in the issue title.

**Comment by felder** [comment]
Signed URL sent!
