### ISSUE TITLE
retrieve old files 

### ISSUE THREAD

**Issue by jasminlee** [berkeley-dsep-infra/hubs#3777]
### Email Id

jasminlee@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
I need the link to datahub folder that's listed in the file dropped in your home directory on the hub.

**Comment by felder** [comment]
Haven't heard back, so I'm closing.  Please reopen and provide me with the link if you still would like your files.
