### ISSUE TITLE
Student getting an error when trying to get in to datahub and pull changes

### ISSUE THREAD

**Issue by wwheeler6** [berkeley-dsep-infra/hubs#3778]
### Bug description

A student in Public Health 251 is getting the attached error when attempting to get into data hub using the following link: https://publichealth.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FPHW290%2FPHW251_Fall2022&urlpath=rstudio%2F
This is intended to pull updates from the course git repo and then open up Rstudio in data hub. She has tried accessing from different browsers and with incognito windows for each browser and still the same error. Please assist
![Screen Shot 2022-09-16 at 5 20 18 PM](https://user-images.githubusercontent.com/36118603/191394904-a4bf66a6-1579-45ac-b5c0-8593d0fb87a5.png)

### Environment & setup

- Hub: 
- Language:

**Comment by ericvd-ucb** [comment]
@wwheeler6 
Please take a look at 
https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html
and see if renaming the folder to try a new pull will help

**Comment by felder** [comment]
I'm going to assume this is fixed.  If it's not, please reopen.
