### ISSUE TITLE
Error opening nbgitpuller links and synchronizing with github

### ISSUE THREAD

**Issue by jonathanold** [berkeley-dsep-infra/hubs#3780]
Several students and I have been getting errors when trying to open nbgitpuller links. The errors seem to be related to github not updating files in the datahub. Common error messages are:

`path 'Sections/107-108-Jonathan/testcode.ipynb' is unmerged`
`Command '['git', 'checkout', '--', 'Sections/107-108-Jonathan/testcode.ipynb']' returned non-zero exit status 1.`

The file `testcode.ipynb` has been deleted, but continues to be referenced in the error messages.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/42833514/191444502-072099f2-f78d-441e-8b2b-fb43b29ccd6e.png">

**Comment by ericvd-ucb** [comment]
@jonathanold  Please take a look at 
https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html

In many cases this is caused by some change in the underlying Github repo that causes the git pull to crash

I would recommend following the instructions to rename your folder and doing a "fresh" pull

**Comment by jonathanold** [comment]
@ericvd-ucb - thank you for the quick reply. I have already tried the troubleshoot. Unfortunately, it does not solve my problem. The unmerged notebook (testcode) has already been deleted for a couple of weeks but seems to make problems. 
How would I do a "fresh" pull (I tried renaming, re-uploading to github, and creating a new link, but without success)? or is there another way to reset nbgitpuller's merging behavior? 
Thanks!

**Comment by jonathanold** [comment]
HI @ericvd-ucb - sorry for asking again, is there any update on this? Unfortunately, my datahub is still not running properly (and files from Gtihub are not being synched with the Datahub folder either). I would like to teach with Datahub this week, do you see a fix for my issues? Thanks!

**Comment by ryanlovett** [comment]
Hi @jonathanold , what is the full URL that triggers this?

**Comment by jonathanold** [comment]
Hi @ryanlovett - the URL in datahub is [this one](https://datahub.berkeley.edu/user/jonathan_old/tree/ECON-140-FA22-RDE/Sections/107-108-Jonathan) and from nbgitpuller, it's [this link](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FECON-140-FA22-RDE&branch=main&urlpath=retro%2Ftree%2FECON-140-FA22-RDE%2FSections%2F107-108-Jonathan%2FSection+3+-+Final+for+students.ipynb). Thanks!

**Comment by ryanlovett** [comment]
@jonathanold Thanks. According to `git status`, your ECON-140-FA22-RDE working directory on datahub has diverged from the upstream repo. Would it be okay if I moved aside the current directory and initiated a new fetch? (the third bullet point from the troubleshooting guide)

**Comment by jonathanold** [comment]
@ryanlovett - yes, that would be great - Thanks!

**Comment by ryanlovett** [comment]
I renamed the directory, then visited your link without any errors. Can you confirm?

The original directory was renamed "ECON-140-FA22-RDE.orig".

**Comment by jonathanold** [comment]
@ryanlovett - thank you! It works now - I just realized that it should be the top directory which needs to be renamed. Super helpful, thanks again!

**Comment by ryanlovett** [comment]
Okay, great.
