### ISSUE TITLE
Request to Retrieve Old Datahub Files

### ISSUE THREAD

**Issue by abdulwasayrida** [berkeley-dsep-infra/hubs#3789]
### Email Id

Hello,

I'd like to request to retrieve my past work/assignments from my old datahub files so I can have a personal private copy. 

This is the information given in the message:

======================================================
The following text is the link to your datahub folder,
it must be included with your request:

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/abdulwasayrida.tar.gz
======================================================

Thanks!

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@abdulwasayrida Please provide your UC Berkeley email address.

**Comment by abdulwasayrida** [comment]
Sorry for the late reply! It's abdulwasayrida@berkeley.edu

**Comment by felder** [comment]
Signed URL sent!
