### ISSUE TITLE
Archival Data Request

### ISSUE THREAD

**Issue by gforrest1026** [berkeley-dsep-infra/hubs#3796]
### Email Id

gforrest1026@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/gforrest1026.tar.gz

**Comment by felder** [comment]
Signed URL sent!
