### ISSUE TITLE
Please retrieve my Datahub files (for IB105)!

### ISSUE THREAD

**Issue by mkoo** [berkeley-dsep-infra/hubs#3803]
### Email Id

mkoo@berkeley.edu

### Link to Datahub Folder

[- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
](gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/mkoo.tar.gz)

**Comment by mkoo** [comment]
HI @felder thanks for reinstating. I will need this for a class demo by 10/4!
Sooner is better since it probably needs polishing- thanks

**Comment by felder** [comment]
@mkoo I need the link to the datahub folder from the file that was left in your home directory.

**Comment by mkoo** [comment]
I dont know where that zipped tar is (since i didnt do that) but this is where we had our code for the class:
https://github.com/ds-modules/IB-ESPM-105
thanks!

**Comment by felder** [comment]
@mkoo If you login to your account on the hub where it was archived, the archive process leaves a file with the link in it.  Are you able to login?

**Comment by mkoo** [comment]
Thanks--
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/mkoo.tar.gz

if you see another folder on the datahub... I was trying to resync with the
previous repo that was syncing with the datahub.
will this archive also restore links to the original repo on github? (
https://github.com/ds-modules/IB-ESPM-105)
Thanks

**Comment by felder** [comment]
@mkoo

The files are not restored in place.

The way this process works is I email you a URL to the archived files, and you can download the archive to your personal computer, and then upload whatever files you want from it to the hub.

**Comment by felder** [comment]
Signed URL sent!

**Comment by mkoo** [comment]
HI @felder this link led me to a tar file that did not contain anything recognizable or useful
Is there no way to sync with an existing GH repo as before?

Perhaps the easiest thing to do at this late date is to upload my .pynb file to the datahub.
Please let me know how to share with my students now that I cannot use nbgitpuller to post a class link

**Comment by felder** [comment]
@mkoo The link leads to a gzipped tar archive.

Make sure when you save it, that the name ends with .tar.gz

If you're on a Mac it should just extract when you double click it.  On Windows, use 7-zip to open it:
https://www.7-zip.org/

I don't understand what you mean by this:
> Is there no way to sync with an existing GH repo as before?

What's the issue you are having with nbgitpuller links?

**Comment by mkoo** [comment]
I tried to make a link to the repo I used before (which has the same files as the tar ball). This is the site we used in the past:
https://jupyterhub.github.io/nbgitpuller/link

This is the generated link:
https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FIB-ESPM-105&urlpath=tree%2FIB-ESPM-105%2FBNHM_biodiversityExample-2022.ipynb&branch=master

But I get an error instead -- pasted below:

Error:
Error: Command '['git', '-c', 'user.email=nbgitpuller@nbgitpuller.link', '-c', 'user.name=nbgitpuller', 'merge', '-Xours', 'origin/master']' returned non-zero exit status 128.

It cannot sync to the folder present on the Jupyterhub now (different histories since I edited it)

I could skip nbgitpuller altogether since I uploaded the .ipnb file that I want to use directly to the datahub; however I dont know how to make a copy for the class to use from the Jupyterhub portal since this is a different workflow than I'm used to (obviously!)

**Comment by felder** [comment]
@mkoo Maybe this page will help with your issue?
https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html

Specifically, item 3.

**Comment by mkoo** [comment]
Thanks for the troubleshooting page. I did figure out the problem and have a working link now for the class.

For future reference, this is what the problem was. Github changed what the default branch is called from 'master' to 'main'. My older nbgitpuller script was looking for 'master' branches, and the repo itself was older using 'master' instead as 'main'. The new tool (chrome extension specifically) let's you specify but my older repo still had a 'master' branch thus it was unable to resolve histories.

So the easiest thing was to start a new repo on github and use the new nbgitpuller chrome extension. Worked smoothly then!

**Comment by felder** [comment]
@mkoo That actually rings a bell with me, the discussion in issue #3695 might be helpful.

Although I think you're using the recommended remedy.

**Comment by balajialg** [comment]
@mkoo Sorry if this process took some time. Going forward, if you need support for any nbgitpuller-related issues or GitHub repository issues, you can also email me directly the issue - balajialwar@berkeley.edu.
