### ISSUE TITLE
Data Archival

### ISSUE THREAD

**Issue by carlimariah** [berkeley-dsep-infra/hubs#3804]
### Email Id

carlioxenham@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz](gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/carlioxenham.tar.gz)

**Comment by felder** [comment]
Signed URL sent!
