### ISSUE TITLE
Increase compute resources for DATASCI 241 between specific date(s)/time(s)

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/hubs#3806]
### Course Name

This is for the suite of courses numbered DATASCI 241. There are six seminars this semester, and each seminar is on the same course calendar, meaning that all of their work is stacked onto the same weekend. 

- https://classes.berkeley.edu/content/2022-fall-datasci-w241-001-wbl-001
- https://classes.berkeley.edu/content/2022-fall-datasci-w241-002-wbl-002
- https://classes.berkeley.edu/content/2022-fall-datasci-w241-003-wbl-003
- https://classes.berkeley.edu/content/2022-fall-datasci-w241-004-wbl-004
- https://classes.berkeley.edu/content/2022-fall-datasci-w241-005-wbl-005
- https://classes.berkeley.edu/content/2022-fall-datasci-w241-006-wbl-006

In total, this request will affect ~ 70 students. 

### Detailed Requirements

- 

The core resource crunch that we are observing is on the weekend before coursework is submitted. Through the rest of the semester, there are three more homework that students will be working on, each due on a Tuesday. 

### Semester Details

Yes

### Request Deadline

# Problem Set 3 
- Increase date: Friday October 7, 4:00pm
- Decrease date: Tuesday October 11, 4:00pm

# Problem Set 4
- Increase date: Friday, October 28, 4:00pm
- Decrease date: Tuesday, November 1, 4:00pm

# Problem Set 5
- Increase date: Friday, November 25, 4:00pm
- Decrease date: Tuesday, November 29, 4:00pm

**Comment by balajialg** [comment]
@d-alex-hughes Thanks for the heads up! I want to clarify the intent behind this request - Is it because RStudio is loading slowly for a few students in the ISchool hub during the past few weeks or something else? We are looking into this issue to evaluate whether any other fix other than the increased resource allocation would solve the problem you highlighted. There is a general issue with RStudio impacting many other hubs.

If there is no other better solution, We will go ahead and create calendar events for your request in the next 1/2 days.

**Comment by d-alex-hughes** [comment]
Thanks @balajialg! Here's a dialogue that we've had students report on several different occasions.

<img width="1037" alt="Screen Shot 2022-10-03 at 6 29 45 PM" src="https://user-images.githubusercontent.com/6474241/193715178-4d2b4929-22c0-4658-9fac-7c763cd7323e.png">

These issues seem to be occurring more frequently the evenings before assignments are due; and virtually never at other points. As well, the nature of this particular assignment points me toward a resource constraint issue. We're asking students to do some light simulation work, and they're all writing for-loops.

**Comment by balajialg** [comment]
Got it. Thanks, @d-alex-hughes for the context! I will discuss this with @felder internally and decide the way forward.

**Comment by felder** [comment]
@d-alex-hughes we discussed this issue in our team meeting today.  We believe there might be two unrelated issues occurring.  The first is a tricky infrastructure issue with NFS that we've been working on solving over the previous month.  People who experience that issue will see a general slow down and will get popups similar to what you're reporting.

Secondly, we see some evidence that in a few cases ischool students might be running out of memory.

We identified and implemented a possible fix for the NFS issue a few days ago and are monitoring the system to see if the fix works.

I'm also putting in a change now to double the memory allocation for ischool students.

**Comment by felder** [comment]
Deployed to prod.

@d-alex-hughes please let us know if your students still have issues.

**Comment by d-alex-hughes** [comment]
Thanks a lot @felder and @balajialg and team! 

The students have another homework run coming due next week, so we will see increased load over the weekend. I'm also reminding them that as we ask them to do more sophisticated work, it becomes increasingly useful for students to provision their own machine.

**Comment by balajialg** [comment]
Thanks, @d-alex-hughes for your patience and the thoughtful request to the students. Please do let us know how the following few assignments fare in Datahub.

Thanks @felder for proactively making the required changes based on today's discussion.
