### ISSUE TITLE
Please send me my Datahub files

### ISSUE THREAD

**Issue by LifeGains** [berkeley-dsep-infra/hubs#3812]
### Email Id

<email redacted since public>

I logged into Datahub to download all my files that I have on here, since I received a message from Jonathan Henke that access to I School Unix/Linux servers will disappear 90 days after I graduate.

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/kevinfu.tar.gz

**Comment by felder** [comment]
Signed URL sent!
