### ISSUE TITLE
Request Cartopy for Data100

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3832]
### Package Name

Cartopy

### Hub details

- Hub: Data 100
- Language:Python

We'd used it in Fall 2021 (#2824) and also in Spring 2021 for Stat 159 (#3279), hopefully it's an easy addition; we're holding again the Climate data lecture.

I seem to recall there were some issues that led to dropping it when we were updating the image in #3605, but I don't recall what. It turns out we're actually going to use it as Chelle kindly offered to deliver a guest lecture on Climate data and xarray.

Thanks!!

### Course Name

Data 100

### Semester Details

Fall 2022

### Installation Deadline

Oct 18, 2022 - that's the date for the lecture, would be great to have it on a bit earlier if possible so we can test (though on local testing with v 0.21 it all works fine).

**Comment by felder** [comment]
Done!

**Comment by fperez** [comment]
Awesome, thx @felder!
