### ISSUE TITLE
Stat 20 server start time

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3836]
### Bug description

On the evening of Wed. Oct. 12, stat20 students reported that their servers were slow to start. NFS activity showed no heavy test_stateid ops, but steady getattr and one read spike at 8:07p:

<img width="786" alt="Screen Shot 2022-10-12 at 10 40 30 PM" src="https://user-images.githubusercontent.com/10248125/195511051-ef24115d-230c-486e-a74b-e57c8f9589d5.png">

It looks like server startup time increased beginning at about 8:45p where servers would take up to 2 minutes to start:
<img width="785" alt="Screen Shot 2022-10-12 at 10 46 22 PM" src="https://user-images.githubusercontent.com/10248125/195511974-3350f37a-7625-4fe3-9c76-419e91d0e00f.png">

I'll collect more info in this issue.

### Environment & setup

- Hub: 
- Language:

**Comment by ryanlovett** [comment]
It looks like the hub pod was restarted 86m ago (~9:38p), which would have affected students starting up their servers, but not those who were already running.
```
hub-5d497fffb-wtx8f             1/1     Running   3 (86m ago)   2d7h
```

**Comment by ryanlovett** [comment]
Here's a 24h snapshot:
<img width="791" alt="Screen Shot 2022-10-12 at 11 05 24 PM" src="https://user-images.githubusercontent.com/10248125/195515054-1b10e9f5-88f2-4fed-97cb-65901d2ab314.png">

**Comment by ryanlovett** [comment]
@andrewpbray shared this student's screenshot:
![unnamed (1)](https://user-images.githubusercontent.com/10248125/195516178-51019a57-6740-4988-8f5b-766cc7d5dc45.png)

**Comment by ryanlovett** [comment]
This happened one hour ago.
```
60m         Warning   FailedScheduling   pod/jupyter-[snip]                  0/42 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/unschedulable: }, 2 node(s) were unschedulable, 26 node(s) didn't match Pod's node affinity/selector, 28 Insufficient memory. preemption: 0/42 nodes are available: 16 Insufficient memory, 26 Preemption is not helpful for scheduling.
60m         Warning   FailedScheduling   pod/jupyter-[snip]                  0/43 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) had untolerated taint {node.kubernetes.io/unschedulable: }, 2 node(s) were unschedulable, 26 node(s) didn't match Pod's node affinity/selector, 28 Insufficient memory. preemption: 0/43 nodes are available: 16 Insufficient memory, 27 Preemption is not helpful for scheduling.
59m         Warning   FailedScheduling   pod/jupyter-[snip]                  0/43 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) had untolerated taint {node.kubernetes.io/unschedulable: }, 2 node(s) were unschedulable, 26 node(s) didn't match Pod's node affinity/selector, 29 Insufficient memory. preemption: 0/43 nodes are available: 16 Insufficient memory, 27 Preemption is not helpful for scheduling.
59m         Normal    Scheduled          pod/jupyter-[snip]                  Successfully assigned stat20-prod/jupyter-[snip] to gke-fall-2019-user-beta-2021-11-06-d520c2e1-6m77
```

**Comment by ryanlovett** [comment]
Non running pods. It seems that none failed, but many were pending and eventually started.

<img width="788" alt="Screen Shot 2022-10-12 at 11 26 27 PM" src="https://user-images.githubusercontent.com/10248125/195518467-84df23b0-4730-42be-babd-af00bcfb4d9e.png">

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/3839 I'm giving stat20 its own nodepool, with a 5 node minimum

**Comment by ryanlovett** [comment]
<img width="660" alt="Screen Shot 2022-10-13 at 9 46 38 AM" src="https://user-images.githubusercontent.com/10248125/195656627-3e0dba05-bda7-4aa5-b2b5-d87bdbf8ff1e.png">
<img width="664" alt="Screen Shot 2022-10-13 at 9 46 56 AM" src="https://user-images.githubusercontent.com/10248125/195656684-adabbc20-62f7-44b4-ac04-4ddb514c8634.png">
<img width="661" alt="Screen Shot 2022-10-13 at 9 47 35 AM" src="https://user-images.githubusercontent.com/10248125/195656814-b589e039-6e6e-40e4-8912-91b2959440c3.png">
<img width="662" alt="Screen Shot 2022-10-13 at 9 49 28 AM" src="https://user-images.githubusercontent.com/10248125/195657198-26d9f3b3-4b75-4499-90db-a684192484ba.png">

**Comment by ryanlovett** [comment]
The beta pool went down to 14 at 8:42p, then went up, up, down, up, up, down, up to 10:18p. Non running pods spiked, probably as a result of this, over that same time period.

@yuvipanda created the epsilon pool in #3839 and move the stat20 hub into it.

@yuvipanda @balajialg Should there be some heuristic about how many different hub images a node pool should support, if this issue was caused due to image-pulling delays?

stat20's image is based on rocker, and we can probably consolidate all rocker-based images into one. However I don't know if there are incompatibilities between libraries in the different rocker images.

Before tonight, the set of hubs with rocker images using the beta pool were biology, ischool, publichealth, and stat20.

**Comment by balajialg** [comment]
@ryanlovett Thanks for the comprehensive report! I guess it will be helpful if and when we choose to write an After-Action report. Maybe @shaneknapp and @felder in discussion with you can review the existing images across the different node pools and make the final call with regard to heuristics? I will also add this as an agenda item for our upcoming team meeting. 

I see that we have been moving other images across node pools in response to issues - Check [this](https://github.com/berkeley-dsep-infra/datahub/pull/3705) and [this](https://github.com/berkeley-dsep-infra/datahub/pull/3615). Might as well take a proactive stance going forward!

**Comment by shaneknapp** [comment]
yep, all sounds good.

**Comment by ryanlovett** [comment]
stat20 has gone from ~10 users to ~190 over the past couple of hours and it looks like the epsilon node count is going up, and not fluctuating.
<img width="963" alt="Screen Shot 2022-10-14 at 10 19 47 AM" src="https://user-images.githubusercontent.com/10248125/195904965-2f86dfe8-28b7-41c6-9e2b-fc2b2a798578.png">
<img width="481" alt="Screen Shot 2022-10-14 at 10 20 01 AM" src="https://user-images.githubusercontent.com/10248125/195905001-0ee39462-5b6c-4d64-bb37-020b92cad038.png">

**Comment by ryanlovett** [comment]
There have been a few occurrances where servers took as long as ~1m to start though:
<img width="659" alt="Screen Shot 2022-10-14 at 10 21 15 AM" src="https://user-images.githubusercontent.com/10248125/195905173-56d6a51f-548b-4f84-8d7c-c48495557aae.png">

**Comment by yuvipanda** [comment]
yeah, 1min is fine. 10min is when hub starts counting them as dead. I think this would've caused a similar outage as last time if we hadn't moved them to their own pool

**Comment by ryanlovett** [comment]
When I display the data for a lot of -prod hubs, there are a lot of other server start times of just less than 1m (not stat20-specific), and they're clustered together. It seems like they're roughly 15m apart. (11:01a, 10:46a, 10:31a, 10:16a, ...)
<img width="908" alt="Screen Shot 2022-10-14 at 11 15 22 AM" src="https://user-images.githubusercontent.com/10248125/195913860-079db238-3407-413b-b50f-b9a75d73f7cc.png">

I picked a day two weeks back to view, and they're mostly around 10s, and they're not clustered together.
<img width="978" alt="Screen Shot 2022-10-14 at 11 32 48 AM" src="https://user-images.githubusercontent.com/10248125/195916790-d7a40c48-8449-4a97-b9dd-e2f900352903.png">

So perhaps the NFS restarts are pushing back some set of  server start times to 1m.

**Comment by ryanlovett** [comment]
stat20 has been moved to a filestore, and will also retain its own node pool going forward.
