### ISSUE TITLE
Adjust spawner messaging when servers are slow to start

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3845]
# Summary

#3836 tracks an issue where servers were slow (~2m) to start up. The current messaging that students see is from kubespawner's [`progress`](https://github.com/jupyterhub/kubespawner/blob/71a9538a892d580476dd31d12ff17ed6217b8ea5/kubespawner/spawner.py#L2296) which emits events messages if available and if the feature is enabled.

Obviously we want to fix any underlying issues around slow server startup, but if they still occur for whatever reason, I think it'd be good to display something simple like "your server is slow to start up", and then something comforting and hopefully true like, "the hub may be busier than normal, please wait just a little while longer. (restarting your server will put you at the end of the queue.)"

Grafana/prometheus have access to real-world data on start up time, so a more advanced solution might involve the messaging displaying the recent startup time average or 90% percentile figure. Maybe that's a hub service which fetches the data from prometheus and exposes it via a simple api. Or maybe the spawner should query prometheus directly.

# User Stories

In this case, students had a bad experience because a 2m startup time seemed like infinity to them -- normally servers start up fairly quickly. It caused a lot of anxiety just before an assignment deadline and a gentle message could have gone a long way to comfort them. This is like when you call up a service over the phone and are put on hold. If you're told what your estimated wait time is, you will probably feel less frustrated.

# Acceptance criteria

- If server startup time exceeds some threshold, the hub's UI for spawner progress will display a message acknowledging the condition, possibly with some data on recent start up time.

**Comment by balajialg** [comment]
@ryanlovett Thanks for raising this request! Seems super important. Is this UI change controlled by the Datahub team or part of the upstream?

**Comment by ryanlovett** [comment]
@balajialg It is already configurable but requires a bit of dev (there’s no single bit to flip). I’m away from keyboard but I think hub lets you define the “slow server” threshold, and then you need to insert the messages.

**Comment by ryanlovett** [comment]
Fixed by @shaneknapp !
