### ISSUE TITLE
Data Retrieval

### ISSUE THREAD

**Issue by christinestliu** [berkeley-dsep-infra/hubs#3846]
### Email Id

christinestliu@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
I need the link to datahub folder from the file left in your home directory.

**Comment by felder** [comment]
Please reopen if you'd still like your files.
