### ISSUE TITLE
Retrieve Archived Files

### ISSUE THREAD

**Issue by olivestheapple** [berkeley-dsep-infra/hubs#3875]
### Email Id

olivestheapple@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/oliverfli.tar.gz

**Comment by olivestheapple** [comment]
If the previously attached email id doesn't work, my updated email id is oliverfli@berkeley.edu, but I made the files when my email id was olivestheapple@berkeley.edu. Thanks

**Comment by felder** [comment]
Signed URL sent to oliverfli@berkeley.edu
