### ISSUE TITLE
Data Archive Request

### ISSUE THREAD

**Issue by dpartovi** [berkeley-dsep-infra/hubs#3880]
### Email Id

dpartovi@berkeley.edu
SID: 3034793867 
Material request from Summer 2021 BioStatistics 
PBHLTH 142 (Session D) | Introduction to Probability and Statistics in Biology and Public Health

gs://ucb-datahub-archived-homedirs/fall-2021/datahub.berkeley.edu/dpartovi.tar.gz

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Signed URL sent!
