### ISSUE TITLE
JupyterHub Archive

### ISSUE THREAD

**Issue by zhuerica** [berkeley-dsep-infra/hubs#3883]
### Email Id

ericaz

ericaz@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/ericaz.tar.gz

**Comment by felder** [comment]
Signed URL sent!
