### ISSUE TITLE
Accessibility: Installing Jupyter Notebook Alpha version 7.0.0.a7 in one of our hubs!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3885]
# Summary

I have been performing accessibility tests on the[ latest alpha version of Jupyter Notebook 7.0 ](https://discourse.jupyter.org/t/notebook-7-pre-releases-are-available/16063) which was released in the last couple of weeks . The latest version has a ton of accessibility changes including Code Mirror 6.0 + other UI updates which have improved the accessibility of the editor. To validate this claim by gathering concrete data, I opened [Data 8 Project 3 Notebook](http://data8.org/materials-sp20-external/) in both Data 8 hub and the binder link showcasing v7.0.0.a7. [Data 8 hub](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data8/image/infra-requirements.txt) has retro version [0.3.21](https://github.com/jupyterlab/retrolab/releases/tag/v0.3.21) which was released almost 6 months ago and the version in binder link was released in the last couple of weeks. 

**Results from Data 8 RetroLab audit:**
![image](https://user-images.githubusercontent.com/2306166/197912436-e7280d1d-b21f-4199-821f-43ba8dfaacbb.png)

**Results from Jupyter Notebook v7.0.0.a7 audit:**
![image](https://user-images.githubusercontent.com/2306166/197912417-c82cbfa2-5bb5-44de-8e23-bb32bc2642ef.png)

Lots and lots of accessibility issues highlighted by the automated checker in v0.3.21 of the retro lab have been fixed in Jupyter Notebook vv7.0.0.a7. I realize that we may not be comfortable installing the alpha version as a stable release in our regularly used hubs. However, @ericvd-ucb and I would like our team to install the latest version in one of our hubs which is not regularly used like a workshop hub or high school hub, or even create a new hub focused on showcasing accessibility upgrades. That way, campus leadership is also aware of the progress made by the Jupyter ecosystem over the past year through concrete data and can do an apple-to-apple comparison (one hub having retro lab vs another having notebook v7.0) while doing an accessibility audit with Web Access.

If interested, Here are the results from the automated check with VSCode enabled in Datahub and Google Colab. The latest version had fewer "critical" and "serious" issues compared to the other tools.

**Results from VSCode Audit:**
![image](https://user-images.githubusercontent.com/2306166/197913127-537c60f5-d6ff-4b85-8795-506b2b1b95cd.png)

**Results from Google Colab Audit:**
![image](https://user-images.githubusercontent.com/2306166/197913587-bbae1601-d0f4-436b-bd83-6d2ea8892753.png)

The above results are not comprehensive and need additional tests to validate my hypothesis. If you are curious to know more about the results of Keyboard and Screen Reader tests then please refer [here](https://docs.google.com/spreadsheets/d/1kpOUkYmy3p4rKiQW72cgrK1HZ_PlVsD2Px60lMGsbms/edit?usp=sharing).

# User Stories

- As a Service Lead for Datahub I want to showcase the progress made by the Jupyter accessibility team in improving accessibility to the campus leadership and perform an audit

# Acceptance criteria

- When I can launch Jupyter Notebook vv7.0.0.a7 in Datahub

# Important information

- Having something by mid-November would be a great value add.

# Tasks to complete

- [x] Decision about installing the alpha version?

- [x]  If yes to the above question, Installing the version in old hubs or new hubs?

**Comment by ryanlovett** [comment]
That's awesome! If showcasing these sorts of things on binder is insufficient, maybe there could be a test.datahub.berkeley.edu for testing and showcasing new technologies.

**Comment by balajialg** [comment]
@ryanlovett That sounds great! I am open to creating a new hub with a generic focus or specific focus (like accessibility.datahub.xx). Open to your perspectives on the best way forward.

**Comment by yuvipanda** [comment]
Would love to hear @shaneknapp's opinion too.

**Comment by afshin** [comment]
@balajialg This is such a helpful thing to see. What did you use to generate the results, I'd love to be able to check results as I make updates to code and I'm sure there are other people working on these projects that feel the same way. Is this something we could fold into our workflows?

Thanks so much!

cc: @SylvainCorlay

**Comment by balajialg** [comment]
@afshin Thanks for your interest! I am copy-pasting my email conversation with Sylvain as that might throw light on your question. Please let me know if you need more information.

_We tested the binder link for Notebook 7.0 alpha shared on this [page](https://discourse.jupyter.org/t/notebook-7-pre-releases-are-available/16063) using the [Axe Deque](https://www.deque.com/axe/) tool for which I have a professional edition. Shared below are the general issues highlighted by the automated checker. I have also attached a spreadsheet export from Axe that details all these issues in depth. I highlighted the critical and serious issues in yellow so that it may help you with prioritization_

![Accessibility Issues](https://user-images.githubusercontent.com/2306166/200215514-8d547f9f-7da5-4eca-9711-0d80eefbf7f9.png)

[hub.gke2.mybinder.org-Jupyter-Notebook-7.0-Alpha-Audit-2022-11-04.csv](https://github.com/berkeley-dsep-infra/datahub/files/9947707/hub.gke2.mybinder.org-Jupyter-Notebook-7.0-Alpha-Audit-2022-11-04.csv)

**Comment by balajialg** [comment]
Thanks, @ryanlovett and the team for your support in deploying the a11y hub with the latest notebook version. I am closing this github issue as I am able to launch the latest Jupyter notebook using a11y hub. Thanks!
