### ISSUE TITLE
Increase compute resources for Data 100 every Tuesday, Thursday 7pm-1am

### ISSUE THREAD

**Issue by andrea2031** [berkeley-dsep-infra/hubs#3886]
### Course Name

Data 100 Fall 2022 William Fithian & Fernando Perez
https://classes.berkeley.edu/content/2022-fall-data-c100-001-lec-001

### Detailed Requirements

We have lab and homework due dates on Tuesday and Thursday every week, so we expect much higher student activity between 7pm-1am. We will appreciated a higher resource limit to minimize associate disruptions. 

### Semester Details

Yes

### Request Deadline

Start of November. Thanks again!

**Comment by balajialg** [comment]
@shaneknapp has created a new node pool and allocated a bigger Virtual Machine (VM) for Data 100 hub. So, that should theoretically solve some of the resource needs problems. @andrea2031 Let's observe how things turn out for a week and close this request if there are no problems next week.

**Comment by shaneknapp** [comment]
> @shaneknapp has created a new node pool and allocated a bigger Virtual Machine (VM) for Data 100 hub. So, that should theoretically solve some of the resource needs problems. @andrea2031 Let's observe how things turn out for a week and close this request if there are no problems next week.

yep, see https://github.com/berkeley-dsep-infra/datahub/pull/3892

the hub is now backed by a [n1-highmem-32](https://cloud.google.com/compute/docs/general-purpose-machines#n1-high-memory), rather than the original n1-highmem-8.

**Comment by andrea2031** [comment]
Hi, multiple students from DATA 100 still reported slow kernel last night (Thur 9pm-12am) and throughout the weekend, do you know what might be the reason?

**Comment by balajialg** [comment]
Closing this issue considering that the semester is over. @andrea2031 please reopen this next semester if the issue persists. Thanks.
