### ISSUE TITLE
Files Retrieval Request

### ISSUE THREAD

**Issue by lunava** [berkeley-dsep-infra/hubs#3907]
### Email Id

lnavarret010@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/lnavarret010.tar.gz

**Comment by felder** [comment]
Signed URL sent!

**Comment by balajialg** [comment]
@felder Thanks. Is Cesar added to the repository? Can we assign him one or two data retrieval requests to start with?
