### ISSUE TITLE
Request python package geopandas for Data 100

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3912]
### Package Name

geopandas

### Hub details

- Hub: Data 100
- Language: Python

### Course Name

Data 100 - this is for a guest lecture to be delivered on November 10 by @danhammer.

### Semester Details

Fall 2022 and later -let's keep it always in the default image config.

### Installation Deadline

Nov 10 is when the lecture will take place.  In the meantime I'm testing the content with a manually pip-installed version.

**Comment by felder** [comment]
@fperez would you be willing to in general, conduct testing using the conda forge version?  You can use mamba to install it from the terminal.

**Comment by felder** [comment]
https://anaconda.org/conda-forge/geopandas

**Comment by fperez** [comment]
For sure! I'll do it now, will report...

**Comment by felder** [comment]
@fperez thanks!  In general we prefer to use packages from conda forge where possible, so this will help ensure that there are no version incompatibilities as was with the case for ipython-sql.

**Comment by fperez** [comment]
Just did - interestingly it caused a bunch of downgrades. Not sure why, I wasn't expecting that:

![image](https://user-images.githubusercontent.com/57394/200081284-db5d3292-82b6-4a92-8865-5a4fe1ae69e7.png)

(and +1 to conda forge - I think I was one of the people arguing precisely for that a while back, so happy to see this! :)

**Comment by fperez** [comment]
But I just tested our only notebook depending on cartopy (the only thing that worried me from those downgrades) and I don't see any issues.

So I'd say go for it with the conda forge version!

**Comment by felder** [comment]
@fperez sadly even after specifying the downgraded version of the packages that mamba wants to downgrade, geopandas won't install.

Going with pip for this.

**Comment by fperez** [comment]
Mmh, that's weird - it installed for me at the terminal as a normal user. Wonder why it would fail for you.

**Comment by fperez** [comment]
But in any case many thanks - we can revisit in another semester, with a clean build, what's going on.

**Comment by felder** [comment]
This should be on prod.  Lemme know if it isn't.

**Comment by fperez** [comment]
Just checked, all good. Thanks a lot @felder & team!!
