### ISSUE TITLE
Request python package yfinance,  quanstats for class Data 88E

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#3915]
### Package Name

yfinance , quantstats

### Hub details

- Hub: 
datahub
- Language: 
Python

### Course Name

https://classes.berkeley.edu/content/2022-fall-data-88e-001-lec-001

### Semester Details

Fall 2022

### Installation Deadline

Nov 8th if possible  - no prob doing !pip  install if not

**Comment by ericvd-ucb** [comment]
@klyankim @oooyiyangc

**Comment by balajialg** [comment]
@ericvd-ucb @felder Would these versions work for this request,
https://anaconda.org/conda-forge/yfinance
https://anaconda.org/conda-forge/quantstats

**Comment by felder** [comment]
Looks good on staging:

```
jovyan@jupyter-felder:~$ conda list | egrep "yfinance|quantstats"
quantstats                0.0.59             pyhd8ed1ab_0    conda-forge
yfinance                  0.1.85             pyhd8ed1ab_0    conda-forge
```

**Comment by felder** [comment]
Should be on prod within the next 30m.
