### ISSUE TITLE
Docs for new hub need note about gcr-key.json, gce-key.json

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#3918]
Admin should copy those from another hub.

**Comment by balajialg** [comment]
@ryanlovett Which step should this issue get covered in our documentation - https://docs.datahub.berkeley.edu/en/latest/admins/howto/new-hub.html
? I am not able to recollect the details.

**Comment by ryanlovett** [comment]
@balajialg I think after step 4 would be appropriate since that is when the prod/staging directories are created. Although, I think you can put these secrets in `deployments/template/{{cookiecutter.hub_name}}/secrets` since they can be copied as-is. That way a separate documentation step is not necessary.

**Comment by balajialg** [comment]
@ryanlovett got it. I added this information in step 6 and created a PR. Can you please review and merge it if it makes sense?
