### ISSUE TITLE
Request python packages dbt-postgres, dbt-bigquery for class Data 101

### ISSUE THREAD

**Issue by lukeliu0415** [berkeley-dsep-infra/hubs#3939]
### Package Name

dbt-postgres, dbt-bigquery

### Hub details

- Hub: Data 101
- Language: Python

### Course Name

Data 101, Lakshya Jain
data101.org

### Semester Details

Fall 2022

### Installation Deadline

11/14. Thank you!

**Comment by balajialg** [comment]
@lukeliu0415 Will these package versions work for you?

https://anaconda.org/conda-forge/dbt-postgres
https://anaconda.org/conda-forge/dbt-bigquery

Can we resolve this request by 11/15? Going forward, Would appreciate it if you give us at least 2 working days to resolve such requests.

**Comment by lukeliu0415** [comment]
Hi! I've only tested out the installations with pip:
https://pypi.org/project/dbt-bigquery/
https://pypi.org/project/dbt-postgres/
If these are equivalent as the conda packages, they should work!

Thanks for letting me know about the request timeframe. Resolving before this Wed 11/16 would be great. Thanks!

**Comment by felder** [comment]
This should be on prod in about 15m or so.
