### ISSUE TITLE
getting old files back from data 8 and 100 for reference!

### ISSUE THREAD

**Issue by shannonzhong1** [berkeley-dsep-infra/hubs#3940]
### Email Id

shannonzhong@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/shannonzhong.tar.gz

**Comment by felder** [comment]
data8 and data100 have their own filesystems, and here is the list of archives for you:

gs://ucb-datahub-archived-homedirs/2022-1-spring/data8/shannonzhong.tar.gz
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/shannonzhong.tar.gz
gs://ucb-datahub-archived-homedirs/spring-2021/prob140.datahub.berkeley.edu/shannonzhong.tar.gz

I'll send you recovery URLs for these.  If the files you seek are not in there, it likely means they have not been archived yet.

**Comment by felder** [comment]
Signed URLs sent!
