### ISSUE TITLE
Retrieve files from W271 and W203 MIDS courses

### ISSUE THREAD

**Issue by kanika79** [berkeley-dsep-infra/hubs#3941]
### Email Id

kanikamahajan@berkeley.edu

### Link to Datahub Folder

[- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz](gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/kanikamahajan.tar.gz)

**Comment by felder** [comment]
Please provide the link to datahub folder from the file left in your hub home directory.

**Comment by felder** [comment]
Haven't heard back.  Closing.

**Comment by kanika79** [comment]
I apologize but this is the link:
https://ischool.datahub.berkeley.edu/user/kanikamahajan/rstudio/

Sorry I was out on holidays. Can we please look into this as I am
graduating soon in December.

Thanks,
Kanika

**Comment by felder** [comment]
@kanika79 Please provide the link from the file in your home directory on the hub.  Not the link to rstudio.

If your files were archived, there should be a single file in your home directory named "WHERE-ARE-MY-FILES.txt"  That file will contain a link of a similar structure to the one in the issue description here.

**Comment by kanika79** [comment]
Hi,

I am not sure which file is being referenced. If I log into by datahub
below is what I see. Is it any file among these? Thank you so much!
[image: image.png]

**Comment by felder** [comment]
@kanika79 the image is not displaying.

**Comment by kanika79** [comment]
Hello,

Can you see now. I attached this as an attachment to this email. Please let
me know,

-Kanika

**Comment by balajialg** [comment]
@kanika79 Going forward, Can you please log in to GitHub and share attachments? Attachments won't be visible in the GitHub issue when replied via email. 

I looked at your content in the home directory using this URL - https://ischool.datahub.berkeley.edu/user/kanikamahajan/tree. It seems like all your files are intact. Are these the files you are looking for?

![image](https://user-images.githubusercontent.com/2306166/206800025-0e83df51-95e4-401f-b25b-2d84e80987cb.png)

Here is the snapshot of my directory which tells you that we took a backup of your file. In your case, all your files seem present if I access this URL. Please do let us know which files are you exactly looking for. Also, double-check whether you are requesting files for the correct hub URL.

![image](https://user-images.githubusercontent.com/2306166/206799699-390c1ef8-b96c-4a16-9299-1aecb6786748.png)

**Comment by kanika79** [comment]
Hi,

No these are not the files I am looking for. These are visible in my
current directory. I am looking for other files which were for W271 and
W203. I don’t remember the exact names but I had used datahub  heavily for
these 2 courses and I am not seeing any files. it possible they are in some
other directory?
I am not very familiar with datahub.
Thanks,
Kanika

**Comment by felder** [comment]
@kanika79 There are a variety of different hubs with different addresses.

For example, did you try https://datahub.berkeley.edu

**Comment by balajialg** [comment]
@felder Yes, My best guess is https://datahub.berkeley.edu/. I saw her base datahub tree and found that her files are replaced with where_are_my_files.txt file. I tried accessing r.datahub as the class @kanika79 mentioned uses R Studio. I couldn't find her username in that particular hub. I am not sure whether our users would be aware of any other hubs other than their dept specific hub (which is Ischool hub in this case) and the main datahubs. To move this forward - Can you please share her files from the base datahub and see whether it fits her needs?

**Comment by balajialg** [comment]
@felder Are you done completing this request?

**Comment by felder** [comment]
@balajialg @kanika79 

Signed URL sent!

**Comment by kanika79** [comment]
Thank you so much. I am using the link sent to retrieve my files.

-Kanika

**Comment by felder** [comment]
Great!
