### ISSUE TITLE
Install python package allensdk for class MCB-160L

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3942]
### Package Name

allensdk

### Hub details

- Hub: Datahub
- Language: Python

### Course Name

https://classes.berkeley.edu/content/2022-fall-mcellbi-160l-001-lec-001

### Semester Details

Fall 2022

### Installation Deadline

Students will use this package as part of this class on Thursday and Friday this week. Recommended instructor to use !pip install till the package gets added to the image.

**Comment by felder** [comment]
The conda forge package for this requires python 3.6 and is also quite old.
https://anaconda.org/conda-forge/allensdk
vs
https://pypi.org/project/allensdk/

Having pip install it separately fails to compile.  Having pip install it from the conda environment downgrades a number of packages and produces package conflicts.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.3.0 requires xarray>=0.16, but you have xarray 0.15.1 which is incompatible.
arviz 0.12.1 requires xarray>=0.16.1, but you have xarray 0.15.1 which is incompatible.
Successfully installed aiohttp-3.7.4 allensdk-2.13.6 argschema-3.0.4 async-timeout-3.0.1 boto3-1.17.21 botocore-1.20.112 cachetools-4.2.4 chardet-3.0.4 distro-1.8.0 glymur-0.8.19 hdmf-3.4.7 jmespath-0.10.0 marshmallow-3.19.0 matplotlib-3.4.2 ndx-events-0.2.0 psycopg2-binary-2.9.5 pynrrd-0.4.3 pynwb-2.2.0 requests-toolbelt-0.10.1 s3transfer-0.3.7 scikit-build-0.16.2 scikit-image-0.16.2 simpleitk-2.2.0 tables-3.6.1 xarray-0.15.1
```

Note that the allensdk docs also only guarantee compatibility with python 3.6 and 3.7, not 3.9 which is what is currently installed.

https://allensdk.readthedocs.io/en/latest/install.html

At this time I do not believe I can accommodate this request.

**Comment by balajialg** [comment]
@petersudmant This class is affiliated with the Molecular and Cell Biology department. Is this something you could help us with by installing allensdk python package in the biology hub? Do you have some bandwidth?

**Comment by petersudmant** [comment]
@balajialg, it looks like @felder tried to already and it's a bit tricky? Am I missing something? Was @felder trying to install this somewhere else and NOW we want to try it in biohub?

**Comment by balajialg** [comment]
@petersudmant Yes, @felder tried to install it in the central Datahub which didn't work due to package conflicts. Wondering if this would be smoother if this installation gets done via bio hub.

**Comment by petersudmant** [comment]
ROGER! I support this - I think this is easy. I don't have a ton of time, but I can try

**Comment by balajialg** [comment]
Thanks a lot @petersudmant! Fingers crossed.

**Comment by felder** [comment]
@petersudmant my hope is that maybe biology hub won't have the same packages...and package conflicts that I'm seeing in datahub.

**Comment by petersudmant** [comment]
makes good sense - I got it built! I'm merging into staging

**Comment by felder** [comment]
@petersudmant one thing to note is that allensdk 0.14.4 is really old, current is 2.13.6.
https://pypi.org/project/allensdk/

Not sure if that matters here.

**Comment by petersudmant** [comment]
I see - 0.14.4 is the latest conda version, but conda failed anyway. I'll try a later build. thanks for the headsup

**Comment by felder** [comment]
@petersudmant yeah the 0.14.4 conda forge package requires python 3.6 and fails spectacularly.

**Comment by petersudmant** [comment]
FYI @felder @balajialg - this builds and it worked when I tested it locally. The staging deploy shoudl be done shortly, but I won't be able to check it until the a.m. - feel free to merge into prod if all looks well

**Comment by petersudmant** [comment]
OK - all good. I tested some examples from their tutorials and it works.  I've merged into prod. 🚀

**Comment by balajialg** [comment]
Thanks a lot @petersudmant!
