### ISSUE TITLE
Data Archival Request

### ISSUE THREAD

**Issue by jaackiekim** [berkeley-dsep-infra/hubs#3964]
### Email Id

jacquelinekim@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/jacquelinekim.tar.gz

**Comment by felder** [comment]
Signed URL sent!
