### ISSUE TITLE
I need to access my archived files and request that you protect them from archiving in the future.

### ISSUE THREAD

**Issue by jmagruder** [berkeley-dsep-infra/hubs#3967]
### Email Id

jmagruder@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/jmagruder.tar.gz

**Comment by balajialg** [comment]
@jmagruder Thanks for reaching out! Our [policy ](https://github.com/berkeley-dsep-infra/datahub/blob/staging/docs/policy/storage-retention.rst)for archiving is that we archive home directories of users **who have not logged into their hubs for the past 180 days**. Your files got archived as you haven't used the hub for the above-mentioned duration. Please do clarify if this is not the case. 

It will require a lot of work at our end to tweak the script to not archive your files alone. Also, this would be an exception to our overall policy to archive for inactivity during the past 180 days. **Our recommendation is that you log into the hubs once in a while within the 180-day timeline (maybe set calendar events) to ensure that your files get never archived in the future**. Let us know if this is a reasonable resolution.

**Comment by felder** [comment]
Signed URL sent!
