### ISSUE TITLE
Can't find my file

### ISSUE THREAD

**Issue by EmilyDii** [berkeley-dsep-infra/hubs#3972]
### Email Id

zhuangemilydi@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@EmilyDii Please provide the link to datahub folder from the file left in your home directory.

**Comment by felder** [comment]
Have not heard back, closing.
