### ISSUE TITLE
Retrieve Files from Spring 2022 STAT20

### ISSUE THREAD

**Issue by rodyucb** [berkeley-dsep-infra/hubs#3973]
### Email Id

Hi! I want to retrieve my files from Spring 2022 STAT 20 course! I am planning to use my projects to apply for internships! My email is berkeley1269595@berkeley.edu, thanks!

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/berkeley1269595.tar.gz

**Comment by felder** [comment]
Signed URL sent!
