### ISSUE TITLE
UC Berkeley

### ISSUE THREAD

**Issue by WonshilPark** [berkeley-dsep-infra/hubs#3976]
### Email Id

wonspark@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by WonshilPark** [comment]
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/wonspark.tar.gz

**Comment by felder** [comment]
Signed URL sent!
