### ISSUE TITLE
Retrieved data from previous course works (eecs16a, eecs16b, ee120)

### ISSUE THREAD

**Issue by menghuichou** [berkeley-dsep-infra/hubs#3978]
### Email Id

menghuichou@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/eecs/menghuichou.tar.gz

**Comment by menghuichou** [comment]
any update on this? I need to reference my work in the past for my final project.

**Comment by felder** [comment]
Signed URL sent!
