### ISSUE TITLE
"Download directory" option results in 5xx error messsages across Data 100, EECS and Stat 159 hubs

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3979]
### Bug description

As a user, whenever I try to download directories in Data 100, Stat 159, or EECS hubs - I get the 500/503 error messages. It works well across other hubs like Public health, Data 8, Datahub, Data 101, Data 102, Biology hub, etc. This would be a useful feature for students to download their course data at the end of the semester. Sharing the error messages below,

![image](https://user-images.githubusercontent.com/2306166/204934456-ab06f3ac-9ceb-4298-9524-ca7cc01308bb.png)
![image](https://user-images.githubusercontent.com/2306166/204934485-49a6c549-dc26-46fd-aa2c-7254ad2e4206.png)

### Environment & setup

- Hub:  Data 100, Stat 159, and EECS

### How to reproduce

1. Select a directory in Data 100, Stat 159, or EECS hub
2. Click on the "Download Directory" option
3. Wait for the 5xx error message

**Comment by ryanlovett** [comment]
@balajialg If you tail the user's logs, e.g. `kubectl -n {hub}-prod logs -f jupyter-{username}`, then push that button, the notebook server reports that the executable `zip` is missing. It needs to be added via the `zip` apt package.

**Comment by balajialg** [comment]
@ryanlovett Thanks for your investigation. I will see if I can create a PR for this by looking at the apt installation for other hubs which work fine.

**Comment by ryanlovett** [comment]
@balajialg In the case of datahub, `r-base-core` depends on `zip` so pulls it in. It sounds like some of the other hubs need `zip` as an explicit dependency, i.e. entered in one of the apt package lists. It might be useful for it to be an explicit dependency for all hubs, even if some pull it in as a side effect.

You can investigate these sorts of dependency chains with `apt-cache showpkg zip`, where `zip` is installed.

**Comment by balajialg** [comment]
@ryanlovett Thanks a lot for the detailed inputs. I created a PR to update "zip" as an explicit dependency in hubs with a file dedicated to adding apt packages. What about other hubs? How are apt packages installed? Is it through a docker file?

**Comment by ryanlovett** [comment]
The hub images that use repo2docker have an apt.txt file, while others use a Dockerfile.
