### ISSUE TITLE
Request more RAM for ENVECON 153

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#3982]
**Which hub do you want more RAM on?**

datahub

**Which class is this request for?**

https://classes.berkeley.edu/content/2023-spring-envecon-153-001-lec-001

**How many students do you expect in this class?**
54 students

**How much RAM does this class need?**

3GB

**Why does this class need this much RAM?**

Students analyze some datasets which require that much ram.

**By when (MM/DD) do you want this request to be fulfilled?**

Start of Spring semester

**Any additional information we should know about?**

Thank you!  Love teaching with datahub!

**Comment by ryanlovett** [comment]
@balajialg Perhaps you can try following the new documentation at https://docs.datahub.berkeley.edu/en/latest/admins/howto/course-config.html for this?

**Comment by balajialg** [comment]
Thanks, @ryanlovett! Will do.

@ligon We made some updates to the Github templates which capture the required information to resolve this request. Can you please fill in the below details just like how you filled in this request - https://github.com/berkeley-dsep-infra/datahub/issues/4057

What is the Academic Guide URL for this class?

What is the bCourses URL for this class?

**Comment by ligon** [comment]
https://classes.berkeley.edu/content/2023-spring-envecon-153-001-lec-001

https://bcourses.berkeley.edu/courses/1521830

**Comment by balajialg** [comment]
Ref #4057 comment!
