### ISSUE TITLE
Upgrade Otter Grader from v3.1.4 to v4.2.x for Data 8

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4004]
### Package Name

Otter Grader

### Hub details

- Hub: Data 8
- Language: Python

### Course Name

Data 8 - https://classes.berkeley.edu/content/2023-spring-data-c8-001-lec-001

### Semester Details

Spring Semester

### Installation Deadline

We need to make this upgrade prior to the start of the next semester. Ideally, on or before 01/11

Otter Grader recently had a [4.2.x release](https://github.com/ucbds-infra/otter-grader/blob/master/CHANGELOG.md) which involves breaking changes. Data 8 plans to use the latest otter version for their classes next semester. As a result, We need to upgrade Data 8 image from v3.1.4 to v4.2.x. @ericvd-ucb @sean-morris @chrispyles Do you know the exact version of otter to which we should upgrade the Data 8 image?

**Comment by chrispyles** [comment]
Whatever the latest version is should be fine. I don't think there will be any breaking changes before v5.
