### ISSUE TITLE
Request python package Otter v4 for class Econ 148

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#4005]
### Package Name

Otter - 4.2

### Hub details

- Hub: 
Not sure which Hub you want to put me on? Im usually on the main datahub - but as we have discussed not sure if we can move the main datahub to Otter v4

- Language: 
Python

### Course Name

Econ 148 - Sp23
https://classes.berkeley.edu/content/2023-spring-econ-148-001-lec-001

### Semester Details

Sp23

### Installation Deadline

Beginning of Next Semester

**Comment by balajialg** [comment]
Couple of things to consider and choose from,

- We don't have a clear understanding of instructors deploying otter grader in their courses using main Datahub. Eric and I are going to get a list of users and do required outreach with them. However, we will not be sure whether that is the sample set of all the instructors. We can still go ahead and upgrade otter with the assumption that there might be one or two instructors who might got missed out as part of the outreach and can complain.
- Or else create a completely new hub focused on economics called econ.datahub.berkeley.edu etc. It is part of our larger strategy to isolate classes that require differing functionalities and also provide unique branding for economics courses that use the main Datahub.

Compiling the list of instructors who should be reached out if we decide to make the upgrade in the main datahub image,

1. John Marshall from Legal Studies 123 - <John Marshall <john.marshall@berkeley.edu>

**Comment by balajialg** [comment]
- [ ] Merge the package upgrade to staging and blast out an email using datahub-announce email list!
