### ISSUE TITLE
Increase compute resources for Course PS 3 January - April 2023 Mondays/Wednesdays 5-6:30 pm

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#4009]
### Course Name

PS 3

### Detailed Requirements

350 students will be using R.Datahub simultaneously from 5-6:30 pm on Mondays and Wednesdays during spring 2023

### Semester Details

No

### Request Deadline

First class January 23
Last class April 26

**Comment by balajialg** [comment]
@dbroockman We are making major upgrades to the infrastructure which might affect the current functionality of the calendar-based auto scaler. We are looking at a 2-3 week timeline to make these changes. We should be able to look into this request and resolve it once the upgrades are completed.

**Comment by balajialg** [comment]
@shaneknapp Can we increase resources for this class? or do we need to tweak the script for auto scaler further?

**Comment by balajialg** [comment]
@felder @shaneknapp @ryanlovett Created a recurring calendar event for Pol Sci 3 between 4.30 - 6.30 PM every monday and wednesday and allocated 8 nodes for this class of 350 students (~45 pods per node amounting to ~8 nodes) in the R hub. Let me know if you think the allocation makes sense?

**Comment by ryanlovett** [comment]
@balajialg That number should not be set to how many total nodes should be allocated. It is how many available spares ("hotspares" or "placeholders") there should be. It is to address the rate of growth so if a lot of people login in a short amount of time then the hot spare value is higher. If all 350 login at exactly 4:30p, try setting the value to be 2 starting at 4:20p. The cluster will make two additional empty nodes available which can handle 90 logins (based on your pod density figure), not counting those that are already running user pods. The cluster will continue to ramp up nodes, always keeping "+2" empty. Once class is underway and the rate of growth has slowed, the hotspare/placeholder count can be set back to 1 or 0.

If 2 proves to be insufficient it can be scaled up higher, or if it is more than enough it can be set lower. You can verify by seeing how many users are in pending and how long server startup takes.

**Comment by balajialg** [comment]
Thanks, @ryanlovett for the detailed explanation! It makes complete sense. I misunderstood that google calendar-based auto-scaler events allocate the exact nodes highlighted in the calendar event. This belief got strengthened after I saw that 10 hot spares got allocated for this class during Spring 2022 (Snapshot attached).  Changed the calendar entry to two nodes for now and let's tweak it based on real-time metrics (as you highlighted).

![image](https://user-images.githubusercontent.com/2306166/213264866-e6aa4c39-cbd8-4a44-9a58-8e1608eba96b.png)

**Comment by ryanlovett** [comment]
@balajialg I made the same assumption the first time I adjusted the calendar. :)

**Comment by balajialg** [comment]
@dbroockman Created a calendar event to handle this request. Please do keep us posted about your experience during the classes. We can increase resources if you have issues during the classes

**Comment by dbroockman** [comment]
Will do. I would ask that you err on the side of more resources for our first class this coming Monday because if everything fails on the first day it will set a really bad tone for this large class of students who have never done coding/data science before.

**Comment by balajialg** [comment]
Thanks for the heads up @dbroockman! I will check with the team (once again) if further tweaks are required for the current allocation which seems sufficient. Thanks!

**Comment by balajialg** [comment]
@dbroockman How did the classes go yesterday? Did students have a smooth experience using Datahub?

**Comment by dbroockman** [comment]
I think it went fine, thanks for checking in. FYI the class alternates between days when they do group work (so only 1/3 of the class uses Datahub) and when they all do, so please don't reduce resources further by looking at performance tomorrow for example :).

**Comment by balajialg** [comment]
@dbroockman Good to hear. Yes - We won't scale down the allocated resources till the end of the semester.  Closing this issue as the request seems to be fulfilled by the creation of calendar event. Please re-open this issue if you need anything else. Thanks

**Comment by dbroockman** [comment]
I'm hearing from students it usually takes around 4-5 minutes for notebooks to load at the beginning of class when all the students are logging in at once (~300 students). Is it possible to up the resources a bit?

**Comment by balajialg** [comment]
@dbroockman Is it happening across any one of the instruction days or across both Mondays and Wednesdays?

**Comment by dbroockman** [comment]
Both, but especially Mondays. After President's day that will be
Wednesday's (the format of the class alternates between days).

**Comment by balajialg** [comment]
@dbroockman Got it. I bumped up the resources for your class today. Can you let me know how it goes? I will replicate the same changes for both days if it works well today or else bump it up further.

**Comment by dbroockman** [comment]
Class was better today. Let's see how Monday goes, though. Thank you!

**Comment by balajialg** [comment]
@dbroockman Sounds good. 

Modified the calendar events to have placeholder nodes for Monday's event equivalent to what we had yesterday. I will keep the issue open to see the startup times of the R hub on Monday.

**Comment by shaneknapp** [comment]
@dbroockman our monitoring is lying to us.  i'll be adding some functionality to allow us to delay certain hubs from launching servers, and we will be able to use this to hunt down why we're not seeing it in grafana, and then what we can do to increase performace and monitoring/alerting.

issue:  https://github.com/berkeley-dsep-infra/datahub/issues/4237
PR: https://github.com/berkeley-dsep-infra/datahub/pull/4241

**Comment by balajialg** [comment]
@dbroockman Just to avoid any potential hassles - Is it possible to request your students to log into their hubs an hour before the class? Sorry for the delayed heads up.

**Comment by dbroockman** [comment]
I don’t think I understand. For today I should ask them to log into a
notebook within an hour before class?

**Comment by balajialg** [comment]
@dbroockman Yes - Can they log in to their hubs an hour before the class to avoid any potential delays when many students log in to hubs at the start of the class. As per my earlier comment, I have increased the resources for your class during the scheduled time which should help. This is an added measure based on Shane's earlier comment about how our monitoring infrastructure needs an update to report accurate metrics around startup times. Let us know if this request is feasible?

**Comment by dbroockman** [comment]
I can ask but I doubt many will do it. There will probably still be around
250 students all logging in right in the 5-510 pm range today.

**Comment by balajialg** [comment]
Got it @dbroockman! Have been generous with our resource allocation for today's class. Fingers crossed about student experience today.

**Comment by balajialg** [comment]
@dbroockman How did the class go yesterday? I see that almost 300+ students logged into the R hub and there was a corresponding increase in the resource allocation. 

![image](https://user-images.githubusercontent.com/2306166/218827496-5d7a94a9-7a77-4fa5-99d0-fade9726d962.png)
![image](https://user-images.githubusercontent.com/2306166/218827779-51730e49-ce19-4225-9e21-709dbcbe38e8.png)

**Comment by dbroockman** [comment]
No issues yesterday, thank you!

**Comment by balajialg** [comment]
that's great to hear @dbroockman. Thanks!

**Comment by balajialg** [comment]
@dbroockman Quick clarification, We are debugging an issue raised by another instructor  which involves the slow launch of the Jupyter application and wanted to check whether what you reported few weeks back is similar to what has been reported. When students reported server startup times were almost ~4 to 5 minutes previously, Did they report based on the timer that loads when you log in to Datahub (something like the snapshot below) which reports the total time taken to load the server? This would help us troubleshoot this issue further. Thanks! 

![image](https://user-images.githubusercontent.com/2306166/219480177-761dd4b4-3f20-4a23-895a-0f145d504f2e.png)

**Comment by dbroockman** [comment]
Unfortunately they told me how long they had to wait but I don't know which
waiting screen they were stuck on. My next class is Wednesday at 5:00 so if
you try to log in at Wednesday around 5:05 you'll probably experience what
they experience.

**Comment by balajialg** [comment]
@dbroockman Sounds good. Thanks for your inputs.

**Comment by dbroockman** [comment]
Around 1/3 students are experiencing very long waits to get access today. Here are examples of what they're seeing. 

![image](https://user-images.githubusercontent.com/6677808/220800364-d1c6721d-409f-43fc-89fc-f4551dc84acc.jpeg)
![image](https://user-images.githubusercontent.com/6677808/220800383-4247b9e5-fffc-480a-aff1-bdca42aeb6b7.jpeg)
![image](https://user-images.githubusercontent.com/6677808/220800395-3a6d973f-1cd3-49c0-8092-a93c9dac462c.jpeg)

**Comment by balajialg** [comment]
Sorry @dbroockman for the issue! Seems like there was a rush around 5 - 5.30 PM when 190+ students accessed R hub. 
![image](https://user-images.githubusercontent.com/2306166/220802535-218d89e4-a82d-47d6-aeb7-98fb39aefcc3.png)

We provisioned 4 additional placeholders for this class using calendar scaler. Node count went from 1 to 3 during the scheduled time (which means we did over allocate for this class) . @ryanlovett @felder Any idea what might be going wrong here.

![image](https://user-images.githubusercontent.com/2306166/220802712-0143657b-502e-4e9b-b71f-ba1c285c8547.png)
![image](https://user-images.githubusercontent.com/2306166/220802781-433c42f0-7ea3-4919-b1ae-bb5bfbbee361.png)

**Comment by dbroockman** [comment]
Can we just up the node count to 10 or something? How much does each node
cost…?

**Comment by balajialg** [comment]
@dbroockman Really sorry about the experience today. We need to do an estimate on the cost for allocating each node. Having said that, We don't have any problem allocating more resources from the next class. From my understanding, we did allocate more than the required resources for this class (based on the node count), and still, the slow server start-up time has persisted. I am trying to understand whether this is an issue with the calendar scaler or if is it something else that is resulting in slow startup times.

**Comment by ryanlovett** [comment]
@balajialg The calendar event for scale up starts at 4:30p, but the graph shows that the nodes don't scale up until after class started. The logs for the pod don't show that it ever parsed the PS3 calendar event. It is not working properly.

I just killed the existing node-placeholder pod (running for 30d).

**Comment by balajialg** [comment]
FWIW, All the users in the R hub got populated in the 3 nodes,

![image](https://user-images.githubusercontent.com/2306166/220805481-e5376ccf-cf95-48b1-a617-5773b1182fd3.png)
![image](https://user-images.githubusercontent.com/2306166/220805649-7561850c-2fca-4340-9930-8ffdce77a2ed.png)
![image](https://user-images.githubusercontent.com/2306166/220805683-7c6be911-4312-412a-a137-c3814bb593ec.png)

**Comment by balajialg** [comment]
@dbroockman - Going forward, We plan to stop increasing resources for your class through the calendar events to avoid issues like today where the calendar event did not work as expected. We are currently exploring alternatives as of now which might involve a) configuring these values within our code base or b) bumping up resources for the R hub overall. Will get back to you either tomorrow or the day after about the plan of action so that you have some clarity before your next class on the 27th.

**Comment by dbroockman** [comment]
Thanks - appreciated!

**Comment by balajialg** [comment]
@dbroockman Manually provisioned resources for your class today (~4 nodes). Going forward, that seems to be the path forward till we find a better solution.
![image](https://user-images.githubusercontent.com/2306166/221723073-86fd00fd-6647-4f7b-82e6-1a21610d6ae7.png)

**Comment by dbroockman** [comment]
Thanks, appreciate it. Going forward, Mondays are moderate-high utilization
(they have group assignments in small groups) and Wednesdays are high
utilization (individual assignments so everyone’s machine is on). It was
previously the reverse but after we missed a Monday due to President’s day
things switched.

**Comment by balajialg** [comment]
@dbroockman Thanks for the clarity! That's helpful.

**Comment by balajialg** [comment]
@dbroockman Manually configured the required resources for the class today by monitoring the metrics. Looks like students are having a smooth experience during today's class (Making this assumption by looking at the metrics and trying to login to R hub without any delay). Please let us know if there are any issues.

**Comment by balajialg** [comment]
@dbroockman Closing this issue as the improvements to calendar based scaler seem to work during the last two classes. Please feel free to re-open if you have any specific queries. Thanks!
