### ISSUE TITLE
Request more RAM for class ARE 212

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#4057]
**Which hub do you want more RAM on?**

datahub

**Which class is this request for?**

Spring 2023, ARE212, "Econometrics: Multiple Equation Estimation"

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-spring-aresec-212-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1521412

**How many students do you expect in this class?**

20

**How much RAM per user is needed?**

4GB

**Why does this class need this much RAM?**

Students are asked to tackle estimation problems using pandas DataFrames that use this much RAM.

**By what date (MM/DD) do you want this request to be fulfilled?**

Before start of Spring Semester!

**Any additional information we should know about?**

Thanks for providing this amazing service!

**Comment by balajialg** [comment]
@ligon Both the requests raised by you to increase resources are merged into production. Can you please test it and see if it works? I am closing your issues for now but please feel free to reopen them if you face any issues. Thanks!

**Comment by ligon** [comment]
When I log into datahub I see the requested amount of RAM.  

This does not test the experience a student enrolled in one of those two classes would have, of course, and I don't know how to test this (aside from asking students in the two classes to check).

I'll do that next week unless there's a better way.

**Comment by balajialg** [comment]
@ligon Thanks for checking! Yes - I think the best way to test this would be to ask students to check it when they log in to datahub. If any of them have issues then please do report them back to us!

**Comment by ligon** [comment]
At least some students in the class do **not** have the additional requested RAM (they have the default 1G).

We have gotten to the point in the semester where they really need the additional RAM!   Help!
