### ISSUE TITLE
Data request for RStudio

### ISSUE THREAD

**Issue by zach-gutz** [berkeley-dsep-infra/hubs#4062]
### Email Id

zach.gutierrez@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@zach-gutz Please provide the link to datahub folder from the text file left in your home directory on the hub.

**Comment by zach-gutz** [comment]
Sorry, I thought it was auto-generated, but just now noticed the "E.g."

gs://ucb-datahub-archived-homedirs/2022-3-fall/ischool/zach-2egutierrez.tar.gz

**Comment by zach-gutz** [comment]
gs://ucb-datahub-archived-homedirs/2022-3-fall/ischool/zach-2egutierrez.tar.gz

**Comment by felder** [comment]
Signed URL sent!
