### ISSUE TITLE
Data Files Retrieval Request

### ISSUE THREAD

**Issue by VSenthilKumar101** [berkeley-dsep-infra/hubs#4077]
### Email Id

vigneshsk@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/vigneshsk.tar.gz

**Comment by felder** [comment]
Signed URL sent!
