### ISSUE TITLE
Request python package pycountry-convert for class econ 148

### ISSUE THREAD

**Issue by rohanjha123** [berkeley-dsep-infra/hubs#4093]
### Package Name

pycountry-convert

### Hub details

- Hub: Datahub
- Language: Python

### Course Name

https://classes.berkeley.edu/content/2023-spring-econ-148-001-lec-001

### Semester Details

All semesters where the class runs (so all Spring semesters)

### Installation Deadline

Ideally by start of spring semester, but should be ok as long as it's done by 2 weeks into the semester

**Comment by shaneknapp** [comment]
@rohanjha123 any specific version, or the latest/greatest?

**Comment by rohanjha123** [comment]
Latest/greatest sounds great, thanks!

**Comment by shaneknapp** [comment]
@rohanjha123 when do you need this package?  i'll merge it during "off hours" as it'll require a new image to be built and i don't want to interrupt uptime for datahub.

**Comment by rohanjha123** [comment]
I’ll need the package in roughly 2 weeks time, thanks so much for working on this!

**Comment by shaneknapp** [comment]
word.  i will probably merge this tonite.

**Comment by balajialg** [comment]
Closing this issue as it got resolved. Thanks @shaneknapp!
