### ISSUE TITLE
please

### ISSUE THREAD

**Issue by shoehair** [berkeley-dsep-infra/hubs#4104]
### Email Id

iborkovic

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Please provide the "link to datahub folder" that is within the file left in your home directory on the hub.

**Comment by felder** [comment]
Haven't heard back, closing.
