### ISSUE TITLE
Request more RAM for class: EE 120

### ISSUE THREAD

**Issue by yousefh409** [berkeley-dsep-infra/hubs#4106]
**Which hub do you want more RAM on?**

EECS Hub

**Which class is this request for?**

EE 120 (Signals and Systems), Spring 2023

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-spring-eleng-120-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1522650

**How many students do you expect in this class?**

190

**How much RAM per user is needed?**

4GB/student

**Why does this class need this much RAM?**

We have signal processing labs that involve working with large amounts of data.

**By what date (MM/DD) do you want this request to be fulfilled?**

02/01

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@yousefh409 We have merged the changes to https://eecs-staging.datahub.berkeley.edu. Please do check whether you or any of your students have 4 GB RAM allocated. 

If it is a yes sign from your end, we will merge the changes to production.

**Comment by balajialg** [comment]
@yousefh409 It is merged to production!
