### ISSUE TITLE
retrieve files 

### ISSUE THREAD

**Issue by tanyasarkjain** [berkeley-dsep-infra/hubs#4107]
### Email Id

tanyasjain@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
- gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/tanyasjain.tar.gz

**Comment by felder** [comment]
Signed URL sent!
