### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by shurmanator** [berkeley-dsep-infra/hubs#4108]
### Email Id

julienshurma@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/julienshurma.tar.gz

**Comment by felder** [comment]
Please provide the "link to datahub folder" that is in the file left in your home directory on the hub.

**Comment by shurmanator** [comment]
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/julienshurma.tar.gz

**Comment by felder** [comment]
Signed URL sent!
