### ISSUE TITLE
[Data 8] Request Otter Grade Rollback to v3.3.0 for Data 8 Sp23

### ISSUE THREAD

**Issue by james-weichert** [berkeley-dsep-infra/hubs#4114]
### Package Name

otter-grader v3.3.0

### Hub details

- Hub: Data 8 Datahub (data8.datahub.berkeley.edu)
- Language: Python

### Course Name

[Data 8](https://classes.berkeley.edu/content/2023-spring-data-c8-001-lec-001)

### Semester Details

Spring 2023

### Installation Deadline

ASAP (week of 1/17)

**Comment by balajialg** [comment]
@james-weichert Closing this issue as the request got resolved! Please re-open if you have any concerns. Thanks!
