### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by tetsu2001** [berkeley-dsep-infra/hubs#4128]
### Email Id

satetsu@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/satetsu.tar.gz

**Comment by felder** [comment]
Signed URL sent!
