### ISSUE TITLE
retrieving files on datahub

### ISSUE THREAD

**Issue by vivektreddy** [berkeley-dsep-infra/hubs#4130]
### Email Id

vreddy704@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
@vivektreddy Can you please provide the "link to datahub folder" that is listed in the WHERE-ARE-MY-FILES.txt file left in your home directory on the hub?
