### ISSUE TITLE
Recovering files have been archived due to inactivity.

### ISSUE THREAD

**Issue by brianfaun** [berkeley-dsep-infra/hubs#4133]
### Email Id

brianfaun@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/brianfaun.tar.gz

**Comment by felder** [comment]
Signed URL sent!
