### ISSUE TITLE
to retrieve a copy of my files

### ISSUE THREAD

**Issue by sarden030** [berkeley-dsep-infra/hubs#4136]
### Email Id

sarden030@berkeley.edu

### Link to Datahub Folder

[- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
](gs://ucb-datahub-archived-homedirs/2022-3-fall/julia/sarden030.tar.gz)

**Comment by felder** [comment]
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.
