### ISSUE TITLE
Data Rettrieval Request: gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/sgpak.tar.gz

### ISSUE THREAD

**Issue by sgpak** [berkeley-dsep-infra/hubs#4138]
### Email Id

sgpak@berkeley

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Signed URL sent!
