### ISSUE TITLE
Accessing my Data 8 Spring 2022 work

### ISSUE THREAD

**Issue by 20sean02** [berkeley-dsep-infra/hubs#4161]
### Email Id

slin25@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/slin25.tar.gz

(This was the one that was provided but I'm actually requesting for Spring 2022 Data 8)

**Comment by 20sean02** [comment]
When I was trying to access the page it showed something like this

<img width="1153" alt="Screenshot 2023-01-23 at 7 39 43 PM" src="https://user-images.githubusercontent.com/112119200/214208809-c2e8d5b4-38a1-46ff-adf6-113ce7ceb76d.png">

<img width="1145" alt="Screenshot 2023-01-23 at 7 39 50 PM" src="https://user-images.githubusercontent.com/112119200/214208819-3ebcfb5c-0bad-4816-993c-246a842fdf35.png">

**Comment by balajialg** [comment]
@20sean02 Can you check whether hack like renaming the folder and pulling in the changes through the link again works for you - https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html#the-nbgitpuller-link-has-been-used-before-and-some-of-the-content-was-changed-in-both-datahub-and-github

**Comment by 20sean02** [comment]
I tried that but all I see is the following screenshot :(
<img width="1199" alt="Screenshot 2023-01-25 at 1 16 40 PM" src="https://user-images.githubusercontent.com/112119200/214692730-c89a707b-b55d-4cdc-87a2-3c8d6e096aca.png">

**Comment by felder** [comment]
@20sean02 Please login to https://data8.datahub.berkeley.edu instead of https://datahub.berkeley.edu if you want to interact with files from data8.
