### ISSUE TITLE
Admin access for Data 102 GSIs

### ISSUE THREAD

**Issue by rameshvs** [berkeley-dsep-infra/hubs#4168]
### Your Name

Ramesh Sridharan

### Affiliated Course Name

Data C102

### Role

Instructor

### Name of the Hub

data102.datahub.berkeley.edu

### End Date

05/31/2023

**Comment by balajialg** [comment]
@rameshvs Have added both the users as admin users using the dashboard. This approach would solve your immediate need for these GSIs to have admin access. I will create a separate PR to add/remove admin users permanently in the Data 102 hub.
