### ISSUE TITLE
Data 100 Retrieval Request

### ISSUE THREAD

**Issue by lukeelammm** [berkeley-dsep-infra/hubs#4170]
### Email Id

lukebe_736@berkeley.edu

### Link to Datahub Folder

[- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
](gs://ucb-datahub-archived-homedirs/2022-3-fall/data100/lukebe-5f736.tar.gz)

**Comment by felder** [comment]
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.
