### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by kmaccuish** [berkeley-dsep-infra/hubs#4174]
### Email Id

kmaccuish@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-3-fall/data100/kmaccuish.tar.gz

**Comment by felder** [comment]
Signed URL sent!
