### ISSUE TITLE
Request more RAM for Data 100

### ISSUE THREAD

**Issue by andrea2031** [berkeley-dsep-infra/hubs#4176]
**Which hub do you want more RAM on?**

datahub

**Which class is this request for?**

Spring 2023, Data 100

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-spring-data-c100-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1521765 (not published)

**How many students do you expect in this class?**

1300

**How much RAM per user is needed?**

4GB

**Why does this class need this much RAM?**

Upcoming memory intensive assignments.

**By what date (MM/DD) do you want this request to be fulfilled?**

1/26-2/9 (inclusive)

**Any additional information we should know about?**

NA

**Comment by balajialg** [comment]
@andrea2031 Hope the assignment was smooth. Confirming whether we can reduce the resources for Data 100 hub tomorrow?

**Comment by andrea2031** [comment]
Yes the assignment went smooth and we are ready to scale RAM back down! Thank you so much :)

**Comment by balajialg** [comment]
Thanks @andrea2031! Good to hear that.
