### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by erfu421** [berkeley-dsep-infra/hubs#4179]
### Email Id

Retrive my old files in my Datahub account. erfu@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.

**Comment by erfu421** [comment]
Sorry, here it is:
gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/erfu.tar.gz

**Comment by cesarvh** [comment]
@erfu421 Signed URL Sent!
