### ISSUE TITLE
Data Retrieval Request: gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/sgpak.tar.gz

### ISSUE THREAD

**Issue by sgpak** [berkeley-dsep-infra/hubs#4193]
### Email Id

sgpak@berkeley.edu 

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Same as #4138
