### ISSUE TITLE
Request R package "psych" and "pacman" for EEP/IAS C118

### ISSUE THREAD

**Issue by sungsy12345** [berkeley-dsep-infra/hubs#4203]
### Package Name

"psych" and "pacman"

### Hub details

- Hub: r.datahub and datahub
- Language: R

### Course Name

EEP 118
https://classes.berkeley.edu/content/2023-spring-envecon-c118-001-lec-001

IAS 118 (Crosslisted)
https://classes.berkeley.edu/content/2023-spring-ias-c118-001-lec-001

Sofia B Villas-Boas

### Semester Details

Spring 2023

### Installation Deadline

Sooner the better. We already started using one of the packages on 2/2/2023.

Thank you so much!!

**Comment by balajialg** [comment]
Hi @sungsy12345 - Thanks for raising this request using the appropriate template. Would versions [2.2.9 for Psych](https://cran.r-project.org/web/packages/psych/index.html) and [0.5.1 for Pacman](https://cran.r-project.org/web/packages/pacman/index.html) work for you? 

Also - Do yo need car package for any of your assignments - https://github.com/berkeley-dsep-infra/datahub/issues/1103?

**Comment by sungsy12345** [comment]
@balajialg Yes. Those versions sounds good! Thanks again!

**Comment by sungsy12345** [comment]
@balajialg Sorry, I missed the last part, where you ask me about "car" package. I have never heard of this package nor used it. So I think we are good for now. Thanks again.

**Comment by felder** [comment]
@sungsy12345 Car was already present.

You can see in the prod repo (which hasn't had these changes merged yet).

https://github.com/berkeley-dsep-infra/datahub/blob/prod/deployments/datahub/images/default/r-packages/eep-1118.r

It was requested in #1103
