### ISSUE TITLE
Request to restore SP22 data8 files for application uses

### ISSUE THREAD

**Issue by ZiqiShi-HMD** [berkeley-dsep-infra/hubs#4206]
### Email Id

ziqi.shi@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by felder** [comment]
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.
