### ISSUE TITLE
Review PS 3 material

### ISSUE THREAD

**Issue by mwboluobao** [berkeley-dsep-infra/hubs#4213]
### Email Id

michellew0915@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by cesarvh** [comment]
@mwboluobao 
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.

**Comment by mwboluobao** [comment]
Would this do?:

Your files have been archived due to inactivity.

If you want to retrieve a copy of your files, please
open a Data Archival Request via github here:
https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml

The following text is the link to your datahub folder,
it must be included with your request:

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/michellew0915.tar.gz

**Comment by cesarvh** [comment]
Yep, that's the one. Just sent the signed URL.
