### ISSUE TITLE
Increase compute resources for EE 120 between Friday 02/17 and Sunday 02/19

### ISSUE THREAD

**Issue by NSagan271** [berkeley-dsep-infra/hubs#4215]
### Course Name

https://classes.berkeley.edu/content/2023-spring-eleng-120-001-lec-001

### Detailed Requirements

- Deadline for EE 120 Lab 1 on Friday, with a grace period until Sunday night.

### Semester Details

Yes

### Request Deadline

Friday, 02/17 at 8am to Monday, 02/20 whenever convenient

**Comment by balajialg** [comment]
@NSagan271 Just confirming the use case here. Are you looking at many students logging into the EECS hub concurrently and working on their assignments during the specified timeline?  If yes, can we assume it will be 100+ students?

**Comment by NSagan271** [comment]
Based on the number of submissions so far, I think you can expect 100+ students scattered throughout that timeframe.

Edit: oops, I forgot that the lab was not due this week. The assignment is open right now and they have about a week left to complete it, so it might not be 100+. It depends on how many work on the assignment last-minute, but it could be 100+.

**Comment by balajialg** [comment]
@NSagan271 Thanks for the context. 

Given the uncertainty around the exact count of students who will be working during the requested time frame - I am wondering if adding one additional node placeholder in Google Calendar for those three days would make sense. Any thoughts @felder @shaneknapp

**Comment by balajialg** [comment]
@NSagan271 Based on the internal discussion, yet another clarification question - You are not currently worried whether the allocated RAM is enough for the assignment that is due next week. You are more worried whether students will have a delay while launching notebooks. Is that right?

**Comment by NSagan271** [comment]
Yes, the RAM is more than sufficient---just making sure students don't have problems launching and saving notebooks.

**Comment by shaneknapp** [comment]
> @NSagan271 Thanks for the context.
> 
> Given the uncertainty around the exact count of students who will be working during the requested time frame - I am wondering if adding one additional node placeholder in Google Calendar for those three days would make sense. Any thoughts @felder @shaneknapp

yes, i think adding pods w/the calendar schedule would be the right way to go.

**Comment by balajialg** [comment]
Added a calendar event for the mentioned dates. @NSagan271 Please feel free to reopen if you face any issues.
