### ISSUE TITLE
file retrieval from datahub

### ISSUE THREAD

**Issue by Gholi-MD** [berkeley-dsep-infra/hubs#4226]
### Email Id

farid.gholitabar@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

**Comment by cesarvh** [comment]
@Gholi-MD 
Please provide the "Link to Datahub Folder" from the file left in your home directory on the hub.
