### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by taylorshimono** [berkeley-dsep-infra/hubs#4235]
### Email Id

taylorshimono@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz

I'm not quite sure where to find this link... I would like to recover all of the files stored in my Berkeley JupyterHub account, especially in my Color-Space folder. The link that I usually use to open this is https://datahub.berkeley.edu/user/taylorshimono/tree/Color-Space

**Comment by taylorshimono** [comment]
My datahub folder is likely gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/taylorshimono.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent!
