### ISSUE TITLE
test/fix prometheus/grafana server start time metric by adding a delay to notebook at server launch

### ISSUE THREAD

**Issue by shaneknapp** [berkeley-dsep-infra/hubs#4237]
grafana is telling us that our server start times are never longer than 2 minutes.  anecdotal, and my actual experience, show that to be false (i had a server start after 3m, and checked grafana and it showed 2 minutes max).

<img width="483" alt="LIES" src="https://user-images.githubusercontent.com/1606572/217946469-7c469a87-6eb3-4fee-a39f-116258752e88.png">

so, i propose adding a traitlet to delay server start.  we can then set the timer to 5 minutes, hubploy to a11y-staging, and confirm that grafana lies.

after that, figure out what's broken and fix it.

**Comment by shaneknapp** [comment]
this will help us debug and improve performance in cases like [this](https://github.com/berkeley-dsep-infra/datahub/issues/4009#issuecomment-1423335899)

**Comment by felder** [comment]
omg...

@shaneknapp Is it possible there is a delay between server start and notebook launch?  We saw that in the meeting this afternoon when our student worker was launching a notebook in eecs.  If there is, that could also explain this behavior.

**Comment by balajialg** [comment]
Hey, @shaneknapp For the #4009 issue you referenced - How did you come to the conclusion that the calendar events not spinning up enough nodes before the classes is no where related to the slow startup times? Based on the below data?

![image](https://user-images.githubusercontent.com/2306166/217982764-d89d255a-ca98-462e-8d9f-5b50ffefc430.png)

![image](https://user-images.githubusercontent.com/2306166/217982951-5eeba8a0-d4f1-4ba6-bc70-cb134ceebaab.png)

**Comment by shaneknapp** [comment]
> omg...
> 
> @shaneknapp Is it possible there is a delay between server start and notebook launch? We saw that in the meeting this afternoon when our student worker was launching a notebook in eecs. If there is, that could also explain this behavior.

yes, it's entirely possible.

however, i just launched a server on a11y-staging w/a 3m delay, and grafana claims that it took 2m.  :\

![image](https://user-images.githubusercontent.com/1606572/217999983-9ca5402e-6ed1-4467-ba38-4238a723e0e2.png)

so:

1) grafana is lying, maybe because
2) prometheus is lying, or
3) we're querying the wrong metric for Server Start time, or
4) the underlying metric that we need is teh borked, or
5) all of the above.

**Comment by shaneknapp** [comment]
> Hey, @shaneknapp For the #4009 issue you referenced - How did you come to the conclusion that the calendar events not spinning up enough nodes before the classes is no where related to the slow startup times? Based on the below data?

these things are orthogonal, and we're trying to find any correlation between node spin-up, server launch and notebook launch times.

when users report slow server start times of > 3m, it should be represented in our monitoring.  this is definitely not the case.

it also appears that even after *server* launch, the *notebook* itself could take much longer than expected (as seen yesterday by @felder , sara, you and myself).  can we monitor this?  it'd be super if we could.

**Comment by shaneknapp** [comment]
> 



> > Hey, @shaneknapp For the #4009 issue you referenced - How did you come to the conclusion that the calendar events not spinning up enough nodes before the classes is no where related to the slow startup times? Based on the below data?
> 
> these things are orthogonal, and we're trying to find any correlation between node spin-up, server launch and notebook launch times.
> 
and to clarify:  if the node pool creation is causing a delay, this will be caught and displayed w/the timer + patience message i added late last year.

**Comment by shaneknapp** [comment]
i will also file an issue upstream in the jupyterhub repo about this behavior...

**Comment by balajialg** [comment]
> > 
> 
> > > Hey, @shaneknapp For the #4009 issue you referenced - How did you come to the conclusion that the calendar events not spinning up enough nodes before the classes is no where related to the slow startup times? Based on the below data?
> > 
> > 
> > these things are orthogonal, and we're trying to find any correlation between node spin-up, server launch and notebook launch times.
> 
> and to clarify: if the node pool creation is causing a delay, this will be caught and displayed w/the timer + patience message i added late last year.

Got it - that clearly highlights that any updates to calendar scaler would not fix the reported issue with server startup times. As you said there might be a delay between a server start up time and notebook startup time which is not reported by any metrics. I couldn't find any information about this in grafana - https://github.com/jupyterhub/grafana-dashboards/issues?q=is%3Aissue+start+up+time repository.

**Comment by felder** [comment]
@shaneknapp 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by shaneknapp** [comment]
created a PR upstream that addresses this:  https://github.com/jupyterhub/jupyterhub/pull/4352

**Comment by balajialg** [comment]
- [x] @balajialg to communicate the Maintenance Window. More details about MW here- #4365

**Comment by shaneknapp** [comment]
i added a 25th percentile view to our server spawn time panel in grafana, and feel that it gives us a more accurate view on actual spawn times.

also, i created a PR upstream in jupyterhub/grafana-dashboards to include this:  https://github.com/jupyterhub/grafana-dashboards/pull/71

i mention that i'm dubious about the utility of displaying the 99th percentile, but have yet to create an issue about this metric.
