### ISSUE TITLE
a11y hub throws "400: Bad Request" error

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4238]
### Bug description

When I try to access a11y.datahub.berkeley.edu/ then I get "400: Bad Request" error (Ref snapshot). 

![image](https://user-images.githubusercontent.com/2306166/217950926-b1b57f11-4be9-49ba-8d06-accb5857224d.png)

When I try to access admin interface it redirects me to datahub.berkeley.edu's interface which is confusing. Wondering if this is a feature or bug as I previously never accessed admin interface of a11y hub.

### Environment & setup

- Hub: a11y

### How to reproduce

1. Go to 'a11y.datahub.berkeley.edu'
2. See error
2.1. (Optional) Try accessing admin interface
2.2. Observe that it redirects to datahub's admin interface

**Comment by felder** [comment]
Fixed.

**Comment by felder** [comment]
@balajialg I'm really confused about which Project board to assign this issue to.

My expectation is there would be a 2023-02 Sprint Board (February), but I see no such thing

**Comment by balajialg** [comment]
Thanks for proactively fixing this @felder! You are awesome. 

Any reason for not assigning this to February user board - https://github.com/berkeley-dsep-infra/datahub/projects/30

**Comment by felder** [comment]
@balajialg I wasn't sure this would go on the user board.

**Comment by balajialg** [comment]
@felder Sure - sorry it was not intuitive. I thought we needed two separate boards - one to track the urgent stuff and another to track the long-term stuff - so had a sprint and dev board. Most of the short-term stuff is requested by our users so based on @rylo's recommendation during the sprint planning meeting - renamed it to the user board. If you have better ideas that would make it easy for you then I am open to exploring that also

**Comment by felder** [comment]
@balajialg I know some projects use trello for long term planning.  However, I have no problem assigning issues to whichever board works best.
