### ISSUE TITLE
Datahub request for Demography department

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#4244]
# Summary

The Demography department has historically administered its own servers running Rstudio and Shiny for instruction. We have a great interest in provisioning a dedicated Demography Datahub for the department in the spirit of other departments/schools like eecs, biology, ischool, etc. This semester we've tried moving Rstudio labs and Shiny simulations from on-premise servers to the Berkeley R Datahub for a large (~300 students) course in [Economic Demography-c175](https://github.com/josh-goldstein-git/econ_demog_c175_2023) and have had a great experience. Having a dedicated departmental hub would further empower our instructors to utilize the Jupyter ecosystem as the primary technology stack for computational social science instruction. 

Other courses where instructors have expressed interest:

Demography 180: Social Networks (undergrad)

Demography 280: Social Networks (grad)

L&S 88: Demography (already a connector course)

Demography 110: Introduction to Population Analysis

# User Stories

- Instructors want to be able to present students with a reliable, seamless, and customizable data analysis environment with all course labs and scripts available in one place regardless of the hardware a student might have (ability to run in a browser is a big win).

- Students want to be able to have low barrier to access to the data analysis environment so that they can focus on the concepts.

- Course administrators (GSI, TA) want to be able to use tools like ngbitpuller to sync course materials in a github repository to Datahub and keep materials up to date.

# Acceptance criteria

- Given `<some scenario>`, when `<some action is taken>`, then `<a specific result happens>`.

# Important information

- Mostly R, Rstudio, Shiny users but having a Python kernel is also desired for some courses. 
- Default R Datahub is 1GB of memory but ability to allocate 2GB or more as well as additional CPU would be necessary for times when peak usage would occur. 
- We also run a 6 week workshop over the summer with ~50 users, many non-Berkeley visiting scholars. Would love to discuss options for spinning up a separate workshop hub or seeing how this hub could work for that (likely a separate request/issue). 

# Tasks to complete

**Comment by balajialg** [comment]
Thanks, @wrathofquan for filling in the required details. What is the timeline you are operating concerning the new demog hub creation and the workshops you plan to run? I was assuming that you are looking at a new hub for Summer/Fall term. Is that a reasonable assumption?

As I said earlier in our call, creating a new hub would take some time given that we need to make a decision using our policy for new hub creation and put dev cycles to actually execute it. So, a tentative timeline would help with prioritization. Thanks

**Comment by wrathofquan** [comment]
Hi @balajialg. Correct, since the semester is underway our timeline would target the Summer/~Fall~ term with ideally something we can start testing sometime in early-mid May 2023 for the workshop. Thank you again!

**Comment by balajialg** [comment]
Sounds great @wrathofquan! I will circle back on this when we have some clarity. Thanks

**Comment by balajialg** [comment]
Closing this issue
