### ISSUE TITLE
Request for copy of my files for Fa20 Data 100

### ISSUE THREAD

**Issue by sothomas99** [berkeley-dsep-infra/hubs#4248]
### Email Id

sothomas@berkeley.edu

### Link to Datahub Folder

- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
gs://ucb-datahub-archived-homedirs/2022-3-fall/data100/sothomas.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent!

**Comment by sothomas99** [comment]
Received, thank you very much!
