### ISSUE TITLE
Request python package sqlalchemy downgrade to 1.4.46 for Econ 148

### ISSUE THREAD

**Issue by oooyiyangc** [berkeley-dsep-infra/hubs#4251]
### Package Name

sqlalchemy==1.4.46 (downgrade from current 2.0.1)

### Hub details

- Hub: Datahub
- Language: Python

### Course Name

[https://classes.berkeley.edu/content/2023-spring-econ-148-001-lec-001](https://classes.berkeley.edu/content/2023-spring-econ-148-001-lec-001)
Econ 148: Data Science for Economists 
Instructor: Prof Eric Van Dusen

### Semester Details

Spring 2023

### Installation Deadline

Hopefully by 02/20 (next Monday) if possible. Sorry for the very short notice!

**Comment by oooyiyangc** [comment]
@ericvd-ucb

**Comment by balajialg** [comment]
Done
