### ISSUE TITLE
Request more RAM for class Econ 148

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#4261]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**
datahub

For example: Datahub (datahub.berkeley,edu), R Hub (r.datahub.berkeley.edu hub), Data 100 Hub (data100.hub.berkeley.edu), EECS hub (eecs.datahub.berkeley.edu), etc

**Which class is this request for?**
2023 Spring Econ 148

For example, "2025 Spring, Robot Studies 101".

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-Spring-ECON-148-001-LEC-001

**What is the bCourses URL for this class?**

(https://bcourses.berkeley.edu/courses/1522114)

**How many students do you expect in this class?**
150
An approximate number would do.

**How much RAM per user is needed?**
2GB
The default is 1GB of RAM per student.

**Why does this class need this much RAM?**

A short justification for this resource request.
Larger SQL exercise

**By what date (MM/DD) do you want this request to be fulfilled?**

02/21 - for 2 weeks or until end of semester ( end of semester preferrred) 

This will help us with prioritization of this request.

**Any additional information we should know about?**

**Comment by felder** [comment]
@balajialg if you put "fixes issue" in a comment for a PR I believe it will auto close the referenced issue when the PR is merged.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

So if you don't want that behavior you should avoid using any of those key words.
