### ISSUE TITLE
Jason Cao's Request to Retrieve Old R files from Stat20

### ISSUE THREAD

**Issue by Hyperion8642** [berkeley-dsep-infra/hubs#4262]
### Your UC Berkeley Email Address

Email: jason.cao.2003@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/stat20/jason-2ecao-2e2003.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent!
