### ISSUE TITLE
Request update of ipykernel to 6.19.4 for Data 8 Datahub

### ISSUE THREAD

**Issue by james-weichert** [berkeley-dsep-infra/hubs#4291]
### Package Name

ipykernel

### Hub details

- Hub: data8.datahub.berkeley.edu
- Language: Python
- See [here](https://github.com/berkeley-dsep-infra/datahub/issues/4067) for details (we're having the same ipywidgets issue as Econ 148 did)

### Course Name

[Data 8](https://classes.berkeley.edu/content/2023-spring-data-c8-001-lec-001) - Instructors: Swupnil Sahai and Joey Gonzalez (Content Lead: James Weichert)

### Semester Details

Spring 2023 onwards

### Installation Deadline

As soon as possible (if an easy fix)

**Comment by balajialg** [comment]
@james-weichert You should be able to use the ipykernel 6.19.4 version
