### ISSUE TITLE
Increase compute resources for Course MIDS 203 between Thursday March 2, and Tuesday March 7

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/hubs#4312]
### Course Name

Hi team! This is the School of Information Stats class, which has students working on their first "lab" this weekend. There are 150 students and nothing they're up to is that complicated, but they will _all_ be working on the hub the weekend.

### Detailed Requirements

There is a deadline upcoming (Tuesday March 7 @ 4:30 Berkeley time) that will have 150 students working on the system over the weekend. 

### Semester Details

Yes

### Request Deadline

*Start*: Thursday, March 2 (i.e. today!) 
*End*: Tuesday March 7 (i.e. next Tuesday).

**Comment by d-alex-hughes** [comment]
Thanks everyone! We haven't had any reports of outages or especially slow performance over the weekend. The big crush will probably be this evening, but seems to be good so far. Thanks!

**Comment by balajialg** [comment]
Thanks, @d-alex-hughes! There wasn't a big rush during the weekend. The Ischool hub had almost 50+ users during the weekend which was easily handled with the default resource allocation. Having said that, I have created a calendar event from 4.30 PM-midnight today with additional resources which should easily handle 150 users accessing the hub. 
  
![image](https://user-images.githubusercontent.com/2306166/223287635-39c3e253-646b-4afe-a622-4445be4b849f.png)

**Comment by balajialg** [comment]
@d-alex-hughes Closing this issue as the spike was not big enough to require an additional calendar event. The current allocation for ISchool hub was enough to handle the load.

![image](https://user-images.githubusercontent.com/2306166/223885139-9359f196-7949-4b23-8742-504615e0c688.png)

**Comment by d-alex-hughes** [comment]
Thanks @Balaji Alwar ***@***.***> ! Talking with our
students, it seems that they were electing to pair program, rather than
each have their own cluster running. Thanks for being responsive!

**Comment by balajialg** [comment]
That's fascinating @d-alex-hughes! Innovative use case :)
