### ISSUE TITLE
Hi I already submitted but haven't heard back. I would like my projects back to show code examples for an interview. 

### ISSUE THREAD

**Issue by izzygerrard** [berkeley-dsep-infra/hubs#4326]
### Your UC Berkeley Email Address

izzy2022@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/izzy2022.tar.gz

**Comment by balajialg** [comment]
@cesarvh Can you please look into this request asap? Would appreciate it

**Comment by cesarvh** [comment]
Signed URL Sent.

**Comment by balajialg** [comment]
Thanks a ton @cesarvh
