### ISSUE TITLE
Retrieving my data hub 

### ISSUE THREAD

**Issue by criscres** [berkeley-dsep-infra/hubs#4337]
### Your UC Berkeley Email Address

Hi, 

I was unable to retrieve my data hub from the link that was sent to me a couple weeks ago. Did I need to do something specific once I had the link to retrieve all my files? Could you send another link together with any other instructions to download my data hub files? Thanks!

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/cristina-5fcrespo.tar.gz

**Comment by cesarvh** [comment]
@criscres I will send a link in a bit. The link is valid for only 7 days, perhaps it expired after I sent the last one?

**Comment by criscres** [comment]
Probably - sorry for that! Thanks for re-sending it!

Cristina Crespo Montañés
+1 628 276 3167 | LinkedIn
<https://www.linkedin.com/in/cristina-crespo-montanes/>
PhD Candidate | Energy & Resources Group
University of California, Berkeley

**Comment by cesarvh** [comment]
Signed URL Sent March 27th
