### ISSUE TITLE
Request more RAM for data 100

### ISSUE THREAD

**Issue by rohanjha123** [berkeley-dsep-infra/hubs#4339]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Data 100 Hub (data100.hub.berkeley.edu)

**Which class is this request for?**

2024 Fall, Data Science 100

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-spring-data-c100-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1521765

**How many students do you expect in this class?**

1200

**How much RAM per user is needed?**

4GB of RAM per student will be great

**Why does this class need this much RAM?**

This class is going to have some very memory-intensive assignments released on march 10th and due by march 28th, and we will need extra RAM for those assignments

**By what date (MM/DD) do you want this request to be fulfilled?**

Ideally, the request will be fulfilled by march 10th, but we should be fine as long as it's done by the weekend

**Any additional information we should know about?**
I would love it if the temporary RAM increase lasted until march 28th. Sorry for the late notice, we were blindsided by the memory usage of some new assignments. Thank you datahub team for all you do <3

**Comment by balajialg** [comment]
Linked PR - #4341

**Comment by balajialg** [comment]
@rohanjha123 Closing this issue as it got resolved!

**Comment by rohanjha123** [comment]
Thanks so much!
