### ISSUE TITLE
Retrieve Old Datahub Files

### ISSUE THREAD

**Issue by worledge** [berkeley-dsep-infra/hubs#4343]
### Your UC Berkeley Email Address

tobiasworledge@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/eecs/tobiasworledge.tar.gz

**Comment by balajialg** [comment]
@cesarvh Can you please respond to the pending data retrieval requests asap? Would appreciate it.

**Comment by cesarvh** [comment]
Signed URL Sent.
