### ISSUE TITLE
Recovering Notebooks after changing Berkeley.edu email address

### ISSUE THREAD

**Issue by myoung2912** [berkeley-dsep-infra/hubs#4385]
Hi,

I changed my Berkeley email address a while back from mark_shark2912@berkeley.edu to myoung2912@berkeley.edu. Since the email change, when I log into datahub.berkeley.edu, I am unable to access the notebooks I created while my email address was still mark_shark2912@berkeley.edu. Is there a way to recover those old notebooks? Please let me know, thank you.

**Comment by felder** [comment]
/export/datahub-filestore/datahub/prod/mark-5fshark2912
/export/datahub-filestore/datahub/prod/myoung2912

**Comment by felder** [comment]
Before I service this request I need to confirm from calnet that this switch did indeed occur.

**Comment by felder** [comment]
Request INC1499528 submitted to calnet to verify.

**Comment by felder** [comment]
Calnet verified this changed occurred.

@myoung2912 I'm going to copy the entire contents from mark-5fshark2912 into your home directory myoung2912

**Comment by felder** [comment]
@myoung2912 I've moved the files over.  You should now see a directory named "mark-shark-files" which contains all of the data associated with your old id.
