### ISSUE TITLE
Migrating Ubuntu 18.04 LTS to 22.04 LTS

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4395]
Ubuntu 18.04 ‘Bionic Beaver’ is reaching the [End of Standard Support](https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices) this May. As per their website, If we don’t take action, it will transition to 18.04 EOL(End Of Life). As per @felder's inputs, We need to migrate the version to 22.04 before the end of May. Hence, scheduling this activity for the May maintenance window which happens between May 12th and 22nd which is the break between the end of Fall and the beginning of Summer classes.

**Comment by ryanlovett** [comment]
These repo2docker images:
- [ ] a11y
- [ ] astro
- [ ] cee
- [ ] data100
- [ ] eecs
- [ ] stat159
- [ ] data8xv2

Also any stand alone vms that might be running 18.04.

**Comment by balajialg** [comment]
Closing this issue as it got done
