### ISSUE TITLE
Updates to WHERE-ARE-MY-FILES.txt

### ISSUE THREAD

**Issue by snviray** [berkeley-dsep-infra/hubs#4397]
# Summary

Update the WHERE-ARE-MY-FILES.txt file with a custom URL to open a GitHub issue and let them know that they will receive their files over email.

This change is needed because our users often enter the wrong link to their Datahub folder (Ex. gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz). See "Pending" in the [User Board](https://github.com/berkeley-dsep-infra/datahub/projects/30) to see all of the issues where users entered the wrong link.

# User Stories

- As a student, I want my datahub file link to be prefilled so I do not need to manually type it or copy paste it, which is error-prone
- As a student, I want to know how I will receive my files so I am not confused. 

# Acceptance criteria

- When a user opens WHERE-ARE-MY-FILES.txt, they can create a Data Retrieval request by only entering their email and submitting the form and know that they will eventually receive their files in an email.

# Important information

- Reference link to a test repo: https://github.com/snviray/test-issue-template/issues/new?template=data_retrieval_request.yml&title=Request+my+old+files+stored+in+Datahub&field1=sviray@berkeley.edu&field2=gs://ucb-datahub-archived-homedirs/2022-3-fall/eecs/sviray.tar.gz
- [Survey Responses](https://docs.google.com/spreadsheets/d/1NXXvyHJBOCN0EdVZoxaPFe6cMKi0iB7L3AflwGEEB7s/edit#gid=1500900788) 

New WHERE-ARE-MY-FILES.txt content

```
Your [HUB NAME] files have been archived due to inactivity.

If you want to retrieve a copy of your files through email, please open a Data Archival Request via GitHub using the custom URL below:

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub&link=[LINK TO USER'S TAR FILES STORED IN LOW COST STORAGE]

After submitting the form, a Datahub admin will send you a signed link to download your Datahub files via email within a few days.
```

# Tasks to complete

- [x] Update the GitHub issue template to add an id called "link" to the "Link to Datahub Field" (See example in https://github.com/snviray/test-issue-template/blob/main/.github/ISSUE_TEMPLATE/data_retrieval_request.yml)
- [x] For future archives, replace the WHERE-ARE-MY-FILES.txt content with the new one above, concatenating the information in square brackets. ex. [LINK TO USER'S TAR FILES STORED IN LOW COST STORAGE]

**Comment by balajialg** [comment]
@felder Let us know if you need more information for making the change. I will take care of updating the github template.

**Comment by balajialg** [comment]
@snviray Closing this issue as it got implemented yesterday (Check the linked PRs). Thanks @felder for your awesome work to update the text file.
