### ISSUE TITLE
Request for my Data Science Work for Portfolio 

### ISSUE THREAD

**Issue by Alex-Eyman** [berkeley-dsep-infra/hubs#4468]
### Your UC Berkeley Email Address

alex.eyman@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/alex-2eeyman.tar.gz

**Comment by Alex-Eyman** [comment]
What is the possible timeline for this being resolved? I have potential employers who are interested in seeing the notebooks.

**Comment by cesarvh** [comment]
Signed URL sent
