### ISSUE TITLE
DATA100 File Retrieval

### ISSUE THREAD

**Issue by brandster33** [berkeley-dsep-infra/hubs#4491]
### Your UC Berkeley Email Address

brandon_g33@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/data100/brandon-5fg33.tar.gz

**Comment by balajialg** [comment]
@cesarvh - Can you please service the data retrieval requests?

**Comment by cesarvh** [comment]
Signed URL Sent!
