### ISSUE TITLE
Issue: Data Retrieval Request

### ISSUE THREAD

**Issue by zachj-j** [berkeley-dsep-infra/hubs#4499]
### Your UC Berkeley Email Address

zachjj279@berkeley.edu

### Link to Your Datahub Folder

[gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/zachjj279.tar.gz](url)

**Comment by cesarvh** [comment]
Signed URL Sent!

**Comment by zachj-j** [comment]
How can I access it? I'm not seeing anything in my email and the link above returns no results. Sorry if it's a dumb question.
