### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by anniemccutcheon** [berkeley-dsep-infra/hubs#4512]
### Your UC Berkeley Email Address

amccutcheon@berkeley.edu

### Link to Your Datahub Folder

https://astro.datahub.berkeley.edu/hub/spawn-pending/amccutcheon

**Comment by cesarvh** [comment]
Hi @anniemccutcheon,

The link we need should begin with "gs://" and should be in a file called WHERE_ARE_MY_FILES within the datahub itself. Please provide that and I can get back to you

**Comment by balajialg** [comment]
@anniemccutcheon Any updates wrt Cesar's request?
