### ISSUE TITLE
Request more RAM for Econ/Demog 175

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#4513]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

datahub.berkeley.edu

**Which class is this request for?**

[Econ/Demog 175](https://github.com/josh-goldstein-git/econ_demog_c175_2023)

**What is the Academic Guide URL for this class?**

[c175](https://classes.berkeley.edu/content/2023-spring-demog-c175-001-lec-001)

**What is the bCourses URL for this class?**

[bcourses](https://bcourses.berkeley.edu/courses/1523121)

**How many students do you expect in this class?**

200

**How much RAM per user is needed?**

8GB of RAM per student.

**Why does this class need this much RAM?**

One of the final projects requires data analysis of a 600 MB csv file. [link to the data](https://drive.google.com/file/d/1yXV08o7D_6rikCQymVuHrQMlDAHJLciq/view?usp=sharing). Attempting to do so crashes Datahub currently. 

8 GB should be ample memory for students to complete the assignment. 

**By what date (MM/DD) do you want this request to be fulfilled?**

Ideally as soon as possible. By 04/26 would give me time for more testing. 

**Any additional information we should know about?**

Also need to store the data. @balajialg mentioned shared folders which would be super helpful. But I can also pursue syncthing if that is also a solution.

**Comment by ericvd-ucb** [comment]
What is the step that crashes - is it getting the datset into Datahub, or trying to manipulate once it is in Datahub

**Comment by wrathofquan** [comment]
The very first step (read_csv()). The default config is not enough memory to read and hold the data.

**Comment by ericvd-ucb** [comment]
got it - so discussing the i/o  eg shared read dir is not going to fix that problem!

**Comment by ericvd-ucb** [comment]
do they need all the 24 columns?

**Comment by wrathofquan** [comment]
To my knowledge, they do need those variables to complete the lab.

**Comment by balajialg** [comment]
@wrathofquan I increased the RAM to 8GB for Econ/Demog 175 course and this change will get tracked through this [PR](https://github.com/berkeley-dsep-infra/datahub/pull/4514). Can I reduce the resource allocation to 2 GB by 05/12 as that seems to be the last day of finals week?
As @ericvd suggested, any efforts at the instructors' end to tune down the dataset is critical as this change request is correlated with increased cloud costs at our end. 

We can restrict the scope of the support request to increase RAM here and explore syncthing and/or shared read/write functionality as part of this https://github.com/berkeley-dsep-infra/datahub/issues/4244 request.  Let me know if that is okay for you. 

Syncthing is currently enabled at https://datahub.berkeley.edu. You can refer to this [documentation ](https://ds-modules.github.io/curriculum-guide/workflow/use-realtimefilesharing.html?highlight=syncthing) and test this feature. Happy to hop on a call if that is helpful.

**Comment by wrathofquan** [comment]
Thank you @balajialg Yes please do drop it back it down on 5/12. I hear you on the data size - we want to be good stewards of the service so will definitely take a closer look at the assignment next time around.

**Comment by wrathofquan** [comment]
Thanks again @balajialg and Datahub team for accommodating us. Everything went great with this last assignment and the resources for this hub can be scaled back as the semester winds down.

**Comment by balajialg** [comment]
Thanks for the update @wrathofquan! That's awesome. Removing the memory allocation is tracked through this PR #2516
