### ISSUE TITLE
Bringing R version up-to-date for individual sessions on Public Health DataHub?

### ISSUE THREAD

**Issue by benmarafino** [berkeley-dsep-infra/hubs#4525]
### Bug description

We have several students in PH 241 who are using the R DataHub to write R code for their homework. They appear to have a base R version running (4.1.2) that is behind the version currently deployed (4.2.2) as well as the one I have access to on my own R DataHub session (4.2.1). Not sure why this would be the case, but the out-of-date version (as well as that of underlying dependencies) seems to be preventing them from installing up-to-date versions of certain R packages required for the homework. How can we advise these students to bring their R sessions up-to-date? 

### Environment & setup

R DataHub (within RStudio session)

Example `sessionInfo()` output from an affected student:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1         stringr_1.4.0         dplyr_1.0.8          
 [4] purrr_0.3.4           readr_2.1.2           tidyr_1.2.0          
 [7] tibble_3.1.6          ggplot2_3.3.5         tidyverse_1.3.1      
[10] medicaldata_0.2.0     lmtest_0.9-39         zoo_1.8-9            
[13] sandwich_3.0-1        marginaleffects_0.3.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8        lubridate_1.8.0   lattice_0.20-45   assertthat_0.2.1 
 [5] digest_0.6.29     utf8_1.2.2        R6_2.5.1          cellranger_1.1.0 
 [9] backports_1.4.1   reprex_2.0.1      evaluate_0.15     httr_1.4.2       
[13] pillar_1.7.0      rlang_1.0.2       readxl_1.3.1      rstudioapi_0.13  
[17] data.table_1.14.2 checkmate_2.0.0   rmarkdown_2.12    munsell_0.5.0    
[21] broom_0.7.12      compiler_4.1.2    modelr_0.1.8      xfun_0.30        
[25] pkgconfig_2.0.3   htmltools_0.5.2   insight_0.16.0    tidyselect_1.1.2 
[29] fansi_1.0.2       crayon_1.5.0      tzdb_0.2.0        dbplyr_2.1.1     
[33] withr_2.5.0       grid_4.1.2        jsonlite_1.8.0    gtable_0.3.0     
[37] lifecycle_1.0.1   DBI_1.1.2         magrittr_2.0.2    scales_1.1.1     
[41] zip_2.2.0         cli_3.2.0         stringi_1.7.6     fs_1.5.2         
[45] xml2_1.3.3        ellipsis_0.3.2    generics_0.1.2    vctrs_0.3.8      
[49] openxlsx_4.2.5    ottr_1.1.4        tools_4.1.2       glue_1.6.2       
[53] hms_1.1.1         fastmap_1.1.0     yaml_2.3.5        colorspace_2.0-3 
[57] rvest_1.0.2       knitr_1.37        haven_2.4.3
```

### How to reproduce

n/a

**Comment by balajialg** [comment]
@benmarafino Just wanted to confirm whether students are using the same hub as the instructional team? There multiple datahub deployments with the R image installed. For eg: Public Health hub (https://publichealth.datahub.berkeley.edu/) has R version 4.1.2 installed in its [image](https://github.com/berkeley-dsep-infra/datahub/blob/45ba733dff9a132cf75d5a0e4b03426487653b3f/deployments/publichealth/image/Dockerfile#L1) while the R hub (https://r.datahub.berkeley.edu) has version 4.2.1 installed in its [image](https://github.com/berkeley-dsep-infra/datahub/blob/45ba733dff9a132cf75d5a0e4b03426487653b3f/deployments/datahub/images/default/Dockerfile#L92). Can you please confirm whether the concerned hub for your course is https://publichealth.datahub.berkeley.edu/?

**Comment by benmarafino** [comment]
Thanks so much, I think that could be it! I wasn't aware that the PH DataHub had a different R version installed, and it looks like that's the one that students were using. We'll advise them to use the R DataHub for the assignment. Thanks again.

**Comment by dsconnell** [comment]
Sorry to re-open an old issue... is this the correct place to request a newer version of R on https://publichealth.datahub.berkeley.edu/ ? I'm working on a class starting at August and those instructors requested a more modern installation for that hub.

**Comment by balajialg** [comment]
@dsconnell Sure - I will create an internal ticket for this request so that we can track it till it gets completed. Do you only require an R version upgrade (How about R studio etc..)? What is the version of R you are looking at? The latest version in CRAN seems to be version 4.3.0 - https://cloud.r-project.org/.

Which course are you requesting this upgrade for (as the public health hub is used across multiple courses)? We might need to reach out to other instructors who also use this hub to verify whether they are comfortable with this version upgrade.

**Comment by wwheeler6** [comment]
@balajialg I'm one of the lecturers working with @dsconnell on the R for Public Health Course (PHW 251).  An update to the RStudio/Posit version would be great to have also!  And we may use Quarto during the course, so if that requires additional dependency updates, that would be great as well.

It looks like only just yesterday 4.3.0 was superseded as the latest version by 4.3.1! R 4.3.0 appears to have been a pretty major update, so it would probably be good to go with at least that version. I can't actually find any 4.3.1 release notes online yet, so can't tell if it's bug fixes or something more substantial.  Could you survey other courses if they are comfortable with 4.3.1 or 4.3.0 while we wait for more documentation on 4.3.1?

**Comment by balajialg** [comment]
@wwheeler6 Thanks for setting the context. I will do outreach with other instructors to confirm whether they are aligned with 4.3.0/4.3.1 R upgrade. 

Yes - Enabling quarto will involve configuration changes as done previously for [Stat 20 hub](https://github.com/berkeley-dsep-infra/datahub/pull/3611/commits/05c3751b5a713d0261bbd15aabaa70d87e06ddf4). Incase if you want to test the quarto related changes then you can access https://stat20.datahub.berkeley.edu/ which has R version 4.2.1, RStudio version 2022.07 and quarto enabled. We can target a similar workflow with latest changes for Public Health hub once we get the instructor buy in.

**Comment by wwheeler6** [comment]
Great thanks @balajialg - sounds good.  It doesn't look like 4.3.1 has any substantial bug fixes, so either R version 4.3.0 or 4.3.1 will work for us.

Would it be possible to also update RStudio/Posit to version RStudio 2023.03.1?  That's the second to most recent update https://docs.posit.co/ide/news/#rstudio-2023.03.1

**Comment by balajialg** [comment]
Thanks @wwheeler6! We should be able to do this version upgrade. I will circle back once other instructors using the hub are okay with this upgrade

**Comment by wwheeler6** [comment]
@balajialg Do you have any estimate about when you'd be able to install these upgrades on the public health data hub?  We're starting to do some recording for the Fall semester and it would be great to be able to run with the upgraded R and Posit if we could.

**Comment by balajialg** [comment]
@wwheeler6 PH 142 instructors accepted the proposal to upgrade to the recent version of R and R Studio in Public Health hub. I should be able to get this upgrade done early next week at the latest? Does that sound good?

**Comment by wwheeler6** [comment]
@balajialg Wonderful!  That sounds great, thanks!

**Comment by balajialg** [comment]
@wwheeler6 Latest R and R studio version upgrade (in addition to enabling quarto) will be done in the staging hub (https://publichealth-staging.datahub.berkeley.edu/) in the next 30-40 minutes. Can you please test the changes before EOD and give us a confirmation whether your usual workflow is working as expected?

**Comment by balajialg** [comment]
Running `quarto check` in the staging hub's terminal provided the following results,

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /usr/lib/rstudio-server/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6 (Conda)
      Path: /srv/conda/bin/python
      Jupyter: 5.3.1
      Kernels: python3, ir

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

RStudio Version in the staging hub
![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/0da5e78a-2e43-4a71-a851-568627820c31)

**Comment by wwheeler6** [comment]
@balajialg A couple of us did some brief testing and everything seems to be in order, so I think we're okay moving that to the production environment.  Thanks so much, this is really great!

**Comment by balajialg** [comment]
@wwheeler6 Great, thanks for the update
