### ISSUE TITLE
Replace IPython-SQL with JupySQL in Data 100, Stat159 and Datahub

### ISSUE THREAD

**Issue by idomic** [berkeley-dsep-infra/hubs#4528]
### Bug description

It might make more sense to update from `ipython-sql` to `Jupysql`.
Adding [more context on depracation](https://github.com/catherinedevlin/ipython-sql#legacy-project).

This transition should help you avoid compatibility issues and get access to newer features.
Just switching the name and version as backward compatibility is on.

### Environment & setup

NA

### How to reproduce

NA

**Comment by balajialg** [comment]
Hey @idomic Are you affiliated to UC Berkeley or the Datahub project by any chance? Can you pls provide more details about what you outlined?

**Comment by idomic** [comment]
> Are you affiliated to UC Berkeley or the Datahub project by any chance?

I'm not. I'm part of the maintainers of JupySQL.
To clarify, `ipython-sql` is deprecated, we're maintaining a fork of it, and switching the dependencies will allow you to stay up to date with new features, avoid old bugs etc.

**Comment by shaneknapp** [comment]
@idomic thanks for the heads up!  we'll get this sorted soon.

to save us some time, are there any user-facing changes or is `JupySQL` a drop-in replacement for `ipython-sql`?

**Comment by shaneknapp** [comment]
> to save us some time, are there any user-facing changes or is `JupySQL` a drop-in replacement for `ipython-sql`?

derp, i re-read your initial post and saw backwards-compatibility is on.  :)

**Comment by balajialg** [comment]
@fperez @yanlisa @rohanjha123 Just a FYI, [Ipython SQL]( https://github.com/catherinedevlin/ipython-sql#legacy-project) is a legacy project. Pls let us know if you want to explore JupySQL next semester.

Thanks for the heads up @idomic.

**Comment by fperez** [comment]
Oh, I wasn't aware of [JupySQL](https://github.com/ploomber/jupysql), thanks for the pointer! Obviously I'd much rather use a maintained project, so I'm all for exploring it and moving forward with an updated alternative.

**Comment by rohanjha123** [comment]
Thanks for the tag and looking into this! I think ideally, the summer TAs for data 100 would test the upgrade from ipython SQL to JupySQL in data100.datahub-staging. If everything works, they would merge it and have the summer data 100 SQL assignment run using JupySQL

**Comment by balajialg** [comment]
Thanks @fperez and @rohanjha123. Plan sounds great.

**Comment by edublancas** [comment]
Hi there, I'm also from the team that maintains JupySQL,

The only API change we've introduced is that we dropped the old SQL parametrization via `$var`, `{var}`, and `:var` (it produced some errors when parsing certain SQL scripts) in favor of `{{var}}`, everything else remains compatible.

We are always mindful of breaking API changes so we only do them when absolutely necessary!

**Comment by balajialg** [comment]
Closing this issue as it got done
