### ISSUE TITLE
UC Berkeley Archive Data Retrieval - Aditya Dwivedi

### ISSUE THREAD

**Issue by aldwivedi** [berkeley-dsep-infra/hubs#4554]
### Your UC Berkeley Email Address

aldwivedi@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/aldwivedi.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent!

**Comment by aldwivedi** [comment]
Hi,

Thank you for addressing this. How may I access the .tar archive file
within R? Is there documentation as I cannot get the archive or utils
library to open the file up, and it is a large file as well. I'm a little
rusty and would appreciate being pointed in the right direction. Thanks so
much!

Best,
Aditya

**Comment by balajialg** [comment]
[@aldwivedi](https://github.com/aldwivedi) Is this Datahub specific issue or more about you figuring out ways to untar archive files in R. If it is the latter, I would recommend taking a look at this documentation for untaring the archive files within R - https://riptutorial.com/r/example/15093/extracting-files-from-a--tar-archive?

Ref: http://web.mit.edu/r/current/lib/R/library/utils/html/untar.html
