### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by harivall** [berkeley-dsep-infra/hubs#4577]
### Your UC Berkeley Email Address

--

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/harivall.tar.gz

gs://ucb-datahub-archived-homedirs/2022-3-fall/eecs/harivall.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent.
