### ISSUE TITLE
Retrieving old EECS 16a/b lab files for reference

### ISSUE THREAD

**Issue by haikdc** [berkeley-dsep-infra/hubs#4595]
### Your UC Berkeley Email Address

haik@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/eecs/haik.tar.gz

**Comment by haikdc** [comment]
Hi, I just realized that this is for the wrong class (I retook eecs16b the semester after this). Do you have any suggestions as to how I should attain info for my eecs16a/b classes?

**Comment by cesarvh** [comment]
@balajialg Any suggestions on the above comment?

**Comment by balajialg** [comment]
@haikdc Which hub did you use for your coursework? https://eecs.datahub.berkeley.edu or https://datahub.berkeley.edu/? @cesarvh Will be able to send the entire zip of the hub's content if you can highlight the name of the hub correctly.

**Comment by balajialg** [comment]
Closing this issue as there is no response from @haikdc for a month!
