### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by Nolan3036** [berkeley-dsep-infra/hubs#4599]
### Your UC Berkeley Email Address

chihung_shu@berkeley.edu

### Link to Your Datahub Folder

I cannot log in to my Datahub, could you help me on this? I attach the event log screenshot below. Thank you!
<img width="789" alt="Screenshot 2023-05-30 at 7 43 28 AM" src="https://github.com/berkeley-dsep-infra/datahub/assets/89554345/03364e6f-ae95-4caf-8fb1-45905a118ad4">

**Comment by balajialg** [comment]
@Nolan3036 What is the url of the hub you are trying to launch? It might be taking more time since the server spawn takes some time. Can you try launching it again, wait for few minutes and then see if we can access it?

**Comment by balajialg** [comment]
Closing this issue as there is no response from @Nolan3036 for a month!

**Comment by Nolan3036** [comment]
Hi, I'm sorry I didn't see the message. I tried waiting for it. But eventually, It's been 10 min, and it showed Spawn failed: Timeout.

**Comment by Nolan3036** [comment]
https://datahub.berkeley.edu/hub/spawn-pending/chihung_shu
this is the url

**Comment by Nolan3036** [comment]
Hello, can I follow up on this, thank you!

**Comment by balajialg** [comment]
@cesarvh Can you please look into this request?

**Comment by balajialg** [comment]
Hey, @Nolan3036 Can you please send a link that looks similar to this gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/xxx.tar.gz. This is stored in the WHERE_ARE_MY_FILES.txt file in your home directory. Without that URL it is going to be difficult to recover your files

**Comment by Nolan3036** [comment]
Hi, the problem is I cannot get in to my home directory, as I mentioned above. should I open the thread other places?

**Comment by balajialg** [comment]
@Nolan3036 Can you please share the URL of your hub?

**Comment by balajialg** [comment]
@Nolan3036 Thanks. Let me look into this

**Comment by balajialg** [comment]
@Nolan3036 

@shaneknapp just deployed a fix for this issue. Can you please confirm whether you are able to login to your hub now?

**Comment by balajialg** [comment]
@Nolan3036 You should be able to launch your server now. By any chance, did you use `pip install --user` to install python libraries? It seems like you have installed python libraries in the home directory which led to the problem you faced currently. 

Also, Please open a [bug report](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=felder%2Cbalajialg%2Cshaneknapp&labels=bug&projects=&template=bug_report.yml) for an issue like this in the future. Your files are not archived currently. (Thanks @ryanlovett and @shaneknapp for fixing this issue)
