### ISSUE TITLE
Request my old files stored in AstroDatahub

### ISSUE THREAD

**Issue by ellietmak** [berkeley-dsep-infra/hubs#4647]
### Your UC Berkeley Email Address

ellietylermak@berkeley.edu

I can't even open my astrodatahub to get the link to my datahub folder, it would be great to get access to screenshots of my files from when I took the Astronomy Data Lab and it was required to use astrodatahub

### Link to Your Datahub Folder

n/a?

**Comment by balajialg** [comment]
Thanks for reaching out @ellietmak! Sorry that you are not able to access your data present in the Astro hub currently. Astro hub got decommissioned during Sp 23 as it was not used for instructional purposes. We are planning to revive the Astro hub during Fall 23 based on instructor Josh Bloom's plan. Can we get back to you in a month with regards to reviving your data?

**Comment by balajialg** [comment]
Communication happening via email!
