### ISSUE TITLE
Request more RAM for Data 100 Summer 2023

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4685]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**
Data 100 Hub (data100.hub.berkeley.edu)

**Which class is this request for?**
2023 Summer, Data 100

**What is the Academic Guide URL for this class?**
https://classes.berkeley.edu/content/2023-summer-data-c100-001-lec-001

**What is the bCourses URL for this class?**
https://bcourses.berkeley.edu/courses/1525605

**How many students do you expect in this class?**
160

**How much RAM per user is needed?**
4GB

**Why does this class need this much RAM?**
Lab 3 contains a lot of tests and the memory usage spikes up to around 3.01GB.

**By what date (MM/DD) do you want this request to be fulfilled?**
Ideally, we would want it to be increased as soon as possible, but by the end of this week should be fine (06/30).

**Any additional information we should know about?**
We can reduce RAM to default (2GB) after Wednesday (July 5th).

**Comment by balajialg** [comment]
Closing this issue as it got resolved!
