### ISSUE TITLE
Request upgrade to otter 4.3.4

### ISSUE THREAD

**Issue by sean-morris** [berkeley-dsep-infra/hubs#4687]
### Package Name

otter-grader

### Hub details

- Hub: Datahub
- Language: Python

### Course Name

Data 8

### Semester Details

They need this so the staff can generate assignments on the datahub.

### Installation Deadline

Nothing specific -- I have an alternate solution in place. 

I will put in another request when Otter 4.4.0 is released but right now I don't see a timeline for this release and the staff needs the fixes in the 4.3.4.

**Comment by balajialg** [comment]
Closing this issue as it got resolved

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/9926e566-2044-4bc5-ba89-b874efdb1f03)
