### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by veronicacister** [berkeley-dsep-infra/hubs#4696]
### Your UC Berkeley Email Address

veronicacister@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/data100/veronicacister.tar.gz

gs://ucb-datahub-archived-homedirs/2022-3-fall/data102/veronicacister.tar.gz

**Comment by cesarvh** [comment]
Signed URL Sent!
