### ISSUE TITLE
Admin access for PH142 Introduction to Probability and Statistics in Biology and Public Health

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#4701]
### Your Name

Paula Marquez

### Affiliated Course Name

Public Health 142

### Role

TA

### Name of the Hub

publichealth.datahub

### BCourses ID
1525581

### End Date

09/01/2023

**Comment by paulamarm** [comment]
Users are: 
mi-suk
paulamarquez
ajuarez
a_kim
hsharma
jznakato
jpiccirillo
kadame

**Comment by balajialg** [comment]
@paulamarm Closing this issue as it got resolved!
