### ISSUE TITLE
Request python package "datascience" for class Data 6

### ISSUE THREAD

**Issue by jonathanferrari** [berkeley-dsep-infra/hubs#4708]
### Package Name

datascience

### Hub details

- Hub: eecs.datahub.berkeley.edu
- Language: Python
- 

### Course Name

https://data6.org/su23/

Instructors: James Weichert, Jonathan Ferrari
Instructor of Record: Lisa Yan

### Semester Details

Summer 2023

### Installation Deadline

Ideally by Thurs July 6th (7/6), however, if that isn't possible, as soon as possible following this date.

**Comment by balajialg** [comment]
@jonathanferrari You should be able to test datascience package in EECS hub.

**Comment by jonathanferrari** [comment]
Thanks, @balajialg, @felder, and @shaneknapp for your amazing help, as always!
