### ISSUE TITLE
EECS 127 old projects

### ISSUE THREAD

**Issue by Victorcr1610** [berkeley-dsep-infra/hubs#4721]
### Your UC Berkeley Email Address

My Old projects

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/victorhcru-5f1213.tar.gz

**Comment by cesarvh** [comment]
@Victorcr1610 Please include your Berkeley e-mail so I can send the link. Thanks!

**Comment by cesarvh** [comment]
Closing since no response
