### ISSUE TITLE
Adding admins on data100-jl4 hub

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4747]
### Your Name

Mihran Miroyan

### Affiliated Course Name

Data 100: Principles and Techniques of Data Science

### Bcourses Id

1525605

### Role

Head TA

### Name of the Hub

data100-jl4

### End Date

08/12/2023 (end of semester)

We want to grant teachers/instructors and TAs admin access on the new hub for assignment testing (higher RAM limit) and submission debugging.

**Comment by shaneknapp** [comment]
i merged this to `staging` and in ~7m you'll be able to test this out!

**Comment by balajialg** [comment]
Closing this issue as it got resolved
