### ISSUE TITLE
Request more RAM for Data 100

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4752]
Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name
Data 100 JL4 Hub (data100-jl4.datahub.berkeley.edu)

Which class is this request for?
2023 Summer, Data 100

What is the Academic Guide URL for this class?
https://classes.berkeley.edu/content/2023-summer-data-c100-001-lec-001

What is the bCourses URL for this class?
https://bcourses.berkeley.edu/courses/1525605

How many students do you expect in this class?
160

How much RAM per user is needed?
4GB

Why does this class need this much RAM?
In Project A2 students train a model, which requires more than 2GB RAM usage.

By what date (MM/DD) do you want this request to be fulfilled?
We plan to release the assignment on Monday (07/17).

Any additional information we should know about?
We can reduce RAM to default (2GB) after 07/27 (accounting for possible extensions).

**Comment by shaneknapp** [comment]
done, will merge to prod momentarily

**Comment by balajialg** [comment]
@mihranmiroyan updated that memory increase can get reverted July 29th

**Comment by balajialg** [comment]
Data 100 JL back to 2GB Ram for all users except for admin!
