### ISSUE TITLE
File Retrieval

### ISSUE THREAD

**Issue by gabewc5** [berkeley-dsep-infra/hubs#4762]
### Your UC Berkeley Email Address

gabewc@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/gabewc.tar.gz

**Comment by gabewc5** [comment]
I want access to my Data  8 Spring 22 projects please

**Comment by cesarvh** [comment]
Signed URL Sent!
