### ISSUE TITLE
[URGENT] Data Retrieval Request

### ISSUE THREAD

**Issue by jdcampuzano** [berkeley-dsep-infra/hubs#4775]
### Your UC Berkeley Email Address

jdcampuzano@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/data8/jdcampuzano.tar.gz

**Comment by jdcampuzano** [comment]
Hello. I know this process likely takes longer, around 5-10 business days as stated, but if possible I really need to access these files as soon as possible. I know this might be hard and I apologize for the inconvenience but I would greatly appreciate if we could find a way to do this sooner. Thank you very much for your attention and efforts!

Best,
Juan Diego

**Comment by balajialg** [comment]
@cesarvh Can you please look into this issue asap?

**Comment by cesarvh** [comment]
Signed URL Sent!
