### ISSUE TITLE
Request python package GraphViz for Data 100

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#4827]
### Package Name

GraphViz

### Hub details

- Hub: Data 100 JL4
- Language: Python

### Course Name

[ds100.org/su23](https://ds100.org/su23/)

### Semester Details

Summer 2023

### Installation Deadline

08/08

**Comment by shaneknapp** [comment]
any specific version, or should we pin this to the latest release?

**Comment by Dominicliu129** [comment]
Yeah the latest release 8.0.1 would be great!

**Comment by shaneknapp** [comment]
8.0.1 or 8.1.0?

**Comment by Dominicliu129** [comment]
Sorry, should be 8.1.0!

**Comment by shaneknapp** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/4829

**Comment by shaneknapp** [comment]
can't get 8.1.0 to install...  how about 8.0.3?

**Comment by Dominicliu129** [comment]
8.0.3 should be fine. Thank you!

**Comment by shaneknapp** [comment]
this is live on `staging`!

(sorry forgot to click 'comment' earlier')

**Comment by Dominicliu129** [comment]
Still shows `No module named 'graphviz'` for me on the staging hub.

**Comment by shaneknapp** [comment]
that's highly strange.  i will look in to this first thing tomorrow.

**Comment by bdsomer** [comment]
I think `graphviz` needs to be listed as a dependency under `pip`

**Comment by shaneknapp** [comment]
https://anaconda.org/conda-forge/graphviz

and from my notebook:

```
(notebook) ***@***.***:~$ conda list | grep graphviz
graphviz                  8.0.3                h2e5815a_0    conda-forge
(notebook) ***@***.***:~$ dot --version
dot - graphviz version 8.0.3 (20230418.1244)
```

i guess we also need this?
https://pypi.org/project/graphviz/

¯\_(ツ)_/¯

**Comment by shaneknapp** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/4832

**Comment by shaneknapp** [comment]
ok, i guess we need double the graphviz for your graphviz!

`staging` is deploying now...  will ping this issue when it's done.  if you could please test before EOD today as we have a lot of commits waiting to be merged/deployed to `prod` besides this one.  thanks!

**Comment by ryanlovett** [comment]
@shaneknapp If you did want to get both from anaconda, you can install the python library from https://anaconda.org/conda-forge/python-graphviz.

**Comment by shaneknapp** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/4834

**Comment by Dominicliu129** [comment]
This works for me on `staging`! Thank you so much!

**Comment by shaneknapp** [comment]
excellent!  we'll get this merged to `prod` hopefully by EOD

**Comment by shaneknapp** [comment]
it's merged!
