### ISSUE TITLE
Data 101 Hub Setup Requirements for FA 23!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4843]
# Summary
@yanlisa will be teaching [Data 101 course](https://classes.berkeley.edu/content/2023-fall-data-101-001-lec-001) using [Data 101](https://data101.datahub.berkeley.ed) hub during FA 23. 250 students will be using this hub during the duration of the semester. Data 101 will have [4 projects ](https://fa22.data101.org/) during the entire semester and all of them will involve dealing with databases (the first 3 assignments will use PostgreSQL database and the last assignment will use Mongo database). [Here](https://data101.datahub.berkeley.edu/user/balajialwar/notebooks/fa22-materials/proj/proj1/proj1.ipynb) is an example assignment from this course.

Listed below are the requirements for this course,

- [x] Students should be able to launch Postgres and Mongo db instances (Currently this is commented out in the [configs](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data101/config/common.yaml))

- [x] Create Data 101 image (Currently, it is using Datahub's [image](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data101/hubploy.yaml))

- [x] Make JupyterLab4 the default interface for Data 101 hub

- [x] Ensure that JupySql package is installed in the image

- [x] Increase the default RAM requirement to 2 GB

Course staff is planning to test the hub early next week. In addition, There will be a meeting scheduled with the GSIs to onboard them (Similar to the training with Data 100 GSIs)

Students access the data in this hub in the following way, 
a) Students will download the zipped version of the required data from Github repositories using nbgitpuller, 
b) They will unzip the file and store the data in a PostgreSQL database and 
c) Use Jupyter notebook to retrieve the data from database. 

@yanlisa believes that this process is inefficient as multiple copies of the same file exist in each user's hub. She is hoping that a long-term requirement will be to explore the idea of shared database instances (Mongo and PostgreSQL) where students can interact with the data directly (w/o downloading it to their home directories). This is something we need to explore during our internal meeting and have a discussion with Lisa during mid semester.

**Comment by shaneknapp** [comment]
edited coz i was wrong:  data101 will need it's own image, or data100's image will need to have mongodb and postgress installed.  any db config will need to be custom for data101.

i'd strongly suggest having a unique data101 image.  this is truly not a lot of work, but the devil's in the details -- especially if setting up the dbs doesn't go smoothly.

for now, we should probably be wasteful, not have shared db access and focus on just getting this done ASAP.

**Comment by shaneknapp** [comment]
fwiw, updating the data100 image was pretty simple:  https://github.com/berkeley-dsep-infra/datahub/pull/4845

`cp data100-jl4/image/* data100/image/`  :)

(and adding a line or two in `common.yaml`)

**Comment by shaneknapp** [comment]
btw @yanlisa the data101 hub's filestore instance is set to 1TiB.  do you think this will be sufficient for the course?

**Comment by balajialg** [comment]
@shaneknapp 1 TB filestore instance for 250 students amounts to around 4 GB per student which seems like a more than sufficient storage allocation but @yanlisa please clarify if I am missing something here.

**Comment by yanlisa** [comment]
Confirmed @balajialg and @shaneknapp that 1TiB is more than enough for our class.

Sounds good to have custom data101 image — would be great for us to start from whatever data100 has and then install postgres/mongo, add db config.

Confirmed that we'll try to have an onboarding meeting for Data 101 TA(s) either late next week or early week of 8/21.
Let's talk more about the shared db stuff later in the semester; it's not a requirement for projects this semester. Thank you!!

**Comment by shaneknapp** [comment]
@yanlisa here's the python environment from the data100 jupyterlab4/notebook 7 beta hub:  https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100-jl4/image/environment.yml

this was tested extensively over the summer and they're super happy with it.

the only caveat is that RTC is still not prime-time and the `jupyterlab-collaboration` package is not installed.

**Comment by shaneknapp** [comment]
> @yanlisa here's the python environment from the data100 jupyterlab4/notebook 7 beta hub: https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100-jl4/image/environment.yml
> 
> this was tested extensively over the summer and they're super happy with it.
> 
> the only caveat is that RTC is still not prime-time and the `jupyterlab-collaboration` package is not installed.

oh, the other big thing is that `ipython-sql` has been EOLed, and it's replacement is `jupysql`.  see:  https://github.com/berkeley-dsep-infra/datahub/pull/4845/files#diff-f255c76593400441de557ffefc9d672b27dc6ca2d62a3bb624481b2dbdfdeb30R92

here's the migration guide:  https://jupysql.ploomber.io/en/latest/community/vs.html

**Comment by felder** [comment]
PR #4851 re-enables mongodb and postgresql for data101 prod.  Tests of assignments in staging work ok.

**Comment by yanlisa** [comment]
@shaneknapp yes, please add `jupysql`; we'll move to that and test whether all sql magic works. Last time I tried it locally I had some difficulty with postgres meta-commands in cells with sql magic, e.g.:

```
%sql \du
```

These are the packages that need to be installed as per tutorial (we shouldn't need docker): https://jupysql.ploomber.io/en/latest/integrations/postgres-connect.html:
jupysql
pandas
pyarrow
psycopg2 (or psycopg2-binary)
pgspecial<2 (see https://jupysql.ploomber.io/en/latest/howto/postgres-install.html#installing-pgspecial)

**Comment by yanlisa** [comment]
Confirming that on my local machine, pgspecial<2 requirement (resolves to 1.13.1) will work with jupysql-0.9.0 and (most recent on pip3, preferred) jupysql-0.9.1!

**Comment by balajialg** [comment]
@yanlisa Just double checking - Is gh-scoped-creds package required for Data 101 image? 

https://github.com/berkeley-dsep-infra/datahub/blob/7facb9201cf6340e069a60bb33ad1d6d836eae1b/deployments/data100-jl4/image/environment.yml#L90?

**Comment by balajialg** [comment]
@yanlisa Seems like all the to-dos in this Github issue are done (Thanks @shaneknapp and @felder). We tested assignments 1 and 4 to test postgres db and mongo respectively. Can you please test some of these assignments and let us know if there are any issues? 

Also - Jupysql version 0.8.0 is installed in the image. Can you test whether you could install Jupysql and write your queries? I tried manually installing the Jupysql package but it failed throwing the error snapshotted below. However, `%reload_ext sql` seems to work perfectly fine

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/c77ec79e-637a-4c05-993f-c4329caf62b5)
![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/b5202a22-84ea-4939-9639-938e36e152c1)

edit: ipython-sql is not currently installed in the image which confirms that jupysql is working!

**Comment by yanlisa** [comment]
Hm, the server doesn't seem to be launching for me....now waiting 165+ seconds.
<img width="1090" alt="Screenshot 2023-08-14 at 4 01 23 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/2431764/7595a2a8-ae9c-4041-bed8-21cf1b46022a">

Update -- launched after 180 seconds. Now testing for the rest of the afternoon, will let you know end of evening about additional updates/requests. Thanks!

**Comment by shaneknapp** [comment]
when no classes are scheduled, we scale down the gcp node pool for data101 to 0 if no one is logged in.  the 180 seconds it took was due to the VM that will host your container spinning up.

this won't be an issue during the semester as we'll set a minimum of 1, and you can expect ~10 sec server spawn times.

**Comment by yanlisa** [comment]
Hello and sorry for delay! Looks like pgspecial isn't installed so proj1 meta-commands like `%sql \l` aren't working (my datahub [proj1 notebook link](https://data101.datahub.berkeley.edu/user/yanlisa/lab/tree/fa22-materials/proj/proj1/proj1.ipynb)):
<img width="544" alt="Screenshot 2023-08-16 at 9 54 47 AM" src="https://github.com/berkeley-dsep-infra/datahub/assets/2431764/f2d8f7d9-5684-4a48-9729-cd5fbb016e4a">

I tried installing with `conda install "pgspecial<2" -c conda-forge` as per jupysql [docs](https://jupysql.ploomber.io/en/latest/howto/postgres-install.html#installing-pgspecial) but it seems to be failing. Could you please install pgspecial<2 requirement (resolves to 1.13.1) on the image?

In general, do I have user permission to `conda install` or pip3 install` on our own datahub instances? Over the next few days we'll be testing jupysql 0.8.0 vs jupysql 0.9.1. Thanks!

**Comment by shaneknapp** [comment]
hey lisa!  we'll get that package added, absolutely.

you can definitely install via pip or conda.  the caveat is that once your
server stop, any changes you made to that image will go away when you next
log in.

fwiw, i also tried to install `pgspecial` via conda and it failed, but
worked fine w/pip.

**Comment by yanlisa** [comment]
Great, thank you @shaneknapp! Let me know when it's added and I can do the rest of the testing.

BTW @balajialg - I don't think `gh-scoped-creds` is needed. Thanks for checking.

**Comment by balajialg** [comment]
Thanks, @yanlisa! That's helpful. Sorry for missing the installation of pgspecial package in our earlier iteration. 

@shaneknapp for our reference,
> @shaneknapp yes, please add `jupysql`; we'll move to that and test whether all sql magic works. Last time I tried it locally I had some difficulty with postgres meta-commands in cells with sql magic, e.g.:
> 
> ```
> %sql \du
> ```
> 
> These are the packages that need to be installed as per tutorial (we shouldn't need docker): https://jupysql.ploomber.io/en/latest/integrations/postgres-connect.html: jupysql pandas pyarrow psycopg2 (or psycopg2-binary) pgspecial<2 (see https://jupysql.ploomber.io/en/latest/howto/postgres-install.html#installing-pgspecial)

**Comment by shaneknapp** [comment]
@yanlisa this is currently live on data101-staging

**Comment by yanlisa** [comment]
awesome, still testing this morning...

Based on the otter [Data 100 pull request](https://github.com/berkeley-dsep-infra/datahub/pull/4869), could you please also upgrade data101-staging to use `otter 4.4.3`? Thanks!!

P.S. -- infra TAs are assigned for Data 101 so we'll be reaching out for an onboarding session with them soon.

**Comment by shaneknapp** [comment]
> awesome, still testing this morning...
> 
> Based on the otter [Data 100 pull request](https://github.com/berkeley-dsep-infra/datahub/pull/4869), could you please also upgrade data101-staging to use `otter 4.4.3`? Thanks!!
> 
> P.S. -- infra TAs are assigned for Data 101 so we'll be reaching out for an onboarding session with them soon.

i just pushed to staging, and it will be live there in ~20m or so.

**Comment by yanlisa** [comment]
Hi, I would like to* reopen this thread. Is it possible to install `mongo` command-line?
https://www.mongodb.com/docs/manual/administration/install-on-linux/

Thanks!
Lisa

**Comment by balajialg** [comment]
Closing this issue as this is done! @yanlisa Please reopen this issue if there are pending asks or open a new issue!
