### ISSUE TITLE
Dedicated hub for gradebook app

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-dsep-infra/hubs#4847]
I've been working with some students on an app that supplements gradescope to help instructors calculate course grades for students. The app is built in shiny, and @ryanlovett had the great idea of serving it up via datahub. @balajialg help set up a data-100-instructor spa account to test for the summer data 100 and so far it seems like a terrific way to deploy the app.

Right now we're using shiny.datahub, but as the app grows, we're realizing we may want certain things on the image that are beyond what other users would want for hosting a more generic shiny app.

My question: would it make sense to set up a dedicated hub for the app with its own image? We should be able to provision it very specifically since it will have few users (perhaps a dozen or two this fall semester).

**Comment by andrewpbray** [comment]
(answered via email)

**Comment by ryanlovett** [comment]
Here was my response from a separate email thread:


> It is technically possible. There's the advantage of being able to use a slimmer image, and it could also have an app-specific name.
> 
> One disadvantage is having to maintain multiple shiny-based images. I guess if we did add jupyter to the stack, it might not actually end up slimmer.
> 
> I think if/when [the app] does end up getting used for managing a lot of student grades, then it could be the default app for its own hub. Like [it] could be installed directly in the image, rather than fetched by nbgitpuller, and [appname].datahub.berkeley.edu would automatically run it as the default app.
> 
> One thing to note is that datahub.berkeley.edu and r.datahub.berkeley.edu use the same exact singleuser image. The R hub is just configured to launch rstudio by default whereas the main datahub runs jupyter notebook. This means instructors don't have to tell students to "change /tree to /rstudio", and there's also the benefit of visibility in the hostname / hub name. So we could have a [...] hub that uses the same image as the shiny image, but launches the [...] app by default. Lots of possibilities.
> 
> In any case, my current thinking is that it is probably fine to run on shiny hub for now, but we can put it on its own hub when it is the destination for the activity.

**Comment by andrewpbray** [comment]
@shaneknapp since we chatted about this briefly today, I just wanted to loop you in to this conversation.

**Comment by shaneknapp** [comment]
i've been quietly following this issue...  ;)

**Comment by balajialg** [comment]
Closing this issue as it got done
