### ISSUE TITLE
Admin access for PH142: Introduction to probability and statistics in biology and public health

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#4860]
### Your Name

Paula Marquez

### Affiliated Course Name

Public Health 142

### Bcourses Id
1527948

### Role

ta

### Name of the Hub

publichealth.datahub

### End Date

12/30/2023

**Comment by balajialg** [comment]
@paulamarm Could you please provide the bCourses ID for PH 142? We're implementing a new procedure to designate administrators for courses starting from Summer 23. Our plan involves granting Datahub admin privileges directly to course instructors and GSIs associated with the PH142 course in bCourses. To proceed with this, we require the bCourses ID.

Ref: https://github.com/berkeley-dsep-infra/datahub/issues/4613

**Comment by balajialg** [comment]
@paulamarm Closing this github issue as this request got served. Please reopen if that is not the case.
