### ISSUE TITLE
Request package otter-grader==5.1.1 for Data 100

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4892]
### Package Name

otter-grader==5.1.1

### Hub details

Data 100

### Course Name

Data 100 Fall 2023

### Semester Details

Fall 2023

### Installation Deadline

We want to have otter 5 before the release of the first assignment (08/25).

**Comment by mmiroyan** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/4891

**Comment by shaneknapp** [comment]
merged to staging
