### ISSUE TITLE
Request otter-5.1.3 for Data 100

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4925]
### Package Name

otter-grader==5.1.3

### Hub details

Data 100

### Course Name

Data 100

### Semester Details

Fall 2023

### Installation Deadline

We would like this package to be updates as soon as possible for testing. I have also made a PR - https://github.com/berkeley-dsep-infra/datahub/pull/4924.

**Comment by balajialg** [comment]
Closing this issue as the changes got merged to prod
