### ISSUE TITLE
Request more RAM for class Data 101

### ISSUE THREAD

**Issue by frank-lsf** [berkeley-dsep-infra/hubs#4934]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Data 101, https://data101.datahub.berkeley.edu/

**Which class is this request for?**

Data 101, fall 2023

**What is the Academic Guide URL for this class?**

https://www.data101.org/

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1528038

**How many students do you expect in this class?**

300

**How much RAM per user is needed?**

4GB for course staff only.

**Why does this class need this much RAM?**

4GB for course staff is for developing course content and testing. Since we need to run Postgres, Mongo, etc. alongside the Jupyter notebooks, more RAM will be helpful.

**By what date (MM/DD) do you want this request to be fulfilled?**

8/31/2023

**Any additional information we should know about?**

We want a similar configuration as for Data 100: https://github.com/berkeley-dsep-infra/datahub/blob/524f721c8be626ce9bb2b7b7b4bd215baef805ae/deployments/data100/config/common.yaml#L63

cc @shaneknapp @balajialg

**Comment by balajialg** [comment]
@franklsf95 Do you have an admin group with instructors for this particular course in bourses?

**Comment by frank-lsf** [comment]
@balajialg yes, that would be "Teachers"

**Comment by balajialg** [comment]
@ryanlovett Despite https://github.com/berkeley-dsep-infra/datahub/pull/4969, @franklsf95 can still not see the RAM increase. What might be going wrong here?

**Comment by balajialg** [comment]
Closing this issue as this got resolved
