### ISSUE TITLE
Request python package gh-scoped-creds for Data 102

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#4935]
### Package Name

gh-scoped-creds

### Hub details

- Hub: Data 102
- Language: Python

### Course Name

Data 102: [https://data102.org/](https://data102.org/)

### Semester Details

Fall 2023

### Installation Deadline

08/29

**Comment by balajialg** [comment]
Works in staging. Needs to get deployed to prod!

**Comment by balajialg** [comment]
Closing this PR as it got merged to prod!
