### ISSUE TITLE
Add TAs as admin to the Data 102 Hub

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#4941]
### Your Name

Dominic Liu

### Affiliated Course Name

Data 102

### Bcourses Id

https://bcourses.berkeley.edu/courses/1526710

### Role

GSI

### Name of the Hub

Data 102

### End Date

End Date: 12/31/2023

Users: 
- hangxingliu@berkeley.edu
- alanjian131@berkeley.edu

**Comment by balajialg** [comment]
@Dominicliu129 Changes are merged to prod. Please reopen if there are any issues!

**Comment by Dominicliu129** [comment]
Thank you!
