### ISSUE TITLE
File Retrieval

### ISSUE THREAD

**Issue by paigemm12** [berkeley-dsep-infra/hubs#4945]
### Your UC Berkeley Email Address

paigemetayer@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/fall-2019/data100/paigemetayer.tar.gz

**Comment by balajialg** [comment]
@gmerritt I am not able to retrieve the files for this particular user. I get the following error message when I make the curl request. Can you please look into what might be going wrong here? Thanks.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: ucb-datahub-archived-homedirs/fall-2019/data100/paigemetayer.tar.gz</Details>
</Error>
```

**Comment by gmerritt** [comment]
Hi Balaji,

The method we're using gives that error when the gs://... url does not reference an actual file that exists in the archive storage. For example, if one gives it the url `gs://ucb-datahub-archived-homedirs/0000000000.tgz` as input, the error quoted above is received (`No such object...`)

The things to check at this point are that:

1. The gs:// url above is as quoted in the `WHERE-ARE-MY-FILES.txt` in the account, and
2. The .tgz actually exists in the archive storage

My understanding is that either condition is sufficient to generate the observed error message.

**Comment by gmerritt** [comment]
An additional clue:

The new version of our tool under development gives the following when attempting download link generation from the gs:// url quoted in this ticket above:

`{"response":"File \"fall-2019/data100/paigemetayer.tar.gz\"does not exist in bucket \"ucb-datahub-archived-homedirs\"","status":"error"}`

**Comment by gmerritt** [comment]
It appears to me that there simply is no "fall-2019" directory in the archive:

![screenshot_1249](https://github.com/berkeley-dsep-infra/datahub/assets/1537654/b7d49a12-8473-479f-b666-a137607a3b6c)

**Comment by paigemm12** [comment]
Does this link work?
gs://ucb-datahub-archived-homedirs/2022-2-summer/data100/paigemetayer.tar.gz

**Comment by balajialg** [comment]
@paigemm12 That seems to work. Signed URL sent. Thanks!

Thanks for looking into this @gmerritt. We can continue to talk about ways to retrieve archives from 2019/2020 in the slack
