### ISSUE TITLE
Data Retrieval for lab work done in R Spring 2022

### ISSUE THREAD

**Issue by RyanLam25** [berkeley-dsep-infra/hubs#4966]
### Your UC Berkeley Email Address

ryan_434@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/ryan-5f434.tar.gz

**Comment by balajialg** [comment]
signed URL sent!

**Comment by RyanLam25** [comment]
Hello, I got the link, but I am unsure how to use the link to retrieve my data. Any guidance?

Thank you!
