### ISSUE TITLE
Request python package X for class Y

### ISSUE THREAD

**Issue by luyi-yang** [berkeley-dsep-infra/hubs#4972]
### Package Name

library(caret) library(arules) library(arulesViz) library(h2o) library(tm) library(SnowballC) library(wordcloud) library(pROC) library(rpart.plot)

### Hub details

- Hub: Datahub
- Language: R

### Course Name

Luyi Yang, MBA247 Descriptive and Predictive Data Mining

### Semester Details

Fall 2023

### Installation Deadline

09/05

**Comment by ryanlovett** [comment]
@luyi-yang This has been fixed by #4971.
