### ISSUE TITLE
MBA247.1  Required Libraries

### ISSUE THREAD

**Issue by Montereytony** [berkeley-dsep-infra/hubs#4976]
# Summary
#
Ryan asked me to list the libraries that Instructor has in his  Docker image. 

ENV R_BASE_VERSION 4.2.3
RUN mamba install --yes \
    r-base=${R_BASE_VERSION} \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \
    'r-e1071' \
    'r-forecast' \
    'r-hexbin' \
    'r-htmltools' \
    'r-htmlwidgets' \
    'r-irkernel' \
    'r-nycflights13' \
    'r-randomforest' \
    'r-rcurl' \
    'r-rmarkdown' \
    'r-rodbc' \
    'r-rsqlite' \
    'r-shiny' \
    'r-tidyverse' \
    'r-reticulate ' \
    'r-mvtnorm' \
    'r-gdata' \
    'r-matrixcalc' \
    'r-gtools' \
    'r-mpoly' \
    'r-moments'\
    'r-tm' \
    'r-SnowballC' \
    'r-wordcloud' \
    'r-pROC' \
    'r-rpart.plot' \
    'r-arules'  \
    'r-ROSE'  \
    'r-imager' \
    'r-ggplot2' \
    'r-gtools' \
    'r-ggwordcloud' \
    'r-gridExtra' \
    'r-igraph' \
    'r-IRdisplay' \
    'r-kableExtra' \
    'r-kknn' \
    'r-ks' \
    'r-knitr'  \
    'r-lubridate' \
    'r-MASS' \
    'r-mclust' \
    'r-mvtnorm' \
    'r-neuralnet' \
    'r-NLP' \
    'r-OpenImageR' \
    'r-pracma' \
    'r-polyclip' \
    'r-psych' \
    'r-qgraph' \
    'r-readxl' \
    'r-reshape2' \
    'r-rjson' \
    'r-rpart' \
    'r-rpart.plot' \
    'r-stringr' \
    'r-SnowballC' \
    'r-tm' \
    'r-writexl'  \
    'numpy'\
    'statsmodels' \
    'r-webshot2' \
    'unixodbc'

**Comment by ryanlovett** [comment]
Thanks Tony! Can you check which ones are not already installed?

Also, we install native R packages as opposed to Ubuntu R packages. Here are examples of our R package installations:
https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/datahub/images/default/r-packages

Here is how we install MBA 247 packages:
https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/images/default/r-packages/2023-fall-mba-247.r

Note that we specify the versions to that the docker image can be built reproducibly.

**Comment by balajialg** [comment]
@ryanlovett @Montereytony Is this issue resolved or still a work in progress?

**Comment by Montereytony** [comment]
This is solved.

**Comment by balajialg** [comment]
Thanks @Montereytony
