### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by nicolebrynjo** [berkeley-dsep-infra/hubs#4988]
### Your UC Berkeley Email Address

nicole.brynjo@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/nicole-2ebrynjo.tar.gz

**Comment by balajialg** [comment]
Signed URL sent

**Comment by nicolebrynjo** [comment]
Hi @balajialg , thanks for your help. This retrieval doesn't have all the data i'm looking for it seems to end around Jul 29th. I did a thesis course over the summer in the month of August where I created and modified python notebooks that I would really like to retrieve. 
I see that the gs path I sent seems to be only for the spring. Could the files I'm looking for be in the summer folder?

**Comment by nicolebrynjo** [comment]
Maybe gs://ucb-datahub-archived-homedirs/2022-1-summer/* ?
