### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by nicolebrynjo** [berkeley-dsep-infra/hubs#4990]
### Your UC Berkeley Email Address

nicole.brynjo@berkeley.edu

### Link to Your Datahub Folder

Hi, this is a follow up request from this [original](https://github.com/berkeley-dsep-infra/datahub/issues/4988) one. The path that I provided didn't have all the data that I saved. I assume that this is because I continued work at UC Berkely over the summer of 2021 (I did an Honor's thesis) and that the files I created might be stored in another directory? Maybe something like this: 

gs://ucb-datahub-archived-homedirs/2022-1-summer/datahub/nicole-2ebrynjo.tar.gz

**Comment by balajialg** [comment]
@nicolebrynjo I am not able to find the archives based on the URL shared. Please do not attempt to construct archived file locations instead use the URL placed in Where_are_my_files.txt in your account. If you are not able to find this text file then can you confirm whether the hub you used is [https://datahub.berkeley.edu/](https://datahub.berkeley.edu/)? I am not able to find archives in your name for that specific hub. 

If you can share the exact hub URL that you used then I can try searching for your files

**Comment by balajialg** [comment]
Closing this issue as there is no response from @nicolebrynjo
