### ISSUE TITLE
Adding bcourses group for increased RAM limit

### ISSUE THREAD

**Issue by mmiroyan** [berkeley-dsep-infra/hubs#4997]
### Your Name

Mihran Miroyan

### Affiliated Course Name

Data 100

### Bcourses Id

1527426

### Role

Infrastructure TA

### Name of the Hub

data100

### End Date

end of semester

**Comment by mmiroyan** [comment]
https://github.com/berkeley-dsep-infra/datahub/pull/4996

**Comment by balajialg** [comment]
Closing this issue as the changes got merged earlier!
