### ISSUE TITLE
Students unable to knit PDFs on public health datahub

### ISSUE THREAD

**Issue by dsconnell** [berkeley-dsep-infra/hubs#4998]
### Bug description

Some students (not all!) are having issues knitting the .qmd files we assign them as problem sets in PHW251. I put more details in the "how to reproduce" section but affected users include (usernames removed by @balajialg). However, myself and GSI had no issues knitting.

These are the repeated error messages that have been reported:

`ERROR: Error executing '/home/rstudio/.TinyTeX/bin/×86_64-linux/tlmgr': Not a directory (os error 20)`

`ERROR: Error executing '/home/rstudio/.TinyTeX/bin/x86_64-linux/tlmgr': Permission denied (os error 13)`

### Environment & setup

- Hub: Public Health
- Language: R

### How to reproduce

1. Go to https://publichealth.datahub.berkeley.edu/user/lymiles/rstudio/
2. In the Files pane, go to PHW251_Fall2023 --> problem_sets --> problem set 1 --> problem_set_1_updated.qmd
3. Click the "Render" button above the source code
5. See error 
![image](https://github.com/berkeley-dsep-infra/datahub/assets/32777425/76df088f-3313-4eb5-b013-eae6137f4b2f)

She says this happens with problem_set_2_updated.qmd as well.

Other students having similar issues include suma_ramu and kevin.ru
<img width="726" alt="Screenshot 2023-09-05 at 19 21 50" src="https://github.com/berkeley-dsep-infra/datahub/assets/32777425/abe1cc92-907c-4d12-adeb-8d7e5c798c35">
<img width="792" alt="Screenshot 2023-09-05 at 19 23 04" src="https://github.com/berkeley-dsep-infra/datahub/assets/32777425/58ae588c-03cb-4fb3-88fb-e8a89c0f45fa">

As well as user hzou, who said in a later comment that is was from datahub, not local R
<img width="770" alt="Screenshot 2023-09-05 at 19 24 53" src="https://github.com/berkeley-dsep-infra/datahub/assets/32777425/3ed01c97-5287-4433-a4d5-7a8ccc87311f">

**Comment by shaneknapp** [comment]
ok, looking in to this now.

**Comment by shaneknapp** [comment]
@dsconnell firstly, we don't support user-installed packages as it makes debugging more difficult and introduces new errors.  for example, one person installed tinytex but the symlinks to the executables are completely broken.  here's one example:

`lrwxrwxrwx 1 ubuntu ubuntu       67 Sep  5 17:47 xetex-unsafe -> /tmp/Rtmp0ynbBv/home/rstudio/.TinyTex/bin/x86_64-linux/xetex-unsafe`

the directory `/tmp/Rtmp0ynbBv/` definitely doesn't exist.  :)

my bigger question is exactly what problem is being solved by installing tinytex?  if we can fix that, then students won't have to install their own (unsupported) packages.

**Comment by dsconnell** [comment]
@shaneknapp Students were trying to knit .qmd files.

**Comment by shaneknapp** [comment]
> @shaneknapp Students were trying to knit .qmd files.

yes, but if the default singleuser image is failing to let some/all students from knitting, i'd like to fix that problem first!  

we can't support custom package installations like this -- they're tricky to properly install and many parts of the system are transient, meaning things will break in interesting and different ways for all involved. 

do you have an example/screenshot of a user that's having a problem knitting on the base singleuser server image?  that'd be a great place to start.

for the folks you mentioned in this issue, my strong recommendation is for them to remove TinyTex entirely from their R environments.

lastly, but not least-ly:  when something like this breaks, please let us know via a github issue immediately!  

please communicate w/the students to not try and install these packages themselves...  that's what we're here for!

**Comment by dsconnell** [comment]
Thanks @shaneknapp !

One user (*****) who is having these issues tried uninstalling tinytex using `[and](tinytex::uninstall_tinytex())` and got this error

`Error in root_dir(normalizePath(path), "..", "..", "..") : 
  /usr/share/texlive does not seem to be the root directory of TeX Live (no "bin/" dir under it)`

To try to debug she tried `tinytex::tinytex_root()` and got an `Error in root_dir` message. When someone else who can knit qmds successfully gets `“/home/rstudio/.TinyTex”` with that command.

Is there a way to reset a user to a "base singleuser server image" to see if they have the same issues? m.adee (GSI) is willing to do this to help figure this out.

**Comment by shaneknapp** [comment]
> Thanks @shaneknapp !
> 
> One user (*****) who is having these issues tried uninstalling tinytex using `[and](tinytex::uninstall_tinytex())` and got this error
> 
> `Error in root_dir(normalizePath(path), "..", "..", "..") : /usr/share/texlive does not seem to be the root directory of TeX Live (no "bin/" dir under it)`
> 
> To try to debug she tried `tinytex::tinytex_root()` and got an `Error in root_dir` message. When someone else who can knit qmds successfully gets `“/home/rstudio/.TinyTex”` with that command.
> 
> Is there a way to reset a user to a "base singleuser server image" to see if they have the same issues? m.adee (GSI) is willing to do this to help figure this out.

every student actually gets the 'base default image', but what we could do is stop the student's server,. and then delete the homedir on filestore.  once they log back in, they will have a freshly-minted and clean environment.

**Comment by dsconnell** [comment]
@shaneknapp cool can you do that for user ****** ? She's a GSI in our course that will test this out.

**Comment by shaneknapp** [comment]
> @shaneknapp cool can you do that for user ****** ? She's a GSI in our course that will test this out.

done!  i backed up her homedir, so if she wants it back i can just do that.

**Comment by shaneknapp** [comment]
> > @shaneknapp cool can you do that for user ****** ? She's a GSI in our course that will test this out.
> 
> done! i backed up her homedir, so if she wants it back i can just do that.

oh, she'll definitely need to log out+restart her server for this change to take place.

**Comment by dsconnell** [comment]
Here's her report after reset:

> I immediately ran code to render a .qmd as PDF (problem set 1) and it worked still with no issues (no install of tinytex or other packages, etc.). However, I can also now verify that TinyTeX is installed in public health datahub already, so students possibly installing that shouldn’t have made a difference.

> I can now also confirm that if they ran the code I gave the students for local tinytex install (install.packages("tinytex")) or updating/reinstalling (tinytex::reinstall_tinytex()), it does not break the ability to render in datahub. However, the reinstall code does give me an error message now.

![Screenshot 2023-09-14 at 12 23 34 PM](https://github.com/berkeley-dsep-infra/datahub/assets/32777425/837c82d2-d32f-454c-8853-23c3686e94de)

Can we test this with the other GSI as well? Please delete the homedir for user ***** (with a backup to restore later). Thanks!

**Comment by shaneknapp** [comment]
good to hear!

regarding the next user to test, i've backed up their homedir.

regarding users manually installing tinytex (or other packages), this is something we do not support and i'm not surprised to see that error.  :)

**Comment by dsconnell** [comment]
Resetting worked for that user, she can now knit qmd files to PDF! Some of our students probably need to be reset in the same way now. I will collect a list and get back to you. Thank you for your help!

**Comment by balajialg** [comment]
Closing this issue for now. @dsconnell Please reopen if you have more inputs!
