### ISSUE TITLE
Request more RAM for DEMOG 180: Social Networks

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#5004]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Datahub (datahub.berkeley,edu)

**Which class is this request for?**

DEMOG 180: Social Networks

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-fall-demog-180-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1528163

**How many students do you expect in this class?**

84

**How much RAM per user is needed?**

5 GB

The default is 1GB of RAM per student.

**Why does this class need this much RAM?**

This course is using datasets that are larger than what the 1 GB mem instance can support. Students are also running simulations and network analyses over the course of the semester with similar requirements. 

**By what date (MM/DD) do you want this request to be fulfilled?**

By weeks end (9/8) ideally but understand that this is short turnaround. Happy to work with you on this. 

**Any additional information we should know about?**

Thank you!

**Comment by balajialg** [comment]
@wrathofquan I am closing this issue as the request got resolved but please reopen if there are any issues.
