### ISSUE TITLE
Access to Archived JupyterNotebook

### ISSUE THREAD

**Issue by ByThaoNguyen** [berkeley-dsep-infra/hubs#5012]
### Your UC Berkeley Email Address

thao.ng@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/thao-2eng.tar.gz

**Comment by balajialg** [comment]
Signed URL sent

**Comment by ByThaoNguyen** [comment]
Hi Balaji,

Can you please resent me the URL? I couldn't access it.
