### ISSUE TITLE
Increase compute resources for Course EE 120 between Thursday 9/14 through Friday 9/15

### ISSUE THREAD

**Issue by edwardneo** [berkeley-dsep-infra/hubs#5024]
### Course Name

https://classes.berkeley.edu/content/2023-fall-eleng-120-001-lec-001

### Detailed Requirements

Deadline for Compute Intensive Assignment -- Lab 1

### Semester Details

Yes

### Request Deadline

Thursday 9/14 through Friday 9/15

**Comment by balajialg** [comment]
@edwardneo, Are there specific times when you want the increased compute resources on both days? This will help us in adding calendar events. Also, Wanted to confirm whether EE 120 is using the EECS hub.

**Comment by balajialg** [comment]
@edwardneo How was students' experience during Lab1 assignments last week? Any hiccups despite adding the calendar event?

Closing this issue as it is resolved

**Comment by edwardneo** [comment]
@balajialg Sorry I missed this again -- we generally have our labs due on Thursday, with a late deadline on Friday, so we get a lot of submissions on those days, and some parts of our labs are computationally heavy. There is no specific time on either of the days. We are using the EECS hub for our lab assignments!

I'm not sure what you mean by calendar event, but we had no hiccups! This could possibly be because Lab 1 is less computationally intensive than future labs. My head TA notes from previous semesters note that I should request increased compute resources on all lab due dates, especially for lab 3, so I'm not personally knowledgable about what hiccups would look like, but I didn't get any emails from students!

Thanks for the help!

**Comment by balajialg** [comment]
@edwardneo Can you tell us the dates you have compute-intensive assignments in the upcoming weeks? We will add a calendar event to our [calendar-based auto scaler](https://docs.datahub.berkeley.edu/en/latest/admins/howto/calendar-scaler.html) that will allocate more resources during the times you want resources to be high (basically when student activity in the EECS hub is high).

**Comment by edwardneo** [comment]
@balajialg Sure! I only have tentative dates for now, but most of these should be accurate -- I'll post a follow-up comment when I get these finalized!
Lab 2: Thursday 10/5 - Friday 10/6
Lab 3: Thursday 10/19 - Friday 10/20
Lab 4: Thursday 11/9 - Friday 11/10
Lab 5: Thursday 11/23 - Friday 11/24 (This one will most likely change)
Lab 6: Thursday 12/7 - Friday 12/8 (This one will most likely change)

**Comment by edwardneo** [comment]
@balajialg I have updated dates!
Lab 2: Thursday 10/5 - Friday 10/6
Lab 3: Thursday 10/19 - Friday 10/20
Lab 4: Thursday 11/9 - Friday 11/10
Lab 5: Thursday 11/30 - Friday 12/1

**Comment by balajialg** [comment]
Thanks @edwardneo! I have added calendar events for the mentioned dates.
