### ISSUE TITLE
Please Ignore,  I had the wrong hub.  Was:Request python package datascience for class UGBA88

### ISSUE THREAD

**Issue by Montereytony** [berkeley-dsep-infra/hubs#5035]
### Package Name

datascience

### Hub details

- Hub:  Datahub
- Language: Python
Below is the error that was reported, you may want to check to make sure statsmodels.formula.api  is also installed.

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 4
      2 from numpy import *
      3 from numpy.random import *
----> 4 from datascience import *
      5 from statsmodels.formula.api import *
      7 # Define some useful functions

ModuleNotFoundError: No module named 'datascience'

### Course Name

UGBA88

### Semester Details

2023 Fall Term

### Installation Deadline

Class is active right now.

**Comment by ryanlovett** [comment]
I found out from @Montereytony over email that this was not on any of the datahubs.
