### ISSUE TITLE
Request python package PyMC for Data 102

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#5037]
### Package Name

PyMC

### Hub details

- Hub: Data 102
- Language: Python

### Course Name

[https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001](https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001)

### Semester Details

all future semesters since the old pymc3 library is deprecated

### Installation Deadline

9/19 but the sooner the better

**Comment by balajialg** [comment]
@Dominicliu129 We are running into a package conflict similar to #4953. I think we need to isolate Data 102 image from the main Datahub image so that we can do these sorts of installs. Need the compiled list of packages for Data 102 as requested in #4953

```
Installed `pymc-base==5.8.1` as `pymc` package needs this

Installed `icu>=68.1,<69.0a01 and `pytensor-base==2.16.1` as  pymc-base needs this

Encountered problems while solving  - package pymatgen-2022.0.11-py39h1a9c180_0 requires numpy >=1.21.1,<2.0a0, but none of the providers can be installed
  - package pytensor-base-2.16.1-py39h3417b97_0 requires pypy3.9 >=7.3.12, but none of the providers can be installed

Encountered problems while solving:
  - package pytensor-base-2.16.1-py39hddac248_1 requires numpy >=1.22.4,<2.0a0, but none of the providers can be installed
  - package fenics-2019.1.0-py39hcaacaa7_37 requires fenics-dolfin 2019.1.0 py39hf7d29c8_37, but none of the providers can be installed

Encountered problems while solving:
  - package shapely-1.8.0-py39hc7dd4e9_1 requires geos >=3.10.0,<3.10.1.0a0, but none of the providers can be installed
  - package nodejs-16.10.0-h73e1104_1 requires icu >=68.1,<69.0a0, but none of the providers can be installed

Encountered problems while solving:
  - package cartopy-0.21.0-py310hcda3f9e_0 requires geos >=3.11.0,<3.11.1.0a0, but none of the providers can be installed
  - package qt-main-5.15.8-hc47bfe8_16 requires icu >=73.2,<74.0a0, but none of the providers can be installed
  - package pytensor-2.8.10-py311h00c38a7_3 requires python >=3.11,<3.12.0a0, but none of the providers can be installed
```

**Comment by Dominicliu129** [comment]
Hi Balaji, here's a list of packages Data 102 currently uses (minus pymc3==3.11.2)

```
matplotlib==3.4.3
numpy==1.21.5
pandas==1.3.5
seaborn==0.11.2
scipy==1.7.3
statsmodels==0.12.2
ipywidgets==7.6.5
Jinja2==2.11.2
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server-proxy==1.2.0
jupyter-telemetry==0.1.0
jupyterhub==1.1.0
jupyterlab==2.1.3
jupyterlab-server==1.1.5
MarkupSafe==1.1.1
nb2pdf==0.5.1
nbconvert==5.6.1
nbformat==5.0.4
nbgitpuller==0.8.0
nbpdfexport==0.2.1
nbresuse==0.3.3
otter-grader==4.2.0
scikit-learn==1.1.1
```

Is this what you are looking for? Let me know if you need anything else!

**Comment by balajialg** [comment]
@Dominicliu129 Yes, thanks. Can we upgrade Python to 3.11? Also, most of the packages are not the latest versions. I am planning to upgrade the packages to the latest version. Do you have any reservations?

**Comment by balajialg** [comment]
@Dominicliu129 @alanjjian This is the final list of packages that have been added to the Data 102 image. Can you confirm whether you all are okay with it?

```
- python==3.11.0
- git==2.39.1
- jupyter-resource-usage==1.0.0
- jupyterlab==4.0.4
- jupyterlab-favorites==3.0.0
- jupyterlab_server==2.23.0
- jupyterlab_widgets==3.0.8
- jupyter_server==2.7.0
- nbgitpuller==1.1.1
- notebook==7.0.2
- ipywidgets==8.0.7
- jinja2==3.1.2
- markupsafe==2.1.3
- matplotlib==3.7.1
- numpy==1.24.2
- nbformat==5.9.2
- nbresuse==0.4.0
- otter-grader==4.2.0
- pandas==2.0.2
- pandoc==3.1.3
# data102, Fall 2023, https://github.com/berkeley-dsep-infra/datahub/issues/5037
- pymc==5.8.1
- scikit-learn==1.2.2
- scipy==1.10.1
- seaborn==0.12.2
- statsmodels==0.14.0
- pip
- pip:
  # - -r infra-requirements.txt
  - ipywidgets==8.0.7
  # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
  # - jupyter_collaboration==1.0.1
  - jupyterhub==4.0.2
  - nbconvert==7.6.0
  - gh-scoped-creds==4.1
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
```
The PR (#5054) to isolate the image is waiting to be merged. If you guys give a heads up then we can merge it immediately.

**Comment by Dominicliu129** [comment]
Looks good to me! Will we be able to test the environment on staging?

**Comment by balajialg** [comment]
@Dominicliu129 Yes, you can test this PR hub in staging in another 30-40 minutes. Please restart your server when you plan to test this PR in the staging hub - https://data102-staging.datahub.berkeley.edu/

Please try to test this PR in the next few hours as these changes will block merges to prod.

**Comment by Dominicliu129** [comment]
We tested it on a few lab assignments and this works fine. This should be good to merge into prod.

We might need the `bambi` package for Bayesian GLMs since PyMC GLM is deprecated in the new version, but we will submit another request once that comes up.

Thank you so much!
