### ISSUE TITLE
Request more RAM for class Data 102

### ISSUE THREAD

**Issue by alanjjian** [berkeley-dsep-infra/hubs#5038]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Data 102 Hub (data102.datahub.berkeley.edu)

**Which class is this request for?**

2023 Fall, Data 102

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1526710

**How many students do you expect in this class?**

255

**How much RAM per user is needed?**

4GB (class currently has 2gb per student)

**Why does this class need this much RAM?**

Our next lab leans heavily on PyMC3 which uses a lot of sampling. When students run the autograder, it can reach upwards of 3.5gb of space.

**By what date (MM/DD) do you want this request to be fulfilled?**

09/17 or the morning of 09/18 would be ideal! The lab is going to be released tonight.

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@alanjjian Thanks. Do you have a deadline to revert this memory increase? I just created a PR (#5041) to increase the RAM

**Comment by alanjjian** [comment]
Yes! Since our homework also relies heavily on PyMC3 as well, could you revert the memory increase on Oct 3rd? That's the last day students are allowed to submit the assignments in question.

**Comment by balajialg** [comment]
@alanjjian great; changes are merged to prod. Please reopen if you can't see the changes
