### ISSUE TITLE
Adding Musescore to datahub

### ISSUE THREAD

**Issue by dzluke** [berkeley-dsep-infra/hubs#5047]
# Summary

Hello! I'm the GSI for Music 30: Computational Creativity for Music and the Arts, and we use jupyterhub for our students to run pre-made iPython notebooks for the lab portion of the class. For one lab, the students generate music and I would like for them to be able to see the score of the music they generate. To do this I use the python package [music21](https://web.mit.edu/music21/) and call the function `score.show()` which displays a musical score like so: 
![Screenshot 2023-09-19 at 11 45 13 AM](https://github.com/berkeley-dsep-infra/datahub/assets/22928303/896f2230-00ab-4e0b-92dd-2f3b31adf953)

This function works only if the user has the application ["Musescore"](https://musescore.org/en) downloaded locally on their computer. I am wondering if it is somehow possible to download this application (it's not a python library) to the students datahub instances so that they are able to see the scores in their notebooks. 

When I run the code on datahub, the following error occurs after hitting the "Generate" button. This happens because musci21 can't find an installation of Musescore:

![Screenshot 2023-09-19 at 11 55 03 AM](https://github.com/berkeley-dsep-infra/datahub/assets/22928303/1a8af974-2f0d-491b-80cc-71aec78ad25c)

Here is a github link to the iPython notebook, **the code in question is in the very last cell**: https://github.com/dzluke/Music30_Fall2023/blob/main/Lab3_Convolution_Markov/lab3.ipynb

It's hosted on datahub at this link: https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdzluke%2FMusic30_Fall2023&urlpath=tree%2FMusic30_Fall2023%2FLab3_Convolution_Markov%2Flab3.ipynb&branch=main

I'm not sure if this will be possible since Musescore is not a Python library, but I thought I would ask! Thanks in advance!

# User Stories

I want to add the application Musescore to datahub so my students can visualize musical scores in their iPython notebook

# Acceptance criteria

When the music21 function `score.show()` is run, a musical score will be displayed in the notebook

# Important information

- [Musescore](https://musescore.org/en) is an application for music notation
- [music21](https://web.mit.edu/music21/) is a Python library that allows music score visualization, and it requires a local copy of Musescore to do this
- I'm not sure if music21 uses Musescore 3 or 4. On my machine, it seems to use Musescore 3

# Tasks to complete

- [x] Add Musescore to datahub

**Comment by shaneknapp** [comment]
i'm installing `musescore` 4 and the `music21` python package.  once i get it to properly build, you'll be able to log in to the datahub staging instance and test it out.

**Comment by shaneknapp** [comment]
> i'm installing `musescore` 4 and the `music21` python package. once i get it to properly build, you'll be able to log in to the datahub staging instance and test it out.

actually, i'll be musescore 3 and music21 8.3.  i'm pushing the to `staging` now and will let you know when you can test.

**Comment by balajialg** [comment]
Audio generation seems to work in staging!

<img width="937" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/8b83ac8b-e4a9-42cc-b012-4f28f47fed90">

**Comment by shaneknapp** [comment]
i tested out this notebook on https://staging.datahub.berkeley.edu and was able to click 'generate' and make something in f-minor (my most favorite of keys):

<img width="601" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/1606572/38f7c9e6-a286-4b6b-bf3c-3f44daaa920c">

i used this redirect to pull down the repo:  https://staging.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/dzluke/Music30_Fall2023&urlpath=tree/Music30_Fall2023/Lab3_Convolution_Markov/lab3.ipynb&branch=main

you can also log in to the staging server and test.  let me know how it goes!

**Comment by shaneknapp** [comment]
@dzluke -- this is also live on datahub.berkeley.edu...  you can also test there!

**Comment by dzluke** [comment]
Wow! Thank you both so much, it works great! I wasn't even sure if this was possible, and not only did you get it working you did it in one day, amazing :)
