### ISSUE TITLE
Issue with launching terminal in Data 101 hub using Safari

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#5050]
### Bug description

@yanlisa reports that a couple of students are not able to launch terminal in the Data101 hub using the Safari browser. One another student is not able to launch the notebook using the Chrome browser. 

The calnet id of the affected students is shared over Slack.  

Message from the teaching staff,

_Just released our first project over the weekend and we're running into trouble already. Hopefully, one of you can help out. One student messaged us that his Data 101 Notebook specifically is failing to run. However, I've already gone into his server, restarted it, and I personally was able to run cells in his notebook. He also reports that he is unable to open his terminal in JupyterHub on Safari, and can't even open the notebook at all in Chrome? For now, I told him to use Jupyter classic which he reports is working fine, but unable to access terminal (which we have strongly encouraged students to do for the first question of the notebook, at least).
Since I can run his notebook perfectly fine, I'm thinking it must be a local machine issue, so I'm not sure how much you all can do, but any insight would be greatly appreciated!! Thank you!_

### Environment & setup

- Hub: Data 101 Hub
- Language: Python

### How to reproduce

1. Access the student's server
2. Launch terminal in Safari
3. Find the reported issue in snapshot

**Comment by balajialg** [comment]
Snapshot shared by @yanlisa

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/0cbdc4da-6bda-4d7c-a343-960b8289fcef)

**Comment by shaneknapp** [comment]
@yanlisa could you please ask the impacted students to share their versions of safari?

**Comment by yanlisa** [comment]
Sure thing:
Safari version is 14.1.2
Safari Version 15.3 (17612.4.9.1.8)
Mapping is on Slack.
Thanks!

**Comment by shaneknapp** [comment]
they'll need to upgrade safari to at least V16.

**Comment by balajialg** [comment]
Closing this issue for now. @yanlisa Please reopen if more students experience this issue!
