### ISSUE TITLE
Request larger database for data101

### ISSUE THREAD

**Issue by frank-lsf** [berkeley-dsep-infra/hubs#5053]
As per discussion with @balajialg , we'd like to increase the Postgres storage for Data 101, similar to what we did in https://github.com/berkeley-dsep-infra/datahub/pull/2124/commits/6d3a20613a1552fb7ad02c25d6bf984352ae405a

**Comment by balajialg** [comment]
@franklsf95 Do you have any deadline in mind for this particular request?

**Comment by frank-lsf** [comment]
@balajialg as soon as possible, thanks!

**Comment by balajialg** [comment]
@franklsf95 Thanks. @felder is currently looking into it. Is there a time period when we can do this activity without any negative impact on your instruction? 

The workflow involved is to lock out the users, delete all the PVS, and then have them re-created with 4GB sizes. There might be data loss involved if students are actively working on their notebooks while we reprovision PVCs with increased storage. Let us know!

**Comment by frank-lsf** [comment]
@balajialg @felder Actually we only need the 4GB increase for TAs; don't need to do it for all students yet.

Just ping us on Slack when you're about to lock the TAs out. It should be no problem. When do you plan to perform this reset?

**Comment by balajialg** [comment]
@franklsf95 Mostly, we plan to do this today afternoon/evening. I will give you a ping via Slack when we are doing the testing. Thanks

**Comment by balajialg** [comment]
@franklsf95 I had a good chat with @felder. The follow-up question is,

- Any reasons why you just want to increase the PVC size for TAs alone and not students? Given the fact that a couple of students faced this **exact issue** a few weeks back, it might be more sustainable to do it for all students. 
- We successfully increased the PVC size to 4 gigs for all users in the [staging hub for Data 101](data101-staging.datahub.berkeley.edu). If you give us a green signal, we can merge the changes to production.

**Comment by felder** [comment]
@franklsf95 to expand on @balajialg post further, it should be possible to do the resize of the pvcs transparently to users whether they have a server running or not.  It does *not* require deleting the existing pvc first.

**Comment by frank-lsf** [comment]
@balajialg @felder Sounds good! Let's increase it for all students and TAs. You can do it now, and ping us on Slack when it is done.

**Comment by felder** [comment]
@franklsf95 Done!  People who are currently logged in should get resized immediately.  People who are not logged in will get resized the next time they login.
