### ISSUE TITLE
Geospatial (terra, sf, and raster) package installation

### ISSUE THREAD

**Issue by AnushaPB** [berkeley-dsep-infra/hubs#5061]
### Bug description

When I try to install and load the terra package the install step works (`install.packages("terra")`), but when I run `library(terra)` I get the error:
```
Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/opt/r/terra/libs/terra.so':
libproj.so.22: cannot open shared object file: No such file or directory
```

This is also an issue for the "sf" and "raster" packages, but doesn't seem to be an issue with other packages (for example, I was able to install and load "ggpubr"and "sp")

### Environment & setup

- Hub: Datahub
- Language:  R

### How to reproduce

run `library(terra)`, `library(sf)`, or `library(raster)`

**Comment by balajialg** [comment]
@shaneknapp @ryanlovett Do you have any inputs for @AnushaPB here?

**Comment by balajialg** [comment]
Adding more inputs to this issue,

This seems to be an issue in the R hub and Dlab hub. However, running library() for all these packages doesn't return any error for [public health hub](https://publichealth.datahub.berkeley.edu/) and [Ischool hub](https://ischool.datahub.berkeley.edu/) which are rocker-based images. Both Ischool and public health hubs were recently upgraded and are pulling geospatial version 4.3.1

**Comment by shaneknapp** [comment]
we'll probably need to install some system packages via `apt` to get this
to work.  this could (rather quickly) become a non-trivial task, and we'll
need some time to experiment.

**Comment by balajialg** [comment]
Got it @shaneknapp. @AnushaPB Are you teaching a course/workshop that is affected by this issue? Is this a time-sensitive issue?

If it is for your individual use and is a time-sensitive task, can you use the https://publichealth.datahub.berkeley.edu/ for time being till the issue gets fixed in the R hub?

**Comment by AnushaPB** [comment]
Thanks for looking into this! 

I was helping a professor set up datahub for their course, but they ended up paying for posit cloud and were able to set things up there, so we are okay. 

Tag me when this issue gets resolved though, would definitely love to use the datahub in the future for instruction!

**Comment by shaneknapp** [comment]
hey @AnushaPB !  thanks for the update...  i created a pull request for this (see link above this comment), and will do some testing on our staging server.  i'll let you know how it goes.  :)

**Comment by shaneknapp** [comment]
@AnushaPB it looks like `terra` and `sf` are working:
```
> install.packages("terra")
Installing package into ‘/opt/r’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/jammy/latest/src/contrib/terra_1.7-46.tar.gz'
Content type 'binary/octet-stream' length 4133919 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

* installing *binary* package ‘terra’ ...
* DONE (terra)

The downloaded source packages are in
	‘/tmp/Rtmpg2IEvI/downloaded_packages’
> library(terra)
terra 1.7.46
> library(sf)
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE
```

however, `raster` was giving me some trouble:
```
> install.packages("raster")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("raster")
Installing package into ‘/opt/r’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/jammy/latest/src/contrib/raster_3.6-23.tar.gz'
Content type 'binary/octet-stream' length 3324897 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

* installing *binary* package ‘raster’ ...
* DONE (raster)

The downloaded source packages are in
	‘/tmp/RtmpFz4KiP/downloaded_packages’
> library(raster)
Loading required package: sp
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
```

it'd be awesome if you could log in to https://r-staging.datahub.berkeley.edu/ and do some testing yourself...  thanks!

**Comment by AnushaPB** [comment]
Works for me! Awesome, thanks!

**Comment by shaneknapp** [comment]
great!  i'll merge these to prod and these changes will be live in ~30m.  you'll need to log out and back in again if you've already got a RStudio session running to be able to do these tasks.

**Comment by AnushaPB** [comment]
Sounds good, thanks again!
