### ISSUE TITLE
PDF to HTML conversion throws "500: Internal Server Error"

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#5062]
### Bug description

In the classic notebook interface, trying to download the notebook as a PDF file through 3 different options returns a 500 error.

File -> Download As -> PDF via HTML and 
 File -> Download As -> PDF via Latex 

returns 500 error.

In the retro notebook interface, 

File ->  Save and Export Notebook as -> webpdf returns 500 error

<img width="1047" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/61cd2188-d840-423b-bdcc-c8c746ebf781">

This is impacting EPS88 students workflow

### Environment & setup

- Hub: Datahub
- Language: Python

### How to reproduce

1. Go to https://datahub.berkeley.edu/
2. Try the options listed above in classic and retro interfaces
3. Get the error message snapshotted above

**Comment by balajialg** [comment]
Running these commands seems to solve the issue,

```
!pip install nbconvert[webpdf]
!playwright install chromium
```

**Comment by shaneknapp** [comment]
was able to reproduce...  will be a mild PITA to fix but i'll get started on that today/tomorrow.

**Comment by balajialg** [comment]
@shaneknapp Yeah, I am recommending instructors to use this fix till we have a permanent solution in place 

> Running these commands seems to solve the issue,
> 
> ```
> !pip install nbconvert[webpdf]
> !playwright install chromium
> ```

**Comment by shaneknapp** [comment]
still not working, will pick this up again monday.  :\

**Comment by felder** [comment]
Noting that as part of this work, we removed the QtPDF option and tried to remove the PDF to LaTeX option.

When adding the config to disable PDF to LaTeX, the option is not removed from "Download As" menu.

See https://github.com/jupyter/nbconvert/issues/2070

**Comment by balajialg** [comment]
This is awesome work @felder! Fingers crossed about Latex functionality
