### ISSUE TITLE
Request Graphviz for Data 102

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#5068]
### Package Name

graphviz==8.0.3

### Hub details

- Hub: Data 102
- Language: Python

### Course Name

Data 102: [https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001](https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001
)

### Semester Details

End of Fall 2023

### Installation Deadline

9/27

**Comment by balajialg** [comment]
@Dominicliu129 Changes got merged to prod. Please reopen this issue if that is not the case.

**Comment by Dominicliu129** [comment]
Hmm I don't see the package on prod; still getting "Package(s) not found: graphviz".

**Comment by balajialg** [comment]
@Dominicliu129 Did you restart your server and then tried importing the package again? If not, can you try once and let me know if you still face issues.

**Comment by Dominicliu129** [comment]
Yes, I restarted my kernel before trying. For example, [this notebook](https://data102.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-102%2Ffa23-materials&urlpath=tree%2Ffa23-materials%2Flecture%2Flecture08%2FLectureEIGHTData102Fall2023.ipynb&branch=main) uses graphviz and I'm still getting `ModuleNotFoundError: No module named 'graphviz'` . 

This also does not work for me on staging.

**Comment by balajialg** [comment]
@Dominicliu129 Ok, the story is repeating like https://github.com/berkeley-dsep-infra/datahub/issues/4827#issuecomment-1670046288. I just added python-graphviz to the image and it should be merged in staging asap. I will give you a ping once it is done so that you can do the testing

**Comment by balajialg** [comment]
@Dominicliu129 Changes just got merged to staging! You can test the package in staging in few mins

**Comment by Dominicliu129** [comment]
Works for me on staging! Thank you!

**Comment by shaneknapp** [comment]
merging this to prod now!
