### ISSUE TITLE
Request python package Bambi for Data 102

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#5085]
### Package Name

bambi==0.12.0

### Hub details

- Hub: Data 102
- Language: Python

### Course Name

Data 102: [Data 102: https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001](https://classes.berkeley.edu/content/2023-fall-data-c102-001-lec-001)

### Semester Details

Fall 2023, but we expect this to be used in future semester too

### Installation Deadline

9/29

**Comment by shaneknapp** [comment]
hey @Dominicliu129!

i merged this change to staging, and i'll let you know here after the image is built and deployed.  should be about ~15m or so.

**Comment by shaneknapp** [comment]
this is live on https://data102-staging.datahub.berkeley.edu

@Dominicliu129 could you log in and see if everything works as expected?  if so, i'll merge to prod asap.

**Comment by Dominicliu129** [comment]
Works for me! Thank you!

**Comment by shaneknapp** [comment]
merging to prod now!
