### ISSUE TITLE
Increase compute resources for Data 8 between 10/11 9pm PST - 10/12 12am PST

### ISSUE THREAD

**Issue by sarsong** [berkeley-dsep-infra/hubs#5125]
### Course Name

https://classes.berkeley.edu/content/2023-fall-data-c8-001-lec-001

### Detailed Requirements

Deadline for Compute Intensive Assignment -- HW07

### Semester Details

Yes

### Request Deadline

10/11 9pm PST - 10/12 12am

Sorry that this is so last minute! We totally understand if it is not feasible to implement -- we didn't realize it was going to be a problem until the early submission deadline last night when DataHub was a bit overloaded (starting around 10pm). We will note this for future semesters to account for this accordingly.

**Comment by balajialg** [comment]
@sarsong I just added a calendar event from 9 - 11.30 PM today (updated based on a discussion with Ryan).

@shaneknapp @felder I looked at the usage data from the previous assignment and found that there were around 460 users during its peak (around 10 PM). We have assigned 4 nodes by default for the Data 8 hub. I set the calendar entry as "data8: 2" to account for the peak usage. Would you suggest increasing it to 3 or keeping it as is based on the math here?

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/746e5c13-9eef-47a4-b4db-08ccc0293348)

**Comment by shaneknapp** [comment]
@sarsong what were people experiencing?  slow logins, or were their notebooks slowing down significantly?

**Comment by sarsong** [comment]
@shaneknapp seems to be a general major slowdown, especially when exporting the notebook at the end. We introduced for loop simulations in this homework, so we think that's what's causing these issues. We pushed the early submission deadline to 2pm today, so we are starting to see an uptick of students stating that runtimes are increasing (along with lecture being 10-11am).

We think a few students are running very very long for loops, but it's hard for us to diagnose these problems on an individual level, especially since it's the first time a lot of them are being exposed to for loop simulations.

**Comment by sarsong** [comment]
a positive is that 800/1200 students have submitted the homework already! so hopefully the demand for the rest of the day will not be as high. we didn't anticipate that this many students would submit the hw early 😅

**Comment by balajialg** [comment]
@sarsong How did yesterday's submission go?

**Comment by sarsong** [comment]
@balajialg It was still a bit slow so we extended the deadline by 12 hours!

**Comment by balajialg** [comment]
@sarsong That's unfortunate. I will not close this Github issue. Whenever you face slowness-related issues in the future, feel free to share more information on this issue directly.

**Comment by shaneknapp** [comment]
@sarsong we just discovered that we were allocating users 512M - 1G ram, and most were getting 512M.  i just updated the hub config so that everyone is guaranteed 1G of ram no matter what.

the side effect of this was that instead of ~50 students per node (the actual VM that runs folks' notebooks) we were packing 100 per, which just compounded the lag.

this is fixed via:  https://github.com/berkeley-dsep-infra/datahub/pull/5133

for students to see this change, they'll need to restart their servers.

**Comment by balajialg** [comment]
Closing this issue for now. @sarsong Please reopen this issue if you have any issues!
