### ISSUE TITLE
Request python package pytorch for Data 102

### ISSUE THREAD

**Issue by Dominicliu129** [berkeley-dsep-infra/hubs#5130]
### Package Name

pytorch

### Hub details

- Hub: Data 102
- Language: Python

### Course Name

Data 102

### Semester Details

Fall 2023

### Installation Deadline

10/13 or sooner. Sorry for the short notice!

**Comment by shaneknapp** [comment]
@Dominicliu129 is there a specific version you're looking for?  the latest in conda is `2.1.0`.

**Comment by Dominicliu129** [comment]
2.1.0 would be great! Thank you!

**Comment by shaneknapp** [comment]
@Dominicliu129 tested this on `staging` and he reports that it works as advertised!  i'm about to merge to prod, closing this now as completed.
