### ISSUE TITLE
Request python package ipyleaflet for class Data 88E

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#5135]
### Package Name

ipyleaflet 

### Hub details

- Hub: 
- Datahub
- Language: 
- Python

### Course Name

Data 88E Fall 2023 Eric Van Dusen

https://classes.berkeley.edu/content/2023-fall-data-88e-001-lec-001

### Semester Details

FA23

### Installation Deadline

10/16?  class is 10/18

**Comment by shaneknapp** [comment]
deploying to staging now, and it should be ready to go for testing in ~90m

**Comment by shaneknapp** [comment]
@ericvd-ucb feel free to test this out!  when ready, i'll merge to prod.

**Comment by ericvd-ucb** [comment]
hey sorry for the slow reply - looks fine on staging to me

**Comment by shaneknapp** [comment]
cool. coz it's live on prod!  :)

**Comment by balajialg** [comment]
Closing this issue as it is done!
