### ISSUE TITLE
can't log in to my data hub

### ISSUE THREAD

**Issue by Nolan3036** [berkeley-dsep-infra/hubs#5141]
### Bug description

Hello, when I log in, it shows me the attached pics, what should I do? This is my Berkeley email: [chihung_shu@berkeley.edu](mailto:chihung_shu@berkeley.edu)
Thanks in advance!
<img width="512" alt="Screenshot 2023-10-14 at 4 10 53 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/89554345/355c4cd3-32a0-416f-8693-bee7f4cc57ee">

### Environment & setup

- Hub: 
- Language:

**Comment by balajialg** [comment]
@Nolan3036 Did you graduate already? Seems like you don't have an active affiliation to get access to bcourses (&Datahub). I would suggest emailing [bcourseshelp@berkeley.edu](mailto:bcourseshelp@berkeley.edu) to get access to bcourses which in turn will allow you to log into Datahub.

**Comment by balajialg** [comment]
Closing this issue. @Nolan3036 Please reopen it if you need additional information.
