### ISSUE TITLE
Request more RAM for class Music 30

### ISSUE THREAD

**Issue by dzluke** [berkeley-dsep-infra/hubs#5153]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Datahub (datahub.berkeley.edu)
Specific notebook that needs more RAM:
https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdzluke%2FMusic30_Fall2023&urlpath=tree%2FMusic30_Fall2023%2FLab6_SoundTypes%2Flab6.ipynb&branch=main

**Which class is this request for?**

Music 30 Fall 2023

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2023-fall-music-30-1-lec-1

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1527878

**How many students do you expect in this class?**

55

**How much RAM per user is needed?**

I'm not sure exactly, all I know is that 1GB is not enough. Perhaps 2GB would be sufficient? Feel free to use your best judgement.

**Why does this class need this much RAM?**

In of our in class labs (which will be from 10am-12pm on Monday 10/23/23), the students load multiple sound files into their notebook and perform operations on the sound files. When I've tested this in the past, it quickly goes past the 1GB limit and the kernel crashes.

**By what date (MM/DD) do you want this request to be fulfilled?**

10/23

**Any additional information we should know about?**

We only need the increase in RAM from 10/23 to 10/30. After that, the students won't be using this specific notebook anymore, and won't need the additional RAM

Thanks!

**Comment by balajialg** [comment]
@dzluke The changes will be live on https://staging.datahub.berkeley.edu/ in an hour or so. Can you log in then and see if the notebooks have 2 GB RAM allocated? If you give us confirmation, We'll merge to prod ASAP.

**Comment by dzluke** [comment]
@balajialg Confirmed I now have 2 GB RAM! Thank you!

**Comment by balajialg** [comment]
@dzluke Changes are merged to prod! Thanks for the confirmation.
