### ISSUE TITLE
Error in downloading as pdf

### ISSUE THREAD

**Issue by anthlittle** [berkeley-dsep-infra/hubs#5221]
### Bug description

My students and I (for PS 88) are having problems downloading notebooks from datahub as pdfs. When trying to download via LaTeX I am getting the following error:
500 : Internal Server Error
The error was:

nbconvert failed: Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html

I think I have had this issue before and it resolved itself when trying again later, but it has been happening all day

### Environment & setup

- Hub: 
- Language:

**Comment by felder** [comment]
This is a known issue introduced in Issue #5062 with a bug reported upstream in Issue https://github.com/jupyter/nbconvert/issues/2070

@anthlittle when converting a notebook to PDF, you should choose the option "PDF via HTML"

<img width="466" alt="Screenshot 2023-11-15 at 2 34 41 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/1211730/a9fb3be2-144c-418b-895e-d198a68bed2f">

"PDF via Latex" will be removed from the menu as soon as the upstream issue is resolved.

**Comment by balajialg** [comment]
Thanks @felder for detailing the alternative! As a policy, we want to move away from supporting the "Download PDF via Latex" option as it has historically been error-prone. We have also documented this in our instructor docs - https://ds-modules.github.io/curriculum-guide/workflow/dowload_PDF.html?highlight=download+pdf. Most instructors are comfortable using the "PDF via HTML" option. @anthlittle If there are specific reasons for choosing "PDF via latex" then please do let us know!

**Comment by anthlittle** [comment]
In the past I thought PDF via html caused problems with gradescope, but if that will work all should be good. Waiting to hear if students are able to make this work.

**Comment by balajialg** [comment]
@anthlittle The workflow to export notebooks from ipynb to PDF has changed with a recent Jupyter Notebook 7 and Lab 4 version upgrade. Please review the steps documented in the [doc](https://ds-modules.github.io/curriculum-guide/workflow/dowload_PDF.html) and reopen this issue if you have concerns with the current workflow
