### ISSUE TITLE
Urgent Help - DataHub Error 500

### ISSUE THREAD

**Issue by harshita524** [berkeley-dsep-infra/hubs#5222]
### Bug description

When I try to access datahub.berkeley.edu it just shows me Internal Server Error 500. It was working fine a few days back so I am not sure what brought about this change.

### Environment & setup

Datahub

### How to reproduce

<img width="506" alt="Screenshot 2023-11-15 at 6 00 07 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/150982387/17cfb7ad-9e08-4f3b-9249-5ca84ca3ada7">

**Comment by shaneknapp** [comment]
@harshita524 could you try again?  i was able to connect to your container and things seemed to be working...
<img width="96" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/1606572/ea168b70-3a54-4e47-96e8-da1147763b03">

ill also check our logs and see if i can find out what happened.  sorry about this!

**Comment by harshita524** [comment]
Thanks. It opens up again but when I try to export any PDF it still shows me the same error. 
<img width="1057" alt="Screenshot 2023-11-15 at 8 50 56 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/150982387/d6b54b9b-4d0c-41fd-b78a-5641f5fdb0f0">

**Comment by shaneknapp** [comment]
this is actually an upstream bug, and something that we can't directly fix right now.  more details, and how to work around this are here:  https://github.com/berkeley-dsep-infra/datahub/issues/5221#issuecomment-1813375334

**Comment by balajialg** [comment]
@harshita524 The workflow to export notebooks from ipynb to PDF has changed with a recent Jupyter Notebook 7 and Lab 4 version upgrade. Please review the steps documented in the [doc](https://ds-modules.github.io/curriculum-guide/workflow/dowload_PDF.html) and reopen this issue if you have concerns with the current workflow
