### ISSUE TITLE
Clarification about Cached RAM in Biology Hub, Request to Have it Cleared OR Increase Available RAM 

### ISSUE THREAD

**Issue by Cal19-life** [berkeley-dsep-infra/hubs#5242]
### Your Role

Student

### Affiliated Course Name

INTEGBI 134L

### Environment & Setup

- My specific Hub URL: https://biology.datahub.berkeley.edu/user/s_shastri19/tree
- Language: Bash(using Linux shell, command line)

### URL to the notebook file (.ipynb, .rmd etc..) with solutions

not in a notebook.

### How to reproduce

chmod +x run_bt2_leonberger_canFam_align.sh
./run_bt2_leonberger_canFam_align.sh

### Number of Impacted Students

1

### Severity of the Issue

High Priority

### Issue timeline

11/27/23

### Snapshots of issue

**Error output:**
Segmentation fault
(ERR): bowtie2-align exited with value 139
Bowtie2 alignment completed for ERR2750967.
Segmentation fault
(ERR): bowtie2-align exited with value 139
Bowtie2 alignment completed for ERR2750968.
Segmentation fault
(ERR): bowtie2-align exited with value 139
Bowtie2 alignment completed for ERR2759446.
Segmentation fault
(ERR): bowtie2-align exited with value 139
Bowtie2 alignment completed for ERR2764781.
Segmentation fault
(ERR): bowtie2-align exited with value 139
Bowtie2 alignment completed for ERR3339010.
All Bowtie2 alignments completed.

**According to links online, seems related to memory availability of my JupyterHub server. When I use free -h, I notice I have 12GB free, and 47 GB memory in cache. According to one website, it mentioned that typically with free memory less than 50GB, the software, bowtie2, does not run. It seems I am not able to clear memory cache on my own, hence this github post.**
[Link](https://www.biostars.org/p/279646/) to webpage with this information
[documentation of software used, bowtie2](https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#the-bowtie2-inspect-index-inspector) documentation of the software I am using, if it is of any use.

### Additional comments

**Deadline to fix:** Would be nice to have some clarity on this by 12/1/23

**MAIN REASON I MADE THIS POST: Just seeking clarity if it is wise to clear my cached memory, and perhaps permission(if the consequences aren't terrible). Open to suggestions you have about solutions, including increasing available RAM**

**If it is useful, I have copied and pasted the bash script which, when run via the code I pasted above, generates the error:**

\#!/bin/bash

output_directory="/home/jovyan/fall2023/final_project_stuff/bt2_alignment_data/leonberger_canFam6_0"
met_file="${output_directory}/metrics_0"
reference_genome="/home/jovyan/fall2023/final_project_stuff/reference_seq_data/bowtie2_index_canFam6/dogCanFam6"  
#full path to bowtie2 canFam index: /home/jovyan/fall2023/final_project_stuff/reference_seq_data/bowtie2_index_canFam6/
base_directory="/home/jovyan/fall2023/final_project_stuff/leonberger_reads_paired_trimmed"

\# Create a directory for individual SAM files
mkdir -p "${output_directory}/individual_sam_files"

for sample_directory in "${base_directory}"/*/; do
    \# Extract sample ID from the directory name
    sample_id=$(basename "$sample_directory")

    \# Set input and output file paths
    input_file_m1="${sample_directory}/${sample_id}_1.trimmed.fastq"
    input_file_m2="${sample_directory}/${sample_id}_2.trimmed.fastq"
    input_file_unpaired="${sample_directory}/${sample_id}_1.unpaired.trimmed.fastq"

    \# Run bowtie2 for each sample and save alignments to individual SAM files
    bowtie2 --met-file "$met_file" -x "$reference_genome" \
    -1 "$input_file_m1" -2 "$input_file_m2" -U "$input_file_unpaired" \
    -S "${output_directory}/individual_sam_files/aligned_${sample_id}.sam"

    \# Print a message indicating the completion of the alignment for each sample
    echo "Bowtie2 alignment completed for ${sample_id}."
done

\# Print a final message indicating the completion of all Bowtie2 alignments
echo "All Bowtie2 alignments completed."

**Comment by shaneknapp** [comment]
how large are your datasets?

**Comment by Cal19-life** [comment]
This is how large my dataset is currently: 716.854 GB

**Comment by Cal19-life** [comment]
My first sample of that dataset is 123 GB

**Comment by balajialg** [comment]
@Cal19-life Please reach out to your instructors with this question as they are better positioned to help you and guide us. We don't increase RAM for individual students unless the instructors explicitly guide us to do so. 

On another note, if you can clean up your home directories with files that you don't need for your final project then that would be helpful. 

I am closing this issue for now. Please reopen if you have further queries.
