### ISSUE TITLE
Requesting Landing Page and Quarto

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/hubs#5251]
### Package Name

Quarto

### Hub details

- Hub: ischool.datahub.berkeley.edu
- Language: Python & R 

### Course Name

This is for [Info 241.](https://www.ischool.berkeley.edu/courses/info/241). 

### Semester Details

Spring 2024

### Installation Deadline

12/13

**Comment by d-alex-hughes** [comment]
Hi team! Filling in more details below the form request: 

# Launcher Preference 

Currently, the ischool.datahub.berkeley.edu redirects users into an Rstudio instance upon authentication. I'd like to modify this so that it directs students to a launcher, rather than having the opinionated launch. For example, below is the desired behavior, which is configured on the eecs data hub.

![Screenshot 2023-12-04 at 3 50 25 PM](https://github.com/berkeley-dsep-infra/datahub/assets/6474241/8ddb69bb-bdec-4e9d-b74c-dbd62006e51f)

# Adding VSCode 

Since I see it configured on the eecs datahub, could you please also add a VS code instance onto the ischool.datahub? This will allow people to work with a generalized IDE (rather than Rstudio or Jupyter notebooks), and will be *very* helpful to achieve the final ask, below. 

# Adding Quarto 

Quarto is a command line tool that expands (and will soon replace) the RMarkdown publishing ecosystem. It is nice because it allows students to write literate reports, without being as opinionated about the data processing language (i.e. students can write natively, using python, which is quite difficult within the RMarkdown framework). Once installed, students can compile reports using any of the following methods: (i) command line interface; (ii) Rstudio; (iii) VSCode. 

Below is a link to the quarto install pages. 

https://docs.posit.co/resources/install-quarto/

# Summary of Tasks Requested

1. [ ] Modify landing page to JupyterLab "Launcher" page. 
2. [ ] Add VS Code as IDE that can be launched. 
3. [ ] Add Quarto as command line tool for student publishing.

**Comment by balajialg** [comment]
Thanks @d-alex-hughes for detailing the requirement! We will discuss this during our sprint planning meeting (12/12) and get back if there are any further clarifications required.

**Comment by balajialg** [comment]
@d-alex-hughes I have enabled VSCode and made JupyterLab the default interface in https://ischool-staging.datahub.berkeley.edu/. You can test it out and let me know if there are any issues. I am working on the Quarto PR and will give an update once it lands in the staging hub.

**Comment by balajialg** [comment]
@d-alex-hughes Quick clarification: Are you okay with the quarto version 1.3.433 or you need the latest version [1.3.450](https://quarto.org/docs/download/)? Version 1.3.433 is already installed in the Ischool hub. 

```
rstudio@jupyter-balajialwar:~$ which quarto
/usr/local/bin/quarto
rstudio@jupyter-balajialwar:~$ quarto --version
1.3.433
```

Do you want to use the latest version of Quarto? Currently, Geospatial version 4.3.1 ships Quarto 1.3.433. However,  Geospatial 4.3.2 ships the latest version of Quarto 1.3.450. Bumping geospatial to the latest ships the latest version for a [ host of packages](https://github.com/rocker-org/rocker-versioned2/wiki/geospatial_7cc207e18d0f). We are nervous about bumping the geospatial version before finals week. Let us know if you are okay with version 1.3.433 or if can you wait for one more week to get version 1.3.450

**Comment by balajialg** [comment]
@d-alex-hughes Closing this issue as it is done. Please reopen this issue if there are specific tasks that are pending. Thanks!
