### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by eordeman** [berkeley-dsep-infra/hubs#5253]
### Your UC Berkeley Email Address

eordeman@berkeley.edu

### Link to Your Datahub Folder

I do not have a link, and it seems I am not able to log in to my berkeley datahub anymore. I was recently able to access my account and saw that there was an option to retrieve old files, so I was going on today to start the process. Please let me know how to proceed. Thanks!

**Comment by balajialg** [comment]
@eordeman As mentioned in the email, I would suggest emailing [bcourseshelp@berkeley.edu](mailto:bcourseshelp@berkeley.edu) to get access to bcourses which in turn will allow you to log into Datahub.

**Comment by eordeman** [comment]
@balajialg I've been able to get access to Bcourses which will remain active temporarily (through the 15th of December). I've now been able to login to datahub, but datahub now throws either a 400 or 500 error after I try to grant canvas authorization (prompted for this upon logging in). Do you know what might be causing these errors in datahub?

Here are screenshots of the errors in case it's helpful:

<img width="908" alt="Screenshot 2023-12-08 at 10 36 25 AM" src="https://github.com/berkeley-dsep-infra/datahub/assets/84334891/675dbbb8-a863-46b3-8dc5-cbb31fb2e172">

<img width="754" alt="Screenshot 2023-12-08 at 2 36 48 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/84334891/6d0f5685-defe-4195-ad73-5a112c611e26">

**Comment by balajialg** [comment]
@eordeman Signed URL sent! Please check your email.

**Comment by eordeman** [comment]
Thank you for all of the help! I was able to successfully download my files from the link.
