### ISSUE TITLE
Request 4 more julia packages for class Math 124

### ISSUE THREAD

**Issue by popersson** [berkeley-dsep-infra/hubs#5265]
### Package Name

FFTW v1.7.1, FastGaussQuadrature v1.0.0, ForwardDiff v0.10.36, NBInclude v2.3.0

### Hub details

- Hub: Datahub 
- Language: Julia 

### Course Name

Math 124, http://persson.berkeley.edu/math124

### Semester Details

Spring 2024 as well as future offerings

### Installation Deadline

By semester start Jan 15.

**Comment by shaneknapp** [comment]
@popersson i just merged this to staging, so you'll be able to test that out in ~45m

**Comment by balajialg** [comment]
Closing this issue as it got resolved. @popersson Please reopen if you are not able to use the packages in your notebook.
