### ISSUE TITLE
Request more RAM for class ARE212

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#5278]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

datahub.berkeley.edu

**Which class is this request for?**

ARE212, Spring 2024

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-spring-aresec-212-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1530121

**How many students do you expect in this class?**

25

**How much RAM per user is needed?**

4GB

**Why does this class need this much RAM?**

We'll be working with datasets that require this much.

**By what date (MM/DD) do you want this request to be fulfilled?**

January 15, 2024

**Any additional information we should know about?**

Thanks for your help!  This is a fantastic service for instruction.

**Comment by balajialg** [comment]
@ligon Thanks! Created a PR to increase RAM for ARE 212 and ENVECON 153 - https://github.com/berkeley-dsep-infra/datahub/pull/5357. Will give an update once it gets merged to prod

**Comment by balajialg** [comment]
@ligon Both the changes are merged to prod! Please reopen this if there are any issues.
