### ISSUE TITLE
Request more RAM for class ENVECON153

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#5279]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

datahub.berkeley.edu

**Which class is this request for?**

ENVECON 153, Spring 2024

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-spring-envecon-153-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1531172

**How many students do you expect in this class?**

54

**How much RAM per user is needed?**

4GB

**Why does this class need this much RAM?**

Student projects require analysis of some larger datasets.

**By what date (MM/DD) do you want this request to be fulfilled?**

January 15, 2024

This will help us with prioritization of this request.

**Any additional information we should know about?**

Thanks for your help!

**Comment by balajialg** [comment]
Closed and the updates are noted in #5278
