### ISSUE TITLE
Request R package ottr version 1.4.0 for class POLI SCI 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#5314]
### Package Name

ottr version 1.4.0 (latest)

### Hub details

- Hub: Datahub
- Language: R

### Course Name

POLI SCI 3, Broockman

### Semester Details

Spring 2024

### Installation Deadline

First week of Jan 2024 so I can test that assignments function as intended prior to course launch.

**Comment by balajialg** [comment]
@dbroockman Ottr version-related changes are merged to prod. Please test the changes

**Comment by balajialg** [comment]
I was able to confirm that ottr version 1.4.0 is installed in the Datahub image. @dbroockman Let us know if there are any discrepancies!

<img width="852" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/bd1349d0-8b8f-4133-b7a4-17207a4b6ce7">
