### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by vtekriwal15** [berkeley-dsep-infra/hubs#5329]
### Your UC Berkeley Email Address

vtekriwal@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2023-2-summer/datahub/vtekriwal.tar.gz

**Comment by balajialg** [comment]
signed URL sent

**Comment by vtekriwal15** [comment]
Hey! This doesn't seem to have the data from prior classes. Would I be able
to retrieve those?
