### ISSUE TITLE
Data Retrieval Request

### ISSUE THREAD

**Issue by irtsui** [berkeley-dsep-infra/hubs#5346]
### Your UC Berkeley Email Address

irtsui@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/irtsui.tar.gz

**Comment by balajialg** [comment]
Signed URL sent

**Comment by irtsui** [comment]
Hi, I opened it and the folder is empty.
