### ISSUE TITLE
Admin access for PH142: Introduction to probability and statistics in biology and public health

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#5368]
### Your Name

Paula Marquez

### Affiliated Course Name

Public Health 142

### bCourses ID

1532521

### Role

ta

### Name of the Hub

publichealth.datahub

### End Date

- 05/30/24

### Request Deadline

- 1/14/23 or before the semester ideally, thanks!

**Comment by balajialg** [comment]
@paulamarm The changes are merged to staging. I will give a heads-up once the changes are live in production.

**Comment by balajialg** [comment]
@paulamarm Changes should be live in publichealth.datahub.b.e. Please reopen this issue if there are any discrepancies!

**Comment by paulamarm** [comment]
Hi!
Apologies that I didn't notice sooner but I still can't access as admin. The message I currently see is 
403 : Forbidden
Action is not authorized with current scopes; requires any of [admin-ui]

**Comment by balajialg** [comment]
@paulamarm I can see that you already have elevated privileges to the public health hub. Are you getting this error while accessing the [admin interface](https://publichealth.datahub.berkeley.edu/hub/admin)?
<img width="1361" alt="Screenshot 2024-01-19 at 5 51 26 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/51020551-fb06-4a71-8127-cfd10fc3248a">

**Comment by paulamarm** [comment]
Yes, it appears in the process of accessing [admin](https://publichealth.datahub.berkeley.edu/hub/admin) 
 
<img width="879" alt="Screenshot 2024-01-19 at 6 08 15 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/107527168/9bab47cb-aec5-4430-aa9d-fdd9a4f90868">

**Comment by paulamarm** [comment]
Is there anything I can do to correct this and have the proper admin access? It would really help me with helping our students on their first assignment in R.

**Comment by shaneknapp** [comment]
is the course published in bcourses?

**Comment by shaneknapp** [comment]
odd, i'm seeing your user as having admin access...
![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/28e0a925-7bcb-4b38-8101-9252618ce81e)

**Comment by balajialg** [comment]
@shaneknapp Yes, it is published in bcourses - https://bcourses.berkeley.edu/courses/1532521! Paula has elevated privileges as per the admin dashboard. I am not sure, what is going wrong here

**Comment by shaneknapp** [comment]
@paulamarm i just pushed @ryanlovett 's fix to prod and it will be live now.  please stop and restart your server and you should be good to go!

**Comment by ryanlovett** [comment]
@paulamarm Actually, rather than restart your server, you need to log out and back in again.

**Comment by paulamarm** [comment]
I was able to access admin properly now: thank you so much!
