### ISSUE TITLE
[Sp24 DS100] 1. Admin access (thru bcourses Admins user group) 2. Grant DS100 Content Team 4G RAM.

### ISSUE THREAD

**Issue by CharlieJCJ** [berkeley-dsep-infra/hubs#5376]
### Your Name

Charlie Cheng-Jie Ji

### Affiliated Course Name

Data 100

### bCourses ID

1531798

### Role

Lead Infra TA

### Name of the Hub

Data 100

### End Date

- 
End of Spring 2024 semester
May 11, 2024. 

### Request Deadline

We are starting the new semester soon, so need access asap, start of semester := Jan 16, 2024. First lab release Jan 19, 2024.

[Pull request](https://github.com/berkeley-dsep-infra/datahub/pull/5375) made. Thanks!

**Comment by balajialg** [comment]
@CharlieJCJ Changes should be live in data100.datahub.b.e. Please reopen this issue if there are any discrepancies!
