### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by khcir** [berkeley-dsep-infra/hubs#5378]
### Your UC Berkeley Email Address

khcir@berkeley.edu

### Link to Your Datahub Folder

https://data100.datahub.berkeley.edu/hub/login?next=%2Fhub%2Fuser%2Fkhcir%2Flab%2Ftree%2Ffa21%2Ffinal_proj%2FTraffic_Part2%2FTraffic.ipynb

https://data102.datahub.berkeley.edu/hub/login?next=%2Fhub%2Fuser%2Fkhcir%2Ftree%2Fsp22

**Comment by balajialg** [comment]
@khcir I need the link to datahub folder from the file left in your home directory. The following text is the link to your datahub folder which is present in "WHERE-ARE-MY-FILES.txt" when you log into Datahub and it must be included with your request:

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/USER_ID.tar.gz

**Comment by balajialg** [comment]
Closing this issue due to lack of response! Please reopen when you need your files.

**Comment by khcir** [comment]
@balajialg 

Hello, I am not clear how to get the link to datahub folder from the file left in my home directory. 


> gs://ucb-datahub-archived-homedirs/2021-1-fall/datahub/khcir.tar.gz

can you try if this work?

**Comment by balajialg** [comment]
@khcir I can't seem to find your files or your account in Datahub. If you don't have access to bcourses, I would suggest emailing [bcourseshelp@berkeley.edu](mailto:bcourseshelp@berkeley.edu) to get access to bcourses which in turn will allow you to log into Datahub.

**Comment by khcir** [comment]
@balajialg 
hello, can you try 

gs://ucb-datahub-archived-homedirs/2021-fall/datahub/khcir.tar.gz

this link instead? 
Thank you in advance.
