### ISSUE TITLE
Unable to Load Jupyter Lab?  (Stuck on loading animation)

### ISSUE THREAD

**Issue by cycomachead** [berkeley-dsep-infra/hubs#5392]
### Your Role

Instructor

### Affiliated Course Name

DS C88C

### Environment & Setup

I am trying to load JupyterLab on DataHub.berkeley.edu and running into the "this is taking a long time to load" modal, and the lab UI never seems to fully load. 

I've tried going to datahub then changing /tree to /lab and also with a nbgitpuller link.

### URL to the notebook file (.ipynb, .rmd etc..) with solutions

https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fcs88-website%2Fsp24&urlpath=lab%2Ftree%2Fsp24%2Flab%2Flab00%2F&branch=main

The content repo is cs88-website/sp24/ which is the public source of c88c.org/sp24.

I am trying to use nbgitpuller to see if might be an option for our assignments.

### How to reproduce

Try to load the previous nbgitpuller link in either Chrome/Safari. 

It's possible the link is bad, but this link does not work for me either, and has the same loading problems:
https://datahub.berkeley.edu/user/ball/lab

### Number of Impacted Students

0

### Severity of the Issue

High Priority

### Issue timeline

today, 1/16 few hours in the afternoon/evening

### Snapshots of issue

<img width="1800" alt="Screenshot 2024-01-16 at 6 13 21 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/1505907/7603e2e8-5aa8-4987-87b0-786d6699ee2a">

### Additional comments

Most students in the class work locally via VSCode, but what I'd like to be able to support is the option of using JupyterLab online -- in that mode, students really need only a text editor + terminal tab.

**Comment by balajialg** [comment]
@cycomachead Thanks for reporting this issue! Appreciate it. We are aware of this issue and are making an upgrade to the latest stable version of Lab 4 via this PR - https://github.com/berkeley-dsep-infra/datahub/pull/5384 which should fix this issue. The changes will be live in prod tonight.

If you require the hubs for a time-sensitive task today, then you can try launching the lab using the staging hub - https://staging.datahub.berkeley.edu/

Link to the repo using staging hub -
https://staging.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fcs88-website%2Fsp24&branch=main&urlpath=lab%2Ftree%2Fsp24%2Flab%2Flab00

**Comment by cycomachead** [comment]
Thanks for the quick response!

**Comment by balajialg** [comment]
@cycomachead Are you able to launch Lab in Datahub? Changes were merged to prod yesterday night

**Comment by cycomachead** [comment]
Thanks, it seemed to work, but I did get redirected to staging.datahub -- not sure if that's intended or if it will present issues?

**Comment by balajialg** [comment]
@cycomachead Have you tried launching lab using the the old link you shared in this Github issue - https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fcs88-website%2Fsp24&urlpath=lab%2Ftree%2Fsp24%2Flab%2Flab00%2F&branch=main? Is it still loading staging.datahub.b.e?

**Comment by cycomachead** [comment]
I swear that was the link I clicked on but I tried again on my phone and it went to the right place. :)Thanks! I’m all set for now I think though I’ll probably follow up with some questions about customizations later (we want mostly terminal + editor buttons and Python 3.11)-- Michael BallFrom my iPhonemichaelball.coOn Jan 17, 2024, at 12:43 PM, Balaji Alwar ***@***.***> wrote:﻿
@cycomachead Have you tried launching lab using the the old link you shared in this Github issue - https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fcs88-website%2Fsp24&urlpath=lab%2Ftree%2Fsp24%2Flab%2Flab00%2F&branch=main? Is it still loading staging.datahub.b.e?

**Comment by balajialg** [comment]
@cycomachead Sounds great! Please feel free to open a new issue with info about the customizations you want. We will get to it ASAP. Thanks
