### ISSUE TITLE
Update to CE110 module

### ISSUE THREAD

**Issue by jstokesdraut** [berkeley-dsep-infra/hubs#5420]
# Summary

 
We developed this module for CE110 several years ago. We included a section that creates sankey diagrams using a tool that an undergrad researcher in the Data Science developed for me. That tool no longer functions. Last year, we just skipped that section. I would love to be able to have the students create Sankeys because they are so informative. Does the team have code or can someone develop new code that will allow students to do that part of the lab. FYI, the most recent link I have to the class module is here: https://datahub.berkeley.edu/user/jsdraut/lab/tree/CE-110/network/Lab.ipynb. Aaron Moore started to help me with this last year but it was never updated in the notebook in time for the class. 

Note: I have tested the other sections for one of the five utilities we analyze in class and they seem to be working. 

# User Stories

- As a `faculty` I want to `be able to develop Sankey diagrams` so that `my students can visualize water flows in California`.
- ...

# Acceptance criteria

- Given `us doing our lab in class`, when `the students complete the Sankey section`, then `<a specific result happens>`they get a diagram they can review and interpret'
# Important information

- The most current lab is at this link: https://datahub.berkeley.edu/user/jsdraut/lab/tree/CE-110/network/Lab.ipynb

- Update Sankey diagram section, if possible. (Last year we just skipped it. If there is not alternative, the section could be deleted but I'd really like to have it.)
- Update the Peer Consulting section so the students have current info about how to get help.

**Comment by balajialg** [comment]
Thanks @jstokesdraut for raising the request! Tagging @ericvd-ucb in case he has specific inputs

**Comment by ericvd-ucb** [comment]
Looks like we shoudl try out https://github.com/ds-modules/CE-110/blob/master/network/Lab_WaterNetworks_Sp22.ipynb

**Comment by balajialg** [comment]
Closing this issue as it is tracked in https://github.com/ds-modules/CE-110/issues/1!

**Comment by jstokesdraut** [comment]
We used the data lab in CE110 without a hitch today. Thanks to this team
for all their support!

Jenn

**Comment by balajialg** [comment]
Thanks @jstokesdraut! Glad to know everything went seamlessly
