### ISSUE TITLE
Request my old files stored in Datahub (got a signed link, but it was empty)

### ISSUE THREAD

**Issue by irtsui** [berkeley-dsep-infra/hubs#5427]
### Your UC Berkeley Email Address

irtsui@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/irtsui.tar.gz

**Comment by balajialg** [comment]
signed URL sent

**Comment by irtsui** [comment]
Hi, the folder is empty again. Does this mean my data 8 files are gone?

**Comment by balajialg** [comment]
@irtsui Seems like your Data8 files are not archived. Check this [link](https://data8.datahub.berkeley.edu/user/irtsui/tree) and see if all your files are present

**Comment by irtsui** [comment]
That works, thank you!
