### ISSUE TITLE
Request for special privileges for Stat 165 course staff

### ISSUE THREAD

**Issue by MatthewDworkin** [berkeley-dsep-infra/hubs#5428]
### Your Name

Matthew Dworkin

### Affiliated Course Name

Stat 165/265 Forecasting

### bCourses ID

1533482

### Role

TA

### Name of the Hub

https://github.com/rsha256/forecasting-class-sp24/tree/main

### End Date

05/31/24

### Request Deadline

By 01/24 please!

**Comment by ryanlovett** [comment]
Hi @MatthewDworkin , under "Name of the Hub" you specified your git repository URL rather than the hub URL. Are you using datahub.berkeley.edu, r.datahub.berkeley.edu, etc. ?

**Comment by MatthewDworkin** [comment]
We’re using datahub.berkeley.edu. Apologies for the mistake!Best,Matthew DworkinOn Jan 23, 2024, at 3:51 PM, Ryan Lovett ***@***.***> wrote:﻿
Hi @MatthewDworkin , under "Name of the Hub" you specified your git repository URL rather than the hub URL. Are you using datahub.berkeley.edu, r.datahub.berkeley.edu, etc. ?
