### ISSUE TITLE
Add TAs as admins for Data 102 Datahub

### ISSUE THREAD

**Issue by shahzarrizvi** [berkeley-dsep-infra/hubs#5437]
### Your Name

Shahzar Rizvi

### Affiliated Course Name

Data 102

### bCourses ID

1532439

### Role

Head TA

### Hub URL

data102.datahub.berkeley.edu

### End Date

- 5/31/2024

**Comment by balajialg** [comment]
@shahzarrizvi This is deployed in prod. Please test it and if there are any discrepancies then reopen this issue. Thanks!
