### ISSUE TITLE
Request more RAM for Econ/Demog 175

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#5447]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

datahub.berkeley.edu

**Which class is this request for?**

[Econ/Demog 175](https://github.com/josh-goldstein-git/econ_demog_c175)

**What is the Academic Guide URL for this class?**

[c175](https://classes.berkeley.edu/content/2024-spring-demog-c175-001-lec-001)

**What is the bCourses URL for this class?**

[bcourses](https://bcourses.berkeley.edu/courses/1531929)

**How many students do you expect in this class?**

200

**How much RAM per user is needed?**

4GB of RAM per user

**Why does this class need this much RAM?**

Students will need to read in datasets of varying sizes for labs

**By what date (MM/DD) do you want this request to be fulfilled?**

By 2/2 would be great

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@wrathofquan Changes are merged to the Datahub prod. I am closing this issue for now. Please reopen this issue if there are any discrepancies during testing.

**Comment by wrathofquan** [comment]
Hi again @balajialg it appears our course hub still is showing 1GB:

<img width="541" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/20607201/aaf46f1f-a6a6-4385-a7f3-543f17c21678">

Are you able to see the increased compute on your end?

**Comment by balajialg** [comment]
@wrathofquan I made a mistake while adding the bcourses id to the config files. I have created a new [commit](https://github.com/berkeley-dsep-infra/datahub/pull/5475/commits/a341a513df0b793ee404ad517ab230b0d1dd6930) that will fix this issue. Apologies for the inconvenience caused. I will let you know once the changes are merged to prod

**Comment by balajialg** [comment]
@wrathofquan Changes are merged to prod. Let me know if the issue persists

**Comment by wrathofquan** [comment]
Thank you @balajialg Everything looks great
