### ISSUE TITLE
nbconvert is unable to export notebooks as PDFs

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#5457]
### Bug description

nbconvert is unable to export notebooks as PDFs

@chrispyles asked me to open this bug at https://github.com/ucbds-infra/otter-grader/issues/766#issuecomment-1913325540.

### Environment & setup

Datahub and R Datahub

### How to reproduce

Run `jupyter nbconvert --to=pdf notebookname.ipynb` and an error occurs. Example error message available here: https://github.com/ucbds-infra/otter-grader/issues/766#issuecomment-1913309226.

This prevents ottr from auto-generating PDFs.

**Comment by shaneknapp** [comment]
this should be fixed in `staging` in ~45 minutes after the image builds. @dbroockman i'll ping you here, and you can test this on r-staging.datahub.berkeley.edu and staging.datahub.berkeley.edu

**Comment by shaneknapp** [comment]
@dbroockman this change is live on both r-staging and staging.datahub!

**Comment by dbroockman** [comment]
Just tested and it worked on staging - thank you!
