### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by khcir** [berkeley-dsep-infra/hubs#5458]
### Your UC Berkeley Email Address

khcir@berkeley.edu

### Link to Your Datahub Folder

when i log in to data hub it shows this error
<img width="472" alt="cc" src="https://github.com/berkeley-dsep-infra/datahub/assets/86247118/bbb206c0-b58e-47af-a8b0-8a3765ae7631">

can you try this instead?
gs://ucb-datahub-archived-homedirs/fall-2021/datahub.berkeley.edu/khcir.tar.gz

**Comment by balajialg** [comment]
@khcir Please refer to my earlier comment [here](https://github.com/berkeley-dsep-infra/datahub/issues/5378#issuecomment-1915826906)
Shared URL is wrong.
