### ISSUE TITLE
Folium "stamen toner" tileset for Legal Studies 123

### ISSUE THREAD

**Issue by jdmarshl** [berkeley-dsep-infra/hubs#5460]
### Package Name

Folium tileset Stamen Toner

### Hub URL

datahub.berkeley.edu

### Course Name

Legal Studies 123 Jonathan Marshall

### Semester Details

Spring

### Installation Deadline

Stamen Toner will not load when students use folium, even when they use the appropriate attirbution statement. There is no trouble doing it locally in Anaconda.

**Comment by shaneknapp** [comment]
hey @jdmarshl i'm not super familiar w/folium et al., but a little digging got me here:
https://stackoverflow.com/questions/77634224/how-to-load-stamen-toner-tiles-in-folium-map

it looks like stamen is no longer hosting the maps themselves, and stadia is (for now) hosting them for free.
https://maps.stamen.com/stadia-partnership/
https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles

does this help?  another thing that might be useful for me is an nbgitpuller link or link to the notebook(s) in question.

thanks in advance!

**Comment by jdmarshl** [comment]
Thank you! I think I see the problem. I am not sure the student used the
right argument for 'tiles'.
I will correct Lab 7 to make sure that's in there (gitpuller link
<https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FLegalst-123&branch=master&urlpath=tree%2FLegalst-123%2Flabs%2F07_Intro+to+Folium>)
and I will let you know if it is still a problem but I forgot that I had to
change the 'tiles' argument when I used Stamen Toner over the summer.

Sincerely,
Jon
Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies
