### ISSUE TITLE
Fixing my datahub account

### ISSUE THREAD

**Issue by AnushaPB** [berkeley-dsep-infra/hubs#5470]
Hello!

I was trying to get the jupyterlab git extension to work and I was messing around and ran pip install jupyterlab==3 jupyterlab-git==0.30 (without thinking, whoops). Now when I try and login to jupyterhub I get this pop-up:

```
Build Recommended
JupyterLab build is suggested:
@jupyterlab/cell-toolbar-extension needs to be included in build
@jupyterlab/lsp-extension needs to be included in build
@jupyterlab/markedparser-extension needs to be included in build
@jupyterlab/mathjax-extension needs to be included in build
@jupyterlab/metadataform-extension needs to be included in build
@jupyterlab/mathjax2-extension needs to be removed from build
@jupyterlab/vdom-extension needs to be removed from build
@jupyterlab/application changed from ~3.0.0 to ~4.0.10
...
```

And no matter what I click (Cancel or Build) it gets stuck or fails. 

Is there any way for you to reset my account (I have nothing important on there so if you have to completely wipe it that is fine). 

Sorry about this! I will be more careful in the future.

**Comment by shaneknapp** [comment]
hey @AnushaPB !  this is pretty easy to fix:  just kill your single user server (not log out, but stop it completely) and then log back in.  that will reset your user image to 'stock'.

**Comment by AnushaPB** [comment]
Thanks so much for the fast response! When I go to log on (e.g. click this link https://datahub.berkeley.edu/) it just automatically takes me to that build message, I don't see any options to kill the server. Should I be looking in a different place?

**Comment by shaneknapp** [comment]
i went ahead and killed and restarted your server...  let me know if that
works for you!

**Comment by AnushaPB** [comment]
It works! Awesome, thanks so much. Is there a way for me to do that on my end (just in case haha)?

I was wondering if you could also give me any insight into the original issue I was having which is that when I try and install the jupyterlab-git server extension, it installs successfully, but I get the error:

```
Failed to load the jupyterlab-git server extension
Git server extension is unavailable. Please ensure you have installed the JupyterLab Git server extension by running: pip install --upgrade jupyterlab-git. To confirm that the server extension is installed, run: jupyter server extension list.
```

when I run `jupyter server extension list.` it confirms that it is installed/enabled:
```
jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.50.0 OK
```

**Comment by shaneknapp** [comment]
to shut down your server, click on 'file' and 'hub control panel':
![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/3cf2898d-9cc4-4b8d-9208-b4481823e4f2)

then click on 'stop my server':
![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/61c87e54-a88b-46a7-abf2-a3ecfe032569)

unsure why jupyterlab-git isn't working for you.  i looked at the github page (https://github.com/jupyterlab/jupyterlab-git) and i'd recommend running through the debugging steps there.  we don't 'officially' 'support' this extension on datahub, and i don't have much (any) experience with it...

**Comment by AnushaPB** [comment]
Sounds good, thanks for your help!
