### ISSUE TITLE
Request more RAM for EE 120

### ISSUE THREAD

**Issue by edwardneo** [berkeley-dsep-infra/hubs#5492]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

EECS hub (eecs.datahub.berkeley.edu)

**Which class is this request for?**

2024 Spring, EE 120

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-spring-eleng-120-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1532904

**How many students do you expect in this class?**

130

**How much RAM per user is needed?**

4GB/student

**Why does this class need this much RAM?**

We have signal processing labs that involve working with large amounts of data.

**By what date (MM/DD) do you want this request to be fulfilled?**

02/03, if it's not too soon.

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@edwardneo Until when (MM/DD) do you require the additional RAM?

**Comment by balajialg** [comment]
@edwardneo Changes are merged to staging hub! You can test whether RAM increased using this [URL](https://eecs-staging.datahub.berkeley.edu/)

**Comment by edwardneo** [comment]
Through 05/05 would be great! Thanks!

**Comment by balajialg** [comment]
@edwardneo Thanks! Closing this issue as the changes were merged to prod
