### ISSUE TITLE
Request python package ottr-force-save-labextension for class POLI SCI 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#5497]
### Package Name

ottr-force-save-labextension

### Hub URL

r.datahub.berkeley.edu

### Course Name

POL SCI 3, Broockman

### Semester Details

Spring 2024

### Installation Deadline

Package URL: https://github.com/chrispyles/ottr-force-save-labextension

Needs to be installed per issue https://github.com/ucbds-infra/otter-grader/issues/767#issuecomment-1921681932.

**Comment by balajialg** [comment]
Closing this issue as the changes were merged to prod!
