### ISSUE TITLE
Request R package ottr v.1.5.0 for class POL SCI 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#5498]
### Package Name

ottr v1.5.0

### Hub URL

r.datahub.berkeley.edu

### Course Name

POL SCI 3

### Semester Details

Spring 2024

### Installation Deadline

ottr v1.5.0 fixes an issue with force save, as detailed in https://github.com/ucbds-infra/otter-grader/issues/767.

**Comment by shaneknapp** [comment]
@dbroockman just so you're aware, this particular package upgrade will affect every user on the hub -- not just for this class.

**Comment by dbroockman** [comment]
Yes. I just noted the class because that's what was in the bug template.

**Comment by shaneknapp** [comment]
btw all of these changes are live on r-staging.datahub.berkeley.edu and staging.datahub.berkeley.edu...  could you please test and make sure everything is working as intended?

**Comment by dbroockman** [comment]
Yes, working as intended! Thank you!

**Comment by balajialg** [comment]
Closing this issue as the changes were merged to prod!
