### ISSUE TITLE
Update Course ID

### ISSUE THREAD

**Issue by channatalie** [berkeley-dsep-infra/hubs#5508]
### Your Name

Natalie Chan

### Affiliated Course Name

Data 101/Info 258

### bCourses ID

1532753

### Role

ta
Want to update the Spring 2024 config with the new course ID

### Hub URL

data101.datahub.berkeley.edu

### End Date

- 05/31/24

**Comment by balajialg** [comment]
@channatalie Changes will be merged hub to staging in the next 30 minutes! Feel free to test your [elevated privileges](https://ds-modules.github.io/curriculum-guide/faq/admin.html?highlight=elevated) in https://data101-staging.datahub.berkeley.edu/

**Comment by balajialg** [comment]
@channatalie Closing this issue as the changes were merged to prod!

**Comment by channatalie** [comment]
Yes, thank you Balaji!!
