### ISSUE TITLE
Increase compute resources for Course Data 101 between specific date(s)/time(s)

### ISSUE THREAD

**Issue by channatalie** [berkeley-dsep-infra/hubs#5509]
### Course Name

Data 101/Info 258
https://classes.berkeley.edu/content/2024-spring-data-101-001-lec-001
https://www.data101.org/sp24/

### Detailed Requirements

Deadline for Compute Intensive Assignment (4 Project Assignment Deadlines)

### Semester Details

Yes

### Request Deadline

Project 1: 2/13/24 5:00 PM - 2/15/24 5:00 PM
Project 2: 2/27/24 5:00 PM - 3/1/24 5:00 PM
Project 3: 3/26/24 5:00 PM - 3/28/24 5:00 PM
Project 4:  4/23/24 5:00 PM - 4/25/24 5:00 PM

**Comment by balajialg** [comment]
@channatalie Added events in the calendar for the dates reported

**Comment by balajialg** [comment]
@channatalie I am closing this issue as it got done. Please reopen if there are any challenges faced by the students during assignment deadlines?
