### ISSUE TITLE
Erol Ayik Data Retrieval Request

### ISSUE THREAD

**Issue by erol-ayik** [berkeley-dsep-infra/hubs#5519]
### Your UC Berkeley Email Address

eroleayik@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/eroleayik.tar.gz

**Comment by balajialg** [comment]
signed URL sent

**Comment by erol-ayik** [comment]
Where do I find the URL? I saw it around an hour ago and now it is suddenly gone.

**Comment by erol-ayik** [comment]
I can't find the URL.

**Comment by balajialg** [comment]
@erol-ayik Please check your email!
