### ISSUE TITLE
Request python package matplotlib for class CE 88

### ISSUE THREAD

**Issue by martagberkeley** [berkeley-dsep-infra/hubs#5526]
### Package Name

matplotlib version 3.5.1

### Hub URL

datahub.berkeley.edu

### Course Name

Data Science for Smart Cities

### Semester Details

 Spring 2024

### Installation Deadline

!pip install matplotlib==3.5.1
Does not downgrade to the needed version , it stays with version 3.7.3

**Comment by shaneknapp** [comment]
hey marta,

as this package is used by many other classes, and i am very reluctant to downgrade it on the datahub image.  the absolute best course of action here is to update the coursework/notebooks to be compatible with 3.7.3.

however, you can force a downgrade by first uninstalling the existing package, and forcing a new installation that ignores any existing versions on the image.  the downside is that you could likely run in to package dependency conflicts, and we don't support these types of operations when performed by a user.  basically, you'll be on your own!

to do this, each time you log in, you would run the following in a cell:

```
!pip uninstall -y matplotlib
!pip install --ignore-installed matplotlib==3.5.1
```

once you log out/exit your kernel everything in the image will be reset, and the next time you log you'll need to go through the process again.

![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/0a5b7d72-3bd9-4605-a6f5-63f885451369)

**Comment by balajialg** [comment]
@martagberkeley Closing this issue for now. Please reopen if there are open questions!
