### ISSUE TITLE
Request more RAM for Legal Studies 123

### ISSUE THREAD

**Issue by jdmarshl** [berkeley-dsep-infra/hubs#5530]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Datahub (datahub.berkeley,edu)

**Which class is this request for?**

Spring 2024 Legal Studies 123

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-spring-legalst-123-001-sem-001

**What is the bCourses URL for this class?**
https://bcourses.berkeley.edu/courses/1532145

**How many students do you expect in this class?**

43

**How much RAM per user is needed?**

Last year we had 2GB per student but I only noticed today that we were back down to 1GB; I think it may be causing problems in the mapping labs

**Why does this class need this much RAM?**

We work with large datasets for some of the lab exercises and definitely for the homework (although we advise students to do those locally), but the mapping labs take up a fair amount of memory.

**By what date (MM/DD) do you want this request to be fulfilled?**

When you can--I am sorry I had not noticed this before. I was too busy revising some of the labs that didn't do what I needed.

**Until when (MM/DD) do you require the additional RAM?**

Until the end of Spring 2024, and then again in Sp25

**Any additional information we should know about?**

**Comment by shaneknapp** [comment]
hey @jdmarshl, this will be live on datahub in about ~10m.  could you check and see that you have 4G of ram?  you'll need to log out and back in again to see this change.

also, be sure that your course is published in bcourses!  :)

**Comment by jdmarshl** [comment]
Hi Shane,

Yes, I have 4GB of RAM. Thanks! I know for sure my course is published, but
because I am the Program Director I may have other courses. The url for the
bCourses site is https://bcourses.berkeley.edu/courses/1532145.

Students in the course will have the same 4GB, correct?

thanks again,
Jon
Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies

**Comment by shaneknapp** [comment]
yep, they will!  only folks who aren't enrolled in a published course won't
see the change.  i think we're good to go, and thanks for helping confirm
that this works!
