### ISSUE TITLE
Datahub not loading

### ISSUE THREAD

**Issue by MatthewDworkin** [berkeley-dsep-infra/hubs#5537]
### Bug description

A Stat 165 student reported 52 minutes ago that they were unable to open the notebook for the lab component of their hoomework this week. Here is the link to the lab.

### Environment & setup

- Hub: Datahub Stat 165
- Language: Python

### How to reproduce

Not sure, but try clicking this link to see if you get the same issue: https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Frsha256%2Fforecasting-class-sp24&branch=main&urlpath=tree%2Fforecasting-class-sp24%2Fhw%2Fhw4%2Fhw4lab.ipynb

**Comment by MatthewDworkin** [comment]
Student is xxx

**Comment by balajialg** [comment]
@MatthewDworkin I am closing this issue for now since we didn't hear back. Please reopen if the student still faces the same issue.
