### ISSUE TITLE
Notebook crashing due to one cell with a large database output

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#5539]
### Your Role

GSI/TA

### Affiliated Course Name

Data C100

### Hub URL

datahub.berkeley.edu

### URL to the notebook file (.ipynb, .rmd etc..) with solutions

Student starter notebook: https://data100.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FDS-100%2Fsp24-student&urlpath=lab%2Ftree%2Fsp24-student%2F%2Fhw%2Fhw03%2Fhw03.ipynb&branch=main

PDF Solutions: https://drive.google.com/file/d/1ametj8hCRpGU-PhLOxZxtmtvW0mEWp8A/view 
(couldn't generate nbgitpuller link for staff notebook as sp24-dev repo is private)

### How to reproduce

1. Go to Question 3aii (cell 60) and enter in the staff solution: 

# BEGIN SOLUTION
sentiment = pd.DataFrame(sentiment_analysis(msft_news_2010["first_sentence"].tolist()),
                         index = msft_news_2010.index) # important to preserve the index
msft_news_2010["sentence_sentiment"] = (
    (2*(sentiment["label"] == "POSITIVE") - 1) * sentiment["score"]
)
# END SOLUTION
msft_news_2010.head(1)

2. Run the cell

### Number of Impacted Students

at least 21

### Severity of the Issue

High Priority

### Issue timeline

02/14/2024, 

### Snapshots of issue

![image](https://github.com/berkeley-dsep-infra/datahub/assets/102919445/38b39aa2-91e1-4061-afa7-2a8fdc7fe325)

### Additional comments

Other students have run into this issue but it seems to rectify itself a few hours later? 
From EdStem: 
"Hi, I am trying to run my entire notebook so that I can submit, however my kernel seems to get stuck forever (10+ minutes) on problem 3aii. This question has run many times before and is only now giving me trouble even though I haven't made any changes to it. I've tried restarting my kernel, closing and reopening the window, etc. but nothing seems to be working. Do you have any advice for how to fix this problem? I can't submit if it never finishes running. 
Edit: working as of 3:01 p.m.

Anonymous Lark
[2h](https://edstem.org/us/courses/51810/discussion/4305581?comment=10036595)
[#686bb](https://edstem.org/us/courses/51810/discussion/4305581?comment=10036595)
Same, I was able to run my 3aii last night and I didn't make changes but now it takes forever. Edit: it seems to be working @1:57 PM."

**Comment by balajialg** [comment]
Closing this issue as the assignment is complete!
