### ISSUE TITLE
Notebooks failing to load/open

### ISSUE THREAD

**Issue by sarsong** [berkeley-dsep-infra/hubs#5561]
### Your Role

GSI/TA

### Affiliated Course Name

Data 8

### Hub URL

data8.datahub.berkeley.edu

### How to reproduce

Open any assignment via the [Data 8 website](https://www.data8.org/sp24/). This issue only seems to be impacting a subset of students. At its worst, around 1/3 of students trying to access notebooks seem to have been impacted.

### Number of Impacted Students

At least 100?

### Severity of the Issue

Critical

### Issue timeline

First occurrence on 2/7, second occurrence on 2/21

### Snapshots of issue

Blank pages after clicking on notebook links via Data 8 website -- no error codes pop up, just a blank page

### Additional comments

Most students are able to work around this issue by using an incognito/private browsing window, but we have had at least 15 students who reported that this did not work for them.

**Comment by balajialg** [comment]
Thanks @sarsong for reporting the issue! Sharing tl;dr for conversations reported via slack - Few students faced "white screen" issue when they launched Data 8 hub to work on an assignment yesterday night (around 10 PM) and today morning. Assignment deadlines has been postponed by a day due to this issue

**Comment by sarsong** [comment]
2/23 update: still having numerous reports of white screen issues, but all of them seem to be resolved by following these steps:
1. [Shut down your server](https://data8.datahub.berkeley.edu/hub/home)
2. Clear cache for all time, not just the last week
3. Reopen assignment

One student reported that after following these steps, their normal browser still did not work, but an incognito window did.

**Comment by balajialg** [comment]
@sarsong Thanks for the update and sorry for the inconvenience caused! You meant "restarting the server' in point 1?

**Comment by sarsong** [comment]
Some students reported that restarting their server --> clearing cache didn't work, and for whatever reason, asking them just to hit the "stop my server" button --> clear cache --> open assignment worked 😭. It's a bit hard to track the exact steps students took because they often will stop replying on Ed once everything starts working :(

**Comment by balajialg** [comment]
@sarsong Got it, thanks for the clarification!

**Comment by shaneknapp** [comment]
closing this as it's resolved.
