### ISSUE TITLE
Request python package GeoPandas for Legal Studies 123

### ISSUE THREAD

**Issue by jdmarshl** [berkeley-dsep-infra/hubs#5571]
### Package Name

geopandas

### Hub URL

datahub.berkeley.edu

### Course Name

Legal Studies 123, instructor Jonathan Marshall

### Semester Details

Spring 2024 (and spring semesters thereafter)

### Installation Deadline

By this Tuesday 2/27. Geopandas used to be on Datahub, I thought. Thank you!

**Comment by jdmarshl** [comment]
Nevermind. I was able to just do !pip install

**Comment by balajialg** [comment]
@jdmarshl Geopandas and rtree packages are added to Datahub image. You can do `pip install` instead of `!pip install `going forward. Let me know if there are any difficulties

**Comment by jdmarshl** [comment]
Thank you! We're about to move into all the text analysis packages starting
next week, but I appreciate the assistance.
jon

Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies
