### ISSUE TITLE
Request python package rtree for geopandas for Legal Studies 123

### ISSUE THREAD

**Issue by jdmarshl** [berkeley-dsep-infra/hubs#5572]
### Package Name

rtree (a dependency for making spatial joins in GeoPandas)

### Hub URL

datahub.berkeley.edu

### Course Name

Legal Studies 123 instructor Jonathan Marshall

### Semester Details

Spring 2024 (and spring semesters thereafter)

### Installation Deadline

Tuesday 27 February 2024
[13_PerformanceMetrics_solutions.pdf](https://github.com/berkeley-dsep-infra/datahub/files/14398548/13_PerformanceMetrics_solutions.pdf)

**Comment by jdmarshl** [comment]
It looks like it might want compiled C files https://geopandas.org/en/stable/getting_started/install.html

**Comment by jdmarshl** [comment]
Once again, I was too hasty to cry for help. I just added !pip install rtree to the dependencies cell and the script ran fine.

**Comment by balajialg** [comment]
@jdmarshl Sustainable approach would be to install the packages in the Datahub image instead of installing it in your notebook. 
If you are doing `!pip install`, once you/your students log out of the hub/exit kernel everything in the image will be reset, and you need to`!pip install` the package when you launch the notebook again.



https://github.com/berkeley-dsep-infra/datahub/pull/5575

**Comment by jdmarshl** [comment]
Agreed--are there instructions for how to install the packages in the
Datahub image for Legal Studies 123 somewhere? You gotta remember I am not
a specialist in this.

Thank you,
Jon

Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl You did the right thing by creating this package request! You need not do anything other than requesting the package to be added to the image. https://github.com/berkeley-dsep-infra/datahub/pull/5575 is my PR adding those packages to the Datahub image.

**Comment by jdmarshl** [comment]
Great. I know that we will be using these labs again next year (I spent a
lot of time rewriting about a third of the labs for the class).
thanks!
jdm

Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl Got it. Will this course be offered during SU 24/FA 24? If not, I will comment the packages at the end of the semester and then re-enable it when you start teaching during SP 25.

**Comment by jdmarshl** [comment]
My GSI will offer the course in Summer 2024, but it will not be offered
Fa24. It will return Sp25. Thanks,

Jon Marshall, Ph.D. (he/him)
Assistant Dean
JSP/Legal Studies

**Comment by balajialg** [comment]
@jdmarshl Thanks for the clarity!
