### ISSUE TITLE
Request for `fontawesome5.sty` ischool.datahub.berkeley.edu

### ISSUE THREAD

**Issue by d-alex-hughes** [berkeley-dsep-infra/hubs#5584]
### Package Name

fontawesome5

### Hub URL

ischool.datahub.berkeley.edu

### Course Name

This is for Info 241 (which is a mirror for DATASCI 241) 

### Semester Details

Spring 2024, and into the future

### Installation Deadline

This month, if possible? 

The latex package is located here: https://ctan.org/pkg/fontawesome5?lang=en

**Comment by d-alex-hughes** [comment]
To provide some more context for this request: The growing quarto ecosystem has so called, "callout blocks" that provide formatted text in boxes. 

Annoyingly, when rendering out to PDF this creates an additional dependency, `fontawesome5` that isn't currently incorporated into the prod stack.

**Comment by ryanlovett** [comment]
@balajialg ~~I think it is provided by the `fonts-font-awesome` ubuntu package, https://launchpad.net/ubuntu/jammy/+package/fonts-font-awesome.~~ Nevermind -- you found the tex package.

**Comment by balajialg** [comment]
@d-alex-hughes Thanks for the clarity, looking into it. 

@ryanlovett Just seeing your message, I just added https://packages.debian.org/sid/texlive-fonts-recommended to the Ischool hub image. Would you recommend installing this package over the other one?

**Comment by ryanlovett** [comment]
@balajialg I'd go with the package you found! Sorry for the confusion.

**Comment by balajialg** [comment]
@ryanlovett Ah, no worries! It was my bad. I didn't see your comment prior to creating the PR

**Comment by balajialg** [comment]
@d-alex-hughes PR changes are merged to staging. Can you test the changes in https://ischool-staging.datahub.berkeley.edu/ and let me know if it works? We will merge the changes to prod anytime soon

**Comment by balajialg** [comment]
@d-alex-hughes Changes are merged to prod. Please test the package and let me know if there are any issues.

**Comment by balajialg** [comment]
@d-alex-hughes I a closing this issue for now. If you have any issues using this package then please reopen the issue.

**Comment by d-alex-hughes** [comment]
Sorry to leave the thread hanging. I wasn't getting pinged on the conversation. I'll test and let you know if anything comes up. 

Thanks so much @balajialg !

**Comment by balajialg** [comment]
No worries at all! Thanks for the heads up @d-alex-hughes
