### ISSUE TITLE
Request more RAM for class AY 128

### ISSUE THREAD

**Issue by dweisz** [berkeley-dsep-infra/hubs#5596]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Astro Datahub (astro.datahub.berkeley.edu)

**Which class is this request for?**

For example, "2024 Spring, Astro Data Lab 128".

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-Spring-ASTRON-128-001-LAB-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1532117

**How many students do you expect in this class?**

25 are enrolled

**How much RAM per user is needed?**

8GB per student

**Why does this class need this much RAM?**

The last two labs in our class (Lab 2 and 3) are more memory intensive than the first two labs.  Students will need to train large models and store moderately-sized datasets for these two labs.  Per previous iterations of Astro data lab, we know that 4GB is not enough.  I'm guessing that 8GB should be manageable for the students based on benchmarks on my laptop.  

**By what date (MM/DD) do you want this request to be fulfilled?**

As soon as possible.  We started Lab 2 this week, and due to some family illness, I forgot to place this request last week.  Sorry for the last minute nature of this request.

**Until when (MM/DD) do you require the additional RAM?**

Through the end of the semester.

**Any additional information we should know about?**

In trying to keep the data hub load manageable, I didn't make this request at the beginning of the semester, because we didn't need the memory increase until now.

**Comment by balajialg** [comment]
@dweisz Thanks for the detailed info. I just created a [PR](https://github.com/berkeley-dsep-infra/datahub/pull/5597) to increase RAM for your course. I will give you a heads up once it gets merged to prod.

**Comment by balajialg** [comment]
@dweisz Changes are merged to prod. I am closing this issue for now but if you still don't see the RAM increase then please reopen this issue.
