### ISSUE TITLE
Request python package `duckdb` (pip install) for class `Data 100`

### ISSUE THREAD

**Issue by CharlieJCJ** [berkeley-dsep-infra/hubs#5634]
### Package Name

duckdb

### Hub URL

datahub.berkeley.edu

### Course Name

Data 100

### Semester Details

Spring 2024

### Installation Deadline

Before end of spring break the latest.

**Comment by CharlieJCJ** [comment]
https://pypi.org/project/duckdb/
<img width="1111" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/55744150/868ee6a1-accc-4736-9bc6-9ecae861a3b1">

**Comment by cboettig** [comment]
@CharlieJCJ is Data100 teaching SQL with DuckDB now? So very nice!  

(now if pandas part of the course switches to the [ibis-framework](https://ibis-project.org/tutorials/ibis-for-pandas-users) we could be using duckdb the whole way along under the hood... :wink: )

**Comment by CharlieJCJ** [comment]
@cboettig Yes! we are switching to duckdb from this semester on SQL for the first time! I can check on the pandas part with Professors~ Thanks for suggesting this!

**Comment by jegonzal** [comment]
Wes had suggested we do that. Might be worth trying. I is has matured a lot I am told.

**Comment by jegonzal** [comment]
@cboettig and @fperez would you be interested in exploring this?

**Comment by shaneknapp** [comment]
Oh nice, we're also happy to help!

**Comment by cboettig** [comment]
@jegonzal very cool!  

Yes, I've been using ibis recently in courses quite happily now.  The syntax is intuitive, SQL-type concepts but with more pythonic expresssions (very close to  polars).   With the duckdb backend it is particularly nice that we can work with much larger datasets without having RAM issues on the small datahub pods.

e.g. this read of unique species from over 2M rows of data works just fine on the default 1 GB hubs:

```python
import ibis
from ibis import _

t = (ibis
 .read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-04-01/occurrence.parquet/000000")
 .select(_.species)
 .distinct()
)

t.to_pandas()
```

It's also cute that users can to `t.to_sql()` if we want to discuss SQL syntax.  The recent support for spatial queries in duckdb (and ibis) has also been really cool.

**Comment by fperez** [comment]
That's very cool @cboettig - I hadn't kept up to date on the progress of Ibis for ages, and hadn't talked to Wes about this recently.

@cboettig  - are you using [jupysql](https://jupysql.ploomber.io/en/latest/quick-start.html)? I really like how naturally it pulls SQL into a python workflow, with very seamless 2-way support. It's also actively maintained (it's a friendly fork of a very old ipython-sql magic that was one of the earliest demonstration of magics for complex multi-language workflows, but that had gone out of maintenance).  This means we can make suggestions/requests and there's an active team behind it.
