### ISSUE TITLE
Demography Workshop Datahub Request

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#5643]
# Summary

We have two workshop events coming up in the Demography/Population sciences department and are looking at using the workshop hub or potentially another dedicated hub. 

- The first event is a workshop/hacakthon type event that actually will run for the entire summer and involves Berkeley faculty, graduate students and post docs. It's a data challenge called the [predicting fertility data challenge](https://stulp.gmw.rug.nl/prefer/). It begins April 1 and expect about 5-6 users training ML models in python and R. Since this is a longer running event (continues through summer), I'm not sure if the workshop hub is suitable but wanted to check in to see if you have suggestions or alternatives.

- This year the Demography department will again host a [week-long workshop, June 3-7](https://populationsciences.berkeley.edu/population-center/annual-workshop-on-formal-demography/#:~:text=The%209th%20Annual%20Workshop%20on,by%20the%20Berkeley%20Population%20Center.) on statistical methods in June with researchers visiting from all over the world. We used workshop hub last year with great success and hope to use it again! Compute needs will be same as last year - 4GB of RAM per user. We expect 20-40 users. 

# User Stories

Workshop instructors and faculty can have all of their instructional materials in a Datahub that is consistent across users.
Attendees won't have to worry about managing their own compute environments.

# Acceptance criteria

- For the data challenge event, users with a calnet can navigate to datahub and use python/r to train ml models. Users will be using same datasets so a `shared-read-write` directory would be required. 

- For the June workshop event, users can navigate to something like: workshop.datahub.berkeley.edu, authenticate without calnet (and potentially manage their own credentials), access the workshop files in RStudio or native R kernel.

# Important information

### Data challenge
- The data challenge (April 1 - September) will have about 5-6 users each needed about 4GB of RAM and a `shared-read-write` to work on shared datasets that exceed storage capacity in github. 

### Demography workshop
- This workshop is in June (3-7)  and we expect somewhere between 20-50 users
- We'd like to have a 4GB allocation of RAM per user.
- We'd want to keep the pods alive for a few weeks after the workshop to give users a chance to save their work.

# Tasks to complete

**Comment by balajialg** [comment]
@wrathofquan Thanks, Responding to the time sensitive request first - Yes, students can use the workshop hub to do their work. We can enable shared-readwrite directories so that they can store their datasets. Is it possible to create a dummy bcourses site, add all the participants of the data challenge to that site and share the bcourses id? 

You might need to assign Teacher/TA role for the folks who will have read/write access and student role for the folks who need read access to the shared drive. We can enable access to the drive using the shared bcourses id in the workshop hub.

**Comment by wrathofquan** [comment]
Thank you @balajialg. bcourses id: 1534506

**Comment by balajialg** [comment]
@wrathofquan Hi Josh, changes are merged to [staging hub.](https://workshop-staging.datahub.berkeley.edu/hub/login?next=%2Fhub%2F) and should be deployed within the next 60 minutes. Can you ask your students added to the bcourses site to check whether they can see a) shared-readwrite directory and b) RAM increase to 4 GB in the staging hub?

**Comment by balajialg** [comment]
@wrathofquan I just updated the configs in Datahub via [this PR](https://github.com/berkeley-dsep-infra/datahub/pull/5646). Changes were merged to prod 10 mins ago. You should be able to test this in https://datahub.berkeley.edu/ in an hour

**Comment by shaneknapp** [comment]
actually, it's live on datahub now!

**Comment by wrathofquan** [comment]
@balajialg Would it be possible to increase RAM to 8GB? We received the assignment datasets today and they are larger than expected. 

Few users have reported their sessions crashing when reading in data and I can confirm that reading in a 300MB csv eats almost half of available RAM
<img width="532" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/20607201/da6cc5f5-e8ea-4895-908e-a783ee2bc2e3">

Thank you for considering!

**Comment by balajialg** [comment]
@wrathofquan Yes, we should be able to increase the RAM to 8 GB. Here is the [PR](https://github.com/berkeley-dsep-infra/datahub/pull/5654)

Having said that, I also want to highlight that an increase in RAM is correlated with an increase in cloud costs at our end. So, any further request to increase RAM would be something @shaneknapp and I might need to review in future.

**Comment by balajialg** [comment]
@wrathofquan I have increased the Workshop Hub RAM to 4 GB. Please inform me if you encounter any discrepancies. When do you recommend reverting the RAM increase? I will schedule it to be reduced accordingly.

**Comment by wrathofquan** [comment]
Thank you @balajialg! Everything looks great. Can we drop it back down on Monday June 10?

**Comment by balajialg** [comment]
Sounds good, thanks!
