### ISSUE TITLE
Pytorch not importing

### ISSUE THREAD

**Issue by dweisz** [berkeley-dsep-infra/hubs#5659]
### Bug description

pytorch is installed on astro.datahub.  However, we try to import it, we get the below error (see screenshot).  Re-installing pytorch via conda or pip doesn't seem to resolve the issue.  Any guidance is appreciated.

<img width="1062" alt="Screen Shot 2024-04-04 at 11 49 06 AM" src="https://github.com/berkeley-dsep-infra/datahub/assets/1222499/b5a3d8e6-1042-4530-8213-f889b9497589">

### Environment & setup

- Hub: AstroHub
- Language: Python

### How to reproduce

import torch

**Comment by shaneknapp** [comment]
looking in to this now...

**Comment by shaneknapp** [comment]
hmm, looks like this is a pytorch issue:  https://github.com/pytorch/pytorch/issues/123097

i'll see if i can't make this work somehow.

**Comment by shaneknapp** [comment]
@dweisz could you log in to astro-staging.datahub.berkeley.edu and confirm that it works for you?

![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/f5d8e2a5-de45-429e-82ca-c2c974185ae3)

**Comment by dweisz** [comment]
Unfortunately, it's still throwing me an error

<img width="962" alt="Screen Shot 2024-04-04 at 1 40 48 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/1222499/f9353dad-91ab-47a7-9ca8-5b08ca87b730">

**Comment by balajialg** [comment]
@dweisz Are you logged into https://astro-staging.datahub.berkeley.edu? It works without any errors in Astro-staging hub for me. I can't see your username `drweisz` listed in the admin interface of staging hub (It should have if you had logged into that hub)

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/d8eb7528-a4ff-4cbf-9de1-a9f177d62f9e)

**Comment by dweisz** [comment]
Apologies, I was logged into the wrong server.

Yes, import torch appears to work on the astro-staging instance.

**Comment by shaneknapp** [comment]
> Apologies, I was logged into the wrong server. Yes, import torch appears to work on the astro-staging instance.
> […](#)
> On Apr 4, 2024, 1:47 PM -0700, Balaji Alwar ***@***.***>, wrote: @dweisz Are you logged into https://astro-staging.datahub.berkeley.edu? It works without any errors in Astro-staging hub for me. image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

glad this works!  we'll get this merged to prod by EOD today

**Comment by ElHouas** [comment]
Hello @shaneknapp ,

I am experiencing the same issue when installing torch using conda inside a docker container using as base images ubuntu:22 and anaconda official docker image. Here is my env.yaml file:

name: ml_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.7
  - mamba
  - pip
  - poetry=1.8.2
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8.0
  - cudnn
  - blas=1.0
platforms:
  - linux-64
  
  
  Thanks for the help! :)

**Comment by shaneknapp** [comment]
@ElHouas which hub are you seeing this issue on?
