### ISSUE TITLE
my students couldn't access my .git repo

### ISSUE THREAD

**Issue by seangallaher** [berkeley-dsep-infra/hubs#5665]
### Bug description

I am teaching a class (MCB C117) where I am having my students use RStudio on the biology.datahub. When accessing one repo, everything went fine, and the students were able to use RStudio with the data in my git repo. However, when trying to access a second repo, almost everyone got stuck at the "Synchronizing git repository, before sending you to rstudio/..." stage. The second, problematic repo has larger files in it, so I am wondering if it is a question of not having enough resources for the student accounts. Both repos work fine for me, and a few of my colleagues when I asked them to try it. 

This is URL I used for the repo that does not work for my students:
[https://biology.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fseangallaher%2FMCB_C117_Lecture_21&urlpath=rstudio%2F&branch=main](url)

This is the URL for the repo that does work for my students:
[https://biology.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fseangallaher%2FMCB_C117_Lecture_20.git&urlpath=rstudio%2F&branch=main](url)

Here is an example of what the students saw for the whole class (vs. a few seconds for me and for my colleagues):
<img width="881" alt="Screenshot 2024-04-05 at 10 12 38 AM" src="https://github.com/berkeley-dsep-infra/datahub/assets/12144558/f53da727-db85-4665-9084-8644a6821f4c">

Any ideas? 

### Environment & setup

- Hub: I only tried with the biology.datahub
- Language: R

### How to reproduce

I cannot. This works fine for me. But did not work for 10 of my 11 students. No reason why that I could identify.

**Comment by shaneknapp** [comment]
we had an outage from ~9pm last night through ~9am this morning where nbgitpuller links weren't working.  i've rolled back the changes that went out last night and i'm now able to open both nbgitpuller links.

i would have the students try again (i just confirmed that both urls work for me), and if they still have issues have them stop their server:  https://biology.datahub.berkeley.edu/hub/home

![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/214fc49d-48ad-4bf6-9fbd-31e8c4966317)

**Comment by seangallaher** [comment]
Wow, was that terrible timing for that to be not working. Thanks for letting me know.

**Comment by shaneknapp** [comment]
> Wow, was that terrible timing for that to be not working. Thanks for letting me know.

not only terrible timing, but also the *first* time we've ever seen an nbgitpuller link fail like that.  now we will put 'click on an nbgitpuller link' in our testing before we deploy to prod.

**Comment by balajialg** [comment]
@seangallaher Closing this issue for now as things are back to normal! Please reopen it if your students still face this issue.
