### ISSUE TITLE
Request more RAM for class IEOR 198

### ISSUE THREAD

**Issue by robyang1** [berkeley-dsep-infra/hubs#5675]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Datahub (datahub.berkeley,edu)

**Which class is this request for?**

2024 Spring, IEOR 198: Intro to Quantitative Finance

**What is the Academic Guide URL for this class?**

No specific URL as this class is a decal. It is under IEOR 198 and general information on classes titled IEOR 198 can be find in the middle of this page: https://guide.berkeley.edu/courses/ind_eng/. A page with course information is here: traders.berkeley.edu/education.

**What is the bCourses URL for this class?**

This class is a decal so it does not have a bCourses. Let me know if some alternative, say, to get the list of students, is needed.

**How many students do you expect in this class?**

There are about 100 people enrolled

**How much RAM per user is needed?**

4 GB

**Why does this class need this much RAM?**

 A lab we released needs the student to download stock data for 503 different stocks, which takes about 2GB of memory, then performs some operations after that so 4GB would be a safe amount without having a kernel crash in the middle of the lab, which can be frustrating.

**By what date (MM/DD) do you want this request to be fulfilled?**

04/13, the sooner the better so students will have more time to work on the lab.

**Until when (MM/DD) do you require the additional RAM?**

05/20, end of the semester

**Any additional information we should know about?**

I’m not sure how this request process works for decals so let me know if any other info is needed!

**Comment by balajialg** [comment]
Hi, @Frestho Is it possible for your instructional team to use the https://data100.datahub.berkeley.edu/ hub for this particular assignment? You might need to check if all the necessary packages are installed in the hub. It allocates 4 GB RAM for each student and could be a short-term resolution for your requirement. Let us know if this is the direction you are interested to explore?

If you are particular about using datahub.b.e then the alternative is to create a dummy bcourses project, add students to the roster and share the bcourses id with us. Here is the [link](https://rtl.berkeley.edu/services-programs/bcourses-project-sites) to create a bcourses site (Thanks Ryan).

**Comment by robyang1** [comment]
Hi @balajialg, thanks for the reply and some possible solutions. Fortunately, after changing some of the starter code for the lab, it is now able to run with the default 1GB of memory. Thanks for the information, which might come in handy in future iterations of this decal. For now this is resolved!
