### ISSUE TITLE
pulling new stat20data R package into Stat 20 image

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-dsep-infra/hubs#5689]
We're looking to update to the newest version of the [stat20data package](https://github.com/stat20/stat20data). I went to add it to the appropriate file and was kinda surprised to see that instead of installing it directly from github, we've been doing it via a symlink.

https://github.com/berkeley-dsep-infra/datahub/blob/64886052d401a12fce0bb381d2df36caf63d0887/deployments/stat20/image/r-packages/2023-fall-stat-20.r#L47

@ryanlovett Do you recall why it was set up this way? Is there any reason to do it this way instead of adding it as another `install_github()` line?

**Comment by ryanlovett** [comment]
@andrewpbray Yes, this was to enable you to do rapid development. By pulling into that directory, you could avoid the CI round trip. This was when you were changing the package frequently while you were teaching.

Shall we change the installation to be like all of the other libraries?

**Comment by andrewpbray** [comment]
Ah, good memory!

Yes, I think it probably makes sense to bring this in line with the other packages. I'll open a PR.
