### ISSUE TITLE
Question about Datahub file sharing

### ISSUE THREAD

**Issue by shanpierson** [berkeley-dsep-infra/hubs#5707]
### Bug description

I'm using Berkeley's Datahub to access RStudio to clean some data and run some statistical analyses. This is a collaborative project, and I'd like to share access with my co-investigator so that we can be operating in the same environment with the same up-to-date data. Do you know if I can simply share this RStudio environment with her? Or is the easiest way to do this via a Github repository, then just update the Rdata files and csvs with push/pull requests? I'm an R novice and Datahub neophyte, so apologies if this quesiton is basic

### Environment & setup

- Hub: 
- Language:

**Comment by balajialg** [comment]
@shanpierson, Is this request related to a course you’re instructing or is it for your own research? If it’s for a course, could you provide details about the course, such as the number of students, size of the data etc.? If it is for your research, you might benefit reaching out to the [Research IT team ](https://research-it.berkeley.edu/connect-us/contact-us) and explore their [offerings](https://research-it.berkeley.edu/services-projects).

(Assuming this request is for a course) The most straightforward solution would be to store your files in a Github repository or Google Drive and manage the data through push/pull operations. The other option is that we can set up a [shared-read-write directory](https://ds-modules.github.io/curriculum-guide/technology/jupyter/large-datasets.html?highlight=shared+read#larger-datasets-tens-of-mbs-to-several-gbs) where you and your collaborator can store the data and perform read/write operations. We will require your course’s bcourses ID to ensure that the data stored in this drive is only accessible to your bcourses project participants.

**Comment by shanpierson** [comment]
It's for our research! We are faculty. I'll reach out to the Research IT team :)

**Comment by balajialg** [comment]
Sounds good
