### ISSUE TITLE
Setup MaCSS datahub

### ISSUE THREAD

**Issue by aculich** [berkeley-dsep-infra/hubs#5710]
# Summary

Requesting a new datahub on behalf of Heather Haveman (Faculty Director) for the [Master of Computational Social Science (MaCSS)](https://macss.berkeley.edu/)

# Important information

This datahub needs to be configured to support [the coursework](https://macss.berkeley.edu/curriculum/) for this one-year Masters program including the Summer Bootcamp (6 units), Fall Semester (14 units), Spring Semester (14 units).

Additionally, it should support Capstone Projects. The capstone provides students with an opportunity to apply their coursework to a current real-world problem and hone their collaborative and leadership skills in preparation for their job search. However, some projects may exceed the capabilities of the default configuration in which case, we'll need to consider on a case-by-case basis whether we resource more resources on this datahub, or if some projects need to be directed to another resources (Savio, Jetstream, etc).

# Tasks to complete
- Collect list of required packages (start with defaults from the vanilla datahub)
- Create [macss.datahub.berkeley.edu](https://macss.datahub.berkeley.edu/) to follow the standard *.datahub.b.e naming conventions
- Create a redirect from datahub.macss.berkeley.edu to the new macss.datahub.b.e above.

**Comment by balajialg** [comment]
Additional request from COMPSS 201 instructor Adam Obeng: 
- Part of the instruction is setting up python and OS packages. Would it be possible to have two different environments, one which is bare-bones which the students can practice setting up correctly, and one which has all the required packages pre-installed?
- SSH access to a Jupyterhub via https://github.com/yuvipanda/jupyterhub-ssh

**Comment by balajialg** [comment]
@aculich I am closing this issue since the MACSS program folks found the generic datahub to suit their use case. Let's chat if you think the issue should remain open.
