### ISSUE TITLE
Add code-server (jupyter-vscode-proxy) to JupyterHub?

### ISSUE THREAD

**Issue by cboettig** [berkeley-dsep-infra/hubs#5716]
# Summary

VSCode (code-server) interface is a popular and feature-rich IDE that already integrates nicely with Jupyterlab via `jupyter-vscode-proxy`

# User Stories

- Lots of users know or use VSCode.
- Code server handles additional proxy ports nicely.  e.g. `streamlit run app.py` we get a pop-up linking us to our new port, and a handy 'ports' tab to manage ports.  
- Code server packages integration with GitHub device authentication automatically.  
- Code server has a rich library of extensions and cross-language support. 

# Acceptance criteria

When VSCode shows up in the launcher! 

![image](https://github.com/berkeley-dsep-infra/datahub/assets/222586/afc56d32-8595-4365-91ed-e8ff66068553)

# Important information

# Tasks to complete

- install the python package `jupyter-vscode-proxy`

**Comment by balajialg** [comment]
@cboettig I am assuming this request is for https://datahub.berkeley.edu/? Is there a specific deadline for completing this request?

FYI, you can launch VSCode in [EECS Hub](https://auth.berkeley.edu/cas/login?service=https%3A%2F%2Fbcourses.berkeley.edu%2Flogin%2Fcas)

**Comment by cboettig** [comment]
@balajialg sorry yes! for https://datahub.berkeley.edu/.  This would be for Fall (2024) semester!

**Comment by shaneknapp** [comment]
@cboettig this is now live on staging.datahub.berkeley.edu!  could you give it a whirl and let me know if we're good to merge to prod?

**Comment by cboettig** [comment]
Works beautifully, thanks!

side note related to #5513 -- from code-server, if we do `git clone` on a github repo, code-server automatically launches GitHub plugin and does device authentication similar to `gh-scoped-creds`.  It has different defaults, notably, it requests scopes that give it access to all a users organizations, probably not ideal, and I have no idea how long the temporary credential persists for.   On the plus side, the UI/UX experience is quite solid, prompts you with pop-up, auto-copies the device login code.  if you refuse auth this way, it falls back on the usual interface prompting for user name and password.  reasonably smooth!
