### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by nivkris19** [berkeley-dsep-infra/hubs#5781]
### Your UC Berkeley Email Address

krishnamurthyniv@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2023-2-summer/datahub/krishnamurthyniv.tar.gz

**Comment by balajialg** [comment]
signed URL sent

**Comment by nivkris19** [comment]
I only recieved my Bio1B files and not my Data8 files
