### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by Dinaeva** [berkeley-dsep-infra/hubs#5784]
### Your UC Berkeley Email Address

dinaevazade@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2023-2-summer/eecs/dinaevazade.tar.gz

https://datahub.berkeley.edu/user/dinaevazade/lab?

**Comment by balajialg** [comment]
signed URL sent

**Comment by Dinaeva** [comment]
Hi, why was the request closed? I have not received a URL or any further instruction.

**Comment by Dinaeva** [comment]
So sorry, it is here, just went to spam for some reason. I am downloading the data now. Thank you!
