### ISSUE TITLE
Git repository synchronization is failing on Datahub

### ISSUE THREAD

**Issue by briangstern** [berkeley-dsep-infra/hubs#5787]
### Bug description

Navigating to Datahub for DATASCI 200 is failing during git repository synchronization.  This appears to have started happening on either 6/6 or 6/7.

When I navigate to the following link:

https://datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/UC-Berkeley-I-School/datasci-200-Drills&urlpath=lab%2Ftree%2Fdatasci-200-Drills/week_06/Modules%20and%20Packages%20Drill.ipynb&branch=main

I get the following error:

Traceback (most recent call last):
File "/srv/conda/lib/python3.11/site-packages/nbgitpuller/handlers.py", line 87, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/conda/lib/python3.11/site-packages/nbgitpuller/pull.py", line 80, in __init__
    elif not self.branch_exists(self.branch_name):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/conda/lib/python3.11/site-packages/nbgitpuller/pull.py", line 92, in branch_exists
    heads = subprocess.run(
            ^^^^^^^^^^^^^^^
File "/srv/conda/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-remote', '--heads', '--', 'https://github.com/UC-Berkeley-I-School/datasci-200-Drills']' returned non-zero exit status 128.

### Environment & setup

Datahub

### How to reproduce

Navigate to: https://datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/UC-Berkeley-I-School/datasci-200-Drills&urlpath=lab%2Ftree%2Fdatasci-200-Drills/week_06/Modules%20and%20Packages%20Drill.ipynb&branch=main

**Comment by shaneknapp** [comment]
i also got this error, but when i attempted to visit the repo it's calling, i get a 404 not found...

![image](https://github.com/berkeley-dsep-infra/datahub/assets/1606572/53695fd3-8a7a-49e9-973b-441d7e9a36b5)

is this a private repo?  if so, you can install the github app to allow access:  https://docs.datahub.berkeley.edu/en/latest/users/private-repo.html

**Comment by briangstern** [comment]
Oh, that's interesting.  It's not a private repo, it's the repo that's being used by the DATASCI 200 courses.  Any idea who might be the owner of this?

**Comment by balajialg** [comment]
@briangstern I agree with @shaneknapp that it seems like a private repo as I am not able to find the repo by searching "Drill" in the public repos listed as part of the Ischool Github org. These are the folks associated with this particular Github org.

<img width="1066" alt="Screenshot 2024-06-10 at 1 42 13 PM" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/5b693970-6269-4339-8e4d-91de8198a7d6">

**Comment by briangstern** [comment]
Thank you very much.  I've shot a note to the DATASCI 200 instructors, but I will ping these owners as well.  I'll close this issue and follow-up with the github owners.  Really appreciate your help.
