### ISSUE TITLE
Data 100 Summer Staff Privileges

### ISSUE THREAD

**Issue by Kevin-Miao** [berkeley-dsep-infra/hubs#5802]
### Your Name

Kevin Miao

### Affiliated Course Name

Data 100

### bCourses ID

1535115

### Role

Instructor

### Hub URL

data100.datahub.berkeley.edu

### End Date

08/15/2024

### Request Deadline

Sorry for the super late heads-up. It would be nice to get this set up by Wednesday 6/19.

**Comment by Kevin-Miao** [comment]
CC: @jcbym

**Comment by balajialg** [comment]
@Kevin-Miao I have merged the config changes to https://data100-staging.datahub.berkeley.edu/. You can test whether you have enhanced privileges in another 20 minutes (and let me know if you have any issues). I will let you know once the changes gets merged to prod.

**Comment by Kevin-Miao** [comment]
Thank you Balaji! 🙌

**Comment by shaneknapp** [comment]
it's actually not deployed yet...  there's something up w/the config.  i'll try and get this debugged ASAP.

**Comment by shaneknapp** [comment]
ok, this is now live on data100-staging.datahub.berkeley.edu ... let me know if you can see your elevated privs!

**Comment by Kevin-Miao** [comment]
I can log into staging, but do not have access to the elevated permissions.

**Comment by balajialg** [comment]
@Kevin-Miao I created a new group named "Admins" in https://bcourses.berkeley.edu/courses/1535115. Can you please add the folks who require elevated permissions in this group? Once you add them to the group, ask them to log out and log back in so that the changes from bcourses gets applied. Let us know if you face any issues!

**Comment by Kevin-Miao** [comment]
@balajialg Hmm it doesn't let me add staff. Since Canvas only allows for students to be added to the group.

**Comment by balajialg** [comment]
@Kevin-Miao I have changed the allocation based on enrollment type and created a new [PR](https://github.com/berkeley-dsep-infra/datahub/pull/5814/commits/6e01877adaf1ef1f9c1f34f7c7a32fe6d85a0706). Once it gets merged to staging, will give an update
 
@shaneknapp I haven't merged the PR to staging yet as I want your fresh pair of eyes (to avoid a deploy failure; I have tested it in yaml linter already)

**Comment by ryanlovett** [comment]
@Kevin-Miao If you need non-students to appear in manually created groups, you can also add them to the bCourse as students. One person can be both a student and an instructor, observer, ta, etc. It is odd that bCourses doesn't let non-student enrollment types into groups.

@balajialg's patch uses the enrollment type to identify course staff, so if that finds the same people that are specified in your manual Admin group, it is easier to use the former.

**Comment by balajialg** [comment]
@Kevin-Miao I can close [this PR](https://github.com/berkeley-dsep-infra/datahub/pull/5814) if you go with @ryanlovett's suggestion to add users to admin group. If not, I can merge the above PR to staging.

**Comment by Kevin-Miao** [comment]
I can confirm @ryanlovett 's solution works! Thank you for helping us debug this. :)

**Comment by balajialg** [comment]
Awesome
