### ISSUE TITLE
jupyterlab-git integration setup for ESPM-157

### ISSUE THREAD

**Issue by cboettig** [berkeley-dsep-infra/hubs#5826]
### Package Name

jupyterlab-git extension

### Hub URL

datahub.berkeley.edu

### Course Name

ESPM-157

### Semester Details

Fall 2024

### Installation Deadline

Start of semester

**Comment by balajialg** [comment]
@cboettig Thanks, Is this a duplicate of https://github.com/berkeley-dsep-infra/datahub/issues/5513 where you highlighted that gh-scoped-creds needs to be enabled for Datahub?

**Comment by cboettig** [comment]
Sorry I was too terse in the template issue.  I think this is different, I'd like students to be able to use https://github.com/jupyterlab/jupyterlab-git?tab=readme-ov-file#jupyterlab-git GUI, which I think is a distinct dependency from https://github.com/jupyterhub/gh-scoped-creds

**Comment by balajialg** [comment]
@cboettig Thanks, that's helpful to know!

**Comment by balajialg** [comment]
@cboettig This is currently enabled in https://staging.datahub.berkeley.edu along with gh-scoped-creds requested in #5513!

**Comment by balajialg** [comment]
Closing this issue as the changes got merged to prod
