### ISSUE TITLE
PH142 Course Staff Datahub Admin Access

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#5831]
### Your Name

Paula Marquez

### Affiliated Course Name

Public Health 142 Intro to Prob and Biostats

### bCourses ID

1535789

### Role

TA

### Hub URL

publichealth.datahub.berkeley.edu

**Comment by paulamarm** [comment]
@paulamarm Thanks, I am removing the email ids in consideration of FERPA guidelines. I think sharing bcourses id as part of Github issues is good enough for us as long as you have added the following folks as TA/Teacher roles in the bcourses project listed.

**Comment by ryanlovett** [comment]
Hi @paulamarm , DataHub staff cannot access each bcourse site to manage roles, however course staff should be able to manage that directly. That information is typically seeded from the Student Information System (SIS) to start with.

**Comment by balajialg** [comment]
@paulamarm I have merged the config changes to https://publichealth-staging.datahub.berkeley.edu/. You can test whether your course staff have elevated privileges and let me know if you have any issues. I will let you know once the changes gets merged to prod

**Comment by balajialg** [comment]
Closing this issue as changes were merged to prod. @paulamarm Please reopen if there are any open issues.
