### ISSUE TITLE
Data 8 Course Staff Datahub Admin Access

### ISSUE THREAD

**Issue by jonathanferrari** [berkeley-dsep-infra/hubs#5834]
### Your Name

Jonathan Ferrari

### Affiliated Course Name

Data 8

### bCourses ID

1535365

### Role

Course Director

### Hub URL

data8.datahub.berkeley.edu

### End Date

- 08/10/24

### Request Deadline

Hopefully ASAP, but not extremely urgent.

**Comment by balajialg** [comment]
@jonathanferrari I have merged the config changes to https://data8-staging.datahub.berkeley.edu/. You can test whether your course staff have elevated privileges and let me know if you have any issues. I will let you know once the changes gets merged to prod

**Comment by jonathanferrari** [comment]
@balajialg looks like we have access, thanks so much!

**Comment by balajialg** [comment]
Thanks @jonathanferrari! Closing this issue as changes were merged to prod
