### ISSUE TITLE
Request more RAM for Data 6

### ISSUE THREAD

**Issue by jedwin3210** [berkeley-dsep-infra/hubs#5849]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

datahub.berkeley,edu

**Which class is this request for?**

2024 Summer, Data 6

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/data-6 (unlisted for summer since its reserved for SEED and Tuskegee Scholars)

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1535590

**How many students do you expect in this class?**

40

**How much RAM per user is needed?**

2gb (I'll update if there needs to be more)

**Why does this class need this much RAM?**

small labs run out of ram, so hw can become an issue

**By what date (MM/DD) do you want this request to be fulfilled?**

7/9/24

**Until when (MM/DD) do you require the additional RAM?**

8/9/24

**Any additional information we should know about?**

I can update if we run into further issues

**Comment by balajialg** [comment]
Closing this issue as it got completed via #5850
