### ISSUE TITLE
Datahub Internal Server Error Code

### ISSUE THREAD

**Issue by minamohebbi** [berkeley-dsep-infra/hubs#5857]
### Bug description

All of my work on datahub disappeared even though I saved and was able to access the notebooks as of 7/6/2024. Additionally, every time I click on my instructor's links to notebooks for assignments, I get error code 500: Internal Service Error. I cannot create or save any new notebooks in R, Python, or Terminal.

### Environment & setup

- Hub: Datahub for MACSS
- Language: Python, R, Terminal

### How to reproduce

Click this link: https://datahub.berkeley.edu/user/minamohebbi/notebooks/COMPSS-202-SU24/Guided%20Projects/compss202_su24_project01.ipynb

File error load appears.

**Comment by minamohebbi** [comment]
This is the error code I get in my terminal:

jovyan@jupyter-minamohebbi:~$ jupyterhub --ip=0.0.0.0
[I 2024-07-12 19:44:08.773 JupyterHub app:2885] Running JupyterHub version 4.1.5
[I 2024-07-12 19:44:08.773 JupyterHub app:2915] Using Authenticator: jupyterhub.auth.PAMAuthenticator-4.1.5
[I 2024-07-12 19:44:08.773 JupyterHub app:2915] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-4.1.5
[I 2024-07-12 19:44:08.773 JupyterHub app:2915] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.1.5
[I 2024-07-12 19:44:08.782 JupyterHub app:1728] Writing cookie_secret to /home/jovyan/jupyterhub_cookie_secret
[I 2024-07-12 19:44:08.856 alembic.runtime.migration migration:216] Context impl SQLiteImpl.
[I 2024-07-12 19:44:08.856 alembic.runtime.migration migration:219] Will assume non-transactional DDL.
[I 2024-07-12 19:44:09.015 alembic.runtime.migration migration:622] Running stamp_revision  -> 0eee8c825d24
[I 2024-07-12 19:44:10.045 JupyterHub proxy:557] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2024-07-12 19:44:10.248 JupyterHub app:2005] Not using allowed_users. Any authenticated user will be allowed.
[I 2024-07-12 19:44:10.310 JupyterHub app:2954] Initialized 0 spawners in 0.010 seconds
[I 2024-07-12 19:44:10.331 JupyterHub metrics:279] Found 0 active users in the last ActiveUserPeriods.twenty_four_hours
[I 2024-07-12 19:44:10.335 JupyterHub metrics:279] Found 0 active users in the last ActiveUserPeriods.seven_days
[I 2024-07-12 19:44:10.338 JupyterHub metrics:279] Found 0 active users in the last ActiveUserPeriods.thirty_days
[W 2024-07-12 19:44:10.339 JupyterHub proxy:747] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2024-07-12 19:44:10.339 JupyterHub proxy:751] Starting proxy @ http://0.0.0.0:8000/
[E 2024-07-12 19:44:10.340 JupyterHub proxy:759] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`.To install `npm`, install nodejs which includes `npm`.If you see an `EACCES` error or permissions error, refer to the `npm` documentation on How To Prevent Permissions Errors.
[C 2024-07-12 19:44:10.340 JupyterHub app:3165] Failed to start proxy
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.11/site-packages/jupyterhub/app.py", line 3163, in start
        await self.proxy.start()
      File "/srv/conda/lib/python3.11/site-packages/jupyterhub/proxy.py", line 755, in start
        self.proxy_process = Popen(
                             ^^^^^^
      File "/srv/conda/lib/python3.11/subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/srv/conda/lib/python3.11/subprocess.py", line 1955, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy'

**Comment by felder** [comment]
I logged in as an admin, started up your server and noted this error in the hub log:

```
[W 2024-07-15 10:20:18.503 ServerApp] Cannot load /pyproject.toml: Invalid value (at end of document)
[E 2024-07-15 10:20:18.504 ServerApp] Uncaught exception GET /user/minamohebbi/api/contents?content=1&1721064018443 (10.
24.0.97)
    HTTPServerRequest(protocol='https', host='datahub.berkeley.edu', method='GET', uri='/user/minamohebbi/api/contents?c
ontent=1&1721064018443', version='HTTP/1.1', remote_ip='10.24.0.97')
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 155, in get
        self.contents_manager.get(
    TypeError: build_jupytext_contents_manager_class.<locals>.JupytextContentsManager.get() got an unexpected keyword ar
gument 'require_hash'
```
I then opened up a terminal and renamed pyproject.toml to pyproject.toml.old

I'd recommend doing your work in a subdirectory vs the root one (one for each assignment).  That may avoid similar issues in the future.

Your server seems to now be working properly.  Also, your files are still there it's just the interface was not loading correctly and wasn't displaying them.  Please let me know if anything else is not working properly.

**Comment by felder** [comment]
Upstream issue filed for this, since a malformed file in the userspace filesystem should probably not cause this to happen to the UI:
https://github.com/jupyter-server/jupyter_server/issues/1443

I should also note that we were able to reproduce this in our accounts in staging.
