### ISSUE TITLE
COMPSS 202 summer 2024

### ISSUE THREAD

**Issue by ryanedw** [berkeley-dsep-infra/hubs#5861]
### Your Name

Ryan D. Edwards

### Affiliated Course Name

COMPSS 202

### bCourses ID

1535811

### Role

Instructor of record

### Hub URL

datahub.berkeley.edu

### End Date

- 
08/14/24

### Request Deadline

07/21

**Comment by balajialg** [comment]
@ryanedw Changes are merged to https://staging.datahub.berkeley.edu/. I will let you know once the changes gets merged to prod.

**Comment by balajialg** [comment]
@ryanedw You should have elevated privileges since the changes were merged to prod. Please let me know if there are any issues with access. Thanks!
