### ISSUE TITLE
Request more RAM for Data 100 Summer 2024

### ISSUE THREAD

**Issue by jcbym** [berkeley-dsep-infra/hubs#5862]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Data 100 Hub (data100.datahub.berkeley.edu)

**Which class is this request for?**

Data 100 Summer 2024

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-summer-data-c100-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1535115

**How many students do you expect in this class?**

150

**How much RAM per user is needed?**

4GB

**Why does this class need this much RAM?**

Memory intensive project (A2)

**By what date (MM/DD) do you want this request to be fulfilled?**

Ideally by tomorrow, 7/17. Sorry for the late request!

**Until when (MM/DD) do you require the additional RAM?**

7/29

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@jcbym quick clarification: Do you need the RAM increase at the latest by tomorrow morning or before EOD?

**Comment by jcbym** [comment]
@balajialg Tomorrow morning is perfectly ok! We have released the assignment already, but I don't expect any students to run into issues with memory this soon after release. Apologies for the late notice and thank you so much for the quick turnaround!

**Comment by balajialg** [comment]
@jcbym Thanks, will update you once the changes gets merged to prod

**Comment by balajialg** [comment]
@jcbym Changes were merged to prod. Please reopen this issue if there are any issues.

**Comment by jcbym** [comment]
Thanks so much!!
