### ISSUE TITLE
Issues with Mass package in Econ 140. Bump R version to the latest in Datahub/R Hub?

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#5873]
### Bug description

*Message from Econ 140 instructor - Seamus Li  (https://classes.berkeley.edu/content/2024-summer-econ-140-001-lec-001)

Greetings. My class has been running into the following issue with R on Datahub:

```
> library("ivreg")
Error: package or namespace load failed for ‘ivreg’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘MASS’
> install.packages("MASS")
Installing package into ‘/srv/r’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘MASS’ is not available for this version of R
‘MASS’ version 7.3-61 is in the repositories but depends on R (>= 4.5)
‘MASS’ version 7.3-61 is in the repositories but depends on R (>= 4.4.0)

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

And...

> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.2                         
year           2023                        
month          10                          
day            31                          
svn rev        85441                       
language       R                           
version.string R version 4.3.2 (2023-10-31)
nickname       Eye Holes  

```

Since MASS is a dependency for a number of common R packages, this has resulted in some course codes breaking and quite a few confused students. We're currently getting around this problem by force installing an older version of MASS via

`renv::install("MASS@7.3-60")
`

Though it seems that the best solution would be to upgrade the R to the latest version. Thank you for your attention to this issue. This is not very urgent since we have a work around. The issue is relatively new and we're rolling back the dependency by just one release, but over time the dependency chain might become completely broken for a lot of packages on older versions of R.

### Environment & setup

- Hub: Datahub, R Hub
- Language: R

### How to reproduce

- install.packages("ivreg")
- library("ivreg")
- install.packages("MASS")

**Comment by balajialg** [comment]
Tagging @seamus-x who is the instructor for this course

**Comment by balajialg** [comment]
@shaneknapp Should this request be scoped for maintenance window?

**Comment by shaneknapp** [comment]
yes please!

**Comment by balajialg** [comment]
@seamus-x Upgrade to the latest version of R in Datahub is done by @shaneknapp. Please feel free to reopen this issue if you don't see those changes.
