### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by mnazneen** [berkeley-dsep-infra/hubs#5888]
### Your UC Berkeley Email Address

moyrarasheed39@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2023-3-fall/publichealth/moyrarasheed39.tar.gz

**Comment by balajialg** [comment]
Signed URL sent

**Comment by mnazneen** [comment]
Good Morning.
My data hub for PHW 142  was working and today as of 10:15 am , it states
services are not provided. I am still preparing for my exam. May I please
continue my access.
Also I don't have access to my data hub for my R class as well. May I have
access to all the material for booth R and PHW 142?
Sincerely,Moyra

**Comment by mnazneen** [comment]
![image](https://github.com/user-attachments/assets/1f9e31d8-d1db-4c21-8dfc-0c1ad16b8aca)

**Comment by shaneknapp** [comment]
we're currently in our pre-semester maintenance window, and the hub should be back up by EOD today.

**Comment by mnazneen** [comment]
Awesome, thanks for the update! That is good to know! Thank you!

**Comment by mnazneen** [comment]
data hub seemed to start working for me... I thought the maintenace is complete. When I tried to open it, I recieved a different error:
![image](https://github.com/user-attachments/assets/9109ec07-ee0b-48f8-8631-ae38fb46e624)
[Doc6.docx](https://github.com/user-attachments/files/16629380/Doc6.docx)

Please let me know if data hub is stillin maintenance. I have 1 day off from work today and I was trying to complete 3 chapters using data hubs homework and labs today in prep for my exam. Sincerely,Moyra Rasheed

**Comment by mnazneen** [comment]
I am getting this now when I go to 142s site on data hub: 
[Doc9.docx](https://github.com/user-attachments/files/16629422/Doc9.docx)

**Comment by mnazneen** [comment]
![image](https://github.com/user-attachments/assets/f7bccd71-d78d-40f7-940f-d27d9c007962)

**Comment by balajialg** [comment]
@mnazneen Can you try accessing datahub via https://publichealth.datahub.berkeley.edu/. You should be able to navigate to your files if you had used it before. The error you face might be due to [this issue](https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html?highlight=troubleshoot+nbgitpuller#the-nbgitpuller-link-has-been-used-before-and-some-of-the-content-was-changed-in-both-datahub-and-github).

To answer your question, yes - we are still in maintenance window and that may result in intermittent outages. However, that is not related to the issue you face now.

**Comment by mnazneen** [comment]
ok the link you sent me is working , but when i go onto the data hub in the
course, it gives me the same error. Will I be able to have access to that
link again by any chance?
Also I tried my R data hub link which was different and it is also showing
me an error. The r homework and assignments are not part of the data hub
you sent me.

**Comment by mnazneen** [comment]
Data hub is working now. I apologize for the multiple emails back and
forth. i am relieved. is there any way i can have my data hub back for my r
course 251 LEC 001,Fall 2022?
Thank you.Sincerely,Moyra Rasheed

**Comment by shaneknapp** [comment]
could you please open a new archive retrieval request for this?

**Comment by mnazneen** [comment]
could you please open a new archive retrieval request for this?
How can I open up a new archive request retrieval for this?
Sincerely,Moyra

**Comment by balajialg** [comment]
@mnazneen https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg%2Cshaneknapp&labels=support%2Cdata+retrieval&projects=&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub
