### ISSUE TITLE
Request basic man pages for Stat department incoming student workshop

### ISSUE THREAD

**Issue by paciorek** [berkeley-dsep-infra/hubs#5906]
### Package Name

`man` and manpages for basic shell tools (e.g., `ls`, `echo`)

### Hub URL

datahub.berkeley.edu

### Course Name

We're developing a new workshop for incoming Statistics graduate students on computational tools. This will be useful for that as we are planning to use DataHub.

### Semester Details

August 2024 (pre-semester workshop)

### Installation Deadline

Workshop is Aug 20-23.

I've discussed this in person with @ryanlovett

**Comment by paciorek** [comment]
I just stopped and restarted my server, and `man ls` etc. still give the same message below. Should I and my users run `unminimize` ourselves?

```
jovyan@jupyter-paciorek:~$ man echo
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.
```

**Comment by ryanlovett** [comment]
@paciorek The relevant packages were installed and are available on staging. This PR will need to be merged to production which will happen soon. However Ubuntu does some additional things in the container like installing `man` as a wrapper script where the real program is `man.REAL`. It also excludes the installation of some manpages. I'll need to fiddle with this a bit more.

**Comment by ryanlovett** [comment]
I'm altering the `man` configuration in #5916.

**Comment by ryanlovett** [comment]
`man` is now working, although not all pages are there. You can `man R`, `man open`, `man vi`, but some basic pages are missing. I think this is because coreutils is installed before the man fix, so we'd have to reinstall coreutils.

@paciorek is this sufficient? The changes are on staging.datahub.berkeley.edu and will get merged to prod soon.

**Comment by paciorek** [comment]
Ideally there'd be man pages for `ls`, `cp`, and `mkdir`. 

But for my workshop I can use `--help` for all of these for my participants to do what they need to do. So not critical.

**Comment by ryanlovett** [comment]
Okay, those are all coreutils. I'll see if I can fix it.

man is now available on datahub however, and many packages do have man pages installed, including man's own.

**Comment by shaneknapp** [comment]
is this completed?

**Comment by ryanlovett** [comment]
@shaneknapp Yes!
