### ISSUE TITLE
Request `/usr/bin/tree` for August workshop

### ISSUE THREAD

**Issue by paciorek** [berkeley-dsep-infra/hubs#5908]
### Package Name

apt package providing `tree`

### Hub URL

datahub.berkeley.edu

### Course Name

see issue #5906

I discussed this with @ryanlovett in person.

### Semester Details

August 2024 (pre-semester workshop)

### Installation Deadline

Aug 20-23.

**Comment by ryanlovett** [comment]
Fixed by #5912.
