### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by majdmuna** [berkeley-dsep-infra/hubs#5913]
### Your UC Berkeley Email Address

majd@berkeley.edu

### Link to Your Datahub Folder

Datahub itself isn't loading for me so I'm not able to go to the home directory. However, i would assume based on the example that it would be:

gs://ucb-datahub-archived-homedirs/fall-2020/datahub.berkeley.edu/majdmuna.tar.gz

**Comment by balajialg** [comment]
@majdmuna I need a link from the file "WHERE-ARE-MY-FILES.txt" left in your home directory from the hubs you actually used. The following example is the link you get from"WHERE-ARE-MY-FILES.txt" when you log into the hub and you should include it as part of this request. 

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/USER_ID.tar.gz

We cannot service this request without this information.

**Comment by majdmuna** [comment]
Hi @balajialg , i'm not able to get into the home directory of the jupyter hub that i used. It tells me there is no account for the user, although i've used it for many years. I can't get into bCourses either as a result as it says Canvas doesn't have an account for the user.

**Comment by balajialg** [comment]
@majdmuna I searched for the files manually, found it in 2022-fall folder (gs://ucb-datahub-archived-homedirs/2022-3-fall/datahub/majd.tar.gz) and sent you the signed URL which is valid for 7 days. Generally,  If you don't have access to bcourses, I would suggest emailing [bcourseshelp@berkeley.edu](mailto:bcourseshelp@berkeley.edu) to get access to bcourses which in turn will allow you to log into Datahub.

**Comment by majdmuna** [comment]
@balajialg thank you so much! just received it on my email. I appreciate your help! will also send bcourseshelp@berkeley.edu an email, hopefully they aren't removing access for alumni
