### ISSUE TITLE
MBA247 Request Elevated Privileges for Course Staff

### ISSUE THREAD

**Issue by luyi-yang** [berkeley-dsep-infra/hubs#5923]
### Your Name

Luyi Yang

### Affiliated Course Name

MBA 247 Descriptive and Predictive Data Mining

### bCourses ID

1536576

### Role

Instructor

### Hub URL

datahub.berkeley.edu

### End Date

- 
Nov 1, 2024

### Request Deadline

August 25, 2024

**Comment by balajialg** [comment]
Addressed via #5952
