### ISSUE TITLE
Request R package Factoextra for class MBA247

### ISSUE THREAD

**Issue by luyi-yang** [berkeley-dsep-infra/hubs#5947]
### Package Name

Factoextra

### Hub URL

datahub.berkeley.edu

### Course Name

MBA 247 Descriptive and Predictive Data Mining
https://bcourses.berkeley.edu/courses/153657
Instructor: Luyi Yang

### Semester Details

Fall 2024

### Installation Deadline

ASAP

**Comment by balajialg** [comment]
@luyi-yang Changes addressing this request and #5923 are merged to https://staging.datahub.berkeley.edu/. I will give you an update once it gets merged to https://datahub.berkeley.edu/.

**Comment by balajialg** [comment]
@luyi-yang Changes are merged to https://datahub.berkeley.edu/. I am closing both of your issues right now. Please feel free to reopen it if there are any issues!
