### ISSUE TITLE
Data Retrieval Request for All Files, including the datasp21 files,  in Jupyter Notebook

### ISSUE THREAD

**Issue by beatricele** [berkeley-dsep-infra/hubs#5987]
### Your UC Berkeley Email Address

 beatricele@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/fall-2021/data100.berkeley.edu/beatricele.tar.gz

**Comment by beatricele** [comment]
Hello, I am still a current student at UC Berkeley. I only became aware that my files have been archived/were gone when I logged into my Jupyter notebook. Besides the data100 files, I also need my other files. I unfortunately do not have a tar.gz link or any other link to those files but I would like to get them all back since a majority of them are related to the progress of my current PhD Project.

**Comment by balajialg** [comment]
@beatricele Signed URL sent!
