### ISSUE TITLE
Request python package X for class Y

### ISSUE THREAD

**Issue by ingolia** [berkeley-dsep-infra/hubs#5988]
### Package Name

MACS2

### Hub URL

biology.datahub.berkeley.edu

### Course Name

MCELLBI201B

### Semester Details

Fall 2024

### Installation Deadline

09/09

**Comment by shaneknapp** [comment]
this will be live on biology-staging.datahub.berkeley.edu in ~45m for testing.  once it's deployed, please log in and confirm that the package is installed and working as intended.

thanks!

**Comment by shaneknapp** [comment]
ok it's live on biology-staging...  looks like the package installed correctly, but you should definitely kick the tires a bit before we merge this to prod.

```
jovyan@jupyter-sknapp:~$ pip list | grep -i macs
MACS2                     2.2.9.1
```

**Comment by ingolia** [comment]
Great—thanks! We're testing this out on the data set we'll use for the course.
Best,
–Nick

On Thu, Aug 22, 2024, at 13:18, shane wrote:
> 
> 
> ok it's live on biology-staging... looks like the package installed correctly, but you should definitely kick the tires a bit before we merge this to prod.
> 
> ***@***.***:~$ pip list | grep -i macs
> MACS2                     2.2.9.1
`

**Comment by shaneknapp** [comment]
be sure you check on https://biology-staging.datahub.berkeley.edu

**Comment by ingolia** [comment]
Hi all,

I restarted my server through the Hub Control Panel, and it looks like at
least on my end, that the base environment and qiime2 environment don't
show the updated package.

***@***.***:~$ macs2 -h
bash: macs2: command not found
***@***.***:~$ source activate qiime2
(qiime2) ***@***.***:~$ macs2 -h
bash: macs2: command not found

When I look through the current packages:

lz4                       3.1.3            py38hebdc3cf_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mafft                     7.487                h779adbc_0    bioconda
make                      4.3                  hd18ef5c_1    conda-forge
markupsafe                2.0.1            py38h497a2fe_1    conda-forge
matplotlib                3.4.3            py38h578d9bd_1    conda-forge
matplotlib-base           3.4.3            py38hf4fb855_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge


May you let me know if there's something I should do on my end to make sure
I'm updated correctly?

Thanks for your help!

Sincerely,
Jack

**Comment by shaneknapp** [comment]
please be sure you're logged in to https://biology-staging.datahub.berkeley.edu, and not https://biology.datahub.berkeley.edu 

i checked, and you're logged in to 'prod', not 'staging'...  :)

```
jovyan@jupyter-sknapp:~$ macs2 -h
usage: macs2 [-h] [--version] {callpeak,bdgpeakcall,bdgbroadcall,bdgcmp,bdgopt,cmbreps,bdgdiff,filterdup,predictd,pileup,randsample,refinepeak} ...

macs2 -- Model-based Analysis for ChIP-Sequencing

positional arguments:
  {callpeak,bdgpeakcall,bdgbroadcall,bdgcmp,bdgopt,cmbreps,bdgdiff,filterdup,predictd,pileup,randsample,refinepeak}
    callpeak            Main MACS2 Function: Call peaks from alignment results.
    bdgpeakcall         Call peaks from bedGraph output. Note: All regions on the same chromosome in the bedGraph file should be continuous so only bedGraph files
                        from MACS2 are accpetable.
    bdgbroadcall        Call broad peaks from bedGraph output. Note: All regions on the same chromosome in the bedGraph file should be continuous so only bedGraph
                        files from MACS2 are accpetable.
    bdgcmp              Deduct noise by comparing two signal tracks in bedGraph. Note: All regions on the same chromosome in the bedGraph file should be continuous
                        so only bedGraph files from MACS2 are accpetable.
    bdgopt              Operations on score column of bedGraph file. Note: All regions on the same chromosome in the bedGraph file should be continuous so only
                        bedGraph files from MACS2 are accpetable.
    cmbreps             Combine BEDGraphs of scores from replicates. Note: All regions on the same chromosome in the bedGraph file should be continuous so only
                        bedGraph files from MACS2 are accpetable.
    bdgdiff             Differential peak detection based on paired four bedgraph files. Note: All regions on the same chromosome in the bedGraph file should be
                        continuous so only bedGraph files from MACS2 are accpetable.
    filterdup           Remove duplicate reads at the same position, then save the rest alignments to BED or BEDPE file. If you use '--keep-dup all option', this
                        script can be utilized to convert any acceptable format into BED or BEDPE format.
    predictd            Predict d or fragment size from alignment results. *Will NOT filter duplicates*
    pileup              Pileup aligned reads with a given extension size (fragment size or d in MACS language). Note there will be no step for duplicate reads
                        filtering or sequencing depth scaling, so you may need to do certain pre/post-processing.
    randsample          Randomly sample number/percentage of total reads.
    refinepeak          (Experimental) Take raw reads alignment, refine peak summits and give scores measuring balance of waston/crick tags. Inspired by SPP.

options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

For command line options of each command, type: macs2 COMMAND -h
```

**Comment by shaneknapp** [comment]
how did the testing go?  i'd like to merge to prod as we have a ton of commits that i'd like to clear out of the staging queue.

**Comment by ingolia** [comment]
The test run went well for us—all good on this one, thanks!
–Nick

Nicholas Ingolia
Associate Professor
Molecular and Cell Biology
UC Berkeley

**Comment by shaneknapp** [comment]
awesome, i'll merge the changes to prod now.  thanks!
