### ISSUE TITLE
Data 140 Request to Elevate Privileges for Course Staff

### ISSUE THREAD

**Issue by mchxo** [berkeley-dsep-infra/hubs#6011]
### Your Name

Michael Xiao

### Affiliated Course Name

Data C140

### bCourses ID

1537389

### Role

Lead TA

### Hub URL

prob140.datahub.berkeley.edu

### End Date

- 
12/27/24

### Request Deadline

08/30

**Comment by balajialg** [comment]
@mchxo Changes are merged to https://prob140-staging.datahub.berkeley.edu/. You can test whether you have elevated privileges in the staging hub. I will let you know once it gets merged to prod.

**Comment by balajialg** [comment]
Closing this issue as changes were merged to prod!
