### ISSUE TITLE
Admin Access Ella DeGuzman

### ISSUE THREAD

**Issue by ella-deguzman** [berkeley-dsep-infra/hubs#6014]
### Your Name

Ella DeGuzman

### Affiliated Course Name

Data 8

### bCourses ID

1538208

### Role

Lead uGSI

### Hub URL

datahub.berkeley.edu

### End Date

-

**Comment by balajialg** [comment]
@ella-deguzman Is this request for datahub.berkeley.edu or data8.datahub.berkeley.edu? Please clarify. Also - You are not listed as a TA in [bcourses](https://bcourses.berkeley.edu/courses/1538208/). Other course staff might need to add you with the role "TA" in bcourses and then DataHub will pick up that information once you log out and log in. Can you confirm once this is done?

**Comment by balajialg** [comment]
@ella-deguzman I have enabled elevated privileges for the teaching team in Data 8 Hub and it is live in prod. If there are any discrepancies with the hub then please feel free to reopen this issue.
