### ISSUE TITLE
admin access to public health datahub for ph142

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#6026]
### Your Name

Paula Marquez

### Affiliated Course Name

Public Health 142 Intro to Prob and Biostats

### bCourses ID

1537782

### Role

TA- paulamarm 
TA - sean-xiangyu-yu
TA - XinruiRuan
TA- Sylvia-Song
TA- yilongHou
TA- juliapiccirillo
TA- zmxie109
Instructor - ahubb40
Instructor - taltman

### Hub URL

publichealth.datahub.berkeley.edu

### End Date

12/31/24 

### Request Deadline

non-urgent / by the beginning of the semester- thank you!

**Comment by balajialg** [comment]
@paulamarm I will create a PR to address this request. Some of the folks listed above are not added as a TA in [bcourses](https://bcourses.berkeley.edu/courses/1537782/). You need to add the other course staff with the role "TA" in bcourses and then Public Health Hub will pick up that information once the folks who are newly added as TA log out and log in. Can you confirm once this is done?

**Comment by balajialg** [comment]
Changes are merged to Public Health staging - https://publichealth-staging.datahub.berkeley.edu/. Can you please confirm whether you have the elevated privilege?

**Comment by paulamarm** [comment]
I think that the full roster of TAs were given TA roles in bCourses around 5pm this evening- I have admin access from the summer but I'm not sure how to check whether it merged for the others since I'm not seeing that instructors or anyone else have the admin box checked off

**Comment by ryanlovett** [comment]
@paulamarm In JupyterHub, you can have elevated privileges without having full admin. If you can visit the admin screen then you have been given elevated privileges.

**Comment by balajialg** [comment]
Closing this issue as the request got resolved. @paulamarm Please reopen if your teaching team still didn't have the required access.
