### ISSUE TITLE
Workshop hub gives '403 : Forbidden XSRF cookie does not match POST argument'

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#6032]
### Your Role

Instructor

### Affiliated Course Name

training workshops 

### Hub URL

other

### URL to the notebook file (.ipynb, .rmd etc..) with solutions

- 
if i go to workshop.datahub.berkeley.edu
and try to log in 
I get 403 : Forbidden
XSRF cookie does not match POST argument

I may need to clear cookies or cache or something 

it seems to only affect people who have previously logged in

### Number of Impacted Students

10

### Severity of the Issue

Medium Priority

### Issue timeline

ran a workshop last Thursday 

### Snapshots of issue

![image](https://github.com/user-attachments/assets/9fc0f0da-1edb-4c29-b028-b91bce70e1dd)

### Additional comments

not pressing but annoyin nonetheless

**Comment by shaneknapp** [comment]
is this still an issue?  i can't recall how to log in to the workshop hub to confirm/deny.

**Comment by balajialg** [comment]
Closing this issue as it seems to have been resolved (based on [slack conversation](https://uctech.slack.com/archives/C04NEF48SCR/p1732311056743459?thread_ts=1732234700.021879&cid=C04NEF48SCR))
