### ISSUE TITLE
All http requests are being redirected to https, causing failures

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#6061]
### Bug description

A markdown block with code like:

```
<img src="http://spiff.rit.edu/classes/phys240/lectures/parallax/hip_obs.gif">
```

leads to a broken image, because the http is getting automatically transformed into an https request, and that particular server does not have an SSL-enabled counterpart. From looking at the JS console, I see this error:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/202a89e3-5c80-4d40-bb8e-8976faba8bb7">

that shows the request went to a different URL than the source had.

This was noticed first by a student of @profjsb, manifesting as broken images that rendered fine on a local installation. We tracked it to this URL change.

### Environment & setup

- Hub: astro (also seen in the main datahub, and probably happens in all).
- Language: markdown cell

### How to reproduce

Create a markdown cell with:

```
<img src="http://spiff.rit.edu/classes/phys240/lectures/parallax/hip_obs.gif">
```

It should render an image, but doesn't.

**Comment by ryanlovett** [comment]
This is reproducible on the main hub in lab, nbclassic, in vscode's jupyter interface, and in quarto's jupyter and knitr renderers. I tracked this down to HSTS in the browser.

In Chrome, click on the icon to the left of the address in the URL bar, then `Site settings` then scroll to `Insecure content` and choose `Allow`. Reload jupyterlab in your browser. The same image that was broken before will display properly.
<img width="1427" alt="Screenshot 2024-08-30 at 5 41 50 PM" src="https://github.com/user-attachments/assets/4f2b2146-4437-4794-be07-8153eaca5f25">

If you change the setting back and reload, the image will break again.

One workaround is to host the image on a server that supports https, but that is painful if there are a lot of links. You could also include the image in the local environment (e.g. pulled via nbgitpuller) and change the references to be local. Finally you could convert the file to a base64-encoded string, e.g. `<img src="data:image/gif;base64,asdfasdfasdfasdf...">`, but that's more painful. Lastly one could try contacting the admin of the remote site and ask if they could enable https.

I'm not sure if there's anything we can do at the hub level though.

**Comment by balajialg** [comment]
Thanks @ryanlovett! Also, wanted to share the [documentation](https://ds-modules.github.io/curriculum-guide/workflow/download_notebook_as_pdf.html?highlight=embedding+image) to embed images in different ways as part of a Jupyter Notebook (for the Astro instructor's reference)

**Comment by felder** [comment]
Just to add to what Ryan said, serving http content within https pages are referred to as mixed content requests.  Modern browsers consider a lot of these sorts of requests to be a security risk and will refuse to load them when using default security settings.  Here's a bit more info regarding that:

https://www.cloudflare.com/learning/ssl/what-is-mixed-content/

The trend for mixed content requests is to become more and more restrictive with the goal of everything being served via https.  I highly recommend you do not use mixed content requests in your notebooks (meaning no http links).  In this case are you able to reach out to the website host for this content and have them enable https?  In 2024, there's seldom a good reason to even allow http.

@balajialg I scanned the linked docs, but did not read them super carefully.  If it's not in there already, we should add a blurb in the docs that specifically indicates that all image links should be https and not http.

**Comment by balajialg** [comment]
@felder Yes, I added a note about this issue in the documentation. Thanks!

**Comment by fperez** [comment]
Thanks a lot team for the detailed forensics, I learned a lot and really appreciate it!!

I hear @felder's points, though in this case it's made harder by the fact that the images being referenced are valid scientific images but hosted in a server beyond the author's control, and unlikely to be responsive to requests.

But at least with this diagnostic we can take preventive measures, and @profjsb can talk to his students about this issue.

One point I'm a bit confused about: do any of you know why it works "OK" (if in violation of these policies) when hosted locally? The browser is still talking to an https server on localhost, yet in that case it seems to accept the http request fine, without rewriting it. Is there an exception to the policy when specifically talking to localhost?

**Comment by fperez** [comment]
Ah, nvm - I was totally convinced that the default behavior on localhost was https, but that is incorrect. At least out of the box, on my machine, a simple `jupyter lab` call produces a server on `http://localhost:8888/lab?token=d1b14...`, NOT `https`.

That explains my confusion, many thanks!

I'll close this issue since it seems as resolved as it can be from your end, so as not to add to your triage backlog.

Many thanks again for your thorough help!!
