### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by lkdy2** [berkeley-dsep-infra/hubs#6084]
### Your UC Berkeley Email Address

lkdy@berkeley.edu

### Link to Your Datahub Folder

I can't find the WHERE-ARE-MY-FILES.txt file in my Datahub home directory. https://datahub.berkeley.edu/user/lkdy/lab/workspaces/auto-n

**Comment by balajialg** [comment]
signed URL sent

**Comment by lkdy2** [comment]
I don't have the 'WHERE-ARE-MY-FILES.txt' file in my home directory for some reason, but the files I'm looking for are from Fall 2023 and are in folders labeled 'ECON-130-FA23' and 'Econ 191' within my directory.

Here's an approximation based on the format of other links; not sure if this is accurate:
gs://ucb-datahub-archived-homedirs/2023-3-fall/datahub/lkdy.tar.gz

Hope this is helpful.

**Comment by balajialg** [comment]
Sent another set of files from your previous archive. Hopefully, those are the files you wanted.
