### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by grub-man** [berkeley-dsep-infra/hubs#6093]
### Your UC Berkeley Email Address

nixkdeng@berkeley.edu

### Link to Your Datahub Folder

https://datahub.berkeley.edu/user/nixkdeng/tree

**Comment by grub-man** [comment]
Unfortunately I don't see a "WHERE-ARE-MY-FILES.txt" in my datahub home directory. I have multiple folders containing past coursework as well as my code for my senior honors thesis, which are somehow all lost when I log in to datahub again a few days ago. I suspect it is due to my status as extended graduation student this fall, and my original E
GT is spring 2024. What shall I do to get them back? Thanks

This is what my current home directory looks like. All current files were added yesterday, but none of my past files remain.
<img width="1501" alt="Screenshot 2024-09-05 at 1 45 10 PM" src="https://github.com/user-attachments/assets/6d67a3da-36c0-4c91-9ad2-56abfffa95fb">

**Comment by balajialg** [comment]
signed URL sent
