### ISSUE TITLE
Request more RAM for Demog 213

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#6094]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

For example: Datahub (datahub.berkeley,edu)

**Which class is this request for?**

[Demog 213](https://github.com/berkeley-demography/demog-213-f24)

**What is the Academic Guide URL for this class?**

[https://classes.berkeley.edu/content/2024-fall-demog-213-001-dem-001](https://classes.berkeley.edu/content/2024-fall-demog-213-001-dem-001)

**What is the bCourses URL for this class?**

[https://bcourses.berkeley.edu/courses/1539545/](https://bcourses.berkeley.edu/courses/1539545/)

**How many students do you expect in this class?**

10

**How much RAM per user is needed?**

4GB of RAM per student.

**Why does this class need this much RAM?**

We will be working with larger datasets for students to practice R

**By what date (MM/DD) do you want this request to be fulfilled?**

Ideally by 9/10/2024

**Until when (MM/DD) do you require the additional RAM?**

12/20/2024

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@wrathofquan PR to increase RAM for Demog 214 got merged to staging hub - you can test the changes in https://staging.datahub.berkeley.edu/

**Comment by wrathofquan** [comment]
Thanks @balajialg. For some reason this staging hub link is not pulling from the course repo (https://github.com/berkeley-demography/demog-213-f24). Is that expected?

Also, I am showing 8GB of RAM which might be a holdover from a previous semester's request. 
<img width="540" alt="image" src="https://github.com/user-attachments/assets/402e0b77-b68a-4b87-a736-67e72b9a3fef">

**Comment by balajialg** [comment]
@wrathofquan That's weird! I can pull the R script to R Hub Staging using the following [nbgitpuller link](https://r-staging.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fberkeley-demography%2Fdemog-213-f24&branch=main&urlpath=rstudio%2F). Can you check whether this link works for you? If not, what is the error message you are getting?

Yes, You already have 8 GB provisioned through the [Data hackathon-related request](https://github.com/berkeley-dsep-infra/datahub/issues/4244) (RAM bump should end by the end of this month right?). Maybe you can ask another student in the Demog 213 course to check or remove yourself from the data hackathon bcourses page, log out and log back in to see whether you have 4 GB RAM allocated via demog213 config. Let me know!

**Comment by wrathofquan** [comment]
@balajialg yes, that link worked and pulled correctly. Also correct that the hackathon request is for the 8GB and we can actually bring it down now since the event has concluded. 

Thank you for your help!

**Comment by balajialg** [comment]
Thanks @wrathofquan! Will do it now

**Comment by balajialg** [comment]
@wrathofquan Closing this issue as the changes are merged to prod. Please reopen if there are any issues.
