### ISSUE TITLE
Request python package update seaborn==0.13.2 for class MCB201B

### ISSUE THREAD

**Issue by MCB201B** [berkeley-dsep-infra/hubs#6115]
### Package Name

seaborn 0.13.2

### Hub URL

biology.datahub.berkeley.edu

### Course Name

[MCB201B](https://classes.berkeley.edu/content/2024-fall-mcellbi-201b-001-lec-001)

### Semester Details

Fall 2024

### Installation Deadline

09/16

**Comment by felder** [comment]
Starting work on this now.

**Comment by felder** [comment]
This should be on prod in about 15 minutes.
