### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by tomschang** [berkeley-dsep-infra/hubs#6116]
### Your UC Berkeley Email Address

tom_schang@berkeley.edu

### Link to Your Datahub Folder

I need help finding this. I tried logging on to julia.datahub.berkeley.edu and using the terminal, but couldn't figure it out.

**Comment by balajialg** [comment]
@tomschang Can you check whether you have WHERE_ARE_MY_FILES.txt in your home directories currently? We just provided a temporary fix to an issue resulting in the text file not getting written to user home directories. You should have the instruction to retrieve your files in the text file.

**Comment by tomschang** [comment]
Yes, I see it now!

Should I open a new request? If not, here is the link.

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub&link=gs://ucb-datahub-archived-homedirs/2024-2-summer/julia/tom-5fschang.tar.gz

**Comment by balajialg** [comment]
@tomschang Thanks, Signed URL sent

**Comment by tomschang** [comment]
Thank you!
