### ISSUE TITLE
Request more RAM for Stat 131a

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#6121]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

r.datahub.berkeley.edu

**Which class is this request for?**

2024 Fall, Stat 131a
**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-fall-stat-c131a-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1537932

**How many students do you expect in this class?**

An approximate number would do.

86

**How much RAM per user is needed?**

2GB

**Why does this class need this much RAM?**

Knitting larger .Rmd files.

**By what date (MM/DD) do you want this request to be fulfilled?**

ASAP

**Until when (MM/DD) do you require the additional RAM?**

End of the term, 06/01

**Any additional information we should know about?**

Related thread in `#ucb-datahub`

**Comment by balajialg** [comment]
@ryanlovett Closing this issue as the changes are merged to prod.
