### ISSUE TITLE
Datahub returning "Service Unavailable" page

### ISSUE THREAD

**Issue by dawsonv** [berkeley-dsep-infra/hubs#6133]
### Bug description

https://datahub.berkeley.edu/ is returning a blank page that says "Service Unavailable". I've reproduced this issue across Chrome and Safari, two laptops, one ipad, and two unique users. 

### Environment & setup

- Hub: [Datahub](https://datahub.berkeley.edu/)

### How to reproduce

1. Go to https://datahub.berkeley.edu/

**Comment by dawsonv** [comment]
Issue seems to be resolved

**Comment by felder** [comment]
This appears to be some sort of issue with the chp proxy pod.  We already have a ticket open with the upstream devs, but it's actually not clear if this was the known issue or something new.

Regardless, these problems while understandably annoying do tend to resolve themselves.  We've got some long term ideas regarding moving away from chp, but that's not likely to occur soon.
