### ISSUE TITLE
Request python packages (pandas==2.0.3; sqlalchemy==2.0.32; ipython-sql; psycopg) for class Data 101

### ISSUE THREAD

**Issue by jonathanferrari** [berkeley-dsep-infra/hubs#6134]
### Package Names

```
pandas==2.0.3
sqlalchemy==2.0.32
ipython-sql
psycopg
```

### Hub URL

[data101.datahub.berkeley.edu](https://data101.datahub.berkeley.edu)

### Course Name

[https://classes.berkeley.edu/content/2024-fall-data-101-001-lec-001](https://classes.berkeley.edu/content/2024-fall-data-101-001-lec-001)

### Semester Details

Needed for all subsequent semesters

### Installation Deadline

**08/12/2024**

It is needed for upcoming projects. Hopefully by **Thursday morning** if at all possible

**Comment by shaneknapp** [comment]
https://github.com/berkeley-dsep-infra/data101-user-image/pull/5

**Comment by shaneknapp** [comment]
alright, this is live on data101-staging!  let me know if we're good to go...

**Comment by balajialg** [comment]
@jonathanferrari Closing this issue as changes were merged to data101-prod
