### ISSUE TITLE
Request python package X for class Y

### ISSUE THREAD

**Issue by ingolia** [berkeley-dsep-infra/hubs#6135]
### Package Name

bowtie2

### Hub URL

biology.datahub.berkeley.edu

### Course Name

[MCELLBI 201B](https://classes.berkeley.edu/content/mcellbi-201b)
_and_
[BIOENG C149 / CMPBIO C149]
(https://classes.berkeley.edu/content/2024-fall-cmpbio-c149-001-lec-001)
[BIOENG C249 / CMPBIO C249]
(https://classes.berkeley.edu/content/2024-fall-bioeng-c249-001-lec-001)
@lianafaye

### Semester Details

Fall 2024 and future fall semesters

### Installation Deadline

Soon is very helpful, apologies for the late notice during the semester.

**Comment by shaneknapp** [comment]
this is currently deploying to biology-staging.datahub.berkeley.edu, could you please log in and confirm that things work as expected?  thanks!

**Comment by ingolia** [comment]
I just confirmed that bowtie2 works as expected on staging, thanks!
Best,
–Nick

Nicholas Ingolia
Associate Professor
Molecular and Cell Biology
UC Berkeley
