### ISSUE TITLE
Elevated Privileges Request for ER131 Staff

### ISSUE THREAD

**Issue by dawsonv** [berkeley-dsep-infra/hubs#6137]
### Your Name

Dawson Verley

### Affiliated Course Name

ENERES 131

### bCourses ID

1538017

### Role

GSI

### Hub URL

datahub.berkeley.edu

### End Date

01/01/2025

### Request Deadline

n/a

**Comment by balajialg** [comment]
PR to enable elevated privileges for merged to staging.datahub.berkeley.edu

**Comment by balajialg** [comment]
@dawsonv Changes are merged to https://datahub.berkeley.edu/. Please reopen if there are any issues.
