### ISSUE TITLE
Intro to CompBio DataHub privileges - needed for assignments

### ISSUE THREAD

**Issue by OberonDixon** [berkeley-dsep-infra/hubs#6139]
### Your Name

Oberon Dixon-Luinenburg

### Affiliated Course Name

BIOE C131

### bCourses ID

1538361

### Role

TA

### Hub URL

datahub.berkeley.edu

### End Date

-

**Comment by balajialg** [comment]
PR to enable elevated privileges for course staff got merged to staging.datahub.berkeley.edu
