### ISSUE TITLE
ECON 140 in Fall 2024

### ISSUE THREAD

**Issue by ryanedw** [berkeley-dsep-infra/hubs#6153]
### Your Name

Ryan D. Edwards

### Affiliated Course Name

ECON 140

### bCourses ID

1538138

### Role

Instructor of record

### Hub URL

datahub.berkeley.edu

### End Date

- 
12/27/24

### Request Deadline

09/13

**Comment by balajialg** [comment]
@ryanedw Changes are merged to https://datahub.berkeley.edu/ and hence closing this issue. Please reopen if there are any issues
