### ISSUE TITLE
Request python package `openpyxl` for class ENERES 131

### ISSUE THREAD

**Issue by dawsonv** [berkeley-dsep-infra/hubs#6155]
### Package Name

openpyxl

### Hub URL

datahub.berkeley.edu

### Course Name

ENERES 131: Data, Environment and Society
https://classes.berkeley.edu/content/2024-fall-eneres-131-001-lec-001

### Semester Details

Fall semesters for the foreseeable future, starting Fall 2024

### Installation Deadline

09/16

**Comment by balajialg** [comment]
@dawsonv Changes are merged to https://staging.datahub.berkeley.edu/. You can test your notebooks and let me know if there are issues.
