### ISSUE TITLE
Data 6 Elevated Privileges

### ISSUE THREAD

**Issue by JedidiahTsang** [berkeley-dsep-infra/hubs#6158]
### Your Name

Jedidiah Tsang

### Affiliated Course Name

Data 6

### bCourses ID

1538010

### Role

Instructor

### Hub URL

datahub.berkeley.edu

### End Date

- 
12/31/2024

### Request Deadline

Anytime :)

**Comment by balajialg** [comment]
@JedidiahTsang 
PR to enable elevated privileges for course staff got merged to staging.datahub.berkeley.edu. I will update you once it gets merged to prod
