### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by amitchjr** [berkeley-dsep-infra/hubs#6163]
### Your UC Berkeley Email Address

amitchjr@berkeley.edu

### Link to Your Datahub Folder

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub&link=gs://ucb-datahub-archived-homedirs/2024-1-spring/publichealth/amitchjr.tar.gz

**Comment by balajialg** [comment]
Signed URL sent

**Comment by amitchjr** [comment]
Hi, I do not see the link to click on to restore my files. Can you direct me to them?
