### ISSUE TITLE
Request more RAM for DATA100

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6167]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Data 100 Hub (data100.hub.berkeley.edu)

**Which class is this request for?**

2024 Fall, Data 100.

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-fall-data-c100-001-lec-001

**What is the bCourses URL for this class?**

[For example, https://bcourses.berkeley.edu/courses/9876543](https://bcourses.berkeley.edu/courses/1537664)

**How many students do you expect in this class?**

1200

**How much RAM per user is needed?**

4GB of RAM per student

**Why does this class need this much RAM?**

This assignment utilises a Language Model to perform sentiment analysis. We will use a fine-tuned version of the **DistilBERT** model ([github](https://github.com/huggingface/transformers/tree/main/examples/research_projects/distillation), [original paper](https://arxiv.org/abs/1910.01108)) to analyze the sentiment of Bloomberg news articles. We will use the model checkpoint specifically trained for sentiment analysis.

We'll be using the [HuggingFace library](https://huggingface.co/) to build the sentiment analysis pipeline and load the model. [Here](https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english) is the card of the model checkpoint we will use for this assignment which contains general information about the model, including the base model used, training arguments, training data, etc.

**By what date (MM/DD) do you want this request to be fulfilled?**

09/19

**Until when (MM/DD) do you require the additional RAM?**

09/30

This will help us scale down resources when the RAM increase is no longer required

**Any additional information we should know about?**

This is a modified version of the Data100 HW3 last semester that was very compute-intensive when student code was inefficient. We're anticipating that our edits will make this assignment less so.

**Comment by shaneknapp** [comment]
you'll need more ram, but also more cpu for each user.

**Comment by balajialg** [comment]
@malavikhasudarshan Changes were merged to prod today morning. Hence closing this issue.
