### ISSUE TITLE
[Data 100] Request for CPU Bump

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6168]
### Reason for the request

We want to make sure that students do NOT max out the CPU due to computationally-intensive operations (previously observed when many users on the same node last semester).

### Student Count

1200

### Duration for this request

9.30am on 09/20 - 11.59pm on 09/30

### Deadline for this request

09/19

### Additional inputs

Last semester, the highest CPU percentages per student were just less than 800%.

**Comment by balajialg** [comment]
@malavikhasudarshan Changes were merged to prod today morning. Hence closing this issue.
