### ISSUE TITLE
Increase compute resources for Course MBA247 between specific date(s)/time(s)

### ISSUE THREAD

**Issue by luyi-yang** [berkeley-dsep-infra/hubs#6177]
### Course Name

MBA 247 Descriptive and Predictive Data Mining 
Instructor: Luyi Yang

### Detailed Requirements

- 
I conduct Live Workshops with 50 plus students running code on the datahub at the same time. Quite a few students had trouble connecting to the Datahub.

### Semester Details

Yes

### Request Deadline

 I will have two more workshops scheduled for September 25 and October 16 (both Wednesdays), 6-9:30 pm. Additional computational resources during those times would be much appreciated.

**Comment by balajialg** [comment]
@luyi-yang Thanks. I just added a couple of calendar events from 5.30 PM to 7 PM to handle the rush at the start of the workshop during those 2 days. I am keeping the issue open so that you can report if there any issues with the 25th workshop.

**Comment by luyi-yang** [comment]
Hi Balaji,

Could you shift the time to 7 to 8:30pm? I will give a lecture in the first
half of the class, so we won't start the workshop until around 7:30 pm.

Thanks,
Luyi

**Comment by balajialg** [comment]
@luyi-yang Thanks for the info. I just updated the calendar event accordingly.

**Comment by balajialg** [comment]
@luyi-yang I am closing this issue since both the workshops happened. How did Oct 16th workshop go?

**Comment by luyi-yang** [comment]
Hi Balaji,

Thanks for asking. The workshop on Oct 16 went well.

Best,
Luyi
