### ISSUE TITLE
Nano text editor

### ISSUE THREAD

**Issue by wrathofquan** [berkeley-dsep-infra/hubs#6195]
### Package Name

Nano

### Hub URL

datahub.berkeley.edu

### Course Name

[https://classes.berkeley.edu/content/2024-fall-demog-213-001-dem-001](https://classes.berkeley.edu/content/2024-fall-demog-213-001-dem-001)

### Semester Details

Fall 2024

### Installation Deadline

As soon as possible! I assumed Nano was already installed as an editor on the terminal but I can only access Micro and Vim.

**Comment by felder** [comment]
Starting work on this.

**Comment by felder** [comment]
Verified change works on local build.  PR incoming.

**Comment by felder** [comment]
Nano is now available.
