### ISSUE TITLE
Shared directory for MCELLBI 201B

### ISSUE THREAD

**Issue by ingolia** [berkeley-dsep-infra/hubs#6199]
# Summary

The MCELLBI 201B course uses large genomics data sets and we would like to put these in a shared directory to manage disk usage.

# User Stories

A shared directory will allow students to work with realistic data sets without making individual, large copies of these data.

# Acceptance criteria

We'll follow instructions on the Data Science Curriculum Guide about using shared directories.

# Important information

# Tasks to complete

**Comment by balajialg** [comment]
@ingolia I need the bcourses id and the hub URL to perform this task. Can you please fill this [template](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&projects=&template=shared_directories.yml) with the required information? Sorry for the double work created.

**Comment by balajialg** [comment]
@ingolia I would like to check once again about sharing the bcourses ID for your course using the template shared above. Ideally, we would like to avoid the use case of students downloading large datasets to their home directory. So, let us know if we need to get this set up asap.

**Comment by ingolia** [comment]
Apologies—this is now #6255 and I must not have finished the submission last time.

**Comment by balajialg** [comment]
Thanks @ingolia! Appreciate it.
