### ISSUE TITLE
shared directory for BioE c149

### ISSUE THREAD

**Issue by lianafaye** [berkeley-dsep-infra/hubs#6205]
### Your Name

Liana Lareau

### Affiliated Course Name

Computational Functional Genomics, BioE c149

### bCourses ID

1537116

### Role

professor

### Hub URL

biology.datahub.berkeley.edu

### Shared Directory Name

- bioe-c149-readwrite
- bioe-c149-shared 

### End Date

-  

### Request Deadline

9/18/2024

**Comment by balajialg** [comment]
@lianafaye I just created a PR (#6206) to add shared directories to Bio hub. I will let you know once the changes gets merged to https://biology-staging.datahub.berkeley.edu/ and https://biology.datahub.berkeley.edu/.

@shaneknapp Can there be a merge to prod today given the time sensitive nature of this request?

**Comment by shaneknapp** [comment]
go for it!

**Comment by balajialg** [comment]
Thanks @shaneknapp!

@lianafaye Changes are merged to https://biology.datahub.berkeley.edu/. Please let us know if there are any issues.

**Comment by balajialg** [comment]
@lianafaye Closing this issue as the request got resolved. Please reopen if there are issues access shared directory.
