### ISSUE TITLE
prob140 Hub not able to export notebooks as PDF

### ISSUE THREAD

**Issue by mchxo** [berkeley-dsep-infra/hubs#6208]
### Bug description

On prob140 hub, students are not able to export the notebook as PDF.

### Environment & setup

- Hub: prob140
- Language: Python

### How to reproduce

1. Go to 'https://prob140.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/prob140/materials-fa24&branch=main&subPath=hw/Homework_03.ipynb'
2. Click File/Save and Export Notebook As/PDF

**Comment by felder** [comment]
The fix will be in place a few minutes after the open PR to prod is merged.
