### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by Marikoangel** [berkeley-dsep-infra/hubs#6217]
### Your UC Berkeley Email Address

mmarikoangel@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2024-1-spring/stat20/mmarikoangel.tar.gz

gs://ucb-datahub-archived-homedirs/2024-2-summer/stat20/mmarikoangel.tar.gz

**Comment by balajialg** [comment]
Signed URL sent
