### ISSUE TITLE
Request R package dada2 for class IB134L to work with Rstudio server and terminal

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6233]
### Package Name

R dada2 through BiocManager 

### Hub URL

biology.datahub.berkeley.edu

### Course Name

IB134L Peter Studmant, Rebecca Tarvin
https://classes.berkeley.edu/content/2024-fall-integbi-134l-001-lec-001

### Installation Deadline

ASAP, discrepancy between R console and Rstudio/terminal R versions. 

I'm a GSI for IB134L using the biology datahub (https://biology.datahub.berkeley.edu/). I found a discrepancy between the R version when I use the R console (4.4.1) vs using Rstudio or R (4.2.1) in the terminal window. Mainly this is an issue because I need a package dada2 for an upcoming lab and we are working through Rstudio. I'm having trouble installing dada2 on 4.2.1, but it seems to be installed on the 4.4.1 version. Is there a way to sync this up to the 4.4.1 version?

Snapshots
![image (7)](https://github.com/user-attachments/assets/121a3037-25a5-49d0-83a5-ffa424300e89)
![image (1) (1)](https://github.com/user-attachments/assets/f3b33da3-a557-4797-8010-c16dcb612c20)
![image (2) (1)](https://github.com/user-attachments/assets/6d6e09fb-3a5d-4d4b-be6b-0379c212f8f4)

Snapshot added by @balajialg 
![Screenshot 2024-09-23 at 10 57 59 AM](https://github.com/user-attachments/assets/3a92a84e-76af-4b63-9bd5-834e0b017a83)

**Comment by shaneknapp** [comment]
i'll take a look at this now...

**Comment by caroluscha** [comment]
One more think would like to add is that it seems like the package "Matrix" is a dependency for dada2 and needs 4.4 to install. I'm no sure if there is an older version of Matrix we can use. 
![image](https://github.com/user-attachments/assets/cfac0f2f-c01a-4afc-ab1c-d1a661232a22)

**Comment by shaneknapp** [comment]
sadly, there is no 4.4.1 version of Rstudio, only 4.2.1.  :(

see:  https://posit.co/download/rstudio-server/

i was also unable to install dada2 in 4.2.1, but i'll muck around a little bit more and see if i can make things work.

i have a bad feeling that our only option would be to downgrade R console so that the versions match...

**Comment by caroluscha** [comment]
So when I go to https://datahub.berkeley.edu/ and open Rstudio. I'm actually able to get R 4.4.1. Is it a limitation with the Biology Datahub? 

![image](https://github.com/user-attachments/assets/3a590f0e-6437-4d5b-a879-a5b6fa4507e1)

**Comment by shaneknapp** [comment]
> So when I go to https://datahub.berkeley.edu/ and open Rstudio. I'm actually able to get R 4.4.1. Is it a limitation with the Biology Datahub?
> 
we had to rebuild the bio image earlier this year, so that may have caused the issue.  i will take a look at the datahub config and see what we did differently there.

also, i *was* able to get dada2 to install w/R 4.2.1:

```
install.packages("BiocManager")
install.packages("devtools")
devtools::install_version("Matrix", version="1.6-0")
BiocManager::install("dada2")
```

**Comment by caroluscha** [comment]
so it seems like i was able to install it but it's not loading 
![image](https://github.com/user-attachments/assets/82c93a09-f2ed-420b-a49f-e599e9709757)

**Comment by caroluscha** [comment]
I forgot to mention we also need a package called phyloseq to be installed as well.

**Comment by shaneknapp** [comment]
it looks like a bioforge python package is installing R v4.2.1, which is
overriding the system R (v4.4.1).  i'm currently trying to manually pin the
python version to be 4.4.1, which *should* fix the version mismatch(es).

once i get that fixed, we can install phyloseq.

**Comment by caroluscha** [comment]
Thanks! I really appreciate the help!

**Comment by shaneknapp** [comment]
@caroluscha i see in the bio hub's python environment file that there is a module we install for this course called `augustus` (here:  https://github.com/berkeley-dsep-infra/biology-user-image/blob/main/environment.yml#L20).

this module is old, and is causing a lot of grief when trying to fix this issue.  does the course still require this, or would a different solution work?  i found a different installation option here, as `apt` packages:  https://github.com/Gaius-Augustus/Augustus?tab=readme-ov-file#ubuntu-1804-debian-9-or-later

**Comment by caroluscha** [comment]
We still require Augustus for the course. Would there be a functional difference if it was installed through apt vs conda?

**Comment by shaneknapp** [comment]
btw, `phylosec` should already be installed:  https://github.com/berkeley-dsep-infra/biology-user-image/blob/main/install.R#L43

**Comment by shaneknapp** [comment]
ok, @felder and i were able to figure this out, and we didn't need to touch the python environment!  :)

it's currently building here:  https://github.com/berkeley-dsep-infra/biology-user-image/actions/runs/11004781492/job/30556350247

once it passes, i'll deploy it to staging and i'll confirm that things are working as intended.

**Comment by petersudmant** [comment]
U folks rock!

**Comment by shaneknapp** [comment]
@caroluscha this is live on biology-staging.datahub.berkeley.edu, please test and let me know if things are working as intended!

![image](https://github.com/user-attachments/assets/516b4ac0-e2b5-4120-994a-13625be7f198)

for R in the terminal, it's just a matter of the `PATH` env var...  by default we prefix `PATH` with `/srv/conda/bin` so that conda binaries are chosen first.  we won't be able to change that w/o potential side effects:

```
jovyan@jupyter-sknapp:~$ which R
/srv/conda/bin/R
jovyan@jupyter-sknapp:~$ ls -la /usr/bin/R
-rwxr-xr-x 1 root root 9061 Jun 16 18:41 /usr/bin/R
jovyan@jupyter-sknapp:~$ R
WARNING: ignoring environment value of R_HOME

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> q()
Save workspace image? [y/n/c]: n
jovyan@jupyter-sknapp:~$ /usr/bin/R

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> q()
```

@petersudmant this image needs some serious auditing.  many of the R and python packages are very old, and this image is just going to become more fragile as time moves on.

the bigest issue is that it would be BEST have both the conda and system R binaries be the same version, but we're quickly running in to [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell)...  the current discrepancy could lead to lurking issues and we'll get to work on that ASAP.

**Comment by caroluscha** [comment]
Yay it works for me now on Rstudio. I think we have a little of leeway for now since the most pressing issue of have dada2 and phyloseq up is resolved.

**Comment by shaneknapp** [comment]
merged to prod
