### ISSUE TITLE
Shared directory for MCELLBI 201B

### ISSUE THREAD

**Issue by ingolia** [berkeley-dsep-infra/hubs#6255]
### Your Name

Nicholas Ingolia

### Affiliated Course Name

MCELLBI201B

### bCourses ID

1537301

### Role

Instructor

### Hub URL

biology.datahub.berkeley.edu

### Shared Directory Name

- 
mcb201b-shared and mcb201b-shared-readwrite

### End Date

- 
05/16/2025

**Comment by balajialg** [comment]
@ingolia Changes are merged to https://biology.datahub.berkeley.edu/. Can you confirm whether you can see the shared directories "mcb201b-shared" and "mcb201b-shared-readwrite"?

**Comment by ingolia** [comment]
Yes, I see these directories, thanks.

**Comment by balajialg** [comment]
@ingolia Thanks
