### ISSUE TITLE
Request python package widgetsnbextension==4.0.9,  ipywidgets==8.0.7, jupyterlab-widgets==3.0.8 for Data 8

### ISSUE THREAD

**Issue by jedwin3210** [berkeley-dsep-infra/hubs#6269]
### Package Name

widgetsnbextension==4.0.9,  ipywidgets==8.0.7, jupyterlab-widgets==3.0.8

### Hub URL

data8.datahub.berkeley.edu

### Course Name

Data 8, Jeremy Sanchez

### Semester Details

Fall 2024

### Installation Deadline

Not urgent, but when most convenient. The packages in "package name" fixed the issue of interactive graphs using ipywidgets.

**Comment by felder** [comment]
This change is now live.  Any running servers need to be restarted for the change to take effect.

Tested using an empty notebook with only the following cell.  Verified that where there was once a JS error, there is now a slider.

```

import ipywidgets as widgets
from ipywidgets import interact

# Function to interact with
def f(x, y):
    print(f"x: {x}, y: {y}")

# Interact with x (slider) and y (dropdown)
interact(f, 
         x=widgets.IntSlider(min=0, max=10, step=1, value=5), 
         y=widgets.Dropdown(options=['Option 1', 'Option 2', 'Option 3'], value='Option 1'));
```
