### ISSUE TITLE
Biology Hub Spawn Failure

### ISSUE THREAD

**Issue by MCB201B** [berkeley-dsep-infra/hubs#6275]
### Bug description

User: tsaichih. Unable to start Biology Hub server. Relaunching server is unable to solve the issue. I get the same response "Spawn failed  - The latest attempt to start your server has failed. Would you like to retry starting it?" Using the Relaunch Server button does not solve the issue. Need server to teach MCB201B class.

### Environment & setup

- Hub: Biology Hub
- Language:  N/A

### How to reproduce

1. Go to https://biology.datahub.berkeley.edu/hub/spawn-pending/tsaichih
2. Receive "Spawn failed" response.
3. Relaunch Server gives the same response.

**Comment by shaneknapp** [comment]
there's something wrong in our configs for the shared directory we have set up for that course.  investigating now.

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-tsaichih\" is invalid: spec.containers[0].volumeMounts[10].mountPath: Invalid value: \"/home/jovyan/mcb201b-shared-readwrite\": must be unique","reason":"Invalid","details":{"name":"jupyter-tsaichih","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"/home/jovyan/mcb201b-shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[10].mountPath"}]},"code":422}
```

**Comment by balajialg** [comment]
@MCB201B Can you try launching your server again and report if you face the same issue?

**Comment by MCB201B** [comment]
I'm still currently having the same issue unfortunately.

**Comment by balajialg** [comment]
@MCB201B 
@felder found that you are currently affiliated to two groups (Lead TA and Teachers) in https://bcourses.berkeley.edu/courses/1537301. It might be causing a conflict with the hub config because it's trying to mount the shared directories twice resulting in this error. The straightforward fix would be to remove yourself from one of the two groups in bcourses, log out of the hub and then log in again. Let us know if that action resolves the spawn failure.

**Comment by MCB201B** [comment]
I've requested that I be removed from one of the two groups since I don't have permissions to do so on bCourses. I'll update you when I've been able to test it afterwards.

**Comment by MCB201B** [comment]
I've been removed from one of the two groups, and I was able to start up my Biology Hub server normally. I can see an mcb201b-shared-readwrite folder now too. Thanks for your help resolving this!

**Comment by balajialg** [comment]
Awesome, thanks @felder!
