### ISSUE TITLE
Request more RAM for MBA247

### ISSUE THREAD

**Issue by luyi-yang** [berkeley-dsep-infra/hubs#6276]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Datahub (datahub.berkeley,edu)

**Which class is this request for?**

Fall 2024, MBA247 Descriptive and Predictive Data Mining

**What is the Academic Guide URL for this class?**

https://docs.google.com/document/d/1j2sS11NorK5QwilxBmV6nLaoh_ODWhgvwQMfhugZKCk/edit

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1536576

**How many students do you expect in this class?**

56

**How much RAM per user is needed?**

2GB of RAM per student.

**Why does this class need this much RAM?**

It is a machine learning course where students work on large data sets. 

**By what date (MM/DD) do you want this request to be fulfilled?**

ASAP. For example, 09/27

**Until when (MM/DD) do you require the additional RAM?**

10/23

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@luyi-yang Changes are merged to prod. Let us know if the students are getting the required 2 GB RAM.

**Comment by luyi-yang** [comment]
Thanks, Balaji!

When I logged into Datahub just now, I still saw 1024MB RAM. Could you
double-check?

Thanks,
Luyi

**Comment by balajialg** [comment]
@luyi-yang Could you please try logging out of the hub and then logging back in to check if the 2 GB of RAM has been allocated? These changes typically take effect after logging out and back in. Let me know if it works!

**Comment by luyi-yang** [comment]
Hi Balaji,

I indeed tried to log out and log back in a few times, but did not see a
change in RAM. Here is a screenshot of what I saw in JupyterLab.

[image: image.png]

**Comment by balajialg** [comment]
@luyi-yang That is weird. I can't find any issue with the configs. Can you share the screenshot again (or email me if that is easier)? Also, is this the case for others who are part of your course?

**Comment by luyi-yang** [comment]
Hi Balaji,

I just checked again and saw the update now! Thanks so much for your help!
Much appreciated.

Best,
Luyi

**Comment by balajialg** [comment]
That's good to know, thanks @luyi-yang
