### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by RobertoGarcia5** [berkeley-dsep-infra/hubs#6293]
### Your UC Berkeley Email Address

robertogarcia@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2024-2-summer/datahub/robertogarcia.tar.gz

**Comment by RobertoGarcia5** [comment]
Hey! Wondering if theres any update here. Would love to get my files from my spring 2024 coding class so I can add them to my portfolio

**Comment by balajialg** [comment]
signed URL sent
