### ISSUE TITLE
Request terminal package bwa for class IB134L

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6294]
### Package Name

bwa 

### Hub URL

datahub.berkeley.edu

### Course Name

Practical Genomics IB134L
https://classes.berkeley.edu/content/2024-fall-integbi-134l-001-lec-001

**Comment by balajialg** [comment]
@shaneknapp This request is for the datahub image instead of biology hub image. Should we reopen this issue since I didn't see any PR corresponding to the datahub image.

**Comment by shaneknapp** [comment]
no, the datahub request was accidental.  this is for bio hub.

**Comment by balajialg** [comment]
Thanks for the clarification!

@caroluscha Just confirming Shane's point that this is an accidental request from you?
