### ISSUE TITLE
Data 100 Grad Project Dataset

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6316]
### Your Name

Malavikha Sudarshan

### Affiliated Course Name

Data C100

### bCourses ID

1537664

### Role

Lead Infrastructure Teaching Assistant

### Hub URL

datahub.berkeley.edu

### Shared Directory Name

data-100-readwrite, data-100-shared

### End Date

12/20/24

### Request Deadline

ideally 10/01, (this was only decided in the early hours of this morning by our staff so this is quite last-min; if it will take longer i can let the content team know)

**Comment by balajialg** [comment]
@malavikhasudarshan Changes are merged to prod now and will be live in few mins. Please test whether you have access to `data100-shared` and `data100-shared-readwrite` directories in your home dir (Please log out and log back in)

**Comment by balajialg** [comment]
Closing this issue as the changes are merged to prod
