### ISSUE TITLE
Request python package `pyogrio` for class ENERES 131

### ISSUE THREAD

**Issue by dawsonv** [berkeley-dsep-infra/hubs#6346]
### Package Name

pyogrio

### Hub URL

datahub.berkeley.edu

### Course Name

[ENERES 131](https://classes.berkeley.edu/content/2024-fall-eneres-131-001-lec-001)

### Semester Details

Fall 2024 and fall semesters thereafter, indefinitely

### Installation Deadline

10/10

**Comment by balajialg** [comment]
@dawsonv The changes are merged to staging. You can test the changes in https://staging.datahub.berkeley.edu/. I will give you an update once the changes are merged to prod.

**Comment by balajialg** [comment]
@dawsonv Changes are merged to https://datahub.berkeley.edu/. I tested the following block and it seems to work fine. Let me know if it works as expected for you. Thanks!

```
import pyogrio
import geopandas as gpd

# Path to the naturalearth_lowres dataset in GeoPackage format, included with geopandas
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'), engine='pyogrio')

# Display the first few rows of the dataset
print("First few rows of the dataset:")
print(gdf.head())

# Write this dataset to a shapefile using pyogrio
output_shapefile = "naturalearth_lowres_output.shp"
gdf.to_file(output_shapefile, engine='pyogrio')

print(f"Shapefile saved to: {output_shapefile}")

```

**Comment by balajialg** [comment]
@dawsonv I am closing this issue for now. Please reopen this issue if things don't work as you expected. Thanks!

**Comment by dawsonv** [comment]
Terrific thank you!
