### ISSUE TITLE
Data Retrieval Request - MIDS w241

### ISSUE THREAD

**Issue by timothy-majidzadeh** [berkeley-dsep-infra/hubs#6373]
### Your UC Berkeley Email Address

tmajidzadeh@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/timothym98.tar.gz

Some useful course materials for MIDS w241 should be accessible via Datahub, but they may have been archived. I would greatly appreciate a chance to retrieve them.

**Comment by balajialg** [comment]
Signed URL sent
