### ISSUE TITLE
python 2 vs 3 and WSGI error?

### ISSUE THREAD

**Issue by mkoo** [berkeley-dsep-infra/hubs#6380]
### Bug description (edited to share the error message below)

a longstanding Notebook is used in IB105 and now one of the API requests is consistently giving timeout errors
```
reserves = requests.get('https://ecoengine.berkeley.edu/api/layers/reserves/features/?format=json&page_size=20').json()
```
The url works everywhere but in this nb:
https://github.com/BNHM/jupyter/blob/master/BNHM-integrateData-2020.ipynb

Is this a library issue? something else? (this is on one of the Berkeley servers so I know the URL is ok)
Maybe someone can take a peek at the error and let me know their thoughts how to fix! thx

### Environment & setup

- Hub:  Datahub
- Language:  Python

### Error
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
File /srv/conda/lib/python3.11/site-packages/urllib3/connection.py:198, in HTTPConnection._new_conn(self)
    197 try:
--> 198     sock = connection.create_connection(
    199         (self._dns_host, self.port),
    200         self.timeout,
    201         source_address=self.source_address,
    202         socket_options=self.socket_options,
    203     )
    204 except socket.gaierror as e:

File /srv/conda/lib/python3.11/site-packages/urllib3/util/connection.py:85, in create_connection(address, timeout, source_address, socket_options)
     84 try:
---> 85     raise err
     86 finally:
     87     # Break explicitly a reference cycle

File /srv/conda/lib/python3.11/site-packages/urllib3/util/connection.py:73, in create_connection(address, timeout, source_address, socket_options)
     72     sock.bind(source_address)
---> 73 sock.connect(sa)
     74 # Break explicitly a reference cycle

TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

ConnectTimeoutError                       Traceback (most recent call last)
File /srv/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:793, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)
    792 # Make the request on the HTTPConnection object
--> 793 response = self._make_request(
    794     conn,
    795     method,
    796     url,
    797     timeout=timeout_obj,
    798     body=body,
    799     headers=headers,
    800     chunked=chunked,
    801     retries=retries,
    802     response_conn=response_conn,
    803     preload_content=preload_content,
    804     decode_content=decode_content,
    805     **response_kw,
    806 )
    808 # Everything went great!

File /srv/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:491, in HTTPConnectionPool._make_request(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)
    490         new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)
--> 491     raise new_e
    493 # conn.request() calls http.client.*.request, not the method in
    494 # urllib3.request. It also calls makefile (recv) on the socket.

File /srv/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:467, in HTTPConnectionPool._make_request(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)
    466 try:
--> 467     self._validate_conn(conn)
    468 except (SocketTimeout, BaseSSLError) as e:

File /srv/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1099, in HTTPSConnectionPool._validate_conn(self, conn)
   1098 if conn.is_closed:
-> 1099     conn.connect()
   1101 # TODO revise this, see https://github.com/urllib3/urllib3/issues/2791

File /srv/conda/lib/python3.11/site-packages/urllib3/connection.py:616, in HTTPSConnection.connect(self)
    615 sock: socket.socket | ssl.SSLSocket
--> 616 self.sock = sock = self._new_conn()
    617 server_hostname: str = self.host

File /srv/conda/lib/python3.11/site-packages/urllib3/connection.py:207, in HTTPConnection._new_conn(self)
    206 except SocketTimeout as e:
--> 207     raise ConnectTimeoutError(
    208         self,
    209         f"Connection to {self.host} timed out. (connect timeout={self.timeout})",
    210     ) from e
    212 except OSError as e:

ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f4edfd89e50>, 'Connection to ecoengine.berkeley.edu timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

MaxRetryError                             Traceback (most recent call last)
File /srv/conda/lib/python3.11/site-packages/requests/adapters.py:486, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    485 try:
--> 486     resp = conn.urlopen(
    487         method=request.method,
    488         url=url,
    489         body=request.body,
    490         headers=request.headers,
    491         redirect=False,
    492         assert_same_host=False,
    493         preload_content=False,
    494         decode_content=False,
    495         retries=self.max_retries,
    496         timeout=timeout,
    497         chunked=chunked,
    498     )
    500 except (ProtocolError, OSError) as err:

File /srv/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:847, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)
    845     new_e = ProtocolError("Connection aborted.", new_e)
--> 847 retries = retries.increment(
    848     method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    849 )
    850 retries.sleep()

File /srv/conda/lib/python3.11/site-packages/urllib3/util/retry.py:515, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    514     reason = error or ResponseError(cause)
--> 515     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    517 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='ecoengine.berkeley.edu', port=443): Max retries exceeded with url: /api/layers/reserves/features/?format=json&page_size=20&page_size=20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4edfd89e50>, 'Connection to ecoengine.berkeley.edu timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

ConnectTimeout                            Traceback (most recent call last)
Cell In[41], line 1
----> 1 reserves = requests.get('https://ecoengine.berkeley.edu/api/layers/reserves/features/?format=json&page_size=20', params={'page_size': 20}).json()
      2 reserves

File /srv/conda/lib/python3.11/site-packages/requests/api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File /srv/conda/lib/python3.11/site-packages/requests/api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File /srv/conda/lib/python3.11/site-packages/requests/sessions.py:589, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    584 send_kwargs = {
    585     "timeout": timeout,
    586     "allow_redirects": allow_redirects,
    587 }
    588 send_kwargs.update(settings)
--> 589 resp = self.send(prep, **send_kwargs)
    591 return resp

File /srv/conda/lib/python3.11/site-packages/requests/sessions.py:703, in Session.send(self, request, **kwargs)
    700 start = preferred_clock()
    702 # Send the request
--> 703 r = adapter.send(request, **kwargs)
    705 # Total elapsed time of the request (approximately)
    706 elapsed = preferred_clock() - start

File /srv/conda/lib/python3.11/site-packages/requests/adapters.py:507, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    504 if isinstance(e.reason, ConnectTimeoutError):
    505     # TODO: Remove this in 3.0.0: see #2811
    506     if not isinstance(e.reason, NewConnectionError):
--> 507         raise ConnectTimeout(e, request=request)
    509 if isinstance(e.reason, ResponseError):
    510     raise RetryError(e, request=request)

ConnectTimeout: HTTPSConnectionPool(host='ecoengine.berkeley.edu', port=443): Max retries exceeded with url: /api/layers/reserves/features/?format=json&page_size=20&page_size=20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4edfd89e50>, 'Connection to ecoengine.berkeley.edu timed out. (connect timeout=None)'))

**Comment by mkoo** [comment]
If this is a Python 2 vs 3 issue, are there any kernels for 2 that I can use temporarily for the class this week (to buy some code updating time?) I think I know the answer but have to ask anyway!

**Comment by shaneknapp** [comment]
~which hub is this happening on?~

nevermind, datahub.  :)

**Comment by mkoo** [comment]
I do have shortcut for pulling the latest version: https://bit.ly/JupyterNotebook-IB105

**Comment by shaneknapp** [comment]
ok, i'm seeing the same thing happen on other hubs than just datahub itself, so i'm inclined to think that it's a firewall or incoming connection rule on https://ecoengine.berkeley.edu that's causing timeouts from the berkeley.edu domain.

from home, i can easily download the file as json, and it's only ~106k.

edit:  a potentially easy fix is to pre-download the data and put it in a shared directory...

regarding python2, that has been EOL for years, and we are not going to install that on our systems.  :(

**Comment by mkoo** [comment]
well thanks -- 2 wont help at all if it's a firewall... let me forward to BNHM programmer to see if that's something to troubleshoot.

**Comment by mkoo** [comment]
I have a workaround now-- thanks for your help @shaneknapp 
we have unresolved firewall issues but it's not really worth trying to solve now!

**Comment by shaneknapp** [comment]
yep, glad i could help identify the issue!
