### ISSUE TITLE
Request more RAM for MCB201B

### ISSUE THREAD

**Issue by MCB201B** [berkeley-dsep-infra/hubs#6385]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**

Biology Hub (https://biology.datahub.berkeley.edu/)

**Which class is this request for?**

2024 Fall, MCELLBI 201B

**What is the Academic Guide URL for this class?**

https://classes.berkeley.edu/content/2024-fall-mcellbi-201b-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1537301

**How many students do you expect in this class?**

16

**How much RAM per user is needed?**

5GB of RAM

**Why does this class need this much RAM?**

We're working with large genomics and transcriptomics datasets. 4GB has been enough so far, but we are now running into issues with more memory-intensive programs when students work with the full dataset for their homework assignment.

**By what date (MM/DD) do you want this request to be fulfilled?**

10/18 if possible, so students can complete their homework assignment. But 10/21 is okay too.

**Until when (MM/DD) do you require the additional RAM?**

11/1

**Any additional information we should know about?**

**Comment by balajialg** [comment]
@MCB201B Changes are merged to https://biology-staging.datahub.berkeley.edu/. I will give you a heads up when it gets merged to prod.

**Comment by MCB201B** [comment]
Great! Thanks for your help!

**Comment by balajialg** [comment]
@MCB201B Changes are merged to https://biology.datahub.berkeley.edu/. Let me know if there are any discrepancies.

**Comment by MCB201B** [comment]
It looks great! Thanks again!

**Comment by MCB201B** [comment]
Hi @balajialg - will it be possible to extend the duration of our 5GB RAM request to 11/15/2024? It's been a great help so far, and we're nearly done with the more computationally heavy programs. We will be done with all the in-class and homework genome alignments and computationally heavy analyses by 11/15/2024. 

Thanks so much for your help! We really appreciate it!

**Comment by balajialg** [comment]
@MCB201B Sounds good. Good luck!
