### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by vibha-y** [berkeley-dsep-infra/hubs#6390]
### Your UC Berkeley Email Address

srivibha_yellamraju@berkeley.edu 

I need access to my files for HW 3 for BioE 149 

## Add the path to this file in the function below

# myeloid_data = scprep.io.load_csv( ## TODO ##,
#                           cell_axis='row', sparse=True).transpose()

## which is why you see the call .transpose()

# Load the Myeloid counts data

I dont see the 'Brain_Myeloid-counts.csv' file in my directory

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2023-2-summer/datahub/srivibha-5fyellamraju.tar.gz

**Comment by balajialg** [comment]
signed URL sent
