### ISSUE TITLE
biology.datahub.berkeley.edu is down?

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6421]
### Your Role

Instructor

### Affiliated Course Name

IB134L

### Hub URL

biology.datahub.berkeley.edu

### URL to the notebook file (.ipynb, .rmd etc..) with solutions

- 

### How to reproduce

Currently the biology datahub has says service unavailable when I try to go on.  

### Number of Impacted Students

ALL

### Severity of the Issue

Critical

### Issue timeline

ASAP

### Snapshots of issue

![image](https://github.com/user-attachments/assets/7f08dea6-834c-4422-9adb-cb0b5d6a24fc)

### Additional comments

We would like to see this addressed ASAP.

**Comment by shaneknapp** [comment]
i just kicked the proxy pod, and it's back up and running now!

**Comment by caroluscha** [comment]
Thanks!
