### ISSUE TITLE
Problem with running phyml

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6429]
### Bug description

I'm trying to run a program with phyml with the file linked below and I'm getting this error. I'm not sure what the error means. 

. Command line: phyml -i squirrel.phy -d nt -b -1 -m GTR malloc(): corrupted top size 
Aborted

https://biology.datahub.berkeley.edu/hub/user-redirect/lab/tree/IB134L-FALL2024/Lab_08/squirrel.phy

I was wondering I can get some help resolving this. 

### Environment & setup

- Hub: 
- Language: 

Bash

### How to reproduce

Run this command  `phyml -i squirrel.phy -d nt -b -1 -m GTR` 
input file for command is linked below 
https://biology.datahub.berkeley.edu/hub/user-redirect/lab/tree/IB134L-FALL2024/Lab_08/squirrel.phy

**Comment by felder** [comment]
@caroluscha what is the nbgitpuller link to grab this?

**Comment by caroluscha** [comment]
Sorry I was able to resolve this issue thanks!

**Comment by felder** [comment]
@caroluscha can you tell me how in case it's seen again?

**Comment by caroluscha** [comment]
It was a problem on my end the file i used had spaces. commas, and parenthesis and the phyml does not like it.

**Comment by felder** [comment]
Ah ok a parsing issue.  Great, thanks and with that I'm closing this issue.
