### ISSUE TITLE
Increase compute resources for Data C8 between specific date(s)/time(s)

### ISSUE THREAD

**Issue by jedwin3210** [berkeley-dsep-infra/hubs#6437]
### Course Name

https://classes.berkeley.edu/content/2024-fall-data-c8-001-lec-001

Data C8 with Jeremy Sanchez

### Detailed Requirements

Data 8's Project 2 and Project 3 has had some slowness in the past for students when approaching the deadline. 

### Semester Details

Yes

### Request Deadline

November 14: 12PM - 5PM
November 15: 12PM - 5PM

December 5: 12PM - 5 PM
December 6: 12PM - 5 PM

**Comment by balajialg** [comment]
@jedwin3210 Added calendar events to support the projects. Keep us posted if there are any issues!

**Comment by balajialg** [comment]
Closing this issue since the event date has passed. @jedwin3210 Did students have a smooth experience?

**Comment by jedwin3210** [comment]
Hey Balaji,

The majority of students had a pretty smooth experience, but there were a notable amount of students whose kernels crashed when trying to download the zip / run all test_cases for project 3 final submission (December 6th). I was able to give work around solutions, so everything worked out in the end. Thank you so much for the support and check-up! :)

**Comment by balajialg** [comment]
@jedwin3210 Thanks, this is helpful to know. Let's explore some options (memory increase?) next semester to avoid the kernel crashing issue during project 3 deadline.

**Comment by jedwin3210** [comment]
@balajialg Yes, I believe the memory increase would fix the issue. I'll be moving to another course staff next semester (DataC88C), but can let the future staff know about this.

**Comment by balajialg** [comment]
@jedwin3210 Sounds good, thanks and good luck!
