### ISSUE TITLE
Adding shared data folder for student projects for IB134L Fall 2024

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6453]
### Your Name

Carolus Chan

### Affiliated Course Name

Practical Genomics

### bCourses ID

1536425

### Role

GSI

### Hub URL

biology.datahub.berkeley.edu

### Shared Directory Name

- 
IB34L_data with subdirectories
Canned_project_data
Canned_project_data/covid_phylo
Canned_project_data/soil_water_metageno

All directories and files under IB134L_data should be readonly for students. They will copy the data to their own folder to use it. 

Total size will be around 1-2 GB

### End Date

- 
12/20/2024

### Request Deadline

11/4/2024 end of day.

**Comment by balajialg** [comment]
@caroluscha Couple of things,

- https://biology.datahub.berkeley.edu/ hub already has a `shared` directory with a subdirectory named `IB134L_data`. You can add the required datasets there and students in Bio hub will have read access to the datasets. However, your datasets will be available to other courses using the biology hub.
- To avoid that, I have created `IB134L-shared-readwrite` and `IB134L-shared` directories. Instructors and TAs affiliated with your bcourses website will have read-write access to `IB134L-shared-readwrite`. Students will have read-only access to `IB134L-shared`. All the files stored in the `shared-readwrite` will be available via `shared` directories. For additional documentation, please refer to https://curriculum-guide.datahub.berkeley.edu/workflows/storing-datasets#shared-directory.
 
Changes are merged to https://biology-staging.datahub.berkeley.edu/ and should be available in the next few minutes. Please test the hub and confirm that you can access the shared directories.

**Comment by caroluscha** [comment]
Great I can access the folders. Just to confirm how this sharing system works. If I upload a file on `IB134L-shared-readwrite`, then students should be able to access it on `IB134L-shared`?

**Comment by balajialg** [comment]
@caroluscha Thanks! Yes, that's right. Changes will be merged to https://biology.datahub.berkeley.edu/ asap!

**Comment by balajialg** [comment]
@caroluscha Closing this issue as changes are merged to prod
