### ISSUE TITLE
Data 100 Elevated Privileges

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6458]
### Your Name

Malavikha Sudarshan

### Affiliated Course Name

Data C100

### bCourses ID

1537664

### Role

Lead Infrastructure Teaching Assistant

### Hub URL

data100.datahub.berkeley.edu

### End Date

2/31/24

### Request Deadline

11/12

**Comment by balajialg** [comment]
@malavikhasudarshan Changes are merged to https://data100-staging.datahub.berkeley.edu/. I will let you know once it gets merged to prod.
