### ISSUE TITLE
Request jupysql for Data 100

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6461]
### Package Name

jupysql

### Package Version

0.10.14

### Hub URL

data100.datahub.berkeley.edu

### Reproducible test case

https://data100.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FDS-100%2Fsp24-student&urlpath=lab%2Ftree%2Fsp24-student%2Flecture%2Flec20%2Flec20.ipynb&branch=main

The cell isn't allowing me to upload an ipynb notebook, but I can send this over Slack if needed. 
For testing, SQL syntax should be highlighted (bold and in green) and shouldn't look like normal black text.
```
%%sql
SELECT * FROM information_schema.tables
```

### Course Name

https://classes.berkeley.edu/content/2024-fall-data-c100-001-lec-001

### Semester Details

Fall 2024 + forward

### Installation Deadline

Ideally between 12.30pm on 11/05 and 11.00am on 11/07.

**Comment by balajialg** [comment]
@malavikhasudarshan `jupysql==0.8.0` is already installed in the Data 100 image. Do you need a version upgrade?

With jupysql version 0.8.0, all the cells execute without errors. I can observe that the SQL syntax is rendered as black text. When I upgrade to version 0.10.14 of jupysql, I can confirm that SQL syntax is rendered as green and bold text and the cells execute without any errors. 

However, I don't understand what you mean by 

> The cell isn't allowing me to upload an ipynb notebook, but I can send this over Slack if needed.

I don't see any code that allows for uploading notebook. Can you pls clarify what am I missing here?

**Comment by malavikhasudarshan** [comment]
Hi Balaji,

A version upgrade to 0.10.14 would be great thanks! Would it be alright if you could hold off of upgrading till after 12.30pm? Prof Norouzi is doing a demo during lectures, from 11.00am - 12.30pm and ideally we don’t want to change any packages during this.

In the instruction template, it suggested uploading an ipynb file for testing; my comment was in response to that prompt. 

Kind regards,
Malavikha

**Comment by balajialg** [comment]
@malavikhasudarshan Thanks, Will create a PR later in the day. I will review the issue template now. We would reallly appreciate it if you can test the notebooks in advance during spring 25 and request such upgrades at the start of the semester.

**Comment by balajialg** [comment]
@malavikhasudarshan Changes are merged to https://data100-staging.datahub.berkeley.edu/ and will be live in few mins. Please test and let us know if there are any issues.
