### ISSUE TITLE
Request duckdb upgrade for Data 100 from 0.8 to 0.10.0

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6462]
### Package Name

duckdb

### Package Version

0.10.0

### Hub URL

data100.datahub.berkeley.edu

### Reproducible test case

https://data100.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FDS-100%2Fsp24-student&urlpath=lab%2Ftree%2Fsp24-student%2Flecture%2Flec20%2Flec20.ipynb&branch=main

I can't upload an ipynb notebook here, but I can send this over slack if needed. 
print(duckdb.__version__) for version

### Course Name

https://classes.berkeley.edu/content/2024-fall-data-c100-001-lec-001

### Semester Details

Fall 2024 + forward

### Installation Deadline

Ideally between 12.30pm on 11/05 and 11.00am on 11/07.

**Comment by balajialg** [comment]
@malavikhasudarshan duckdb is already at version 0.10.1. Do you need a downgrade to 0.10.0?

<img width="388" alt="Screenshot 2024-11-05 at 12 10 32 PM" src="https://github.com/user-attachments/assets/894fd596-041e-47a9-9515-cdfbb07d9cb9">
