### ISSUE TITLE
Request otter-grader upgrade for Data 100

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6473]
### Package Name

otter-grader

### Package Version

6.0.4

### Hub URL

data100.datahub.berkeley.edu

### Reproducible test case

otter --version

### Course Name

https://classes.berkeley.edu/content/2024-fall-data-c100-001-lec-001

### Semester Details

fa24

### Installation Deadline

ideally 11/08 :face_with_spiral_eyes

**Comment by shaneknapp** [comment]
this is live on data100-staging.d.b.e...  could you please test and let me know if this solves the otter issue?
