### ISSUE TITLE
Request bioconda package bcftools for class IB134L

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6477]
### Package Name

bcftools

### Package Version

latest version

### Hub URL

biology.datahub.berkeley.edu

### Reproducible test case

Was able to install on my own personal datahub with `conda install -c bioconda bcftools`

### Course Name

IB134L - https://bcourses.berkeley.edu/courses/1536425 

### Semester Details

Fall 2024

### Installation Deadline

Before 11/19 would be ideal.

**Comment by shaneknapp** [comment]
i was only able to install `bcftools==1.16` without diving deeply in to dependency hell.  does that version work for you?

**Comment by shaneknapp** [comment]
this is now live on biology-staging.datahub.berkeley.edu...  please confirm that the package is working as expected, and i will then merge it to prod.

**Comment by caroluscha** [comment]
it works and 1.16 is fine also.

**Comment by shaneknapp** [comment]
this is now live in prod!
