### ISSUE TITLE
Request PyTorch for Data 100

### ISSUE THREAD

**Issue by malavikhasudarshan** [berkeley-dsep-infra/hubs#6498]
### Package Name

pytorch

### Package Version

2.5.1

### Hub URL

data100.datahub.berkeley.edu

### Reproducible test case

import torch

print(torch.__version__)

### Course Name

https://classes.berkeley.edu/content/2024-fall-data-c100-001-lec-001

### Semester Details

Fall 2024

### Installation Deadline

(12/02)

**Comment by shaneknapp** [comment]
this is now live on data100-staging

**Comment by shaneknapp** [comment]
pushed to prod
