### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by ajalc** [berkeley-dsep-infra/hubs#6519]
### Your UC Berkeley Email Address

ajalc@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2024-1-spring/datahub/ajalc.tar.gz
gs://ucb-datahub-archived-homedirs/2024-2-summer/datahub/ajalc.tar.gz

**Comment by balajialg** [comment]
Signed URL sent
