### ISSUE TITLE
Request my old files stored in Datahub

### ISSUE THREAD

**Issue by LaishaCastillo** [berkeley-dsep-infra/hubs#6521]
### Your UC Berkeley Email Address

laishacastillo@berkeley.edu

### Link to Your Datahub Folder

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=data_archival_request.yml&title=Request+my+old+files+stored+in+Datahub&link=gs://ucb-datahub-archived-homedirs/2024-2-summer/datahub/laishacastillo.tar.gz

**Comment by balajialg** [comment]
Signed URL sent
