### ISSUE TITLE
Accidentally deleted an important ipynb file (12/6) in my 'Titanic Competition' folder. Need it for Finals. Don't know how to restore

### ISSUE THREAD

**Issue by blakehoover12** [berkeley-dsep-infra/hubs#6526]
### Your UC Berkeley Email Address

blakehoover@berkeley.edu

### Link to Your Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-1-spring/datahub/blakehoover.tar.gz

**Comment by balajialg** [comment]
@felder @shaneknapp Is it possible to recover the deleted file? Any ideas?

@blakehoover12 Fwiw, I sent you a signed URL with the archived files from your home directory. I am not sure whether that would have the files that got deleted. 

In the future, I would recommend backing up your ipynb files on your local device regularly.

**Comment by shaneknapp** [comment]
> @felder @shaneknapp Is it possible to recover the deleted file? Any ideas?
> 
> @blakehoover12 Fwiw, I sent you a signed URL with the archived files from your home directory. I am not sure whether that would have the files that got deleted.
> 
> In the future, I would recommend backing up your ipynb files on your local device regularly.

no, we won't be able to restore accidentally deleted files.  i'm truly sorry about this!

**Comment by ryanlovett** [comment]
Hi @blakehoover12 , There is a directory in your `Titanic Competition` directory named `.ipynb_checkpoints`. It contained a few notebooks, but they all had counterparts in the parent folder. That is, if there was a file named `missing.ipynb`, there is no equivalent checkpoint file for it. Nevertheless, I copied the checkpoints to a new `restored` directory just in case.

**Comment by shaneknapp** [comment]
i did look in the `.ipynb_checkpoints` directory in the titantic competition folder, and saw the following notebooks...  the timestamps don't match up but perhaps these will help?

```
/export/datahub-filestore/datahub/prod/blakehoover/Titanic Competition/.ipynb_checkpoints# ls -la
total 508
drwxr-xr-x 2 ubuntu ubuntu   4096 Dec  6 19:02 .
drwxr-xr-x 5 ubuntu ubuntu   4096 Dec  9 18:32 ..
-rw-r--r-- 1 ubuntu ubuntu 194906 Oct 10 01:58 DMA24_Competition-checkpoint.ipynb
-rw-r--r-- 1 ubuntu ubuntu 110632 Oct 15 21:39 Untitled-checkpoint.ipynb
-rw-r--r-- 1 ubuntu ubuntu 150616 Oct 16 01:47 Untitled1-checkpoint.ipynb
-rw-r--r-- 1 ubuntu ubuntu     72 Nov  9 00:03 Untitled2-checkpoint.ipynb
-rw-r--r-- 1 ubuntu ubuntu      0 Nov  9 00:03 python_exceptions-checkpoint.txt
-rw-r--r-- 1 ubuntu ubuntu  41186 Nov  9 00:06 python_exceptions_full_text-checkpoint.txt
```

**Comment by balajialg** [comment]
@blakehoover12 Closing this issue since the issue is inactive. Please reopen if you want to discuss the proposed options.
